### ISSUE TITLE
Odd entry in the project Add Item context menu

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1006]
![image](https://cloud.githubusercontent.com/assets/12820357/13329313/084a8990-dba8-11e5-906b-828dd199715a.png)

**Comment by jflam** [comment]
@MikhailArkhipov to open a bug in Web Essentials Github and link to it from here.

**Comment by MikhailArkhipov** [comment]
https://github.com/madskristensen/WebEssentials2013/issues/1992
