### ISSUE TITLE
RRE 7.5: "warning message: cannot decrease memory memory: ignored"

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1009]
build 2016-02-24.3
machine: VM with 4G memory
RRE 7.5

The first command (ls()) shows warning message. I seems like from setting memory limit initially.

> ls()
character(0)
Warning message:
cannot decrease memory limit: ignored 
>

**Comment by MikhailArkhipov** [comment]
7.5 is no longer relevant
