### ISSUE TITLE
Respect Windows DPI setting in plots

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1013]
If you dynamically drag the slider that controls DPI settings in Windows, Visual Studio will dynamically adapt its UI to accommodate. We should do the same thing for plot windows.

![image](https://cloud.githubusercontent.com/assets/8877/13331084/c9fddf80-dbb0-11e5-8187-5a3537438d7a.png)

**Comment by Hong-Revo** [comment]
Possibly related: the font size for plot windows is half what it should be on a high-DPI setting. That is, if Windows is set to 200% text size, RTVS currently ignores it and keeps the text at 100%, ie half-size.

**Comment by huguesv** [comment]
Information on events: https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410(v=vs.85).aspx

**Comment by huguesv** [comment]
Done
