### ISSUE TITLE
Add New Item doesn't activate new document

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1027]
In C# project, when you do Add New Item, the new file that is created is opened, activated, and you can start typing in it immediately.

In R project, it opens the new file, but it doesn't get activated.  It feels like it randomly selects one of the opened documents, and activates one of them.  It's very annoying.

To reproduce, open a few .R scripts first, then Add New Item.

**Comment by jflam** [comment]
No repro
