### ISSUE TITLE
Add samples to the New Project dialog

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1035]
The dialog that opens lets you open a new template, as well as open samples. These map to Visual Studio Gallery.

This is what templates look like:

![image](https://cloud.githubusercontent.com/assets/8877/13361934/8bd4ee9e-dc76-11e5-9b79-9d25cd007477.png)

This is what samples look like:

![image](https://cloud.githubusercontent.com/assets/8877/13362002/d1940582-dc76-11e5-8070-75b2d1cb2bf2.png)

**Comment by MikhailArkhipov** [comment]
Is this happening in 0.3?
