### ISSUE TITLE
Variable declared during debugging doesn't appear in VE or Autos

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1045]
![image](https://cloud.githubusercontent.com/assets/12820357/13363954/090f44d6-dc81-11e5-8cc8-1a91008c93ce.png)

Start with

x <- 2

f <- function() {
    x <<- 3
    x <- 2
    while (y > 1) {
        x <- 3
        for (i in 1:10) {
            x <<- x + 1
        }
    }
}

f()

set BP on x <<- x + 1
Attach debugger and source
when BP is hit, change code to

y <- 2

f <- function() {
    x <<- 3
    x <- 2
    while (y > 1) {
        x <- 3
        for (i in 1:10) {
            y <<- y + 1
        }
    }
}

f()

Step through, everything works but
'y' does not appear in Auto, or Variable Explorer
Manual adding to Watch works

It would be nice to get it appear either in Auto (which is actually completely empty) or in VE.

**Comment by jflam** [comment]
See #1037
