### ISSUE TITLE
Create a Visual Studio toolbar with common commands for current editor tab

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1061]
user submitted
eg a triangle on the editor or repl?

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/14217118/1845581e-f801-11e5-9a6c-ddc71af2e547.png)

Mightly small. Need moar buttons. I guess I can add 'runApp'. What else?
