### ISSUE TITLE
AF when requesting help on keyword

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1065]
Right click on 'while' in the editor and choose 'Help on while' (eval calls ?while). appears to be ignorable.

![image](https://cloud.githubusercontent.com/assets/12820357/13400203/8e629f02-debb-11e5-8154-c17381e6226c.png)

**Comment by MikhailArkhipov** [comment]
Please verify

**Comment by JeongPyoHam** [comment]
verified
