### ISSUE TITLE
Placement of R project templates in New Project dialog is weird

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1069]
The "R" node is wedged between C# and VB:

![image](https://cloud.githubusercontent.com/assets/1175142/13404483/9949daee-dece-11e5-80bc-a826f6a71a5d.png)

Note how, on the other hand, Python is below all the "Visual *" stuff.

**Comment by huguesv** [comment]
It's controlled by:
```
    [DeveloperActivity(RContentTypeDefinition.LanguageName, RGuidList.RPackageGuidString, sortPriority: 9)]
```
Changing it to 40 moves R right below SQL Server.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/17312704/77fbc014-5809-11e6-8c4a-a7377a125a1b.png)
