### ISSUE TITLE
Import data into a data frame

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1106]

**Comment by jflam** [comment]
This is a user story.
Tasks:
1. Prototype
1. Local import
1. Import from web with cancellation semantics

**Comment by JeongPyoHam** [comment]
After discussion, the expectation of this task is making GUI version of reading CSV.

**Comment by MikhailArkhipov** [comment]
CSV is OK to start but in the future we could look into file extension and auto-import via other functions

http://www.statmethods.net/input/importingdata.html

CSV, SPSS, SAS, Excel, Stata
