### ISSUE TITLE
R project properties page

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1126]
We'll scope this work item to the following options related to Run/Debug:
- Startup file
- Command line args
- Reset REPL

They can be saved in the .rxproj.

Note that we cannot save non RStudio options in the .rproj, as RStudio will overwrite any options that it doesn't know about the next time the user changes project settings.

**Comment by huguesv** [comment]
Notes to myself:
`IVsProjectDesignerPageProvider`: returns list of IPageMetadata

`IPageMetadata`: name and guid of property page impl

`WpfBasedPropertyPage`: has a guid applied to it as an attribute, factory methods for `PropertyPageViewModel` and `PropertyPageControl`

`PropertyPageViewModel`: has `Initialize()` and `Save()`

**Comment by MikhailArkhipov** [comment]
Is it done? PR was merged

**Comment by huguesv** [comment]
Done
