### ISSUE TITLE
Create REPL Window Tests

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1141]
1. Type something into REPL to validate outputs
2. Interaction between REPL and other components in the tool (e.g., Editor)
3. Validate that history works correctly

**Comment by jflam** [comment]
We already have 90% code coverage through unit tests without creating UI tests, which is what this item describes.

**Comment by MikhailArkhipov** [comment]
We wrote number of tests without VS so this no longer needed
