### ISSUE TITLE
plot window has right arrow even with one plot

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1210]
from user:

Hi,

I just created one plot (and not a second one), but the next button is enabled

 

When I click on it, nothing happens (sure), but I could go back

 

Also the menu entries are enabled the same way (R Tools -> Plots Previous).
This should only be anabled if there is more than one plot available.

**Comment by huguesv** [comment]
I'll close this because I can't repro.  If anyone is experiences this, please include the code snippet that is causing it.  Thanks!
