### ISSUE TITLE
Unicode characters still not working in the REPL

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1211]
(user-reported)

Locale is Japanese, and it looks like R itself is configured to use Japanese localization, as well.

![image](https://cloud.githubusercontent.com/assets/1175142/13557183/56462d94-e39f-11e5-81ef-9f50ba3fe1d2.png)

**Comment by int19h** [comment]
Costing is tentative until such time this is properly investigated - currently it assumes 4 hours investigate / 4 hours fix, but the latter figure might be bigger.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/14439430/fa917e56-ffdf-11e5-88a0-ad70a3c8e77c.png)

Going to try full Russian VM now

**Comment by int19h** [comment]
Dupe of #1340, same fix also fixes this.
