### ISSUE TITLE
Loading solution is stuck

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1229]
repro steps: double click on xyz.sln, which contains a R project

Dump is here: \\pytools\R\Bugs\Project_open_stuck\devenv.DMP

**Comment by MikhailArkhipov** [comment]
Haven't seen this for long time. Update 2 might have fixed it.

**Comment by AlexanderSher** [comment]
Did you get a good repro?

**Comment by huguesv** [comment]
I saw this yesterday, and again today on a different machine.  Yesterday it was by starting VS from the taskbar by selecting a project from the taskbar quicklist.
Today it was from double-click of .sln and choosing the Visual Studio Version Selector.
Both cases produce same effect as in JP's screenshot.
I zipped the project I tried to open here: "\\pytools\R\Bugs\zevross.zip"

**Comment by huguesv** [comment]
Dump here: "\\pytools\r\Bugs\devenv-1229.DMP"
