### ISSUE TITLE
library, data, ... pop up external window

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1235]
from user:

Examples of functions that do this:
```r
library()
data()
```

**Comment by int19h** [comment]
Okay, so there are some alternatives here. The default and current behavior is to open a separate window (R offers that):

![image](https://cloud.githubusercontent.com/assets/1175142/13864953/4a2d4d9a-ec63-11e5-9375-7c93cefcc99e.png)

We can set `options('pager')` to `'console'`, in which case it will just print out to the REPL - that's by far the easiest solution (1h to implement), and it works in a sense that there are no windows, and REPL is scrollable, so functionally it's adequate. But clearly the intent is to provide a separate viewing window...

RS opens the text as a document in the editor well instead - this can also be done, but it requires more effort, as we'll need to implement it as a virtual document to give R control over the title, and also support automatic deletion of the displayed temporary file once the document is closed. I'd estimate it as at least one full day of work to wire everything up and test.

@jflam, your take?

**Comment by MikhailArkhipov** [comment]
I remember JavaScript debugger in VS opens runtine JS as 'transient' document. Typically comes to the editor factory with name like ^something.js. Basically, no file on disk, just transient text buffer with contents.

**Comment by int19h** [comment]
Yes, VS supports that. it's a bit easier for debuggers though, because there you just need to implement [IDebugDocument2](https://msdn.microsoft.com/en-us/library/bb145153.aspx) to retrieve the source code, and VS debugger service wires it up to the editor. Since this scenario doesn't actually involve the debugger, I'll need to figure out how it all works under the hood first.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c15056c2fa91884f38d5b672002d84598d3be5e1 for library and View(). data TBD.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2ac3848c8cd29014a9aeca12f0d3855e26f04bd8
