### ISSUE TITLE
Interactive: option to write all input/output to a file

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1248]
basically tee option for the repl window.

**Comment by int19h** [comment]
What is the scenario?

Note that if you just want to capture the output, you can always do Select All, Copy, Paste into Notepad.

**Comment by jflam** [comment]
Please chime in via comments if this is an important feature for you so we have more data to help prioritize this work. Thx.

**Comment by MikhailArkhipov** [comment]
Workaround is a @int19h mentioned. Closing while cleaning up the backlog.
