### ISSUE TITLE
shortcut key to change dir

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1249]
user tweeted.

RS has support for quickly changing/setting dir.

**Comment by int19h** [comment]
We have a command for this already - it's on REPL toolbar. So this is just the shortcut?

**Comment by MikhailArkhipov** [comment]
Part of #1089?

![image](https://cloud.githubusercontent.com/assets/12820357/13862801/afbb235a-ec52-11e5-8a32-da3bd2d4e409.png)

**Comment by smortaz** [comment]
+1

**Comment by MikhailArkhipov** [comment]
OK, closing then in favor of #1089 (about to be submitted for review)
