### ISSUE TITLE
Wizard or Utility that can convert R into F#, C# or C++

### ISSUE THREAD

**Issue by dngoins** [Microsoft/RTVS#1257]
Many people use R for research and analysis. It would be great to take that research and make it production ready by converting it to a production ready language such as C# or C++.

Have a wizard/utility that can convert R into F#, C# or C++ for embedding the R test/pilot/research code into real production applications that require C# or C++

**Comment by MikhailArkhipov** [comment]
Generally language conversion is very hard even between similar languages such as Java and C#. Conversion of class-less languages to CLR or languages with automatic garbage collection to native like C++ is close to impossible.
