### ISSUE TITLE
Rmd code chunks and highlighting

### ISSUE THREAD

**Issue by joeledvina** [Microsoft/RTVS#1264]
Other highlighting seems to be correct, but all of my comments inside code chunks are displayed in a much larger font, as if they were markdown headings instead of comments.

Also, code folding does not recognize code chunks, only headings (and treats comments as headings).

It would also be nice if there were an option to visually distinguish code chunks from markdown text.

**Comment by jflam** [comment]
@joeledvina can you provide a code snippet that repros what you have. screenshot would be awesome as well.

**Comment by MikhailArkhipov** [comment]
Different fonts are provided by Web Essentials and not RTVS. Web Essentials does not know about R.
