### ISSUE TITLE
raster::click doesn't work

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1265]
from user:

I have some problem in running the function click from raster package:
raster::click()
also the same problem with the locator() function
What could I be doing wrong?
how can I run this functions ?

**Comment by huguesv** [comment]
Thanks for the feedback.  Support for locator() has not been implemented yet, and it looks like that's what raster::click() uses.

**Comment by jflam** [comment]
This feature puts VS into a modal state until the user clicks on the plot window.

**Comment by huguesv** [comment]
Done.
