### ISSUE TITLE
detection of packages in custom locations (intellisense)

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1267]
from user:

I have my user-installed packages located in the d:\rlibs directory, and RTVS seems to have trouble picking them up. Intellisense only finds the packages which are installed under the R install tree (…\R-3.x.x\library), and not elsewhere.

How I’ve set it up: I have a .Renviron file under c:\users\hongooi\documents containing 1 line

R_LIBS=d:/rlib

Does RTVS check for this file at startup? Note that everything works fine in R; I can load packages without any problems. It’s Intellisense that doesn’t pick them up.

**Comment by MikhailArkhipov** [comment]
See #1095
