### ISSUE TITLE
Smart indent should be aligning arguments

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1275]
```
x <- function(a<ENTER>
```

should position caret under 'a'

**Comment by MikhailArkhipov** [comment]
#1285

**Comment by huguesv** [comment]
While it does achieve what was described in the example above, I feel it's not quite correct and need to allow more flexibility, like in RS.

- It should be aligning based on the column of the previous argument.  Right now it's always aligning with column+1 of the open paren.
- When there's no previous argument and you press ENTER, it should indent one level relative to the first char of the function name.

In RS it is easy to do this:
```
res <- this.function.name.is.somewhat.long(
  'this long message would go over 80 cols if aligned with open paren',
  'other parameter'
)

```
But trying to do the same in RTVS is infuriating.


Examples (where indentation is 2 spaces):

action:
```
res <- myfunc(<ENTER>
```

expected:
```
res <- myfunc(
  <caret>
```

actual:
```
res <- myfunc(
              <caret>
```


action:
```
res <- myfunc(1,<ENTER>
```

expected & actual (already correct):
```
res <- myfunc(1,
              <caret>



action:
```
res <- myfunc(
  1,<ENTER>
```

expected:
```
res <- myfunc(
  1,<ENTER>
  <caret>
```

actual:
```
myfunc(
       1,
       <caret>
)
```

**Comment by MikhailArkhipov** [comment]
We used to handle user indent, but user found it improper and rather have arguments aligned. However, we can technically combine smart indent and block indent (i.e. that is what RS does based on the previous line).

**Comment by int19h** [comment]
If they're typing a new call, user indent will equate to having the arguments aligned (in a way that user explicitly asked for by the placement of the first argument), no?

**Comment by MikhailArkhipov** [comment]
RS:

```
x <- function(a,<ENTER>
                     <caret>
```
