### ISSUE TITLE
Double-clicking in the REPL doesn't highlight words

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1279]
It seems that double-click simply doesn't do anything.

**Comment by MikhailArkhipov** [comment]
any specific text? It won't select text that is inert though like the R startup message.

**Comment by int19h** [comment]
I don't remember what it was exactly, but it was the result of an earlier expression.

By "inert text", do you mean any outputs?

**Comment by int19h** [comment]
Basically my scenario was something like this:

1. Start running code.
1. Error message gets printed out about a package not being installed.
1. I start typing `install.packages`, and want to copy/paste the name of the package from the error message.
1. Double-clicking on the package name does not highlight it.

**Comment by MikhailArkhipov** [comment]
Easy fix, part of #1355
