### ISSUE TITLE
SerializeVisualTree is unstable in tests

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1283]
It writes properties that are different on different machines and also writes tons of unnecessary properties.
```
    <VisualTreeProperty Name="ActualWidth" Value="784" />
    <VisualTreeProperty Name="ActualHeight" Value="561" />
    <VisualTreeProperty Name="ActualWidth" Value="786.285714285714" />
    <VisualTreeProperty Name="ActualHeight" Value="563.428571428571" />
```

VisualTreeWriter used to filter...

**Comment by JeongPyoHam** [comment]
Tree comparer uses filters, which is mentioned in opening description. Nothing changed in test's perspective. We can write to extend existing code for convenience of test data preparation, as needed later easily. I close this issue, as test itself is not unstable.

**Comment by JeongPyoHam** [comment]
Please reopen, if oppose the resolution.

**Comment by JeongPyoHam** [comment]
done.
