### ISSUE TITLE
.Rprofile is not loaded

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1287]
`.Rprofile` is the standard place to put various initialization code and settings for R. However, RTVS (or rather R-Host) doesn't load it.

**Comment by int19h** [comment]
#915 is possibly related.

**Comment by jflam** [comment]
We should definitely load this, as this is where folks do lots of customization. For example, would be helpful to talk to Andrie about this as he heavily customizes his .Rprofile.

**Comment by int19h** [comment]
Trying to repro this, both `.Rprofile` and `Rprofile.site` do get loaded from the locations documented in the R manual (`Documents` and `R-x.y.z\etc, respectively).

The only other place that the manual says it can be loaded from is the current directory, but it's unclear what meaning this would even hold in case of RTVS, since there's no concept of VS-wide current directory in UX. In practice, when we start the host process, we set the current directory for that process to R's `bin` folder (so that it locates the right DLL to load).

Either way, needs clarification from the user regarding expected behavior.

**Comment by MikhailArkhipov** [comment]
Since we do load profile, I suggest we close this for now.

**Comment by int19h** [comment]
Agreed.
