### ISSUE TITLE
Help viewer does not show images.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1289]
e.g. mai.png on ?par is missing.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/13864451/c7bbae3c-ec5e-11e5-9f40-a2308c2ccbae.png)

**Comment by int19h** [comment]
VS uses IE as embedded browser. Can you check if you have images disabled in it? It's under Tools -> Internet Options, and looks like this:

![image](https://cloud.githubusercontent.com/assets/1175142/13864701/21850b3c-ec61-11e5-942f-bf2edd30bf20.png)

**Comment by jflam** [comment]
If it is broken on a machine, it appears to be broken everywhere: This is with 3.2.3.

1. RTVS
2. RStudio
3. External browser + RTVS

**Comment by jflam** [comment]
This appears to be a bug in the actual docs vs. a tooling bug.

**Comment by jflam** [comment]
@MikhailArkhipov to verify whether this is fixed in 3.3.

**Comment by Marchen** [comment]
Thanks for the replies. I found Show pictures was checked on IE settings and confirmed this also happen in usual R 3.2.3 both on Windows and Mac.

**Comment by int19h** [comment]
Thank you, Michio! If you do file a bug on R regarding this, can you please post the link to it here, so that other users running into the same problem can find it?

**Comment by Marchen** [comment]
OK, I will post the link to here after I will report the bug.

**Comment by Marchen** [comment]
I tried R 3.2.4 before filing the bug and found that this issue was already fixed in 3.2.4.
![default](https://cloud.githubusercontent.com/assets/3863577/13890975/ba22759c-ed91-11e5-9a76-9b762a69b829.PNG)

**Comment by jflam** [comment]
Thanks, @Marchen! Closing this issue.
