### ISSUE TITLE
Incorrect operator priorities

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1298]
Some operators have priorities assigned to them that do not correspond to the actual evaluation order. In particular:

Function call has higher priority than `@` and `$`. This is important in expressions such as `Class$new(...)`, where `Class$new` is evaluated first, and is the target of the call.

`:` has higher priority than `^` and unary `+`, `-`, `!`. So e.g. `-a:b` is parsed as `-(a:b)`, not as `(-a):b` as it is actually evaluated.

`::` and `:::` have lower priority than almost everything. So `a::b+1` is parsed as `a::(b+1)`, but it's actually evaluated as `(a::b)+1`.

There's some other weirdness in `OperatorPrecedence.cs`. For example, a bunch of `%..%` operators are special-cased to have lower precedence than some other operators, even though per language grammar they all have the same precedence.

R docs have a [precedence table](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Syntax.html), but it's missing some things - notably, function calls.

**Comment by MikhailArkhipov** [comment]
-1:2 produces correct result: operator ':' over -1 and 2. Tree looks like
```
    ExpressionStatement  [-1:2]
        Expression  [-1:2]
            TokenOperator  [: [2...3)]
                NumericalValue  [-1 [0...2)]
                TokenNode  [: [2...3)]
                NumericalValue  [2 [3...4)]
```
i.e. 
```
       :
-1          2
```

**Comment by int19h** [comment]
This is because you're using literals here. My repro was `-a:b`.

By the way, the above tree is also somewhat incorrect, in that the sign in `-1` is actually an operator, and evaluation of `-1` is performed as `1` followed by applying function `-` to it, so redefining `-` will affect the result:
```
> `-` <- function(x) x*2
> -2
[1] 4
```
