### ISSUE TITLE
Parser doesn't properly handle loops as values

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1299]
Consider:

``` r
x <- for (i in 1:10) {}
```

This is valid R code - `for` is an expression that always produces `NULL`. However, the editor will squiggle it.

Similar problem exists with `while`, `repeat`, `break` and `next`. All of these are expressions and should be treated as such (basically, everything is an expression).

**Comment by int19h** [comment]
Note that the real scenarios here are more convoluted than simple assignment, and don't actually utilize the return value; but all boil down to loops being expression.  For example, suppose that the body of the loop makes assignments, and we want to localize them. Then:
```r
local(for (i in 1:10) { ... })
```
we currently don't parse it right. Similarly with `eval` and `quote`.

**Comment by MikhailArkhipov** [comment]
Folding into #3642
