### ISSUE TITLE
User-defined operators can contain whitespace

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1301]
E.g. this is legal:
```r
`% a %` <- function(x, y) x + y
1 % a % 2
```
It appears that `%` behave like true quotes, in that any character other than `%` is legal inside - including whitespace (except for newlines), other quotes etc.

Currently, any operator with whitespace produces an error squiggle with message "Unexpected token".

**Comment by smortaz** [comment]
weird.

**Comment by MikhailArkhipov** [comment]
This was fixed by https://github.com/MikhailArkhipov/RTVS/commit/9195bd4f6489cf933810bc35c930fe4ebe0fe9f9
