### ISSUE TITLE
Review full list of popular shortcuts, see if we can match more

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1308]
[Shortcuts.txt](https://github.com/Microsoft/RTVS/files/182961/Shortcuts.txt)

**Comment by cg31** [comment]
I definitely need these two:
Move cursor to Console	Ctrl+2
Move cursor to Source Editor	Ctrl+1

**Comment by int19h** [comment]
@cg31, you can have Ctrl+2 do that already (and a bunch of other similar shortcuts) if you use R Tools | Data Science Settings, and proceed with both prompts (first one sets the window layout, second one sets the keybindings). Just keep in mind that it will change your VS settings with automatic undo, so use Tools | Import and Export Settings first if you want to be able to revert it.

**Comment by cg31** [comment]
Thanks, @int19h, I wasn't aware this Data Science Settings.

Now my workflow is like:
Ctrl+2 => R Console
Ctrl+Tab => Editor

Not exactly like Rstudio, but not bad.

**Comment by karthikjipmer** [comment]
Keyboard shortcut to insert a code chunk - like CTRL +ALT + I in RStudio?

**Comment by MikhailArkhipov** [comment]
In VS snippets (code templates) are inserted via intellisense. You can see them with a scissor icon. First TAB completes to enttry, second to snipped. Try `lm[TAB][TAB]`. Roxygen block is inserted by double `##` right before the function similar to `///` in C#.
