### ISSUE TITLE
Execute an entire block of R code within an R markdown document

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1309]
from user:

Only feature I did not find or figure out is the ability to run the whole chunk I’m standing on in an R markdown file (ctrl+alt+c in RStudio).

**Comment by MikhailArkhipov** [comment]
In favor of wider #1308

**Comment by int19h** [comment]
#1308 is about shortcuts, but this is actually a new command that we need.

**Comment by MikhailArkhipov** [comment]
I actually meant including commands but OK :-)

**Comment by int19h** [comment]
Let's create and keep around separate items for commands that we know someone wants already - so that people can upvote them etc.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/080da5457cc2e72ce0becb078822e6de85a18cc9
