### ISSUE TITLE
Several TaskCancelledException while scrolling in editor cause extreme slowdown

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1316]
Run RTVS in debugger.
Open JSON.r in editor.
Press and hold DOWN arrow key.

Result:  It stutters a lot and jumps over several lines.  If you enable Break on Exceptions for all CLR exceptions, you'll see some TaskCanceledException occurred, and it breaks in DataTipTextViewFilter.cs's Exec method.

**Comment by int19h** [comment]
Is that really the first place where the exception occurs? It feels weird, since `DataTipTextViewFilter.Exec` does nothing except for invoking the next command filter's `Exec`; so if something like that gets thrown, it would imply that the other filter is throwing it, but then it should really break in that other filter...

**Comment by MikhailArkhipov** [comment]
Can you please attach the file

**Comment by huguesv** [comment]
[json.zip](https://github.com/Microsoft/RTVS/files/199984/json.zip)

I just tried it again and i don't see the slowdown that i saw before.  You should try it and if you don't see it either, then close.  Those TaskCanceledException are still being thrown, so the source of the slowdown may have been something else.

**Comment by MikhailArkhipov** [comment]
There was significant performance work on smart indent and related code that used to call parser to often. This could have mitigated this. I'll check exceptions. I tried 5K lines file I have but it didn't throw any.

**Comment by MikhailArkhipov** [comment]
Don't see any task exceptions...

**Comment by huguesv** [comment]
![image](https://cloud.githubusercontent.com/assets/1696845/14217049/d19fc6b0-f800-11e5-9e70-81f9287a57a6.png)

**Comment by MikhailArkhipov** [comment]
Can you disable just my code and see what's the source?

**Comment by MikhailArkhipov** [comment]
If it is not visible to user, I am going to punt to 0.4 since there are higher priority issues.

**Comment by MikhailArkhipov** [comment]
Does it still repro?

**Comment by huguesv** [comment]
Closing, since i'm not seeing the slowdown anymore.
