### ISSUE TITLE
Colorize inside Roxygen block

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1317]
It would be nice to colorize parameter names and other related items differently in 

```
#' @param ...
```

similar to what C# does in /// blocks

**Comment by Neil-Schneider** [comment]
Currently, I use extra white space to make roxygen keywords stand out more. Colorization of the `@` parameters would be a nice addition.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f654cfd573f15c2fbf477393bfb6675359d9422e
