### ISSUE TITLE
cxxfunction: Error in system(cmd, intern = !verbose) : 'C:/Program' not found

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1318]
from user:
```r
setwd("e:/hmad")

emad_dat <- list(mad = 50)

library(rstan)
fit <- stan(file = 'e:/hmad/EMAD1.stan', data = emad_dat,
            iter = 10000, chains = 4)
```
I get the error: 
> Error in system(cmd, intern = !verbose) : 'C:/Program' not found

Easier repro:
```r
fx <- cxxfunction(signature(x = "integer", y = "numeric"), 'return ScalarReal( INTEGER(x)[0] * REAL(y)[0] )')
```

**Comment by int19h** [comment]
We don't use `system` anywhere, so it looks like a Stan bug - probably due to installation path having spaces? I'd ask to see if this repros with Rgui.

**Comment by smortaz** [comment]
he said it works in RS.

**Comment by int19h** [comment]
What's actually failing here is `inline::cxxfunction`. Easier repro:
```r
fx <- cxxfunction(signature(x = "integer", y = "numeric"), 'return ScalarReal( INTEGER(x)[0] * REAL(y)[0] )')
```

**Comment by int19h** [comment]
The root cause is that this code assumes that `R.home()` never has spaces in it, and so doesn't quote it. It works in Rgui and RS, because they use short path. In Rgui/RS:
```
> R.home()
[1] "C:/PROGRA~1/R/R-32~1.3"
```
In RTVS:
```
> R.home()
[1] "C:/Program Files/R/R-3.2.3"
```
