### ISSUE TITLE
Non-ASCII output is garbled when R locale is not Latin-1

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1340]
The content of the attached file is

"Language"
"English"
"日本語"

If I read the file using read.csv(), it returns

read.csv("test_cp932.txt")
  Language
1  English
2   “ú{ê

Adding fileEncoding = "CP932" had no effect.

[test_cp932.txt](https://github.com/Microsoft/RTVS/files/187791/test_cp932.txt)

**Comment by int19h** [comment]
Is it the data that is garbled, or is it the output in the REPL? If you use `write.csv` on the data, is the output correct?

**Comment by Marchen** [comment]
This problem only occurred in the REPL. If I use write.csv to file, the output data was correct. But if I print the result to the  R interactive, the result was garbled like

> write.csv(data)
"","Language"
"1","English"
"2","“ú{ê"

And I found this is not a problem of read.csv but a problem of showing data in data.frame because following code caused same problem.

> data.frame(lang="日本語")
    lang
1 “ú{ê

**Comment by int19h** [comment]
Thank you. So it seems that this is the same problem as in #1211?

**Comment by Marchen** [comment]
I'm not sure, actually. When I print a element of data.frame, it works correctly.

> df <- data.frame(lang = "日本語")
> df[1, 1]
[1] 日本語
Levels: 日本語

but when I print entire data.frame, it garbles Japanese characters.
> df
    lang
1 “ú{ê

Following part of print.data.frame() seems to cause garbling.
> m <- as.matrix(format.data.frame(x, digits = digits, 
            na.encode = FALSE))

but again, I'm not sure this is the same problem as in #1211.

**Comment by int19h** [comment]
I wonder if it escapes things in a different way, and we handle one correctly, but not the other...

Could you try these two things. and give me the output for each:
```r
lapply(capture.output(df), utf8ToInt)

lapply(capture.output(df[1, 1]), utf8ToInt)
```

**Comment by Marchen** [comment]
Your codes returned following.

lapply(capture.output(df), utf8ToInt)
[[1]]
[1]  32  32  32  32 108  97 110 103

[[2]]
[1] NA

lapply(capture.output(df[1, 1]), utf8ToInt)
[[1]]
[1] NA

[[2]]
[1] NA

**Comment by int19h** [comment]
Tentative estimate - needs investigation to root cause.

**Comment by int19h** [comment]
I'm trying to reproduce this on Win10 JPN (with locale etc). But I'm getting escaped characters instead:
```
> data.frame(lang = "日本語")
                      lang
1 <U+65E5><U+672C><U+8A9E>
```
Can you tell what `Sys.getlocale()` prints out for you?

**Comment by Marchen** [comment]
It returned the following on my win10 Japanese.
```
> Sys.getlocale()
[1] "LC_COLLATE=Japanese_Japan.932;LC_CTYPE=Japanese_Japan.932;LC_MONETARY=Japanese_Japan.932;LC_NUMERIC=C;LC_TIME=Japanese_Japan.932"
```

**Comment by MikhailArkhipov** [comment]
Seems to be R locale issue (although we output different garbage string as compared to RS. None of the below encodings appear to work.

$`ibm-866_P100-1995`
[1] "ibm-866_P100-1995" "ibm-866"           "IBM866"           
[4] "cp866"             "866"               "csIBM866"         
[7] "windows-866"      

![image](https://cloud.githubusercontent.com/assets/12820357/14439984/ba690a76-ffe2-11e5-8f18-1a7a7bf81a04.png)

**Comment by MikhailArkhipov** [comment]
RTVS matches RGUI output

![image](https://cloud.githubusercontent.com/assets/12820357/14440040/005c6050-ffe3-11e5-82be-a74acf4208c4.png)

**Comment by MikhailArkhipov** [comment]
RS provides a way to reopen file with proper encoding (VS does the same). However, Import data dialog needs to be fixed since we can't convert R encodings to .NET encodings. Will be fixing that so at least files can be imported properly via the dialog.

**Comment by int19h** [comment]
Note that this is not just about `read.csv`. It's about REPL output in general in some cases. E.g. in this case there's no data loading, but output is not right:
```r
data.frame(lang = "日本語")
```

**Comment by int19h** [comment]
In fact, this is specifically not about `read.csv` per https://github.com/Microsoft/RTVS/issues/1340#issuecomment-201147745. Can you file a separate bug for Import Data issues?

**Comment by int19h** [comment]
To repro it on an arbitrary machine regardless of locale etc, just manually set R locale to something other than the default Latin-1:
```r
Sys.setlocale('LC_CTYPE', 'Japanese_Japan.932')
data.frame(lang = "日本語")
```

**Comment by int19h** [comment]
So the problem is that when we're converting output to UTF-8, we're using VC's `mbstowcs`, which uses VC CRT locale - which is different from MinGW CRT locale. We need to be calling `mbstowcs` from msvcrt.dll.

**Comment by MikhailArkhipov** [comment]
Sure, https://github.com/Microsoft/RTVS/issues/1532

**Comment by MikhailArkhipov** [comment]
This one back to you then

**Comment by int19h** [comment]
https://github.com/Microsoft/R-Host/pull/55
