### ISSUE TITLE
Survey/News web site performance when 'cold' is terrible

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1354]
Terrible means it sometimes takes over 15 secs for the page to show up after you've clicked on Survey/News menu item.  When the site is warm, it's less than 1 sec.

Web site goes to sleep and takes a long time to wake up ;)

We should look at the tips here:
https://lnx.azurewebsites.net/python-app-on-azure-web-apps-frequently-restarts/

**Comment by MikhailArkhipov** [comment]
No complaints
