### ISSUE TITLE
äöü characters breaks formatting

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/RTVS#1361]
Hello

The auto-formatter is adding a space in front of an umlaut character (when the umlaut is not the first character in the name).

```
a <- c(1, 2, 3, 4)
testDataFrame <- data.frame(testü = a)
testDataFrame$testü
```

After formatting:

```
a <- c(1, 2, 3, 4)
testDataFrame <- data.frame(test ü = a)
testDataFrame$test ü
```

R Tools for Visual Studio   0.2.20304.1341

**Comment by MikhailArkhipov** [comment]
Thanks for reporting, will be fixed asap.

**Comment by MikhailArkhipov** [comment]
Also #1360
