### ISSUE TITLE
IntelliSense truncates number of columns in dataframe

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1362]
From Hong Ooi on rtvs-disc

I have a df with 49 columns, but IS only lists 16 of them:

![image](https://cloud.githubusercontent.com/assets/8877/14081228/83bd4ffc-f4be-11e5-8592-dc4699aba9c8.png)

Notice how the scrollbar on the dropdown list is much longer than it should be, meaning the list is shorter than it should be.

**Comment by MikhailArkhipov** [comment]
Intellisense is using the same data source. If VE is fixed, completion will get it automatically.

**Comment by MikhailArkhipov** [comment]
Should be fixed as #1398
