### ISSUE TITLE
Open in Excel: c(functions) fails to show

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1374]
f1 <- function(){}; f2<-function(){}; f3<-function(){};
x<-c(f1, f2, f3);

click excel icon in VE

Error message shows as below
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class ""function"" to a data.frame

**Comment by MikhailArkhipov** [comment]
Also #1376

**Comment by MikhailArkhipov** [comment]
Unfortunately, we can't say up front without round tripping to R what might be in the list and this is prohibitively expensive just to check button visibility. The error is self-explanatory.
