### ISSUE TITLE
Double click on function in VE should do View('function_name')

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1375]
Since we will be getting View(...) implemented for various things soon

**Comment by MikhailArkhipov** [comment]
This can also be used in Peek Definition for library functions written in R

**Comment by int19h** [comment]
Rather than doing `View('name')`, it should do `View(expression)`. That way it'll get the right function regardless of which stack frame, package etc the function is in (e.g. for a stack frame, the expression will be something like `sys.frame(1)$f`).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c15056c2fa91884f38d5b672002d84598d3be5e1
