### ISSUE TITLE
RTVS for Dev15

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1386]
Check functionality, setup, etc. Specific bugs/tasks will be opened under this story

#1397
#1426
#1435
#1436
#1437

**Comment by AceHack** [comment]
When can we expect this to work with Dev15?  Where I can download?

**Comment by MikhailArkhipov** [comment]
Currently it is marked for Preview 0.4 and milestone dates are here https://github.com/Microsoft/RTVS/milestones

**Comment by AceHack** [comment]
I understand, you have features you are trying to get out but I would love to see this in milestone 0.3 if possible.

**Comment by MikhailArkhipov** [comment]
There multiple changes in Dev15 including breaking changes in the project system so this, unfortunately, does not amount to just updating references and rebuilding..

**Comment by MikhailArkhipov** [comment]
Remaining work is 0.5

**Comment by MikhailArkhipov** [comment]
Apart from one bug all tasks completed

**Comment by MikhailArkhipov** [comment]
RTVS 0.4 will appear in Dev15 Preview 3 Data Science Workload (Willow aka lightweight setup).
