### ISSUE TITLE
Import from Web URL dialog UI issues

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1401]
![image](https://cloud.githubusercontent.com/assets/12820357/14217744/bb2d64b0-f804-11e5-8496-369d6d12e94f.png)

Buttons should be equally sized
ESC doesn't Cancel
Dialog is light on dark theme

**Comment by MikhailArkhipov** [comment]
And it can be resized! 8[ ]

![image](https://cloud.githubusercontent.com/assets/12820357/14217807/117a6ade-f805-11e5-8a52-82180fc4e839.png)

**Comment by huguesv** [comment]
Well, dialogs shouldn't be themed.
There should be a reasonable minimum size.
Since resizing vertically doesn't make sense, maybe a size==min==max will prevent that.

**Comment by MikhailArkhipov** [comment]
Depends. File | New Project is themed. Account Settings is themed. Most old native dialogs not themed (like Tools | Options)

**Comment by JeongPyoHam** [comment]
Also, [Enter] after typing URL should have same effect as pressing OK

Also, Cancel should keep active while download, and the download should be able to be cancelled.
