### ISSUE TITLE
Grid's title will better to show simpler 

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1404]
Now, it shows the expression as is.

e.g.
matrix.2x2 <- matrix(1:4, 2, 2);

shown as...
as.environment(".GlobalEnv")$matrix.2x2

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c15056c2fa91884f38d5b672002d84598d3be5e1
