### ISSUE TITLE
Package manager should default to Installed or Loaded

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1411]
![image](https://cloud.githubusercontent.com/assets/12820357/14220576/cb971240-f815-11e5-8470-0a4ba2384819.png)

**Comment by MikhailArkhipov** [comment]
currently it defaults to nothing

**Comment by MikhailArkhipov** [comment]
Load balance

**Comment by AlexanderSher** [comment]
Fixed in #1447
