### ISSUE TITLE
Package manager: filter text is not shown while filtering is working

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1414]
- click on Available and loaded available packages
- click on filter edit box (the one with search icon)
- type in 'p' 'a' 'g'

The result looks like this
![image](https://cloud.githubusercontent.com/assets/13896241/14220596/ec990714-f815-11e5-9a80-477280848a9b.png)

**Comment by MikhailArkhipov** [comment]
It is probably b/c the control is clipped and obscured.

**Comment by MikhailArkhipov** [comment]
Load balance
