### ISSUE TITLE
Some rows in VE are taller than others

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1424]
E.g. compare `fac` and `fac1` here:

![image](https://cloud.githubusercontent.com/assets/1175142/14220948/3e162156-f818-11e5-8020-21534d2a7948.png)

Seems to be due to Excel icon being too tall, and stretching the rows it appears in vertically.

**Comment by MikhailArkhipov** [comment]
It is not Excel specific, both images are from monikers and are 16x16. The issue is that with images rows height is bigger than regular text height (~18-20). It needs to be bound to font size + some padding to make row heights even across. Or we need smaller images

**Comment by JeongPyoHam** [comment]
Working on it.

**Comment by MikhailArkhipov** [comment]
Thanks

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/14399990/7b3b7a6a-fda7-11e5-99eb-b94aa0b133e5.png)
