### ISSUE TITLE
VS not responding after some editing

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1430]
Start with the file attached.
[script.zip](https://github.com/Microsoft/RTVS/files/200564/script.zip)

Copy/paste the last line on the line immediately next to it (put cursor on first column and hit CTRL-C, CTRL-V)
Move the cursor to location in picture (before closing paren on the first call to merge)

Consistently repros.  Code isn't stuck in an obvious loop as far as I can tell.

![image](https://cloud.githubusercontent.com/assets/1696845/14222630/9d88312e-f827-11e5-928d-2623ad67b6b2.png)

**Comment by MikhailArkhipov** [comment]
Doesn't repro for me. Don't mind if you show it :-) Also, may be some setup issue or clean build issue since I don't see those task canceled exceptions either. This one may be related.

**Comment by huguesv** [comment]
Oops, turns out I forgot the last step.  When the cursor is in the position of the picture, press CTRL-SHIFT-LEFTARROW (which selects the preceding word).  I got that to hang on both my dev machine and in the VM where I installed today's build.

**Comment by MikhailArkhipov** [comment]
Facepalm

**Comment by MikhailArkhipov** [comment]
Looks like VS doesn't like us returning 0-length span and keeps calling same method.
