### ISSUE TITLE
If R\bin is in PATH, wrong R.dll is loaded

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1432]
When we start the host process, we append the path to the designated R interpreter bin folder to PATH, so that the DLL gets picked up. But because we append it at the end, if it already has a path to bin somewhere on it, that path will be preferred, and we end up picking the wrong DLL. If it happens to be a 32-bit DLL, or if it's an old version of R that we don't support, the host process cannot start at all.

(This is likely to be the root cause of various user-reported issues where REPL is completely inoperable on startup.)

**Comment by MikhailArkhipov** [comment]
Should probably fix this for 0.3 as it is user-reported
