### ISSUE TITLE
Build for Dev 15, identify differences

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1436]
Part of #1386

**Comment by int19h** [comment]
We can avoid the a - just define the references conditionally where needed. PTVS does that.

**Comment by MikhailArkhipov** [comment]
We'll see how it goes. There problem is in CPS where, as I've been told, there are breaking changes. If they amount to mostly namespace changes, we may be able to get away with ifdefs. Also, opening our package in Dev15 led to one way upgrade.

**Comment by MikhailArkhipov** [comment]
Builds and runs. Solution Explorer is still empty (CPS is different). REPL assemblies, although changed to 2.0.0.0 are still bound to Shell.14.0. So I abandoned wholesale effort to change all references to 15.0 and only changed minimally relying on Dev15 redirects to 15.0 where needed.
