### ISSUE TITLE
Whole-word replace Highlighting Bug

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/RTVS#1446]
I think this is a small bug in the editor, I am replacing  “df”  with “ribdf” with the whole-world option and the search preview isn’t highlighting those instances that have a $ appended to them. It actually does the replacement correctly, but it looks like it is going to be wrong. 

![image](https://cloud.githubusercontent.com/assets/7562887/14287608/9b21d10e-fb53-11e5-9a39-bb066976236f.png)

**Comment by MikhailArkhipov** [comment]
This is fixed in 0.3 as part of the new, R-specific text structure navigator
