### ISSUE TITLE
Shortcuts for commands are not enabled on startup

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1457]
With default settings (i.e. no RTVS tool windows visible), when VS starts, none of the shortcuts are active:

![image](https://cloud.githubusercontent.com/assets/1175142/14298883/3d5c97e6-fb3c-11e5-9458-874915b85528.png)

Shortcuts become enabled once one of RTVS tool windows, or the editor, is active:

![image](https://cloud.githubusercontent.com/assets/1175142/14298913/5e43ccc2-fb3c-11e5-8c0b-72e24d9445af.png)

However, it means that on first launch, there's no way to quickly open the REPL via keyboard. You have to mouse through R Tools | Windows.

**Comment by MikhailArkhipov** [comment]
Technically design since we don't bind shortcuts in global.

**Comment by MikhailArkhipov** [comment]
Partial fix: bind Ctrl+2 to global so REPL is accessible
