### ISSUE TITLE
scan() doesn't work properly in R Interactive

### ISSUE THREAD

**Issue by cg31** [Microsoft/RTVS#1467]
In R Interactive, if you enter the code: data = scan()
then input data, like "1 2 3", in R console, it looks like:

> data = scan()
1: 1
2: 2
3: 3
4: 

when 4: appears, if you press Enter key, scan() should end scanning.

but RTVS keeps showing 4: and can't stop.

**Comment by int19h** [comment]
This is the same as https://github.com/Microsoft/RTVS/issues/626#issuecomment-180479383. Basically, we currently don't accept empty lines as valid input due to a bug in VS REPL.

**Comment by MikhailArkhipov** [comment]
Duplicate

**Comment by huguesv** [comment]
Fix has been merged into Roslyn, and will be available in Visual Studio 2015 Update 3.
