### ISSUE TITLE
Smart indent doesn't work after "{"

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1468]
On R Tools for Visual Studio   0.2.20304.1341

```
function(){
	glm(
	| <- Now the cursor is here.

```

**Comment by MikhailArkhipov** [comment]
This is fixed in 0.3, smart indent has been reworked. It looks like this


![image](https://cloud.githubusercontent.com/assets/12820357/14325341/b674c7ec-fbdd-11e5-969d-08b5589a917e.png)

**Comment by MikhailArkhipov** [comment]
Caret is before the )
