### ISSUE TITLE
Package Manager will send library() and detach() commands to REPL

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1489]
When the green circle next to a package is clicked, the corresponding package is loaded or unloaded. However, the fact that it does so is not reflected in any obvious way in the UI, because loading & unloading is done directly via `RSession`, and so the corresponding expression is not visible in the REPL.

It would be better if loading/unloading would submit the code to the REPL window, such that it (and any output that it produces) is immediately visible.

**Comment by int19h** [comment]
RS does submit it to the REPL - e.g. when you click on "abc" in the package manager, you see something like this:
```
> library("abc", lib.loc="~/R/win-library/3.2")
Loading required package: abc.data
Loading required package: nnet
Loading required package: quantreg
Loading required package: SparseM

Attaching package: ‘SparseM’

The following object is masked from ‘package:base’:

    backsolve

Loading required package: MASS
Loading required package: locfit
locfit 1.5-9.1 	 2013-03-22
```
while in RTVS, you don't see the first line. If the package doesn't produce any warnings on load, you don't see any output at all - it just silently updates `search()`.

**Comment by smortaz** [comment]
this is important because i want to see my record of load/unload/etc. in the History window.

**Comment by AlexanderSher** [comment]
Depends on #1469: Allow BeginInteractionAsync to notify RInteractiveEvaluator that response should be added to REPL 

The problem we have here is that Interactive Window doesn't allow to update its text buffer when its executing, so I can add command to the history, but I don't know if I can correctly add it to the Interactive Window.

**Comment by MikhailArkhipov** [comment]
Not entirely convinced this is worth the risk.

**Comment by MikhailArkhipov** [comment]
There are more places line this, opened Epic https://github.com/Microsoft/RTVS/issues/1534
