### ISSUE TITLE
Switch to Installed second time take forever

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1501]
Open PM 
Observe Installed populated quickly
Switch to Loaded
Switch back to Installed

Spinning wheel...........................................................

**Comment by AlexanderSher** [comment]
It waits for `available` to load

**Comment by MikhailArkhipov** [comment]
Yeah that's what I think too

**Comment by MikhailArkhipov** [comment]
We

a) need to prefetch available and
b) not wait in this case

**Comment by huguesv** [comment]
I don't know if you are using debug build or not, but don't judge performance based on debug build.  It is extremely slow compared to release.

**Comment by MikhailArkhipov** [comment]
In any case it will depend on machine speed and download speed. Can't be blocking
