### ISSUE TITLE
After installing, Uninstall button in details is visible but greyed out

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1509]
![image](https://cloud.githubusercontent.com/assets/1696845/14398120/9b126b70-fd96-11e5-9f16-e54eb68fecd1.png)

In this case, it also failed to appear in the list on the left.

**Comment by MikhailArkhipov** [comment]
Specifically reproes in Available after install:

Uninstall button in details is disabled
Uninstall button in list is visible but does nothing

Switching to Installed tab and back recovers

**Comment by MikhailArkhipov** [comment]
Sounds like 'IsChanging' property remails true
