### ISSUE TITLE
Encoding list in the import dialog may appear empty

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1511]
Looks like population is async and may not complete timely

**Comment by JeongPyoHam** [comment]
When encoding is empty, read.csv uses default option. UI should show default value such as 'Automatic' rather than leaving the combobox empty.

**Comment by MikhailArkhipov** [comment]
Have the fix. Automatic is already in the list, it is DoNotWait on the encoding list population was trouble. Selected encoding is used to read the file.
