### ISSUE TITLE
Import From Web URL: data frame part is empty at loading

### ISSUE THREAD

**Issue by JeongPyoHam** [Microsoft/RTVS#1512]
https://raw.githubusercontent.com/Microsoft/RTVS-docs/master/examples/MRS_and_Machine_Learning/Datasets/Bike_Rental_UCI_Dataset.csv

![image](https://cloud.githubusercontent.com/assets/13896241/14398222/5d9ba346-fd97-11e5-8760-6b85d6c10849.png)

**Comment by MikhailArkhipov** [comment]
B/c of #1511

**Comment by MikhailArkhipov** [comment]
Dupe of #1511
