### ISSUE TITLE
Variable names with non-ASCII characters produce errors

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1513]
I imported bikes.csv (set separator to semicolon, keep everything else default), and tried to expand the node in VE, go this message:
![image](https://cloud.githubusercontent.com/assets/1696845/14398230/6b42e554-fd97-11e5-9b23-f817b40f2e6a.png)

\pytools\r\TestData\bikes.csv

**Comment by int19h** [comment]
The issue is with variable/children names with Latin-1 characters in general. A very basic repro is:
```r
ü <- 1
```
