### ISSUE TITLE
Encodings in Data Import dialog don't work correctly

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1532]
We need map of R encoding names to .NET encoding names and code pages

**Comment by MikhailArkhipov** [comment]
So general importing of non-ASCII data in R is pretty miserable... read.csv works with encoding="UTF-8" but that's pretty much it. Reading in encoding like KOI-8R (encoding="866") doesnt work. RS has same results. So - we can make this quite a bit better:

a. Showing list of encoding .NET handles with descriptive names and code pages. No need to show 'shift_jis", "shift-jis" and all their spelling variations. Japanese (Shift_JIS) - 932 is better.

b. Convert file to temp file in UTF-8 before calling read.csv on the temp file and import always in UTF-8. This appears to produce proper results without loss of data.

**Comment by int19h** [comment]
Can you try this?
```r
read.csv(..., fileEncoding = 'cp866')
```

**Comment by MikhailArkhipov** [comment]
Same. cp866 is the same as 866

![image](https://cloud.githubusercontent.com/assets/12820357/14451486/616a0038-003c-11e6-8bcb-c4dba0beb0a3.png)

**Comment by MikhailArkhipov** [comment]
with UTF-8 conversion I properly get

![image](https://cloud.githubusercontent.com/assets/12820357/14451523/ab86da7e-003c-11e6-9913-d320a597d9d4.png)

And VE grid shows actual Russian

![image](https://cloud.githubusercontent.com/assets/12820357/14451543/c6327e5a-003c-11e6-97ec-62d73a7541e9.png)

See also http://stackoverflow.com/questions/18789330/r-on-windows-character-encoding-hell

**Comment by MikhailArkhipov** [comment]
Now need to figure out why VE grid shows proper characters while data frame in preview shows ```<U+...>```

**Comment by MikhailArkhipov** [comment]
Now, ```fileEncoding``` appears to work BUT produces odd error message

![image](https://cloud.githubusercontent.com/assets/12820357/14451604/460fddac-003d-11e6-8d79-708013d2799f.png)

**Comment by MikhailArkhipov** [comment]
Also, default R reader doesn't like UTF-8 with BOM while with conversion everything works fine

**Comment by MikhailArkhipov** [comment]
There

![image](https://cloud.githubusercontent.com/assets/12820357/14451943/d003844e-003f-11e6-98ef-886c7a5ab61d.png)

**Comment by int19h** [comment]
They have a separate encoding for UTF-8 with BOM (I think it was "UTF-8-BOM"?). But no auto-detect.

**Comment by int19h** [comment]
:+1:
