### ISSUE TITLE
Package manager could warn user when uninstall didn't remove all files

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1538]
If you install `ffbase`, load it, then try to uninstall, uninstall will not be able to delete `ffbase/libs/x64/ffbase.dll`.  You have to reset the REPL, then you can manually delete the leftover file.

The user experience is that after uninstall, `ffbase` still shows up in the list of installed packages, which can be confusing.

After uninstall is done, we could check if the folder still exist and warn the user that some files could not be deleted and will have to be removed manually.  Right now there are no warning/errors being displayed in REPL.

We could also fix up the result of installed.packages to remove packages that don't have a NAMESPACE file, so it doesn't show up in the UI anymore. Though if we do that, we open ourselves up for another error later on, if they try to re-install `ffbase` after they've installed, loaded, uninstalled it.  It fill fail to re-install:
```
Warning: cannot remove prior installation of package ffbase
```

**Comment by MikhailArkhipov** [comment]
100% same effect as RS. R unloads R part of the package but it is unable to unload native dlls.

**Comment by MikhailArkhipov** [comment]
Here is what you get in RS though if you

a. install and load ffbase
b. uninstall ffbase
c. try installing it again

![image](https://cloud.githubusercontent.com/assets/12820357/14449817/8cbf70fc-002c-11e6-91f0-34111ccef175.png)
