### ISSUE TITLE
Assertion failed: Exception in RHost run loop: System.OperationCanceledException: Connection closed by host

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1547]
Whenever I run with package manager in the background, eventually, this assert pops up (usually also in the background, so you need to check the taskbar to even see it). The easiest repro is make sure that package manager window is visible on VS startup, then restart VS and just wait for 1-2 minutes - the error shows up.

It's clearly not about the REPL, since that keeps working, so it's likely the package manager dedicated host. However, there's nothing in host logs that would indicate that the host process is down.

![image](https://cloud.githubusercontent.com/assets/1175142/14473516/5b7d1996-00ad-11e6-9b3b-d89f2887d47c.png)

**Comment by int19h** [comment]
[Microsoft.R.Host_REPL_20160412_125413_pid10648.txt](https://github.com/Microsoft/RTVS/files/215828/Microsoft.R.Host_REPL_20160412_125413_pid10648.txt)
[Microsoft.R.Host_PkgMgr_20160412_125414_pid13764.txt](https://github.com/Microsoft/RTVS/files/215829/Microsoft.R.Host_PkgMgr_20160412_125414_pid13764.txt)

**Comment by smortaz** [comment]
ok, i had seen that too, tho i thought it was because i closed/opened my
laptop & vs puked.

**Comment by int19h** [comment]
It is an error that can manifest itself in many different contexts. The scenario that you describe is where it can legitimately appear, and is likely unrelated.

**Comment by huguesv** [comment]
Can you make sure that this runs without error (in the REPL):
```
i1 <- rtvs:::packages.installed()
j1 <- rtvs:::toJSON(i1)
```

**Comment by int19h** [comment]
Yep, just ran both and they completed successfully, right after getting the assert.

**Comment by huguesv** [comment]
Back when I had bad R code that was generating named lists where the name was sometimes not unique, the effect that it had was a confusing assert like this one because JSON serialization was failing.  But I just looked at the attached log, and there's no mention of any error there.

**Comment by int19h** [comment]
What's even more weird is that there's also no mention of any host shutdown there, either. It's not clear where the dropped connection comes from, given that the other side is alive and well, and didn't even notice that connection is gone (otherwise the host would have logged it & terminated)...

**Comment by int19h** [comment]
Comparing host and client logs, it seems that something is going wrong when it is sending over the list of packages. It's a single very large packet (it blows up the log to ~5.5Mb), and while host logs indicate that it had been sent, the client logs don't have the corresponding receive. So it is that receive that is failing.

**Comment by int19h** [comment]
Okay, so what's happening here is that it takes so long (>60s) to send the available packages packet, that websocket-sharp drops the connection as timed out (because the other side doesn't send any pings while it's transmitting the packet).

**Comment by int19h** [comment]
So far as I can tell from the code of the library, there's no way to change the timeout - it's hardcoded to 60s:

https://github.com/sta/websocket-sharp/blob/6656b471bad8932a3b7d867306f8cb1a6305b776/websocket-sharp/Server/WebSocketSessionManager.cs#L76

**Comment by int19h** [comment]
So this only shows up in Debug builds, likely because JSON serialization of 5Mb of data takes that long there. So it's not a release blocking issue. I'm going to look into it though, because it is very annoying when debugging.

**Comment by MikhailArkhipov** [comment]
It would be great to have a switch controlling timeout since in slow debugging/stepping during development sometimes host dies.

**Comment by int19h** [comment]
So 60s is how often websocket-sharp does a "sweep" of inactive connections, and that value is hardcoded. But the timeout it uses to determine whether a connection is inactive is not hardcoded, and can be changed - the default is 1s. I'll definitely change it to something higher under `#if DEBUG`.

For this particular issue, though, the root cause seems to be that something is blocking the host thread that sends & receives messages for way too long, such that it cannot timely respond to pings. Since that thread doesn't do anything R-related directly (i.e. evals etc), and only sends and receives messages, my suspicion is that it's one of the locks - basically it's waiting on some lock that it shouldn't be waiting for, which is being held by the eval thread. Or something like that.

**Comment by int19h** [comment]
It stopped reproing on all the machines that I have, so closing this for now - reopen if it surfaces again.
