### ISSUE TITLE
Same-file IntelliSense does not work when using "=" as an assignment operator

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1548]
"=" is a valid assignment operator (albeit not idimoatic R), but IntelliSense does not recognize it in scenarios where the variable is assigned to in the editor, but not evaluated (works fine if evaluated):

![image](https://cloud.githubusercontent.com/assets/8877/14474008/b09a2912-00af-11e6-9166-3ba09bd310a6.png)

**Comment by MikhailArkhipov** [comment]
Trivial fix, just added another operator type check.
