### ISSUE TITLE
Sometimes they never die...

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1562]
![image](https://cloud.githubusercontent.com/assets/12820357/14512310/c72fa72c-0192-11e6-876a-abc17e16bb26.png)

**Comment by int19h** [comment]
Is it from regular product use, or a unit test run?

**Comment by MikhailArkhipov** [comment]
Most debug | stop debugging. By design?

**Comment by int19h** [comment]
The host should detect that the other side is gone eventually even in that case. But it might be that the default timeout is too big to be practical, and needs to be adjusted.
