### ISSUE TITLE
VS/host connection does not survive sleep

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1567]
When machine goes into sleep, the socket connection between VS and the R host process often doesn't survive. As a result, once awaken, VS reports connection loss, and R session needs to be restarted.

We should figure out if there's any way to preserve the connection through sleep; and if not, then implement a low-level reconnect facility that can be utilized in that scenario to "re-attach" the existing host to VS.

**Comment by MikhailArkhipov** [comment]
Perhaps just save sessions and then reload on wake

**Comment by int19h** [comment]
Need to see if this still repros with the new broker code, since it's a completely different websocket implementation on both sides.

**Comment by int19h** [comment]
@smortaz, since you were the only one to repro this before, can you give it a try during our next bash and see if it still happens now?

**Comment by MikhailArkhipov** [comment]
#2176 is the majority or work. We will investigate  machine specific in RTM

**Comment by MikhailArkhipov** [comment]
#2176 is the majority or work. We will investigate  machine specific in RTM

**Comment by MikhailArkhipov** [comment]
Folding into #2385
