### ISSUE TITLE
Can't continue debugging with Enter

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1572]
Typing "c" can advance debugging steps, but just typing Enter key can't when debugging with browser() or debug() functions.
![capture](https://cloud.githubusercontent.com/assets/3863577/14565303/68c07d5e-0365-11e6-9177-d7593e467eda.PNG)

OS Information 
    Version:       Microsoft Windows NT 10.0.14316.0 
RTVS Information: 
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.3.20413.2227

**Comment by smortaz** [comment]
this is a bug in the main VS repl, not RTVS i believe.  RTVS essentially
doesnt "see" that you've hit enter.  they've been informed.

**Comment by huguesv** [comment]
Yes, it's this issue: https://github.com/dotnet/roslyn/issues/8569 and we have a PR pending to fix it: https://github.com/dotnet/roslyn/pull/9894

**Comment by Marchen** [comment]
Thanks for the comments, I got it.

**Comment by huguesv** [comment]
Fix has now been merged into Roslyn, and will be available with Visual Studio 2015 Update 3.
