### ISSUE TITLE
Default encoding of R Markdown file created by RTVS cause garbling of non-ascii characters

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1573]
Default encoding of R Markdown seems to be system encoding (for my case, it was Japanese CP932), but it causes garbling of Japanese text in HTML.
If I change the encoding of the R Markdown file to UTF-8, Japanese characters are shown correctly.
So I think for the default encoding of R Markdown file, UTF-8 is more preferable.

![rmd](https://cloud.githubusercontent.com/assets/3863577/14566497/c6436716-036a-11e6-9255-0e0d177e273a.png)

**Comment by MikhailArkhipov** [comment]
We use the same template as RS and generally pass same options to ```rmarkdown::render```. However, when saving file we should be setting encoding via ITextDocument.Encoding
https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.text.itextdocument.encoding.aspx

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/06dd7fe7f461afe30972f30b903ec51ae9337950

**Comment by Marchen** [comment]
Thanks for the fix!
