### ISSUE TITLE
VSBlogPost project shows up as incompatible

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1581]
https://github.com/jflam/VSBlogPost

![image](https://cloud.githubusercontent.com/assets/1175142/14578072/6aec4de2-0333-11e6-950e-32014593d5ea.png)

This is in experimental VS instance with the most recent bits from master. It seems to be something about this particular project, as I can create new projects and re-open them fine.

**Comment by int19h** [comment]
The project in question is missing one line that I can see in other projects:
```xml
  <Import Project="$(MSBuildUserExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\RTVS\Rules\rtvs.rules.props" Condition="Exists('$(MSBuildUserExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\RTVS\Rules\rtvs.rules.props')" />
```
Adding that missing line fixes it.

So this only affects running in experimental hive. But I'm still curious as to why that was missing. Did we add it to the project template at some later point, after John has already started working on the project?

**Comment by AlexanderSher** [comment]
No, we don't include this line in release version of RTVS: 
```{csharp}
        private IEnumerable<XImport> CreateMsBuildExtensionXImports(string import) {
            var msBuildImportExtensionPath = Invariant($@"$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\{import}");
#if DEBUG
            var msBuildImportUserExtensionPath = Invariant($@"$(MSBuildUserExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\{import}");

            yield return new XImportExisting(msBuildImportUserExtensionPath);
            yield return new XImportExisting(msBuildImportExtensionPath, $"!Exists('{msBuildImportUserExtensionPath}')");
#else
            yield return new XImportExisting(msBuildImportExtensionPath);
#endif
        }
```

**Comment by int19h** [comment]
Is there any particular reason why we suppress it? It would be no-op unless running in experimental, but at the same time it prevents opening user projects in experimental (for debugging etc) unless this change is applied. It might also be very confusing to anyone who might try to build RTVS, and suddenly their projects are not opening.

**Comment by AlexanderSher** [comment]
It is not related to Experimental version of VS. It depends on what build of RTVS you use - debug or release. If you install debug version of RTVS, you'll get the same effect.

**Comment by int19h** [comment]
That's even worse then. We might want to provide debug builds to users occasionally to diagnose issues.

I think we should just use the `#if DEBUG` branch in all cases, and drop the other one.

**Comment by AlexanderSher** [comment]
To reproduce the issue, they will have to
- Install debug build
- Create project
- Uninstall debug build (otherwise project will find `rtvs.rules.props` in Program Files)
- Download sources
- Build and run RTVS from VS (so that it is deployed without MSI)

Do you think it is reproducible by any real user?

**Comment by int19h** [comment]
No, I mean the other way around. Suppose they install a release build and create a bunch of projects. Then later they decide that they want to build the product itself from source, and do so using our instructions (which will result in debug build running in experimental hive by default). Then try to open some of their existing projects created by "normal" RTVS with that built product. They're going to run into this error, no?

Though for me, the fact that I cannot open any project coming from a user that was created with a release build, in my local debug build, without touching the project file, is sufficiently inconvenient to want this change.

**Comment by AlexanderSher** [comment]
Ok, let's do it your way.
