### ISSUE TITLE
Pandoc not found

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1582]
Pandoc is installed:

![image](https://cloud.githubusercontent.com/assets/1175142/14578188/3d722640-0336-11e6-8d86-06b9ad39a370.png)

(as are `knitr` and `rmarkdown` packages)

But when doing "Preview HTML", I get this:

> Error: pandoc version 1.12.3 or higher is required and was not found.
> Execution halted
> Markdown conversion failed

I've also tried restarting VS, since I installed Pandoc after getting the message for the first time. But it still can't find it after the restart.

**Comment by int19h** [comment]
It might have something to do with the installation path. I used the default that Pandoc installer suggested, which is `C:\Users\int19\AppData\Local\Pandoc` (so it was a per-user install). Do we require a global install?

**Comment by int19h** [comment]
@jflam, do you remember if you had to do any extra steps above and beyond what's here?
http://microsoft.github.io/RTVS-docs/rmarkdown.html

**Comment by MikhailArkhipov** [comment]
It needs to be installed globally and VS needs to restart to pick up new PATH.

On Apr 15, 2016, at 18:30, Pavel Minaev <notifications@github.com<mailto:notifications@github.com>> wrote:


@jflam<https://github.com/jflam>, do you remember if you had to do any extra steps above and beyond what's here?
http://microsoft.github.io/RTVS-docs/rmarkdown.html<https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fmicrosoft.github.io%2fRTVS-docs%2frmarkdown.html&data=01%7c01%7cmikhaila%40microsoft.com%7cbd3ef92f349d4558779b08d36596b132%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=axG5xXpCuleEOcf%2b3V4syhhi40%2fYSmUFmpNVyAc3rdQ%3d>

-

**Comment by int19h** [comment]
Okay. This needs to be doc'd somewhere, because by default Pandoc installs per-user, and it's not readily obvious that you even have other alternatives (it's hidden under "Advanced").

**Comment by int19h** [comment]
Hm... I've reinstalled Pandoc globally - it's now in `C:\Program Files (x86)\Pandoc` - but `rmarkdown` still can't pick it up (after VS restart). Same exact error message.

**Comment by int19h** [comment]
Ah, figured it out. Since I was running in experimental hive, I had to restart the "outer" VS instance, too. It works now.

**Comment by jflam** [comment]
I’ll update the docs to reflect the restart in case they have VS running.

**Comment by MikhailArkhipov** [comment]
Yes, the message is cryptic, it is coming from rmarkdown package without explanation what to do :-( . This is why RS install pandoc locally inside RS installation folder. Pandoc is GPL though and we won't be able to directly preinstall it in Dev15 Willows file-only setup. However, we can consider creating 'third party components' setup as MSI like Cortova tools used to have and offer users to run it at RTVS first launch. Opened https://github.com/Microsoft/RTVS/issues/1589

**Comment by int19h** [comment]
So it turns out that per-user or global install doesn't actually matter; the only real problem here was caused by running in experimental hive, and not restarting the host VS. On the doc side, John has already updated it to indicate that restart is needed, so this is fixed.

**Comment by MsSQLGirl** [comment]
I have installed Pandoc and it looks like RTVS still thinks that I don't have it installed. However, when I run VS2015 in Administrator mode, this seems to work just fine. 

Julie

**Comment by MikhailArkhipov** [comment]
Pandoc is located by system PATH. It can be installed for a single user - but please install it for all users on the machine. You need to restart VS since changes in system environment variables do not propagate to running processes.
