### ISSUE TITLE
Rmd doesn't have lightbulbs for library

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1583]
In regular .R files, there is a lightbulb for `library()` statements which lets you install the referenced package quickly. This lightbulb doesn't show in .Rmd files, however.

**Comment by MikhailArkhipov** [comment]
Similarly, R completion doesnt work in RMD - if we made R projected language we'd get everything

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/080da5457cc2e72ce0becb078822e6de85a18cc9
