### ISSUE TITLE
Preview HTML of   R Markdown doesn't show embedded plot

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1585]
![rmarkdown](https://cloud.githubusercontent.com/assets/3863577/14578817/60221752-03ce-11e6-9825-3ce04e2575a7.PNG)

**Comment by MikhailArkhipov** [comment]
Preview is part of Web Essentials, not RTVS. https://github.com/madskristensen/WebEssentials2015

**Comment by Marchen** [comment]
I got it. Sorry for my misunderstanding...
