### ISSUE TITLE
echo=FALSE doesn't work in HTML preview of R Markdown

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1586]
![rmarkdown](https://cloud.githubusercontent.com/assets/3863577/14578847/2d42d946-03d0-11e6-9978-90272835d826.PNG)

**Comment by MikhailArkhipov** [comment]
This preview comes from Web essentials, not RTVS. It doesn't know about R. See https://github.com/madskristensen/WebEssentials2015

**Comment by Marchen** [comment]
I got it!
