### ISSUE TITLE
Can't convert R Markdown to Microsoft Word by missing 'yaml' package

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1587]
Because 'yaml' package is not installed by default, making Word file failed with following message.

> Markdown conversion failed
> Error in loadNamespace(name) : there is no package called 'yaml'

**Comment by MikhailArkhipov** [comment]
#1589

**Comment by MikhailArkhipov** [comment]
We now auto-install `rmarkdown` on demand ant brings `yaml`

**Comment by Marchen** [comment]
Thank you for your great effort!!
