### ISSUE TITLE
Can't preview R Markdown with UTF-8 encoding

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1588]
R Tools > Publish > Preview HTML, couldn't render R Markdown file having non-ascii (Japanese) characters in code chunk encoded by UTF-8.
The error message was like "Invalid multibyte characters while syntax analyzing" (translated from Japanese).

![markdown](https://cloud.githubusercontent.com/assets/3863577/14581429/5c61728e-0428-11e6-9a52-acfe8df70d68.PNG)

Because preview function worked if I saved the file with CP932 encoding, i.e. my system encoding, I guess RTVS passing system encoding to rmarkdown::render() rather than encoding of the file.

**Comment by MikhailArkhipov** [comment]
This was fixed with https://github.com/Microsoft/RTVS/commit/06dd7fe7f461afe30972f30b903ec51ae9337950. Should appear in updated 0.3 on Monday
