### ISSUE TITLE
Support Add Connected Service

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1594]

**Comment by huguesv** [comment]
A connected service defines a wizard UI to configure the service, and a handler for each technology/project type that it supports.

It is possible to add a handler in our VSIX that adds R support for an existing connected service.

Example stub for adding R support for Azure Storage:
```
    [ConnectedServiceHandlerExport("Microsoft.Azure.Storage", CustomEvaluator = true)]
    class AzureStorageConnectedServiceHandlerR : ConnectedServiceHandler, IVsHierarchyCustomEvaluator {
        public override Task<AddServiceInstanceResult> AddServiceInstanceAsync(ConnectedServiceHandlerContext context, CancellationToken ct) {
            throw new NotImplementedException();
        }

        public bool Evaluate(IVsHierarchy hierarchy) {
            Guid typeGuid;
            hierarchy.GetGuidProperty(VSConstants.VSITEMID_ROOT, (int)__VSHPROPID.VSHPROPID_TypeGuid, out typeGuid);
            object typeName;
            hierarchy.GetProperty(VSConstants.VSITEMID_ROOT, (int)__VSHPROPID.VSHPROPID_TypeName, out typeName);
            bool supported = typeGuid == RGuidList.CpsProjectFactoryGuid && ((string)typeName) == "R";
            return supported;
        }
    }
```

**Comment by huguesv** [comment]
We need to decide on which connected service we want to support in R.  AFAIK, none of the existing connected services even have R libraries for their service, so it doesn't make sense to add R project support for them until someone creates the R library first.

**Comment by MikhailArkhipov** [comment]
That one actually may be us :-)

I can imagine Blobs and Tables. Also, there is SalesForce service in VS and it appear to have the adapter https://hiratake55.wordpress.com/2013/03/28/rforcecom/

**Comment by MikhailArkhipov** [comment]
Also, it looks like R Server can access blobs

https://github.com/Azure/azure-content/blob/master/articles/hdinsight/hdinsight-hadoop-r-server-storage.md

maybe we could borrow some code.

**Comment by MikhailArkhipov** [comment]
Probably pending creation of Azure SDK for R. We don't have bandwidth to code this ourselves.

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
