### ISSUE TITLE
R Application

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1595]
R Applications integrate the semantics of R execution with how Visual Studio treats projects. For example, if you hit `F5`, you expect Visual Studio to start executing your program under control of the debugger. But what executes? There is no `main()` function in R. 

The work in this epic will create different notions of R projects including a `Basic Project` which is roughly analogous to a console application. There will also be a `Web Service Project` which is a unit of code that can be deployed to Azure, as well as a `Shiny Project` for Shiny applications.

A key aspect of the application is having a place to store the metadata for the project (e.g., what files get sourced when the user hits `F5` or `CTRL+F5`).

**Comment by Victsz** [comment]
I built a c# program with R client api.

When deploy the program (simply copy all files under Debug folder to another machine with R installed), an exception throws at StartHostAsync.
_session = RHostSession.Create(id);
_session.StartHostAsync(new RHostSessionCallback()).Wait();

Did I miss somthing?

**Comment by MikhailArkhipov** [comment]
Is `Microsoft.R.Host.exe` present in the folder? You can try and run it directly just to check that it starts. Same for the `Microsoft.R.Host.Broker.exe`

**Comment by Victsz** [comment]
Yes, but 
![image](https://user-images.githubusercontent.com/8154646/29980154-1051c33c-8f7b-11e7-9d5e-e44eb71c7b0a.png)

**Comment by Victsz** [comment]
That machine has RStudio and R installed and works just fine

**Comment by MikhailArkhipov** [comment]
The message is normal since path to the selected R is set to the R process environment by the broker process. Running executable manually fails b/c R is often not on the path. What happens if you run 'Microsoft.r.host.broker.exe`.

**Comment by Victsz** [comment]
![image](https://user-images.githubusercontent.com/8154646/29992360-883a28d4-8fcc-11e7-8b52-afbba31f32b2.png)

And for Microsoft.R.Host.exe, besides Rgraohapp.dll missing, R.dll and VCRuntime140.dll are missing as well.

What`s the prerequisite to start R host ,its broker and R Client API c# program?

And I have check the app.config

**Comment by MikhailArkhipov** [comment]
Missing `VCRuntime140.dll` is probably the issue. You can try copying it along with the binaries. R dlls are usually located at run time by the broker. 

Missing certificate message is fine, you are not doing remote connection to R.  I just wanted to check that broker does not report missing dependencies.

**Comment by Victsz** [comment]
Copy VCRuntime140.dll solves the problem.^_^

**Comment by MikhailArkhipov** [comment]
Great. I will fix the package to include the runtime.
