### ISSUE TITLE
Intellisense should be disabled for readline() in interactive window

### ISSUE THREAD

**Issue by timsneath** [Microsoft/RTVS#1605]
readline() is of course used for user-generated text. It should therefore not trigger IntelliSense when used in the interactive window. See, for example, the way that swirl() prompts me with inappropriate content (in this case, one of the sample datasets). 

![image](https://cloud.githubusercontent.com/assets/2319867/14583951/fd804bfa-03e6-11e6-9bd4-2433ba691638.png)

This is R Tools for Visual Studio 0.2, running with Microsoft R Open on Visual Studio 2015 Update 2.

**Comment by int19h** [comment]
We also do unnecessary syntax highlighting and parse error squiggles in this case.

The tricky part is figuring out that a particular prompt is `readline` vs REPL prompt. R doesn't provide any explicit flags here in its `ReadConsole` callback, but it might be possible to distinguish by looking at the current context stack - need to investigate.

**Comment by huguesv** [comment]
The `addToHistory` parameter to `ReadConsole` callback appears to be reliable for this.
Regular code input: 1
Browse prompt: 1
Press ENTER for next plot: 0
scan: 0

I looked at where R_ReadConsole within R itself, and they consistently pass 0 when it's non code input.

**Comment by int19h** [comment]
Ah, very nice. We should flow that through the code in `IRSessionInteraction` and have the REPL check.

**Comment by AlexanderSher** [comment]
What should happen if `readline` is part of multiline input or there are pending inputs in Interactive Window queue?

**Comment by int19h** [comment]
It looks like it gives us an opportunity to actually fix that scenario. We should stop processing pending inputs, and let the user interact with the prompt.

BTW, we should also wire this up to `BeginInteractionAsync` so that it ignores non-code prompts entirely - right now you can actually send some code in response to one, and only a few places check the context (e.g. debugger _usually_ checks for Browse). Ideally there should be a way to specify whether you want to respond to anything, or code only, or non-code only; but I don't think we have any present scenarios where we use interactions for anything other than code, so we can keep it simple.

**Comment by AlexanderSher** [comment]
That's something I need to verify. In `RInteractiveEvaluator.ExecuteCodeAsync` we call `BeginInteractionAsync` multiple times, so if we get readline after one of these requests, we should not process the next one until `addToHistory` is true again, which will not allow `ExecuteCodeAsync` to complete.

**Comment by int19h** [comment]
I think that's fine. If the code snippet contains a `readline()`, then it's logical that it doesn't complete until user provides input, and whatever is waiting for completion should keep waiting until that's done. It's similar to the case where they, say, show a message box or other blocking UI.

**Comment by AlexanderSher** [comment]
No, I need to check if `InteractiveWindow` supports such scenario :)

**Comment by int19h** [comment]
Oh, you mean reading input while code is running? Pretty sure it does, as that's exactly what the separate read input method was provided for. PTVS triggers that in some cases when configuring dependencies (e.g. when a new Django project is created, initializing it runs some Python code in the REPL, which will prompt things like username and password for admin).
