### ISSUE TITLE
Running project in solution with multiple projects 

### ISSUE THREAD

**Issue by sriksrid** [Microsoft/RTVS#1615]
Hi

I have a solution that has an R project and a Python project. I am unable to set the R project as the startup project (or run/debug any R script from the solution explorer). When I right click the R project, both options under Debug (Start New Instance and Step Into New Instance) are both grayed out.

Is there a way to run/debug the R code in such a situation?

Thanks

**Comment by MikhailArkhipov** [comment]
Generally speaking, there is no concept of 'entry point' in R and thus it is unknown which code to launch on F5. Debugging in R begins with attaching debugger first and then sourcing the code and calling the desired function from the interactive window.

**Comment by MikhailArkhipov** [comment]
Have a look at https://github.com/Microsoft/RTVS/issues/1595 which we are considering for the future.

**Comment by MikhailArkhipov** [comment]
Also, here is doc on R debugging https://microsoft.github.io/RTVS-docs/debugging.html

**Comment by sriksrid** [comment]
Thanks. I couldn't see any information in #1595, so what I type below might be a duplicate. 
I personally like the way PTVS handles this issue - I can designate a particular script as startup script. Additionally, any file can be run (from a context menu) with or without debugging. 

Thanks for the great work on this awesome tool.
