### ISSUE TITLE
REPL hang after detach debugger with multiple breakpoints

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1625]
"\\pytools\r\Bugs\1625\rproject17.zip"

Extract to your machine and open above solution
Attach debugger
Source hist.R (breakpoint first line)
Stop debugger
Notice `browse` prompt still there
Type `1` + enter
REPL hangs

**Comment by int19h** [comment]
Neither me nor Hugues could get a reliable repro lately, but there is a good reason to suspect that this is a dupe of #1629, so closing as such for now.
