### ISSUE TITLE
Hang after sending multiple lines to REPL in one block

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1629]
Start VS
Create new project
Insert the following code in the editor
```
url <- "https://cran.revolutionanalytics.com/web/packages/packages.rds"
tf <- file.path(tempdir(), "packages.rds")
download.file(url, destfile = tf, mode = "wb")
extra <- readRDS(tf)
```
Line by line, send to REPL with CTRL-ENTER

Result: everything works as expected

Reset the REPL (IMPORTANT!)

CTRL-A then CTRL-ENTER to send all the lines at once

Result: REPL hangs

**Comment by MikhailArkhipov** [comment]
Should have a look in 0.3

**Comment by huguesv** [comment]
Turns out you need to have package manager window open, if it has never been opened in this VS instance, then it won't repro.

**Comment by int19h** [comment]
So likely related to that other hang issue with package manager that you've had?

**Comment by huguesv** [comment]
The one with breakpoints?  Not sure, could be.

**Comment by int19h** [comment]
Can repro. The hang does not preclude resetting the REPL again, but after reset, any further input will bring it to the same state again, requiring a VS restart.

**Comment by int19h** [comment]
https://github.com/Microsoft/R-Host/pull/60
