### ISSUE TITLE
VE shows Excel icon for expression objects.

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1643]
```r
expr <- body(source)
```
Then observe `expr` in VE. It will have the Excel icon, which, when clicked, produces this error in the REPL:
> Error in as.data.frame.default(x[[i]], optional = TRUE) : 
> cannot coerce class ""{"" to a data.frame

Which is not unexpected. Really it just shouldn't show the Excel icon for these in the first place.

**Comment by MikhailArkhipov** [comment]
Also #1376 #1374
