### ISSUE TITLE
file downloaded is wrong version

### ISSUE THREAD

**Issue by EngrStudent** [Microsoft/RTVS#1652]
You say this is version 0.3, but when I hit "download" it gives me 0.2.

**Comment by MikhailArkhipov** [comment]
0.3 is not public yet, it is going through testing at the moment. Hence the official/public download link is still 0.2

**Comment by EngrStudent** [comment]
I was invited to 0.3, and clicked the 0.3 link.  It gave me 0.2.

**Comment by jflam** [comment]
What version does RTVS say it is in the About box? If you're using our invite link (I just verified) you will get the 0.3 build from 4/18.
