### ISSUE TITLE
Simple button to remove all objects

### ISSUE THREAD

**Issue by fabriciovasselai** [Microsoft/RTVS#1653]
It would be useful to have a simple button in R-Interactive to remove all objects from memory, just like the option available in main R's "Misc" menu - the one that passes the following command to the console:

`rm(list=ls(all=TRUE))`

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8686cc5e5132f2336df3950b9d1765abdc44c6e5
