### ISSUE TITLE
Inputting Roxygen comment block by ### doesn't work

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1660]
I turned on automatic formatting, but inputting ### did not insert Roxygen comment block.

![editor_option](https://cloud.githubusercontent.com/assets/3863577/14699582/e714e5f6-07d3-11e6-8d59-cbe429bb9f99.PNG)
![options](https://cloud.githubusercontent.com/assets/3863577/14699583/e7167da8-07d3-11e6-87f2-7551213db5e6.PNG)

**Comment by MikhailArkhipov** [comment]
This functionality doesn't depend on formatting. However, it needs function definition to work. Both ```###``` and context menu item work when invoked right before the function definiton such as

```
###
x <- function(...) {
}

**Comment by Marchen** [comment]
Thanks for the explanation. Just before a function definition, it worked correctly.
