### ISSUE TITLE
Preview 0.4

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1664]
# 0.4 Release Planning

This is the master epic that encapsulates the list of things that we are doing in the 0.4 release.

## Release Process

The scheduled public ship date for 0.4 is 6/20. 

We typically take ~2 weeks from code complete to shipping a release:

- On 6/6, internal testers at Microsoft will get a notification of the new release. 
- On 6/9, we will ship a release to a subset of our external Early Access customers. (If you want to join our Early Access customer list, send mail to [rtvs-invite@microsoft.com](mailto:rtvs-invite@microsoft.com)).
- On 6/13 we will ship a release to the remainder of our Early Access customers.
- On 6/20 we will ship a release publicly

All of our releases will be signed by Microsoft. You are, of course, welcome to create your own nightly builds yourself to gauge our progress. Read [the contribution guide](https://github.com/Microsoft/RTVS/blob/master/CONTRIBUTING.md) for details on how to build your own copy of RTVS from the sources.

## Big Rocks

The 0.4 release has a number of "big rocks" or areas that we are investing in. There are epics that describe each of these areas:

#1595 *R Application* contains the work to define what an "R Application" is in Visual Studio. Think of this work as the project metadata necessary to enable users to easily create Shiny Applications, or R code that can be deployed as a web service. 

#1614 *Editor improvements* is the catch-all set of improvements to the editor. We are doing a relatively small number of improvements in the editor for 0.4: 
- #1122 IntelliSense for variables in packages
- #836 IntelliSense for package methods in function arguments
- #1591 Peek / Goto definition for functions in packages
- #1605 IntelliSense should not appear during readline() operations

#1602 *Variable Explorer improvements*. We have a significant investment in improving the Variable Explorer and the Data Grid in 0.4. We will add searching and categorization in the variable explorer, and have a multi-instance Data Grid as well:
- #1113 Search in Variable Explorer
- #1123 Remove variables from R Session
- #1372 Display variables in categories (functions, data frames). Related to #1601 
- #1375 Double-clicking on a function will go to definition
- #1404 Improve the Data Grid's title
- #499 Create a multi-instance Data Grid
- #1371 Improve the display of functions in Variable explorer by showing tooltip with signature
- #1373 Ensure that the Variable Explorer shows up when switching to debug window layout
- #1377 and #1423 bug fixes 

#1635 *Quality and code hygiene*. This captures the work that we are doing to improve the baseline quality of the product through refactoring and test improvements.
- #1553 Import Data code refactoring to improve testability
- #554 Improve stability of tests that create isolated RHost sessions
- #1121 FxCop clean
- #1626 Improve stability of image comparisons in plot tests

## Smaller investments

We also have smaller investments that we are making in targeted areas.

#1632 *Markdown editor improvements*. We are investing lightly in the markdown editor in 0.4:
- #1072: Enable sending R commands from history to the markdown editor
- #1309: Execute an entire block of R code within an R markdown document

#1534 *UI actions that result in R commands should be captured in REPL and History*. In response to customer feedback, we will ensure that UI actions that execute R code will have that R code sent to the REPL and captured in command history.
- #1551 Variable Explorer data import will send read.csv command to REPL
- #1489 Package Manager will send library() and detach() commands to REPL

#1620 *R Packaging and Versioning Improvements*. This is a long-lead project where we want to make significant improvements in the versioning story for R. The goal is to move the R community closer to the model supported by Python through `requirements.txt` or JavaScript through `packages.json`. This starts with a versioning proposal (#1634) that will be circulated to the R community and the RStudio folks where we define a protocol for for how versioning should work for both public and private R package repositories.

#1589 *Improve setup experience for 1st and 3rd party dependencies*. This epic encompasses work to improve the setup experience for external dependencies such as pandoc (an MSI-based install), rmarkdown (an R package), and Microsoft's R distribution (an MSI-based install). This work will add features to the product to enable installing these dependencies at runtime when those features are required by the user. This work will also make it possible to have those dependencies installed during the initial install of RTVS.

#1386 *Ensure RTVS runs on Dev15*. This epic encapsulates work that we need to do in build / setup / codebase to ensure that RTVS will install on Dev15 "classic mode".

**Comment by MikhailArkhipov** [comment]
Apart from bugs and updates to Dev15 we are done
