### ISSUE TITLE
R Interactive hangs on reset

### ISSUE THREAD

**Issue by jmagosta** [Microsoft/RTVS#1665]
Please briefly describe what you were doing that led to the issue, if applicable:

1. load a data.frame
2. inspect it with head()
3. reset R interactive from the ribbon
4. >> variable name still exists in .GlobalEnv, but the variable does not

     head() hangs

The variable still appears in the Variable Explorer, but cannot be inspected. 
    >  ls()
character(0)

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

Additional resets appear to clear the problem. 

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.3.20418.1523, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO\R-3.2.4

**Comment by int19h** [comment]
Thanks for reporting it! Most likely, this is the same issue as in #1629. Would you be interested in testing the fix? If so, please ping me at rtvsuserfeedback@microsoft.com

**Comment by int19h** [comment]
We have now shipped RTVS 0.4, which contains the likely fix for this issue. If you have had a chance to try it out, could you share your experience? Are you still running into this problem?

**Comment by MikhailArkhipov** [comment]
0.3 I think :-)

**Comment by int19h** [comment]
I'll close this for now - please reopen if it still repros.
