### ISSUE TITLE
Path completion IntelliSense does not work in Code Snippet expansion

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1671]
Repro:

readc<TAB><TAB>

First parameter is the path to the file. Press <TAB> to highlight the file parameter. Now try and invoke path IntelliSense while focus is set there. Note there probably should be a keyboard shortcut for activating file completion IntelliSense as well.

**Comment by MikhailArkhipov** [comment]
Path completion does not know if particular parameter is a path. It is just a string. Path completion works only at the end of a string that ends with /. Invoked with TAB. ```"C:/|"```

**Comment by MikhailArkhipov** [comment]
So actually it works (Ctrl+J brings it up), but completion fights with TAB navigation between snippet fields. Not sure how to resolve this...

![image](https://cloud.githubusercontent.com/assets/12820357/14930511/4320f6f0-0e19-11e6-976a-448419869670.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8686cc5e5132f2336df3950b9d1765abdc44c6e5
