### ISSUE TITLE
Parameter alignment auto-formatting breaks Code Completion

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1672]
xyplot<TAB><TAB>

The nice reformatting of parameters puts all of the highlighted tab completions in the wrong areas:

![image](https://cloud.githubusercontent.com/assets/8877/14746775/12b6ee4c-0866-11e6-924b-a5b1bf5e7749.png)

**Comment by MikhailArkhipov** [comment]
#1640. Multiline snippets are not particularly useful in REPL due to its stitched buffer nature. Also, We have no control over highlights, it is very old IDE code (circa 2003-2005). It is not known up front if particular snippet is going to be multiline or not.

**Comment by MikhailArkhipov** [comment]
Need to look into if we can suppress some snippets in REPL

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0e1f37a27c39fe0e6694ac171b5e6eebe648bd1f
