### ISSUE TITLE
Provide options to control space between ) and {

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1677]
Between ) and { of a function definition, code formatting put extra space like `function() {`.

**Comment by MikhailArkhipov** [comment]
Can you please give code example? I see a single space in

```
x <- function() {

}
```

in both autoformat and format document cases. Thanks

**Comment by Marchen** [comment]
Sorry for my bad wording.
I don't want to add space between ) and {, but RTVS add a space when I turned on automatic formatting.
But if turn on auto-formatting place of a closing curly brace become somewhat strange (#1689).

Usually I don't put space between ) and { though I'm not sure it's a common coding style.
If RTVS have a option to control space between ) and {, its better for me.

**Comment by MikhailArkhipov** [comment]
Yes, automatic settings do provide space between ) and {. they are set per common guidelines such as https://google.github.io/styleguide/Rguide.xml . We will consider adding more customization in the future.

**Comment by Marchen** [comment]
Thanks for the comment. I just find space between ) and { is a common coding style!
But all my codes having style of ){, so I hope RTVS will have this option, not only in function definition, but in other statement like if, for, while, etc.

**Comment by MikhailArkhipov** [comment]
Added in https://aka.ms/rtvs-1.0rc3

**Comment by Marchen** [comment]
Thanks! It works well!
