### ISSUE TITLE
Editor steals focus when evaluating expressions at Browse> prompt when debugging

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1678]
When debugger is attached and REPL is at a Browse> prompt, and an expression is evaluated at that prompt, the focus is transferred to the editor, again highlighting the current line in the code that is about to be executed.

This is inconvenient for someone who is just trying to evaluate several expressions one by one while e.g. paused at a breakpoint, because they need to change focus to the REPL every time they press Enter. It's too easy to not notice, too, and end up typing in the wrong place.

**Comment by int19h** [comment]
The fundamental problem is that every time you type something for execution in the REPL, the Browse> prompt that follows is a _new_ prompt; and the debugger has no way to tell if it's "really new", or if it's "same as before". For example, consider code like this:
```r
f <- function() {
  browser()
}
f()
```
And suppose we have a breakpoint at the last line. When it's hit, R reports it as a Browse> prompt, and debugger responds by indicating a Break event and producing a call stack. VS handles that by opening that file in the editor (or focusing it if it's already opened), and moving cursor to the line of code indicated by the topmost stack frame.

Now the user types `1+2` in the REPL. Since R is evaluating now and not awaiting commands, the debugger has to report that execution has resumed to VS, which applies appropriate changes to UI, such as disabling "Continue" button and enabling "Pause", hiding Call Stack and Locals etc. 

Now R evaluates it, prints out the result, and produces a new Browse> prompt, at the same location and stack as before. The debugger has to report another Break event to VS, which then treats it in the same manner as the first Break - again focusing that line of code in the editor.

But, furthermore, the expressions that user evaluates at the prompt won't necessarily result in a new prompt being at the same location as the previous one. Imagine if user types `c` at the prompt - that isn't really an expression then, it's a browser command "continue", which will cause execution to continue, invoking `f()`, and stopping at the `browser()` call inside - which changes the current executing location, so we need to reflect that.

And it's not necessary for the code executed in REPL to be a browser command. The user could simply type `f()` - that would be an expression, not a command, but when evaluated, it would again hit `browser()`, and change the current position / call stack.

Thus, there are two problems here.

First, after every REPL expression evaluation, the R debugger component needs to be able to determine whether the new Browse> is at the same location as the one before the evaluation; that can be done by remembering and comparing the stacks.

Second, after the debugger has determined that location is identical, it needs some way to communicate it to VS to disable its focus-on-editor-after-break behavior. There does not seem to be any existing API that provides this, so it will probably require some changes on VS side of things. We could work around it by hijacking the focus back, but it would be visible (focus rapidly switching back and forth) and unreliable.

**Comment by MikhailArkhipov** [comment]
CheckPossibleBreakModeFocusChange() does this for breakpoint hits via

```_debuggerModeTracker.IsEnteredBreakMode```

now we need to know another condition...

**Comment by MikhailArkhipov** [comment]
Looks like https://github.com/Microsoft/RTVS/commit/715523de8ac656d765bb2b9f2260a46bbdc59fd3 broke the focus fix, see also #1902

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/79c0e2fbca7cdb1be13083e34edd8cb762cc44dd
