### ISSUE TITLE
Publishing markdown in folders named in Unicode fails

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1679]
```
In addition: Warning messages:
1: In dir.create(output_dir, recursive = TRUE) :
  cannot create dir 'C:\Users\mikhaila\documents\visual studio 2015\Projects\rproject15\rproject15\????', reason 'Invalid argument'
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/mikhaila/documents/visual studio 2015/Projects/rproject15/rproject15/????": The filename, directory name, or volume label syntax is incorrect
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/mikhaila/documents/visual studio 2015/Projects/rproject15/rproject15/????/markdown.rmd": The filename, directory name, or volume label syntax is incorrect
Execution halted
Markdown conversion failed
```

will try setting cp for non-Unicode

**Comment by MikhailArkhipov** [comment]
Setting command line CP makes display OK but publishing still fails

```
Error in tools::file_path_as_absolute(input) : 
  file 'C:/Users/mikhaila/Documents/Visual Studio 2015/Projects/rproject15/rproject15/фыва/markdown.rmd' does not exist
Calls: <Anonymous> -> setwd -> dirname -> <Anonymous>
Execution halted
Markdown conversion failed
```

also, display of the temp folder is wrong. 

![image](https://cloud.githubusercontent.com/assets/12820357/14773575/5c82543e-0a60-11e6-9c1c-606db957764e.png)


Most probably same as #1661

**Comment by int19h** [comment]
Can we avoid Rscript for publish, and do direct eval in the current R session (or maybe a freshly spawned session)? I suspect the problem here is that it has to go through command line, which means that it has to undergo codepage/Unicode translation back and forth; whereas with eval, it's Unicode end-to-end now (if you use `REvaluationKind.Json` for the result).

**Comment by MikhailArkhipov** [comment]
Yeah #1156

**Comment by MikhailArkhipov** [comment]
After switching to R Host per #1156 both evaluation and interaction produce
```
Error in find_external_resources(original_input, encoding) : 
  The input file file 'C:/Users/mikhaila/Documents/Visual Studio 2015/Projects/rproject6/rproject6/<U+0444><U+044B><U+0432><U+0430>/mark down.rmd' does not exist.
In addition: Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/mikhaila/Documents/Visual Studio 2015/Projects/rproject6/rproject6/<U+0444><U+044B><U+0432><U+0430>": The filename, directory name, or volume label syntax is incorrect
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/mikhaila/Documents/Visual Studio 2015/Projects/rproject6/rproject6/<U+0444><U+044B><U+0432><U+0430>/mark down.rmd": The filename, directory name, or volume label syntax is incorrect
3: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:/Users/mikhaila/Documents/Visual Studio 2015/Projects/rproject6/rproject6/<U+0444><U+044B><U+0432><U+0430>": The filename, directory name, or volume label syntax is incorrect
```

**Comment by int19h** [comment]
Are you using `REvaluationKind.Json`?

**Comment by MikhailArkhipov** [comment]
Yep

**Comment by MikhailArkhipov** [comment]
```find_external_resources(original_input, encoding)``` has encoding field...

**Comment by MikhailArkhipov** [comment]
We need to provide an option to set locale at the host start. The option should have 'Default' and 'OS OEM code page'. In the future we could provide actual list, but these two should be sufficient in most cases.

**Comment by MikhailArkhipov** [comment]
Neither ```setlocale(LC_CTYPE, "")``` nor ```setlocale(LC_CTYPE, ".OCP")``` seem to work (va msvcrt). There is a list of locale names msvcrt support and it is orthogonal to list of cultures. I can get OEM codepage, but 1251 or 866 map to several cultures that use Cyrillic. So what we could do it provide list of locales in Options and let user set R locale manually. Or just leave this as is and user will have to set locale in R as in other environments.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c318fdd428f4323e39844919b0a56d45c155511f
