### ISSUE TITLE
Unreadable characters while installing packages on VS 2015 Comm (Simplified Chinese)

### ISSUE THREAD

**Issue by hszest** [Microsoft/RTVS#1681]
The whole scene is below:

> install.packages("ggplot2")
»¹°²×°ÏàÒÀ¹ØÏµ¡®stringi¡¯, ¡®magrittr¡¯, ¡®colorspace¡¯, ¡®Rcpp¡¯, ¡®stringr¡¯, ¡®RColorBrewer¡¯, ¡®dichromat¡¯, ¡®munsell¡¯, ¡®labeling¡¯, ¡®digest¡¯, ¡®gtable¡¯, ¡®plyr¡¯, ¡®reshape2¡¯, ¡®scales¡¯

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/stringi_1.0-1.zip'
Content type 'application/zip' length 14270876 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/magrittr_1.5.zip'
Content type 'application/zip' length 149779 bytes (146 KB)
downloaded 146 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/colorspace_1.2-6.zip'
Content type 'application/zip' length 391253 bytes (382 KB)
downloaded 382 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3224907 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/stringr_1.0.0.zip'
Content type 'application/zip' length 83259 bytes (81 KB)
downloaded 81 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/RColorBrewer_1.1-2.zip'
Content type 'application/zip' length 26684 bytes (26 KB)
downloaded 26 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/dichromat_2.0-0.zip'
Content type 'application/zip' length 147670 bytes (144 KB)
downloaded 144 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/munsell_0.4.3.zip'
Content type 'application/zip' length 133881 bytes (130 KB)
downloaded 130 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/labeling_0.3.zip'
Content type 'application/zip' length 40764 bytes (39 KB)
downloaded 39 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/digest_0.6.9.zip'
Content type 'application/zip' length 171707 bytes (167 KB)
downloaded 167 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/gtable_0.2.0.zip'
Content type 'application/zip' length 58055 bytes (56 KB)
downloaded 56 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/plyr_1.8.3.zip'
Content type 'application/zip' length 1114362 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/reshape2_1.4.1.zip'
Content type 'application/zip' length 503780 bytes (491 KB)
downloaded 491 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/scales_0.4.0.zip'
Content type 'application/zip' length 603750 bytes (589 KB)
downloaded 589 KB

trying URL 'http://mirrors.opencas.cn/cran/bin/windows/contrib/3.2/ggplot2_2.1.0.zip'
Content type 'application/zip' length 2001880 bytes (1.9 MB)
downloaded 1.9 MB

³ÌÐò°ü¡®stringi¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®magrittr¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®colorspace¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®Rcpp¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®stringr¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®RColorBrewer¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®dichromat¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®munsell¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®labeling¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®digest¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®gtable¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®plyr¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®reshape2¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®scales¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý
³ÌÐò°ü¡®ggplot2¡¯´ò¿ª³É¹¦£¬MD5ºÍ¼ì²éÒ²Í¨¹ý

ÏÂÔØµÄ¶þ½øÖÆ³ÌÐò°üÔÚ
	C:\Users\HONG\AppData\Local\Temp\RtmpcdIZas\downloaded_packagesÀï
starting httpd help server ... done
>

**Comment by int19h** [comment]
What is your RTVS version?

**Comment by hszest** [comment]
The whole environment:
Windows 7 SP1 x64 (Simplified Chinese)
Visual Studio 2015 Comm Update2 (Simplified Chinese)
RevoMath-3.2.4
MRO-3.2.4
RTVS_2016-03-04.1

**Comment by int19h** [comment]
Thanks! The date on RTVS installer indicates that you're using RTVS 0.2, in which this is a known issue (#1340) that has since been fixed. We will be shipping version 0.3, which includes the fix, to the public very soon.

**Comment by hszest** [comment]
Thanks :)
Also, when I started an R project on VS 2015, then a C# project ,the R windows(R variables and history, etc.) is still here, taking a large portion of screen space, so I have to close them manually one by one
Is it possible to make the R windows disappear automatically when I switch my working programming language?

**Comment by MikhailArkhipov** [comment]
Generally no. VS only closes or hides windows when you switch between 'modes'. For example, between  editing and debugging.

**Comment by hszest** [comment]
Thanks for the info, MikhailArkhipov
The left windows of last working programming language may become even more disturbing when more and more working languages with their own windows are added to VS

**Comment by smortaz** [comment]
perhaps R Tools should have a menu option + key sequence to close all RTVS
related windows in one action.

**Comment by int19h** [comment]
But then we have the reverse issue - those windows won't automatically reopen when you load an RTVS project.

And this problem also exists with PTVS, NTVS, C# and F# (their respective REPLs) and others.

In VS 2015, there is a feature called Window Layouts that is separate from vssettings, and captures _only_ the visibility and position of various windows inside the IDE. See Window | Save Window Layout and Window | Apply Window Layout. You can use these to create layouts for your various languages (or generic tasks), and then switch between them. Keyboard shortcuts for fast switching (Ctrl+Alt+1 etc) are provided, as well.

Unfortunately, VS doesn't have the notion of preconfigured layouts, like Eclipse does for its perspectives (a roughly equivalent feature). It also doesn't have automatic switching for layouts, e.g. depending on the project types in the currently loaded solution.

**Comment by hszest** [comment]
Thank int19h for the information
The Window Layouts works, though not automatic enough :)
I'm going to post the "automatic layouts for languages" idea on the VS 2015 feedback board

**Comment by int19h** [comment]
Can you link to that here, so that we can reference it in future discussions?

**Comment by hszest** [comment]
To int19h:
https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/13593123-the-vs-2015-needs-a-automatic-layout-mechanism-for

**Comment by smortaz** [comment]
upvoted.

**Comment by int19h** [comment]
Thanks!
