### ISSUE TITLE
VS crashes often - observed ever increasing CPU & RAM usage

### ISSUE THREAD

**Issue by ripvlan** [Microsoft/RTVS#1691]
Please briefly describe what you were doing that led to the issue, if applicable:

While using VS & R the CPU usage & RAM usage slowly increases over a 1 hour period until VS reports failure.  User input for both the R Interactive and VS (general) becomes slow to non-responsive.  

It appears that one must [Attach Debugger] in order for this to occur.  May also require an active breakpoint to be stopped at least once to begin the sequence (just a hypothesis - unconfirmed).

After situation begins - Detaching debugger doesn't resolve issue.  Also tried rm(list=ls()) with no change in behavior.

Note: VS "devenv.exe" consumes the memory - MS R host is the consumer of CPU.  
This is R 0.3 Preview.

Failure occurs in one of two ways:
  a) VS reports it is in an unstable mode "most probably caused by plugin" and closes/restarts
  b) Windows reports that VS has failed
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Red Herring or Hint?  Microsoft.R.Host.Client_REPL and MS.R.Host_RdData Logs are full of  "rtvs:::signature.help2('return', 'base')"
which returns the online help - also contained in the logs.

Last entry in ActivityLog.xml begins as such (full log attached)
   <entry>
    <record>543</record>
    <time>2016/04/25 20:16:40.168</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.OutOfMemoryException: Exception of type &apos;System.OutOfMemoryException&apos; was thrown.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetText(Int32 startIndex, Int32 length)&#x000D;&#x000A;   

[ActivityLog.xml.txt](https://github.com/Microsoft/RTVS/files/236714/ActivityLog.xml.txt)

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.1.7601 Service Pack 1

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.3.20418.1523, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO\R-3.2.3

**Comment by MikhailArkhipov** [comment]
Could you please send us Frown via  R Tools | Feedback with said logs. Thanks!

**Comment by MikhailArkhipov** [comment]
Might be issue with RD data parser. Taking over.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1dd47ee8d17f6da57b7aaa2d89649588ae03efa3
