### ISSUE TITLE
Just having solution open consumes 20% CPU

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1696]
No windows opened whatsoever. R Host is idle

![image](https://cloud.githubusercontent.com/assets/12820357/14835378/4d72c3a2-0bbe-11e6-8217-7eb39081c9fd.png)

**Comment by smortaz** [comment]
hmmm... i don't see that.  consistent?

**Comment by MikhailArkhipov** [comment]
Can't repro in 0.4 debug. Will try some more machines.

**Comment by MikhailArkhipov** [comment]
Seems to be a fluke
