### ISSUE TITLE
NullRef typing deparse()

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1699]
Type deparse() in REPL. Null reference processing signature. VS survives

**Comment by MikhailArkhipov** [comment]
Broken RD with syntax errors. Need to harden against them

```
deparse(expr, width.cutoff = 60L,
        backtick = mode(expr) 
            c("call", "expression", "(", "function"),
        control = c("keepInteger", "showAttributes", "keepNA"),
        nlines = -1L)
```

note comma missing after ```mode(expr)```

**Comment by int19h** [comment]
Are you sure it's broken? in RS, the doc for `deparse` looks like this:
```r
deparse(expr, width.cutoff = 60L,
        backtick = mode(expr) %in%
            c("call", "expression", "(", "function"),
        control = c("keepInteger", "showAttributes", "keepNA"),
        nlines = -1L)
```
Note the `%in%`. This looks like a valid expression to me - perhaps we're stripping that operator at some point before it's parsed?

**Comment by MikhailArkhipov** [comment]
Well there is no %in% in the RD and that causes R parser to parse function definition with errors and said named argument is missing value (looks like ```backticks=```). RD is written by humans (it is basically LaTex) so it can contain errors anyway.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c15056c2fa91884f38d5b672002d84598d3be5e1
