### ISSUE TITLE
Dev14.2 + Dev15 SxS debugger doesn't start

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1705]
Click Attach debugger

Unable to start debugging.
The system cannot find the file specified.

Repairing Dev14 doesn't help.

```
 	mscorlib.dll!System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int errorCode)	Unknown
>	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.Repl.Debugger.AttachDebuggerCommand.Handle() Line 64	C#
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.Commands.PackageCommand.OnCommand(object sender, System.EventArgs args) Line 26	C#
```

**Comment by int19h** [comment]
Was the original repro with F5, or did you use installers for both?

**Comment by MikhailArkhipov** [comment]
F5

**Comment by MikhailArkhipov** [comment]
Basically Dev15 installed, not running. Dev14 with RTVS, F5.

**Comment by int19h** [comment]
Okay; I cannot repro this with VS2015 U2 and Dev15 25123.0. If you still have a machine with both, can you try again and see if it still repros for you?

**Comment by MikhailArkhipov** [comment]
Sure we can try my laptop. will let you know.

**Comment by int19h** [comment]
Did you get a repro?

**Comment by MikhailArkhipov** [comment]
For whatever reason it started working now.
