### ISSUE TITLE
Can't input Tab after a comment

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1717]
In a comment line like `#comment`, typing Tab just after the 'comment' doesn't insert a Tab.
If a space exists after the 'comment', hitting Tab key can insert a Tab.

**Comment by MikhailArkhipov** [comment]
I can't repro with 0.3. Perhaps some special code snippet? Thanks

**Comment by Marchen** [comment]
I found that this was only occur when I turned on "Completion list on Tab key" of IntelliSense.
For other editor settings, see
![editorsettings](https://cloud.githubusercontent.com/assets/3863577/14934323/58e07090-0ee8-11e6-8a1f-91563513e756.PNG)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
