### ISSUE TITLE
Support non-system encoding for Source R Script command

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1725]
When editing a script of UTF-8 encoding, I can't run the script from Source R Script because my system encoding is CP932.

**Comment by int19h** [comment]
Does it work fine for you if you manually invoke `source` with the appropriate `encoding` argument?

**Comment by Marchen** [comment]
Yes.
![src](https://cloud.githubusercontent.com/assets/3863577/14998297/3ba0aa62-11be-11e6-966e-7d35f1b6a196.PNG)

**Comment by Marchen** [comment]
In my previous post, tests.r had Japanese characters in comments so it produced warnings.

But if a script has character vector, it produces errors.

e.g. if Script.r is
`a = "日本語"`

> source("C:/Users/mic/Dropbox/おしごと/かいせき/model.adapter/R/Script.r")
Error in source("C:/Users/mic/Dropbox/おしごと/かいせき/model.adapter/R/Script.r") : 
  invalid multibyte character in parser at line 1
In addition: Warning message:
In grepl("\n", lines, fixed = TRUE) :
  input string 1 is invalid in this locale
