### ISSUE TITLE
View(x) should work for all language objects, not just formulas

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1733]
Formulas are just language objects with class "formula" slapped on them. `View` should work for other stuff as well, like e.g. `quote(1+2)`.

**Comment by MikhailArkhipov** [comment]
```View(quote(1+1))``` doesn't do much in RS

**Comment by int19h** [comment]
`View(1~2)` doesn't do anything, either, but we support it now.

It's extremely cheap for us, too - we just need to change the check inside `FunctionViewer` to test for `TypeName == "language"` instead of checking classes for `"formula"`.

**Comment by int19h** [comment]
I'm poking around this source code for call stack fixes anyway, so I'm going to make the change there.
