### ISSUE TITLE
Indentation breakdown by auto formatting

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1737]
When using functions requires function definition or code block in their option (e.g. setRefClass, test_that in testthat package) inputting { cause breakdown of indentation by auto formatting.
![before](https://cloud.githubusercontent.com/assets/3863577/15037874/b2640344-12d9-11e6-8383-390bdfbd10e4.PNG)
![after](https://cloud.githubusercontent.com/assets/3863577/15037875/b6290a1a-12d9-11e6-8a9d-6866c290ec31.PNG)
![newline](https://cloud.githubusercontent.com/assets/3863577/15037876/b8000dac-12d9-11e6-9100-c8dca518e513.PNG)

**Comment by MikhailArkhipov** [comment]
What is broken exactly - the caret appears properly indented into the function scope.

**Comment by Marchen** [comment]
I expected auto formatting only affects current line like
```R
cls <- setRefClass(
	"test",
	methods = list(
		test = function() {}		
	)
)
```
```R
cls <- setRefClass(
	"test",
	methods = list(
		test = function() {

		}
	)
)
```
For me, affecting indentation other than current line is not intuitive.

**Comment by MikhailArkhipov** [comment]
It is not quite clear still what is incorrect. ```{ <ENTER>}``` appear to correctly indented braces and the caret inside the function scope. And yes, automatic formatting does can affect multiple lines - up to the enclosing scope. Example in C#:

```
            int x;
            if(x<1){
                |
```

type } at the caret - the line with the ```if``` gets formatted.

**Comment by Marchen** [comment]
My intention was that auto formatting affects multiple lines (including lines I manually formatted) was not intuitive for me.
But if auto formatting provides more options to control its behavior, this may not be a problem (e.g. #1736).

**Comment by MikhailArkhipov** [comment]
OK, we'll consider #1736 separately (maybe also add more options). Formatting multiple lines is otherwise normal.
