### ISSUE TITLE
Auto formatting uses Space when R editor setting for indentation is Tab

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1738]
Though VS Options > Text Editor > R > Tab > Tab is set to Keep tabs, auto formatting insert spaces rather than tabs.
 

![options](https://cloud.githubusercontent.com/assets/3863577/15038098/df0876da-12db-11e6-8475-61e22cb48289.PNG)

See the line 430.

![before](https://cloud.githubusercontent.com/assets/3863577/15037997/f9f56dc8-12da-11e6-91d5-dbd32add1bcd.PNG)
![after](https://cloud.githubusercontent.com/assets/3863577/15037998/fce3870e-12da-11e6-9225-6975b9387677.PNG)

**Comment by MikhailArkhipov** [comment]
Spaces may still be inserted if indentation length is not a multiply of tab size. Ex indent of 5 will consist of tab and 1 space.

**Comment by Marchen** [comment]
Sure.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
