### ISSUE TITLE
Auto-formatting brings inconsistent result when Expand braces is True

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1739]
Format Selection command brings different results for same code when Expand braces is True.
Editor settings: #1738.

![autoformat](https://cloud.githubusercontent.com/assets/3863577/15038290/6d868464-12dd-11e6-8e79-fad8251727f0.PNG)

![step1](https://cloud.githubusercontent.com/assets/3863577/15038295/7a17b39c-12dd-11e6-8ca8-3fe2f17b8c9d.PNG)

Ctrl + K, Ctrl + F

![step2](https://cloud.githubusercontent.com/assets/3863577/15038300/827e9e06-12dd-11e6-9805-a27f9a0244b7.PNG)

Ctrl + K, Ctrl + F

![step3](https://cloud.githubusercontent.com/assets/3863577/15038302/87c1749c-12dd-11e6-87a7-63d504f61faf.PNG)

Ctrl + K, Ctrl + F

![step4](https://cloud.githubusercontent.com/assets/3863577/15038307/8dbd6bf8-12dd-11e6-9931-990536fb8037.PNG)

Ctrl + K, Ctrl + F

![step5](https://cloud.githubusercontent.com/assets/3863577/15038308/92bfec66-12dd-11e6-933c-564afd24090a.PNG)

Ctrl + K, Ctrl + F

![step6](https://cloud.githubusercontent.com/assets/3863577/15038320/a8bc5126-12dd-11e6-9e5e-834d78ce5989.PNG)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
