### ISSUE TITLE
Suppress ' completion in Roxygen block

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1740]
When making Roxygen block with Automatic brace completion on, RTVS add extra ' like `#''`.

**Comment by MikhailArkhipov** [comment]
This should be fixed in 0.3, it was 0.2 issue. Please reopen if you are still seeing this in 0.3. Thanks.

**Comment by Marchen** [comment]
I couldn't reopen the issue #385, but left a comment on there.

**Comment by MikhailArkhipov** [comment]
OK, reopened

**Comment by Marchen** [comment]
Thanks!

**Comment by MikhailArkhipov** [comment]
Feel free to reopen if you still see it.

**Comment by Marchen** [comment]
On  0.4.20623.1711, I still see this issue.
So please reopen this.
![animation](https://cloud.githubusercontent.com/assets/3863577/16644268/a7d69e38-4456-11e6-96b6-0615e9486a8e.gif)

**Comment by MikhailArkhipov** [comment]
OK, thanks for the detailed repro!

**Comment by MikhailArkhipov** [comment]
Async issue, with fast enough typing parser hasn't finished file processing just yet.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/15b3daef67a9e6af9066230afe4a057c7c3a7739
