### ISSUE TITLE
open in Excel with German locale does not work

### ISSUE THREAD

**Issue by enicklas** [Microsoft/RTVS#1741]
Opening a data.frame in Excel via the Variable Explorer does not work properly with a German locale (see attached screenshot).

I suppose, the reason is that a German Excel expects csv files to use ";" as the field separator and "," as the decimal separator.

Please let me know if I can be of any further help.

![irisingermanexcel](https://cloud.githubusercontent.com/assets/53766/15048502/269ec036-12ea-11e6-8efd-877536b81634.png)

**Comment by MikhailArkhipov** [comment]
Need to look into current locale and specify appropriate separator to write.csv
