### ISSUE TITLE
Support Execute only R chunks in Interactive for R Markdown editor.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1755]
Currently, Execute in Interactive command sends all selected text from R Markdown editor and causes R errors. This is annoying when working with long R Markdown file because I need to select each R chunk and run the command again and again. I think sending Markdown text outside of R chunks to interactive is useless for most cases, so if Execute in Interactive command send text in R chunks only, it would be nice.

**Comment by MikhailArkhipov** [comment]
Current behavior is same as in RS. This will happen automatically per #1181

**Comment by Marchen** [comment]
Thanks for the comment! I hope RTVS will handle R Markdown better since R Markdown is a good way to store both code and its explanation in one file.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/080da5457cc2e72ce0becb078822e6de85a18cc9
