### ISSUE TITLE
VE display wrong entry on Enter

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1767]
Create 3 sets such as

```
t1 <- mtcars
t2 <- airmiles
t3 <- airquality
```
Open VE
Select t2
ENTER

- selection moves to t3 and t3 data is shown in the grid

**Comment by int19h** [comment]
Now that we have multi-instance grid, it actually opens a new grid every time.

**Comment by MikhailArkhipov** [comment]
Opening grid every time is sort of by design. The data could have changed so user may want to see both old and new values. Although I am not 100% sure.

**Comment by int19h** [comment]
I believe grids are supposed to track changes as they happen (because of lazy data fetching during scrolling, it would look really weird if they didn't, since you'd end up with a mix of old and new data).

**Comment by MikhailArkhipov** [comment]
OK, made it reuse the frame

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
