### ISSUE TITLE
Variable Explorer copy/paste

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1768]
There is no way to copy variable name or value from VE and paste it elsewhere. Ideally, it should provide means to do both, probably in a context menu (like Locals does in debugger), with value being the default for Ctrl+C.

**Comment by MikhailArkhipov** [comment]
I had code in Cordova Tools  that constructed proper VS context menu in WPF controls, will try and find it.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/828b4e3919cbed507a4d0f51b621b00a7fc8c25b
