### ISSUE TITLE
Add "Preview PDF" option for Rmd files

### ISSUE THREAD

**Issue by thmaterna** [Microsoft/RTVS#1771]
Allow conversion of Rmd file into pdf. I suppose it wouldn't be hard as generating pdf is just calling `render` with different arguments than for html. Another option would simply be to have a simple "Preview" option and let the Rmd file's header determine the output format.

We use rmarkdown routinely to generate parametrized pdf reports and not having that option in RTVS prevents us from adopting it unless we want to constantly move back and forth to a console to run the appropriate `render` call.

**Comment by MikhailArkhipov** [comment]
Primary issue was requirement to install pdflatex manually. But I guess there is no other way.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
