### ISSUE TITLE
Download and install R Host on first RTVS run

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1776]

**Comment by MikhailArkhipov** [comment]
This would simplify Dev15 setup quite a bit.

**Comment by int19h** [comment]
We can even place it into a per-user location to avoid the need to elevate - it doesn't need to be in Program Files. For that matter, we might not even need an installer for it anymore, but just download and place the .exe directly.

**Comment by MikhailArkhipov** [comment]
Needed for Dev15

**Comment by MikhailArkhipov** [comment]
First run download is not a great experience since product installed and then launched offline won't be working. Need to find different solution for Dev15.
