### ISSUE TITLE
R Interactive:  data.frame subset() displays complete data.frame not subset 

### ISSUE THREAD

**Issue by karlti** [Microsoft/RTVS#1791]
**Description:**
When subsetting a data.frame and then outputting it in "R Interactive", the complete data.frame is displayed not the subset.

For example:

`setosa      <- subset(iris, levels(iris$Species) == "setosa", select = - Species)`

Will dump all 148 rows/observation in "R Interactive" and not the expected 50 observations

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14342.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.3.20427.2043, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\R\R-3.2.3

**Comment by MikhailArkhipov** [comment]
RGUI and RStudio output 148 entries. So this appears to be by design?
