### ISSUE TITLE
Go To Definition even if the function is in a sourced file

### ISSUE THREAD

**Issue by norrasverige** [Microsoft/RTVS#1795]
I have one suggestion that I normally use a lot when programming in C++ in Visual Studio. In my R-scripts, I use to place functions in a separate file that I include in my script using source(). When I right-click a function in my script and select “Go To Definition”, I would like to go to the sourced file and look up the function… But that doesn’t work. It can only find functions that are located in the same R-file…

**Comment by MikhailArkhipov** [comment]
Yes, it is a planned feature, see #1364. Thanks.
