### ISSUE TITLE
Quickly expanding & collapsing a node in Variable Explorer opens it in Grid View

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1809]
This seems to be a side effect of supporting double-click to open - repeated clicks on the expander triangle are then treated as a double click (even though they _also_ expand/collapse the children).

Not sure what the proper behavior is here, but it should be one or the other - i.e. either it's a double-click, and then it opens the grid but does not cycle the expansion state, or it's not, and then it cycles expansion but doesn't open the grid.

**Comment by MikhailArkhipov** [comment]
Standard Windows sequence of events Click - Click - Double Click (Win32 is the same - WM_LBUTTONDOWN, UP, DOWN, UP, DOUBLECLICK). It is not possible to tell its a double click until it comes after two clicks. Waiting to see if second click comes within timeout is not very reliable as timeout is customizable and can be pretty long. If code waits, then someone with a long timeout will have to wait until timeout expires before we happen to decide that this was a single click.

What may be possible to to check location of the click.

**Comment by int19h** [comment]
Double-click is bubble-up event in WPF, isn't it? So we should be able to suppress it on the expander to make it do nothing there.

**Comment by AlexanderSher** [comment]
I'll take a look

**Comment by MikhailArkhipov** [comment]
No complaints so far
