### ISSUE TITLE
Function viewer crashes VS if variable name contains special characters

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1810]
E.g.:
```
`?` <- function() {}
```
Then click on the magnifying icon in Variable Explorer.

(Alternatively, just open `package:utils` in the environment selector, and use the definition of `` `?` `` there.)

It produces an `ArgumentException` with message "Illegal characters in path.". Stack:
```
at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.ChangeExtension(String path, String extension)
   at Microsoft.VisualStudio.R.Package.DataInspect.Viewers.CodeViewer.GetFileName(String functionName, String title)
   at Microsoft.VisualStudio.R.Package.DataInspect.Viewers.CodeViewer.<ViewAsync>d__6.MoveNext()
```

**Comment by MikhailArkhipov** [comment]
File name is easy to fix, but there is another problem. On ```View(`?`)``` JSON comes as

```
{[
  "#120#",
  "View",
  "?",
  ""
]}
```

note missing backticks around ```?```. Interestingly, RS grid has somewhat similar issue

![image](https://cloud.githubusercontent.com/assets/12820357/15475678/17a10272-20c0-11e6-8a23-efd23223edfd.png)

**Comment by int19h** [comment]
`deparse` has a `backtick` argument that controls this.

**Comment by MikhailArkhipov** [comment]
Yep, found it. Its done, will be in the next PR.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/080da5457cc2e72ce0becb078822e6de85a18cc9
