### ISSUE TITLE
Active bindings should be evaluated by default

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1815]
Active bindings in R are basically the equivalent of the property getter in C#, and are used in that manner for e.g. S4 classes. Right now we avoid actually executing them, and just show `<active binding>` in VE value column and in Locals. But C# evaluates property getters by default, and we should follow suit - in most cases, the code that has to run to produce a value is side-effect-free. Might be worth adding an option, just in case.

**Comment by MikhailArkhipov** [comment]
VS debugger indeed has an option

![image](https://cloud.githubusercontent.com/assets/12820357/15508249/80c4b708-2183-11e6-8387-66b810abd815.png)
