### ISSUE TITLE
FileSystemMirroringProjectFileGenerator overwrites existing .rxproj

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1816]
In `EnsureCpsProjFile`, it deletes the existing .rxproj if there is one, before it creates a new one.

This happens when you File->Open Project and select an .rproj file.

This is a problem since we are now storing run settings (startup file, command line args, reset repl) in the .rxproj file, and we don't want them to get wiped out.

**Comment by AlexanderSher** [comment]
In this case I think we should check if file exists rather than rewrite it.

**Comment by huguesv** [comment]
Fixed.
