### ISSUE TITLE
XamlPropertyRule build action doesn't work

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1817]
Applying this to Run.xaml makes it generate the .cs file at build time, but if you try to call any of the generated code, it gives you a compile error.  I've verified that the generated code gets included in the assembly using ildasm.

For now, I've hand-modified the run.cs file and included it as part of the project.  This means that any change to run.xaml will require a multi step process to get the necessary changes into run.cs, which is highly undesirable.

I can't repro this issue in a new CPS project.

**Comment by MikhailArkhipov** [comment]
So if it doesn't repro, shall we close it?

**Comment by MikhailArkhipov** [comment]
I believe I fixed this a while ago as part of SQL work.
