### ISSUE TITLE
VS not responsive while installing packages

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1843]
I installed `ggvis`, and also `Rcmdr`, and during both, I wasn't able to do anything in VS (clicking on windows, menus didn't do anything) until install was complete (which took maybe 1 minute - they depend on a lot of packages).

**Comment by MikhailArkhipov** [comment]
There is usually a visible progress in REPL. I think we can look at this later.

**Comment by MikhailArkhipov** [comment]
Pretty old, no user complaints
