### ISSUE TITLE
Messages during MRC install regarding closing VS are confusing

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1850]
When RTVS detects that no R is available, and prompts you to install MS R Client, the messages that it shows are contradicting. First it says that if you continue, it will automatically close VS and install MRC. But if you do choose to continue, the next message tells you to close VS after MRC installer appears. In practice, the second message seems to be correct, so the first one should be amended.

**Comment by huguesv** [comment]
Here are the exact messages we have currently (I just went through this on a new machine)
```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to detect the location of the R interpreter.  If you have installed R, please specify path to R engine in  R Tools | Options. If R is not installed, Visual Studio can launch setup of the Microsoft R Client.



Would you like to start installation of the Microsoft R Client now? Visual Studio will close when the setup application starts.
---------------------------
Yes   No   
---------------------------
```

When you click 'Yes', you get
```
---------------------------
Microsoft Visual Studio
---------------------------
Microsoft R Client setup is about to start. Please close Visual Studio now and reopen it when setup is complete.
---------------------------
OK   
---------------------------
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
