### ISSUE TITLE
Solution Explorer should not show temporary files

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1851]
![image](https://cloud.githubusercontent.com/assets/3840081/15839913/2f8d32de-2bfb-11e6-910a-d065c009e038.png)

**Comment by huguesv** [comment]
Similar to https://github.com/Microsoft/RTVS/issues/1307.

**Comment by MikhailArkhipov** [comment]
How do we know it is temporary? Project shows everything that is on disk.

**Comment by huguesv** [comment]
Look at the screenshot.  The icon shows the file as missing.  That shouldn't happen, it should have been removed from solution explorer.

**Comment by MikhailArkhipov** [comment]
So it is not the issue with 'temp' file but rather than file was deleted but is still visible.

**Comment by karthiknadig** [comment]
The file got created when i first did File > New Project > Rproject. I assumed it was a temp file since it  was deleted automatically.

**Comment by AlexanderSher** [comment]
Any additional information? I can't repro it on any of my machines.

**Comment by Marchen** [comment]
I'm also having this issue but I can't repro... It seems that if I use RTVS longer time, number of the temporary files increases.

**Comment by MikhailArkhipov** [comment]
Found it. Happens when we get file names in 8.3 format.

```
 	Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll!Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcherEntries.DeleteDirectory(string relativePath) Line 58	C#
 	Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll!Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.DirectoryDeleted.Apply() Line 29	C#
>	Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll!Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.Consume() Line 146	C#
 	Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.dll!Microsoft.VisualStudio.ProjectSystem.FileSystemMirroring.IO.MsBuildFileSystemWatcher.ConsumeWaitPublish() Line 115	C#
```

![image](https://cloud.githubusercontent.com/assets/12820357/16179002/54009810-360d-11e6-8b7c-8b81c53c1b0f.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/d1abb246f92653296219f17c8f586c359e8cf086

**Comment by Marchen** [comment]
In RTVS 0.6, I still see the deleted files in the Solution Explorer. Please reopen the issue.

In addition, I think these files are created when sourcing scripts or running selected part of the script because these files always appear in directories having R scripts.
