### ISSUE TITLE
R Tools | Change R to Microsoft R Open error message mentions R Client

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1853]
If you you already have MRO set as your R interpreter, activating that command produces the following message box:

![image](https://cloud.githubusercontent.com/assets/1175142/15840032/02075cda-2bfc-11e6-868f-90355d75bf50.png)

Note that it says "Microsoft R Client". This should probably be consistent with the name of the command.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5a1d437180a33787d2eaceae65755d8ef210c273
