### ISSUE TITLE
Switch MRO link in REPL to MRC

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1854]
When CRAN R is being used, we add a link to MRO installer in the startup banner in the REPL. Now that other places in the product offer to install MRC, this should be made consistent with that.

**Comment by huguesv** [comment]
It's a forward link, so no code changes need :)

But which page should it go to?
https://msdn.microsoft.com/en-us/microsoft-r/install-r-client-windows

**Comment by int19h** [comment]
Sounds like  http://aka.ms/rclient/download is the right place.

In fact, we might actually want to change the code here and switch the existing fwlink to that - there's no advantage in having two layers of redirection, and this way we'll always be pointing at the most recent MRC.

**Comment by huguesv** [comment]
That aka.ms page requires you to log in.  People may just give up without even learning about the distro.

**Comment by int19h** [comment]
@jflam, do you know if there's an appropriate landing page for MRC for us to use? So far the best one that I know of is that MSDN link that Hugues posted above.

**Comment by jflam** [comment]
+Carl – do you have an aka.ms link setup for this? Thx!

**Comment by jflam** [comment]
The download page for R Client is at: http://aka.ms/rclient/download .

We are going to have a web page for R Client very soon (end of today or early next week). I can share with you the link when I have it.

Regards,
Carl



From: John Lam (AZURE)
Sent: Friday, June 10, 2016 2:49 PM
To: Microsoft/RTVS <reply@reply.github.com>; Microsoft/RTVS <RTVS@noreply.github.com>; Carl Nan <zhnan@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/RTVS] Switch MRO link in REPL to MRC (#1854)

+Carl – do you have an aka.ms link setup for this? Thx!

**Comment by int19h** [comment]
What we need is a landing page that describes what it is etc, not a direct download link.

**Comment by int19h** [comment]
So basically we need this: https://msdn.microsoft.com/en-us/microsoft-r/install-r-client-windows - but in a place that doesn't require the user to log in with their Microsoft account before they can even read it.

**Comment by int19h** [comment]
It appears that the link above no longer requires login (and likely never did - what we saw before was an intermittent bug). Updated fwlink accordingly.
