### ISSUE TITLE
demo(plotmath) doesn't work

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1858]
After writing demo(plotmath), R Interactive shows
```Type  <Return>	 to start : ```

but hitting Return couldn't proceed demo.

R Tools for Visual Studio   0.3.20427.2043

**Comment by MikhailArkhipov** [comment]
Please see #626. It is external to RTVS, the fix will appear in VS Update 3. Thanks.

**Comment by Marchen** [comment]
Thanks. I got it.
