### ISSUE TITLE
R Help: Can't search again for same topic

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1863]
1. Open R Help window.
2. Type `cross` in the search text box and hit ENTER.
3. Click the Home button on the toolbar to navigate to a different page, or click on a link in the current page.
4. Put focus on the search text box, which still shows `cross`, and hit ENTER.

Result: Nothing happens.
Expected: When I hit ENTER in a search box, I expect a search to be performed!

The only way you'll be able to search for `cross` again is if you search for something else first, or clear the search by clicking the `x` and retype `cross`.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/12f9210896ddb3fdee8e24f9663e9845d3a6eddf
