### ISSUE TITLE
Assigning to a constant should show red squiggly line

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1866]
Assigning value to a constant here, this should have a red squiggly line.

![image](https://cloud.githubusercontent.com/assets/3840081/15908365/2e0a945c-2d76-11e6-85c7-444578ed55cf.png)

**Comment by MikhailArkhipov** [comment]
By design. we do not have any code evaluation engine so only basic syntax check is performed.

**Comment by int19h** [comment]
I originally mistakenly claimed that this should be a syntax error, but I was wrong and Mikhail is right - it's actually a runtime error, and syntactically it's valid.

The way you test it is by using `quote()` to ensure that the expression is only parsed, but is not evaluated. For example, in this case:
```
> quote(1 <- 0)
1 <- 0
> as.list(quote(1 <- 0))
[[1]]
`<-`

[[2]]
[1] 1

[[3]]
[1] 0
```

In contrast, here we have an actual syntax error:
```
> quote(function TRUE() {})
Error: unexpected numeric constant in "quote(function TRUE"
```
