### ISSUE TITLE
RMarkdown: make sure that the preview menu appears when user right-clicks on an R code block

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1874]
Right now, the preview menu only appears when you right-click on a markdown part of the document.

**Comment by MikhailArkhipov** [comment]
This basically requires adding markdown items to R menu and hiding them outside of RMD files

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
