### ISSUE TITLE
 Add R Script vs. Add > New item > R Script have inconsistent filename casing (.r vs .R)

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1877]
![image](https://cloud.githubusercontent.com/assets/3840081/15945204/1043d0ac-2e46-11e6-9537-b77d16e93de2.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf

**Comment by huguesv** [comment]
Tested with the build where it's supposed to be fixed, but it's not ;)

I expect it's because Git didn't actually rename the template file name on disk, you have to do that in 2 steps when doing a rename that only changes file name casing.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2672327dadc2f80501ae313d688a7b2cd7e09468
