### ISSUE TITLE
Help on X command in rmarkdown is disabled and incorrect

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1881]
Open a regular .R file and right click on an R function such as `plot`.
Context menu last command shows 'Help on plot'.

Open an R markdown file.
Right click on an R function in an R code section.
Context menu last command is disabled, and named 'Help on plot'.
It keeps whatever was the last one it saw in a regular R file.

Command should probably be enabled for .rmd, or made invisible if it's disabled.  The fact that it's disabled and shows some unrelated topic can be confusing.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
