### ISSUE TITLE
Rmarkdown: right click - P in Preview should have an accelerator 

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1882]
Underscore P

**Comment by MikhailArkhipov** [comment]
Actually P is taken by Paste. Preview is set to 'v'

**Comment by smortaz** [comment]
cool. thx.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
