### ISSUE TITLE
Changing column names while grid is sorted breaks grid

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1884]
```r
m <- matrix(1:9, 3, 3)
View(m)
```
then sort by any of the columns - e.g. V1. Then:
```r
colnames(m) <- c(1,2,3)
```
You get:
```
Error in `[.data.frame`(x, "V1") : undefined columns selected
```
As with #1883, after this happens, REPL hangs, and cannot even be reset.

**Comment by MikhailArkhipov** [comment]
I think we need to reset sorting on mutation

**Comment by int19h** [comment]
We also need to harden that code in general. Basically, it has to assume that anything it evaluates that is based on user input in any way can throw, and catch/recover accordingly.
