### ISSUE TITLE
Collapsible sections do not work everytime

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#1886]
![image](https://cloud.githubusercontent.com/assets/3840081/15949549/499c207c-2e5d-11e6-8157-ddb7cf0a88a6.png)

Repro:
type # followed by - or = or # 

Expected: After the 4th - or = or # the section should be collapsible
![image](https://cloud.githubusercontent.com/assets/3840081/15949675/1df1eb90-2e5e-11e6-801a-2cfeadf09fb8.png)

Sometimes it does not form the collapsible section even after pressing enter
![image](https://cloud.githubusercontent.com/assets/3840081/15949544/3eadccc4-2e5d-11e6-88d6-d406d9239bae.png)

Removing the 4th - or = or # form the end of the line should remove the collapse UI.
![image](https://cloud.githubusercontent.com/assets/3840081/15949621/c70b046a-2e5d-11e6-8c95-4938ae172eb7.png)

**Comment by MikhailArkhipov** [comment]
For performance reasons most of the typing in comments is ignored so not all cases will work. sect[TAB][TAB] snippet.  But I'll see what can be done. May also add menu item to like right-click/Insert Section or something

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/82d5a2d02357aa6ce25563c5a302c5c8627f71cf
