### ISSUE TITLE
Existing projects do not get F5 support automatically

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1891]
For F5 to work, the project must be buildable - this is indicated by the presence of target named "Build" in the .rxproj file. For new projects that are created with 0.4 (after the change went in), that target is inserted into the generated project file. But existing project files do not contain it, and so F5 does not work for them - the "Start with Debugging" and "Start without Debugging" commands are simply disabled with no explanation.

Short-term, this needs to be properly documented. The workaround is to manually add the following line to .rxproj:

``` xml
<Target Name="Build"/>
```

Long-term, we might want to implement project upgrade, and insert it automatically.

**Comment by MikhailArkhipov** [comment]
OK, for 0.4 this is just to document/readme.

**Comment by MikhailArkhipov** [comment]
0.4 is long gone.
