### ISSUE TITLE
Project properties gives error

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1898]
this was a new mostly empty project.

![image](https://cloud.githubusercontent.com/assets/742484/15979708/9bba882c-2f1a-11e6-9f46-e21dc75089e1.png)

**Comment by huguesv** [comment]
In the screenshot, the Solution Configurations and Solution Platforms combo boxes are empty and grayed out.  That is also not normal.

**Comment by MikhailArkhipov** [comment]
I believe we actually fixed this
