### ISSUE TITLE
Suppress switching from the console to the editor after executing a command at a breakpoint.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#1902]
After executing a command in R Interactive, R editor is activated when debug is suspended at a breakpoint.
This is annoying when I want to run several commands in R Interactive.
In many situations, I think users want to run several commands at a breakpoint to check parameters and users don't want to edit the program just after running a command in the Interactive.
Please suppress this behavior or provide a option to control it.

**Comment by MikhailArkhipov** [comment]
This, unfortunately, default VS behavior where languages historically were compiled and didn't use interactive window. We have some code that tries to prevent that switch to the editor, can you please provide steps to reproduce the behavior, perhaps some case is missing.

We are working with VS IDE on making said behavior more controllable.

**Comment by Marchen** [comment]
For me, this was occurred at least two situations.

1)
  - Add a breakpoint on a R script.
  - Attach debugger.
  - Source the R script from the context menu of R editor.
  - At the breakpoint, execute a command in R Interactive.
  - R editor is activated and input cursor is there.

2)
  - Add a breakpoint on a R script (e.g. script.R).
  - Attach debugger.
  - Send a code block with "source" command  to include the script (e.g. `source("script.R")`) to the Interactive.
  - At the breakpoint, run a command in R Interactive.
  - Editor is activated.

With R Tools for Visual Studio   0.3.20427.2043

**Comment by MikhailArkhipov** [comment]
715523de broke this

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/79c0e2fbca7cdb1be13083e34edd8cb762cc44dd

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/79c0e2fbca7cdb1be13083e34edd8cb762cc44dd
