### ISSUE TITLE
File->New->File->R Script creates file with lowercase .r extension

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1918]
It should be consistent with Add New Item, and Add R Script and use uppercase .R extension.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/828b4e3919cbed507a4d0f51b621b00a7fc8c25b

**Comment by jflam** [comment]
Still seeing this behavior on 2016-06-15.2 build.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/6eaa07fd75da341fe426e61e81894b357d2e933c
