### ISSUE TITLE
Code snippet parameter replacement doesn't work in REPL

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1920]
Open R Interactive.
Type: `sql` and hit TAB
You'll see 2 highlighted sections, one for connection, one for query.
Hitting TAB should toggle between the 2, and typing should replace the boilerplate.
That doesn't happen.  Typing TAB or anything else just adds text at the end of the line.

**Comment by MikhailArkhipov** [comment]
By design. Legacy extension manager behavior that knows nothing about projections.

**Comment by int19h** [comment]
Can we file a bug on them?

**Comment by MikhailArkhipov** [comment]
Sure. Don't expect much though.

**Comment by smortaz** [comment]
Somehow I recall that this used to work

**Comment by MikhailArkhipov** [comment]
It [sort of] worked like this https://github.com/Microsoft/RTVS/issues/1672

**Comment by MikhailArkhipov** [comment]
Going to play with this a bit...

**Comment by MikhailArkhipov** [comment]
It is possible to implement custom caret navigation in REPL but editing is not 100% the same. Specifically, yellow fields don't always expand with editing.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/12a09cb3420bb9496799b18a718593e84450ebea
