### ISSUE TITLE
Provide search for current item in editor/REPL in Web

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1926]
Using specific configurable site. I.e. F1 that is similar to 'Help On Current' but instead of R help, search Web for the current term under caret with specific site such as stackoverflow.com.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/12a09cb3420bb9496799b18a718593e84450ebea

**Comment by smortaz** [comment]
works great.  improvements:

change label to:

F1 keyword search string    [<keyword> R site:stackoverflow.com                        ]   Pop out [N]

because someone might want to use rstats, or rtvs or rstudio or rlang etc.

**Comment by MikhailArkhipov** [comment]
It may not be F1 though, it is just bound by default. Also, 'F1 keyword' may also mean keyword for VS help on MSDN. 

In ```Pop out``` do you mean external browser? 
We may not be able to track instances so each new URL may end up opening new browser instance. Process ID is unreliable since browsers transfer URLs through brokers to pool of processes they have for each tab.

**Comment by smortaz** [comment]
OK understood. The more important part is letting the user configure the
parameters that are passed with a reasonable starting default like what you
have already

**Comment by MikhailArkhipov** [comment]
Implemented
