### ISSUE TITLE
Add fluent assertion for 2D arrays

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#1928]
Need to add `.Should().Equal()` for 2D arrays, including arrays with non-zero lower boundaries. That can then be used to simplify data grid tests.

https://github.com/Microsoft/RTVS/pull/1927/commits/b8ecadb5042d91c33d8d62208054703d6f9d09e6#diff-2ae440de6d36febd3f6fd2e406060fcaR61

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
