### ISSUE TITLE
Remote intellisense

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1948]

**Comment by MikhailArkhipov** [comment]
Switch function completion to use R Host

**Comment by int19h** [comment]
Are you thinking of doing HTML scraping inside the host? Or going away from HTML entirely?

**Comment by MikhailArkhipov** [comment]
I hope to go away entirely, use R to get functions if possible. If not, then do HTML thing in the broker (as a last resort)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/61a643b907e7e167d311b464c8e4252aaf93bba4
