### ISSUE TITLE
Shiny is installed but does not appear in library() completion

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#1967]
![image](https://cloud.githubusercontent.com/assets/12820357/16159454/b591f76e-3477-11e6-8a79-31ab722d37ad.png)

**Comment by MikhailArkhipov** [comment]
Looks like completion is looking at the top level folder rather than under versioned folder

![image](https://cloud.githubusercontent.com/assets/12820357/16159579/7f552760-3478-11e6-82af-f6f473f08753.png)

**Comment by MikhailArkhipov** [comment]
Specific to R Client.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/eb0e7a8b36a4bbd30734e999eec37cdcd6ce008c

**Comment by int19h** [comment]
Verified.
