### ISSUE TITLE
Editor: can't select last line with shift-down-arrow

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1970]
![image](https://cloud.githubusercontent.com/assets/742484/16165161/31ae10ac-3497-11e6-9c45-039b6f135a97.png)

repro:

start at cursor at line 16
press shift down arrow to select the lines to send to repl
when you get to line 22, it will not get selected.  instead you can to shift right arrow or end which is a pain & unnatural.

expected:

last line should be selected as part of same motion.

**Comment by MikhailArkhipov** [comment]
Standard VS editor behavior: there is no line break at the end of the file. Same as in C#:


![image](https://cloud.githubusercontent.com/assets/12820357/16165572/7d8741c2-3499-11e6-8cea-6457f12e19f2.png)

Workaround: Add line break at the end.

**Comment by smortaz** [comment]
hmm... makes noe sense in a REPLy world.  can we add one by default?

**Comment by MikhailArkhipov** [comment]
Add where? User can always delete it. BTW Notepad is exactly same

![image](https://cloud.githubusercontent.com/assets/12820357/16167100/17af2362-34a6-11e6-9493-31dc06fc761f.png)

**Comment by MikhailArkhipov** [comment]
Closing as it works the same as in other languages and products.
