### ISSUE TITLE
F1 does not work in comments

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#1986]
1. it should

2. allow to highlight a phrase (eg "how to plot via ggplot") and pass that as the search string

(suggestion from Rimma :))

**Comment by MikhailArkhipov** [comment]
Yeah it currently looks at R tokens so it can extract proper sequence such as in complex expression with operators, brackets, etc. However, if there is a non-empty selection perhaps it should be used instead.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5aead99fab615886b9099b1953e7f76513e69f17
