### ISSUE TITLE
Wrong reported default for Use multiline selection

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#1990]
It's a fresh install on a new VM.  I haven't changed any options, but this one is bolded, which implies that it's not the default.

![image](https://cloud.githubusercontent.com/assets/1696845/16249931/5c50d4cc-37ce-11e6-89cd-dbc9b6d92d8a.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5aead99fab615886b9099b1953e7f76513e69f17
