### ISSUE TITLE
Null reference exception when using code snippets for ">" and "=" in editor

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#1996]
Repros on 2 machines with 2016-06-22.2 build. Editor window only. Works fine in REPL.

This is a release blocking bug for 0.4.

**Comment by AlexanderSher** [comment]
Fails in `ExpansionClient.GetFieldMarkers()` on `ErrorHandler.ThrowOnFailure(Session.GetSnippetSpan(pts));` because `Session` is `null`

**Comment by MikhailArkhipov** [comment]
That is probably b/c shippet does not actually have any fields. So null check is probably sufficient.

**Comment by MikhailArkhipov** [comment]
Actually no.... This code is old, prev version had _expansionSession which is same thing.

**Comment by MikhailArkhipov** [comment]
OK, old code had same bug but managed to get away since it didn't manually position caret in the first field.
