### ISSUE TITLE
RTVS is not offering the correct versions of MRO, and fails to offer updated versions of MRO

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2007]
On my computer, I have Microsoft R Open 3.2.2 (which is really old BTW) installed. Since I recently installed RTVS on a repaved machine, and I don't recall explicitly installing R Open, I suspect that I let RTVS point me to R Open when I installed RTVS. This leads me to believe that there are two separate problems here:

1. Let's double check that, while installing RTVS, we offer the most recent version of MRO.
1. Install R Client command will not offer newer version if it detects that _any_ version of MRO already exists. We need to change this to check if there is an updated version, and offer that. Or at the very least, send me to their web page regardless.

**Comment by MikhailArkhipov** [comment]
We use whatever is at http://go.microsoft.com/fwlink/?LinkId=800048. There is no mechanism to tell that there is an update.

**Comment by MikhailArkhipov** [comment]
```Yes, R Client 1.0 downloads and installs MRO 3.2.2 and MRS 8.0.3.```

So 3.2.2 is the current.

**Comment by MikhailArkhipov** [comment]
Updates to MRO will be pushed eventually through Windows Update

**Comment by jflam** [comment]
The problem is that if there is an MRO installed, I can't get to that link. We should have it always go to that link rather than saying "hey, you have a version of MRO installed, you don't need to see the page where you can get updates"

**Comment by MikhailArkhipov** [comment]
There is page to go to. I was told that link has the latest and updates will come via WU.

**Comment by jflam** [comment]
Then we should probably change the command to not just run the installer from a link, but instead take the user to a page where they can see what version of R Client is available. Right now this is a terrible upgrade experience because I don't know where to go (well at least not unless I ask Google). If we have a command, then it should absolutely let the user update to latest.

**Comment by MikhailArkhipov** [comment]
No, it was explicit request to install. No more download pages. VS 15 Willow does exactly the same. Now, we could add menu item pointing to MRC page. But not installing is not an option.

**Comment by jflam** [comment]
If that's the case how does someone upgrade to a newer version? Welcome suggestions.

**Comment by MikhailArkhipov** [comment]
You may want to take this offline. As I said - MRC updates will come via Windows Updates.

**Comment by smortaz** [comment]
we should add this to do the 0.4 docs so people (who actually read docs) at
least get a heads up about the surprise downgrade/upgrade.

**Comment by MikhailArkhipov** [comment]
0.4 is long shipped, I don't think there is an action item for us anymore.
