### ISSUE TITLE
Provide a option to search R help when pressing F1

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2016]
Pressing F1 to search the keyword under the cursor is very useful function of 0.4.
But usually I use internal R help to find information of the keyword first.
So if RTVS have a option to search internal R help, I think the function becomes more useful.

**Comment by MikhailArkhipov** [comment]
Ctrl+F1 or Right Click => Help On ...

**Comment by Marchen** [comment]
Thanks for the comment. I found it.
