### ISSUE TITLE
Putting $ evaluates the code and shows an error.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2019]
On 0.4, typing $ seems to evaluate the object just before the $ and shows an error if it doesn't exist.
But this is not true for existing object like `iris$`.

![default](https://cloud.githubusercontent.com/assets/3863577/16416984/66a7eb48-3d7f-11e6-8334-a326c0655934.PNG)

**Comment by MikhailArkhipov** [comment]
In this particular case intellisense attempts to enumerate members of something$iris and fails. I guess the error can be hidden though.

**Comment by Marchen** [comment]
The error was shown just after typing something$, not after typing iris$.

**Comment by MikhailArkhipov** [comment]
Evaluation is by design since we need to know members and that is achieved by actual code evaluation. However, we should hide the error. ```rtvs:::describe_children``` appears to evaluating with visible output.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5aead99fab615886b9099b1953e7f76513e69f17
