### ISSUE TITLE
RTVS 0.4 Install is failing due to missing R Host msi file

### ISSUE THREAD

**Issue by peran038** [Microsoft/RTVS#2021]

**Comment by MikhailArkhipov** [comment]
The Host MSI is packaged separately due to GPL licensing and has to be downloaded when RTVS is installed. So it is recommended that machine is online during setup. If you must be offline try downloading the file from ```https://rtvs.azureedge.net/download/RHost_2016-06-23.msi```

**Comment by cradleccchiu** [comment]
I have the same problem when installing RTVS 1.0 . It was failing due to missing R Host msi file. Where to download the file offline.

**Comment by smortaz** [comment]
please see the Installation page and steps for zip installs:

http://microsoft.github.io/RTVS-docs/installation.html
