### ISSUE TITLE
Installing Visual Studio Update 3 resets the version of R

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2024]
I had just installed MRO 3.2.5, but after Update 3 installed it was reset to 3.2.2.

**Comment by jflam** [comment]
Screenshot of post-install startup:

![image](https://cloud.githubusercontent.com/assets/8877/16433091/492e87d0-3d3d-11e6-801e-27e410748301.png)

**Comment by jflam** [comment]
The odd thing is that when I went to the dialog to manually change the directory of the R installation, it was set to the directory for 3.2.5! Restarting VS fixes the problem and the correct version of R starts up (3.2.5). Is this a first-run bug of some sort?

**Comment by MikhailArkhipov** [comment]
Resets from what to what?

**Comment by int19h** [comment]
There is a separate bug that when an existing R installation (that you have already configured in RTVS) goes away from any reason, we don't properly detect that and reset that option / tell user to reconfigure.

On top of that, it sounds like installer unconditionally installs MRC, even if you already have MRO.

And so that unconditional installation removes the existing MRO, which was already configured, triggering that other bug.

**Comment by MikhailArkhipov** [comment]
MRO is superseded by MRC.

**Comment by int19h** [comment]
At the very least, we should fix that other bug and reset the option (or transparently update it somehow, though I'm not sure if we have enough info for that).

**Comment by jflam** [comment]
To answer @MikhailArkhipov's question from above, it was from 3.2.5 to 3.2.2 (this is the version that is installed when I first installed RTVS on this machine and didn't have R installed at all - it was a repave of the OS).

**Comment by MikhailArkhipov** [comment]
AFAIK MRO *was* 3.2.5 but MRC takes over and it puts 3.2.2

**Comment by int19h** [comment]
I think the way this works is that for installation purposes, MRC is considered a "newer version" of MRO, and so it is just a silent update. But MRC uses R version 3.2.2, so you effectively get a downgrade in that respect.

**Comment by MikhailArkhipov** [comment]
Yep. Perhaps to match SQL R setup

**Comment by MikhailArkhipov** [comment]
Need to check what's with MRO/MRC 3.3

**Comment by MikhailArkhipov** [comment]
We no longer expose path in options and it should be easy to restore the desired connection in Workspaces in case it does change.
