### ISSUE TITLE
Installed RTVS 0.4. Now R Tools -> Data is grayed out

### ISSUE THREAD

**Issue by CBrauer** [Microsoft/RTVS#2026]
After installing RTVS 0.4 I notice that the R Tools-.Data menu is grayed out.  How can I get these menu items back?

Charles

**Comment by MikhailArkhipov** [comment]
The menu becomes active when R Interactive window opens (i.e. when R actually started). Although R Tools menu is visible for performance reasons VS does not load responsible components until they are actually needed.

**Comment by MikhailArkhipov** [comment]
Does it work for you when R Interactive window is up? Thanks

**Comment by CBrauer** [comment]
Yes, that’s the secret.  Thanks for the help.
