### ISSUE TITLE
RTVS does not recognize R Server when version from SQL 2016 is installed

### ISSUE THREAD

**Issue by TheoVanDrimmelen** [Microsoft/RTVS#2028]
I have installed R Server Standalone from the SQL 2016 iso. When I install R Tools 0.3, I says that it was not able to locate the R language engine.

Moreover, after starting Visual Studio, I have to set the R engine in the R Tools -> Option dialog

Hint: Is this related to the fact that SQL 2016 installer install R on a different location than the standard R Server installer?

**Comment by MikhailArkhipov** [comment]
This is fixed in 0.4. The reason was that unfortunately, SQL installer only writes 32-bit registry keys while RTVS only supports x64 and did not look into 32-bit registry hive.
