### ISSUE TITLE
Handle RHost disconnected state in UI

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2030]
Interactive Window, Package Manager, Variable Explorer, Project loading
Probably will require refactoring the pull of sessions

**Comment by MikhailArkhipov** [comment]
Output of a message to REPL should be sufficient for now

**Comment by MikhailArkhipov** [comment]
Project loading was covered in #2093. Otherwise UI looks reasonble:

![image](https://cloud.githubusercontent.com/assets/12820357/18359619/8c24af2e-75af-11e6-93bc-f823e34fde7d.png)
