### ISSUE TITLE
Refactor:  IMessageTransport

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2042]
@int19h:  I think we should revisit this. This interface is too low-level now - it's meant to be the message transport, but it's effectively a packet transport now (since you need multiple Receive calls to get a single message where blobs are involved).

Let's move `Message `and all related functionality here, so that `RHost `only ever deals with complete message instances. This will also let us do things more efficiently if we ever decide to move to a different protocol that allows mixing binary and non-binary data in a more efficient way.

**Comment by karthiknadig** [comment]
Change blobs filed in `Message` to use `IReadOnlyCollection<byte[]>`.

**Comment by MikhailArkhipov** [comment]
Does it need to be done for RTM?

**Comment by int19h** [comment]
It's already done as part of broker work, actually.
