### ISSUE TITLE
The new code folding feature does not recognize whitespace between regions

### ISSUE THREAD

**Issue by AMarthallerMS** [Microsoft/RTVS#2057]
If you have multiple regions on top of each other, the white space between regions is ignored. When the code is collapsed you end up with all the regions stacked without any whitespace.

# Region 1 ----
FooBar

# Region 2 ----
FooBar

# Region 3 ----
FooBar

# End ----

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/21cc269b6ce0172d999bac543f125869873915a2
