### ISSUE TITLE
Rename Shiny pages browser option

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2067]
It's not specific to Shiny, for example plotly uses it when it generates html pages and opens them in browser.

See https://github.com/Microsoft/RTVS/issues/2056

**Comment by MikhailArkhipov** [comment]
What should we name it then

**Comment by huguesv** [comment]
I don't have a great idea.  Category "Web", or "Html"?  Name "Web browser", "Html page browser"? Change description to include plotly in addition to shiny.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
