### ISSUE TITLE
REPL output speed is much slower that in other products

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2069]
Try ls("package:base")

**Comment by smortaz** [comment]
mine returns the responses (1210 lines) in < 1 sec...  what are you seeing?

**Comment by int19h** [comment]
Maybe a Debug/Release thing? Or slows down when running RTVS under debugger?

**Comment by MikhailArkhipov** [comment]
It is less than a second, but RS is instant. I'll check on release.

**Comment by int19h** [comment]
In Debug, it is very slow, and lines show one by one.

In Release, there is a noticeable 1-2 sec delay where nothing is output, then all the output comes in at once.

**Comment by MikhailArkhipov** [comment]
OK.

**Comment by int19h** [comment]
I suspect it might have something to do with lines being sent one by one, so each line is basically its own packet. It might be possible to improve it if we start buffering writes.
