### ISSUE TITLE
Save As... does not change file name

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2070]
New Script.R
Save As... and change to Script5.R

Observed: Script5.R is created in the project, but current file is still Script.R. It works as 'Make Copy Of'.
Expected: same as in other projects, Save As... changes file name in the active editor tab.

Doesn't seem to be specific to R, SQL and HTML are working same way,

**Comment by AlexanderSher** [comment]
Opened file is in fact Script5.R, but it shows Script.R in header.

**Comment by AlexanderSher** [comment]
Issue happens because CPS treats this action as rename, while file watcher just sees a newly added file

**Comment by AlexanderSher** [comment]
Issue happens because CPS doesn't call `RunningDocumentTable.RenameDocument` for the "Save as" operation

**Comment by MikhailArkhipov** [comment]
@AlexanderSher did we file CPS bug and if yes, what is the number in VSTS

**Comment by AlexanderSher** [comment]
No, there is no bug in VSTS

**Comment by MikhailArkhipov** [comment]
Does it repro in Dev15?

**Comment by MikhailArkhipov** [comment]
Reproes in Dev15

**Comment by MikhailArkhipov** [comment]
VSTS 370378

**Comment by MikhailArkhipov** [comment]
Won't be fixed in RTW. Pushing to Update 1.

**Comment by MikhailArkhipov** [comment]
Punted to Dev16.
