### ISSUE TITLE
GPU Profiler support

### ISSUE THREAD

**Issue by drcrook1** [Microsoft/RTVS#2071]
This would be fantastic.  Specifically for NVidia class GPUs.

**Comment by MikhailArkhipov** [comment]
I assume you are running C++ code? VS does support GPU profiling. You can attach to any process running native code. If this does not work with gcc-produced binaries, you may want to file feedback with C++ team via standard VS `Send Feedback` feature.

**Comment by MikhailArkhipov** [comment]
Closing since this is not about R and rather about native code.
