### ISSUE TITLE
R project (.rxproj) become unavailable after committing by SourceTree

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2073]
I'm using SourceTree for git client.
After I committed changes by SourceTree, the R project in the repository was unloaded and showed as unavailable.
If I reload the project from the context menu of solution explorer, it appear again.

I think this problem started from when I updated to 0.4.

**Comment by AlexanderSher** [comment]
Hi Michio,

I've tested this scenario on VS2015 Update 3 with the current RTVS build (https://aka.ms/rtvs-current) and SourceTree 1.9.6.2. I've tried commit, push, pull, rebase, cherrypick, stash - all those operations work as expected, project stays loaded with icon overlays correctly updated.

Do you still have this issue?

**Comment by MikhailArkhipov** [comment]
Closing. Please let us know if you can still repro in 0.5. 0.6. will be out soon.

**Comment by Marchen** [comment]
I'm sorry for my so slow reply.
I confirmed this issue was fixed in my environment.
Thanks a lot!
