### ISSUE TITLE
Remote connection info display

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2077]
I'd like to get this info in a hopefully central place for my remote computation experience:
- list of machines i've already connected to (eg drop down)
- ideally info on each machine (see winhpc - "24 proc Xeon @ 3.00 GHz")
- R's found on the machine
- Last connect + disconnect date, time, duration + what machine + what R i connected to
- Failed connection attempts, error messages, info, ...
- Amount of data uploaded & downloaded 
- Current connect status (detailed version of connect status on repl)
- Files uploaded / downloaded (?)
- Info saved in the Log for debugging (frown)

**Comment by MikhailArkhipov** [comment]
Bringing back as part of connection diagnostics proposal

**Comment by AlexanderSher** [comment]
Where to store all this information? And should it be available for all the VS installations on current machine?

**Comment by MikhailArkhipov** [comment]
Actually this is a bit bigger. The discussion was about having a detailed log of connection/disconnection/etc. This log is separate from our diagnostic logs and should always be created so IT org can help user with connection issues. Sort of like in Direct Access you can click a button and have connection logs gathered for the help desk.

As a side effect we could display current connection information somewhere. Simple approach is to use another output window pane and just output there all the tracing along with storing it in a log file. The log file should be somewhere in accessible location.

**Comment by MikhailArkhipov** [comment]
This most probably doesn't fit into 0.5 as it stands.

**Comment by smortaz** [comment]
hmmm.  why?  let's discuss.  i think there's a basic version of this & a
fancy version.  all i (users) want is a basic user visible set of msgs that
show what we connected to, success/failure, giving up trying, current
status as a linear set of msgs in the output windows.  this should be
doable by dumping a msg with a timestamp for each major "status" change in
the connection state machine.

**Comment by MikhailArkhipov** [comment]
Some of it is implemented via different means. For example

`list of machines i've already connected to (eg drop down)`
- no dropdown but Workspaces window contains all your connections and local interpreters
`R's found on the machine`
- as above, see Workspaces window

`Info saved in the Log for debugging (frown)`
- remote issues etc are already being logged. There is a reparate task for fetching remote logs for frowns

So what remains is
- ideally info on each machine (see winhpc - "24 proc Xeon @ 3.00 GHz")
- Last connect + disconnect date, time, duration + what machine + what R i connected to
- Failed connection attempts, error messages, info, ...
- Amount of data uploaded & downloaded
- Current connect status (detailed version of connect status on repl)
- Files uploaded / downloaded (?)

There are no cycles left until 9/16

**Comment by MikhailArkhipov** [comment]
Current connect status (detailed version of connect status on repl) is also covered in status bark and Workspaces window. There is a task for a separate prompt on remote.

**Comment by MikhailArkhipov** [comment]
Current connect status (detailed version of connect status on repl) is also covered in status bark and Workspaces window. There is a task for a separate prompt on remote.

**Comment by smortaz** [comment]
thx.  this is fine for a "current status snapshot".  what i want to see is
a linear list of msgs in the output window that shows a time line display
of connect, disconnect, try, give up, duration, etc. etc.  ideally it
should be a simple moral equivalent of printf'ing a msg which with status
change in the big connection state machine.  the low hanging version of
this shouldnt be too hard at all.  tho i understand it's lower prio.

**Comment by MikhailArkhipov** [comment]
Information about remote machine now appears in REPL upon connection and there is Session | Display Information... command in the menu. So this item is mostly covered for RTM.

**Comment by MikhailArkhipov** [comment]
Machine load information is also available in the status bar. Closing this one, we can open separate smaller items for further improvements.
