### ISSUE TITLE
Use pipes to communicate between broker and host

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2081]
Using websockets the way we do now presents a potential security issue in a multi-user environment, since it is possible for one user to connect to a socket that is intended for another by racing against the original connection.

Instead, we should use a transport mechanism that does not offer an attack window between process start and establishing the connection. It seems that using stdin/stdout for this purpose would fit the bill, and could also simplify the host code significantly, as there's no websocket dependency anymore.

**Comment by smortaz** [comment]
how is jupyter doing this with their protocol (which i assume they've done
& redone & addressed some of the same types of issues)?

**Comment by int19h** [comment]
On a multi-user system, they have the same problem, potentially. It may be mitigated by using authentication - the problem is that there's no websocket library for C++ that supports it.

There are also various schemes utilizing one-off generated auth tokens. The problem is that there's no good way to transmit them from the broker to the host. Command line and environment variables can both be inspected by other processes, so they do not constitute a secure transmission channel.
