### ISSUE TITLE
Settings - Type Expression shouldn't be quoted

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2090]
In project properties, settings:

Add a new value:
Name: m1
Value: 500
Type: Expression

Click Add.

Save and open the .R file in editor.  Notice that it says:
````
m1 <- '500'
```

That's the same as if you selected Type: String.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/15b3daef67a9e6af9066230afe4a057c7c3a7739
