### ISSUE TITLE
Settings page tab order

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2092]
Put the cursor in the text box for `Name`, and press TAB several times.  You will see focus go:

1. `Name`
2. `Value`
3. Help text
4. `Type`

We should either prevent focus from going to help text, or swap 3 & 4 order.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/15b3daef67a9e6af9066230afe4a057c7c3a7739
