### ISSUE TITLE
Intellisense tests failing

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2098]
Up-to-date master as of today.

![image](https://cloud.githubusercontent.com/assets/1175142/16965475/1e1782d0-4db5-11e6-969d-fd50d66c9adf.png)

Most seem to be failing with `NullReferenceException` in this code:
```cs
        public async Task LoadFunctionsIndexAsync() {
            var functionNames = await GetFunctionNamesAsync();
            foreach (var functionName in functionNames) {
                _functions.Add(new FunctionInfo(functionName));
            }
        }
```

**Comment by MikhailArkhipov** [comment]
Which version or R is it

**Comment by int19h** [comment]
I'm not sure. I have CRAN 3.2.3 and MRS (which would be MRO 3.2.2) installed side by side.

**Comment by int19h** [comment]
Same errors were also showing up on a different machine, that one with 3.2.5 and MRC.

**Comment by MikhailArkhipov** [comment]
Looks like for some reason

```
                    var r = await _host.Session.EvaluateAsync<JArray>(Invariant($"as.list(getNamespaceExports('{this.Name}'))"), REvaluationKind.BaseEnv);
 functions = r.Select(p => (string)((JValue)p).Value).ToArray();
```
yields null. It might happen I guess if eval failed when, for example, package dependencies are missing. Can you check if this is what throws?

**Comment by int19h** [comment]
Actually it throws `REvaluationException`, but the code in `GetFunctionNamesAsync` then swallows it, and so the value remains null.

**Comment by int19h** [comment]
Here's the error:
```
R evaluation failed:

as.list(getNamespaceExports('lme4'))

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘nloptr’
```

**Comment by int19h** [comment]
And I'm also seeing a similar error trying to do `library(lme4)`, so it is a package that is broken on my machine for some reason. The bug in our code is that we don't gracefully handle such cases.

**Comment by MikhailArkhipov** [comment]
Yes, it swallows it exactly b/c of this - if dependencies are missing, eval fails and dependencies can be randomly uninstalled or deleted. Adding null check then and returning empty enumerable.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/15b3daef67a9e6af9066230afe4a057c7c3a7739
