### ISSUE TITLE
Solution explorer shows deleted directory

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2108]
Like #1851, Solution Explorer shows deleted directory on 0.4.

**Comment by MikhailArkhipov** [comment]
There were fixes made in 0.5 for this.

**Comment by MikhailArkhipov** [comment]
Closing as fixed, will verify in 0.5

**Comment by Marchen** [comment]
I'm sorry for my slow response (I'm a bit busy on my work now...).
Thanks for the fix. I'm awaiting for the next release!
