### ISSUE TITLE
new Feature Switch Settings?

### ISSUE THREAD

**Issue by mstaelen** [Microsoft/RTVS#2109]
It's should be interesting to have with "Data Science Settings" another menuitem with "Go back Classic (or save) settings".

**Comment by MikhailArkhipov** [comment]
There a default VS way for this: Tools -> Import/Export Settings -> Reset Settings. VS then presents list of standard setting sets that come out of the box. Thanks.

**Comment by MikhailArkhipov** [comment]
Closing since this is really IDE functionality they are planning to improve. Feel free to send feedback to VS via VS Feedback button.
