### ISSUE TITLE
InvalidOperationException in file watcher

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2127]
```
      public void MarkAllDeleted() {
            foreach (var entry in _entries.Values) {
```
when deleting files in the project I got 'collection was modified, enumeration cannot continue'

**Comment by MikhailArkhipov** [comment]
```
                    case Added:
                        _entries.Remove(entry.RelativePath);
                        break;
```
is odd within enumeration loop.

**Comment by AlexanderSher** [comment]
`foreach (var entry in _entries.Values.ToList()) {` should be enough.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/afd6d8a1ea26f85c75152836eee2063159dae95e
