### ISSUE TITLE
Specified startup file does not exist

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2137]
Create new project
F5 or CTRL-F5
Interactive window:
```
The specified startup file does not exist: script.R
```
It does exist!

**Comment by huguesv** [comment]
Looks like the path needs to be made absolute, right now it's checking File.Exists on just 'script.R', which would only work if current working directory is the project directory.

**Comment by MikhailArkhipov** [comment]
```Path.Combine(Path.GetDirectoryName(ConfiguredProject.UnconfiguredProject.FullPath), file)```

**Comment by huguesv** [comment]
Would like to see both the settings files and the startup files to be treated the same.
https://github.com/Microsoft/RTVS/issues/2139

**Comment by huguesv** [comment]
This was fixed when we switched to a combo box for startup file selection.

**Comment by Masutani** [comment]
Similar error occur when I updated my RTVS to 1.0 RTM. Path seems to be set as $(SolutionDIr)\$(SolutionName)\script.R which doesn't exist. It should be $(SolutionDir)\$(ProjectDir)\script.R. It cannot be fixed in project file in a target.
