### ISSUE TITLE
Intellisense not showing up for newly installed packages

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2143]
Repro steps:
1. Install package, say 'RODBC'
2. when doing library() it does not show up.
3. Later it does not show any functions from thew newly installed package.

**Comment by MikhailArkhipov** [comment]
This basically same as #1604. We need some knowledge that new package got installed or loaded from REPL. We do look at ```library(...)``` statements in the editor and can try and discover package but in REPL we don't.

**Comment by MikhailArkhipov** [comment]
RS overrides ```install.packages``` and ```remove.packages```. We need to do the same, probably map over to ```rtvs:::package_uninstall``` and ```rtvs:::package_update``` and have them sending events

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
