### ISSUE TITLE
How I can debug external function

### ISSUE THREAD

**Issue by Valentin-Miroshnichenko** [Microsoft/RTVS#2152]
Hello. I would like to know How I can debug external function? I mean function that contains in external package. For example, I want to understand how a works function substr. I clicked go to definition and set a breakpoint and click source startup file but that has not happened. 
![Image of Yaktocat](http://content.screencast.com/users/Compaqster/folders/Snagit/media/5b5fef5b-eab2-49a6-9260-f3060256fbc8/08.05.2016-23.09.png)
I disabled Enable Just my code but it didn't help. How can I debug an external function?

**Comment by MikhailArkhipov** [comment]
Currently there is no support for stepping into external functions. The problem is with locating source code as R packages don't have equivalent of PDB/GDB information. We may implement some heuristics though.

**Comment by MikhailArkhipov** [comment]
This is basically the same as #802, so I am folding this one into the primary. Thanks.
