### ISSUE TITLE
Test failures with NullReferenceException due to null TelemetryRecorder

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2174]
At this line:

https://github.com/Microsoft/RTVS/blob/74139149da551ad63a1035f6adf4d8ef0a091adb/src/Common/Core/Impl/Telemetry/TelemetryServiceBase.cs#L41

(don't have the list of failing tests at hand, but can be obtained by doing a full test run)

**Comment by MikhailArkhipov** [comment]
They seem to be passing OK now

**Comment by MikhailArkhipov** [comment]
Closing unless there is a new repro
