### ISSUE TITLE
description for "str" has an extra space

### ISSUE THREAD

**Issue by zxzxy1988** [Microsoft/RTVS#2180]
The description is:

"...display the internal str ucture of an R object" - but it should be "structure"

![image](https://cloud.githubusercontent.com/assets/1185090/17800685/d1e85d82-6617-11e6-8d7a-87193a6e58ec.png)

**Comment by int19h** [comment]
The original doc text for `str` bolds the "str" in "structure" using `<b>` tags. It looks like we inadvertently insert a space there when stripping tags.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
