### ISSUE TITLE
"Open in Excel" needs progress notification

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2181]
For remote connections and huge data sets, it can take many seconds for the generated CSV file to be transmitted over to VS. Right now we offer no indication whatsoever that the operation is in progress - you click on the Excel icon in VE, and seemingly nothing happens, and then a few seconds later Excel suddenly pops up.

**Comment by MikhailArkhipov** [comment]
It actually does show some indication in the status bar. We could do output window as well. But showing progress dialog is probably not a good idea since it is modal

**Comment by int19h** [comment]
It's the transmission of the data that isn't currently reflected, because we transmit as a single blob. Once it's chunked, progress bar can be implemented for that part.
