### ISSUE TITLE
Credentials dialog pops up in background sometimes

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2182]
If you're poking around in VS while it's connecting to a remote broker, the dialog that it shows to request credentials may end up in the background, so you don't see it until you check the taskbar.

**Comment by int19h** [comment]
Probably need to set the parent window correctly when calling `CredUIPromptForCredentials`

https://msdn.microsoft.com/en-us/library/windows/desktop/aa375183(v=vs.85).aspx

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac
