### ISSUE TITLE
IntelliSense support for data.table objects

### ISSUE THREAD

**Issue by ksavin** [Microsoft/RTVS#2186]
data.table is a popular package that extends data.frame and is capable of fast and complex data transformations.

Its syntax exposes column names when applying transformations within "[ ]", e.g:

```
library(data.table)
dt <- data.table(mtcars)

# find average gross horse powers for 6-cylinder cars grouping by number of forward gears
dt[cyl == 6, mean(hp), by = gear]
```

It would be great if auto-completion of column names within brackets is supported by IntelliSense.

**Comment by smortaz** [comment]
+1

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e083bf16d48cbca63550deeb70ac06407475089d
