### ISSUE TITLE
RPackageManager.GetLibraryPathAsync doesn't work for remote connection

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2187]
Path to the preferred `libPath` should be provided by RHost.
Currently it is deducted from local connection's `RBasePath`

**Comment by int19h** [comment]
Note that there is a way to query the remote interpreter for its path via the broker - the `/interpreters` endpoint includes this information.

**Comment by MikhailArkhipov** [comment]
Played with this, nothing appears broken. What gives?

**Comment by int19h** [comment]
Make sure that you're trying it on a remote machine that has a different directory structure from your own - e.g. `Users` dir in a different place, or logging in as a different user entirely.

**Comment by karthiknadig** [comment]
https://github.com/Microsoft/RTVS/pull/2582
