### ISSUE TITLE
Regression: 1st RTVS install on a new machine fails to detect and ask to install R Client

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2188]
This used to work on previous machines. But while setting up a new machine today, I installed RTVS and was not prompted to install R Client.

**Comment by AlexanderSher** [comment]
Isn't it of by design now? Since we support remote rhost now, do we want to bother user with local RHost installation every time he installs VS?

**Comment by int19h** [comment]
I definitely didn't touch that intentionally.

But I'm not sure which build is that? Is it the MSI that I built locally on Friday (i.e. not the usual VS installer stuff)? If so, I'm not sure it's even supposed to do anything other than opening the start page in the browser.

**Comment by jflam** [comment]
It was from the MSI. I was wondering why we changed from .exe to .msi at the time.

**Comment by MikhailArkhipov** [comment]
We should be popping new UI either offering connect to remote or install of R Client.

**Comment by MikhailArkhipov** [comment]
So basically we should be auto-creating local connection if present.  If nothing is present and user hasn't created any remote connections we should be offering MRC (as before, only once). The wording of the message should change to remove notion of Tools | Options settings and instead tell to either create remote connection or a local connection manually in the Connections window. We should then bring connections window up automatically.

**Comment by int19h** [comment]
I would suggest that the auto-created connection is also non-removable, and the path in it is not editable - to prevent situations when user accidentally removes it, and doesn't know how to recreate it, because they never had to create connections before (as things Just Worked).

**Comment by MikhailArkhipov** [comment]
+1. I think [local] entry can be removed only when the underlying interpreter is uninstalled.
We should also output as much info as possible to REPL, not just 'host disconnected' but inform that there are no local interpreters or that remote machine has no R installed and so on.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/fff25f88abe22f5a6df42ca02e4b7c298fcf4a2f
