### ISSUE TITLE
R Package fails to load on fresh install

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2189]
Trying to run any of the commands under R Tools menu results in an R Package fails to load error and a modal dialog popping up. After restart of VS, commands now fail silently.

This is Visual Studio 2015 Update 3 + 2016-08-19.01 build.

**Comment by int19h** [comment]
That build is not from a buildserver, but is an unsigned local build, so you need to disable assembly signature verification for it to work (e.g. via preinstall.cmd).

**Comment by jflam** [comment]
I ran it again (new machine) but that didn’t fix it. Rebooted and relaunched VS and still none of the commands work. Installed RTVS again and same thing.

**Comment by jflam** [comment]
Should also mentioning that uninstall of RTVS and reinstall of RTVS - this is using your private build - doesn't fix this. I'll try just installing a signed build tomorrow from the build server. Thx.

**Comment by MikhailArkhipov** [comment]
Reinstall won't fix it if you clicked 'don't show this again' in package load failure dialog. VS marks package as failed and won't ever load it, signed or not. Run devenv /resetskippkgs

**Comment by jflam** [comment]
Package loads, but still getting the error. Attaching logs.

**Comment by jflam** [comment]
Actually attaching logs

[ActivityLog.zip](https://github.com/Microsoft/RTVS/files/433190/ActivityLog.zip)

**Comment by jflam** [comment]
Here's the actual error message from the logs: looks like something in the rhost work is breaking things:

Source: &apos;System&apos; Description: Value cannot be null.&#x000D;&#x000A;Parameter name: uriString&#x000D;&#x000A;System.ArgumentNullException: Value cannot be null.&#x000D;&#x000A;Parameter name: uriString&#x000D;&#x000A;   at System.Uri..ctor(String uriString)&#x000D;&#x000A;   at Microsoft.R.Host.Client.Host.RHostBrokerConnector.SwitchToLocalBroker(String rBasePath, String rHostDirectory)&#x000D;&#x000A;   at Microsoft.R.Host.Client.Host.RHostBrokerConnector..ctor(Uri brokerUri, String name)&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.CreateRInteractiveWorkflow()&#x000D;&#x000A;   at System.Lazy`1.CreateValue()&#x000D;&#x000A;   at System.Lazy`1.LazyInitValue()&#x000D;&#x000A;   at System.Lazy`1.get_Value()&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Package.Repl.VsRInteractiveWorkflowProvider.GetOrCreate()&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Packages.R.PackageCommands.GetCommands(ExportProvider exportProvider)&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Packages.R.RPackage.CreateMenuCommands()&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Package.Packages.BasePackage`1.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.R.Packages.R.RPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

**Comment by int19h** [comment]
Is it, by chance, on a machine without R?

**Comment by jflam** [comment]
Yes. That part is intentional since that's an important path for us. 😀😀

Get Outlook for iOS<https://aka.ms/o0ukef>




On Tue, Aug 23, 2016 at 11:09 AM -0700, "Pavel Minaev" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it, by chance, on a machine without R?

**Comment by AlexanderSher** [comment]
https://github.com/Microsoft/RTVS/issues/2141

**Comment by MikhailArkhipov** [comment]
Should be fixed with my recent merge
