### ISSUE TITLE
What is IsLoadingFromStorage option

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2197]
In R Tools/Options:
![image](https://cloud.githubusercontent.com/assets/1696845/17950593/14f585f8-6a11-11e6-8f3d-5600c81bf414.png)

**Comment by MikhailArkhipov** [comment]
```
        public bool IsLoadingFromStorage { get; private set; }
```

was added to the class. It may be possible to hide it via 

https://msdn.microsoft.com/en-us/library/system.componentmodel.browsableattribute(v=vs.110).aspx
