### ISSUE TITLE
"Include In Project" gives "Sequence contains no elements" error

### ISSUE THREAD

**Issue by klausmh** [Microsoft/RTVS#2200]
My project files tend to get hidden in the Solution Explorer. When selecting "Show All Files" and then "Include In Project", I get a "Sequence contains no elements" dialog box error.

**Comment by MikhailArkhipov** [comment]
R project is not a traditional VS project (i.e. files are not listed in the project file so it is compatible with how R Studio works). Solution Explorer simply shows content of the folder. So 'Include in project' doesn't apply here. If some files are not visible, can you please give us more details - perhaps send us logs via R Tools -> Feedback -> Send Frown.

Thanks!

**Comment by MikhailArkhipov** [comment]
Can also be one of #2108 #2060

**Comment by MikhailArkhipov** [comment]
We have 'exclude from project' disabled/removed, need to do the same with this one.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/d438dc8cf54f4b468cdf5687d4de94cd7f754da2
