### ISSUE TITLE
Connections window needs UI work and styling

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2208]
Initial appearance: 

1. Empty. Need to add some frame for the list? Watermark? Help text?
2. Delete is enabled. Why?
3. Add - what am I adding?

![image](https://cloud.githubusercontent.com/assets/12820357/17988671/a8f2f72e-6adc-11e6-8411-39e21eed5895.png)

Click Add

![image](https://cloud.githubusercontent.com/assets/12820357/17988704/dc46f18e-6adc-11e6-8124-de48d3881943.png)

Controls are not visible and no way to make them visible except by resizing the window to large enough. 

Field names are unclear. Tooltips name be helpful. Name = machine name or conntection name?
Path = machine name? URL? UNC?

**Comment by MikhailArkhipov** [comment]
For consistency sake it should have toolbar like database explorer with New..., Delete... buttons and the list filling the window.

![image](https://cloud.githubusercontent.com/assets/12820357/17988955/a1307988-6ade-11e6-82c0-e81070f8cc41.png)

List entries should either display connection info or have a tooltip with the connection info or work via Properties window.

Context menu 

![image](https://cloud.githubusercontent.com/assets/12820357/17988991/ed6e25d4-6ade-11e6-9249-f4be38303041.png)

Add Connection... dialog can be modal and should be verifying connectivity.

**Comment by AlexanderSher** [comment]
It is consistent with package manager and nuget. I agree that we need icons instead of buttons, but I don't want to use limited default list. I also don't think that it should be modal - making changes to connections doesn't block anything until you change your current connection, but the same thing can be done via dropdown in the status bar

**Comment by MikhailArkhipov** [comment]
I mean Name/Path/Arguments can be modal. As in 'Add Database Connection'. It will be model anyways when we add connect to Azure since standard connection building dialog is modal

**Comment by AlexanderSher** [comment]
Got it.

**Comment by MikhailArkhipov** [comment]
#2222
