### ISSUE TITLE
Cannot decrease memory limit when running remote

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2209]
```
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
...
Microsoft R Open 3.2.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation
```

```
> 5
[1] 5
Warning message:
cannot decrease memory limit: ignored 
```

**Comment by int19h** [comment]
I don't think this is remote-specific. It's just that this particular machine (VM?) had so little RAM, that our code that sets the limit, when it computed the desired limit based on physical RAM, arrived at a figure lower than R's default. So the fix is to add a check for that case.
