### ISSUE TITLE
Connection Manager has the wrong title

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2211]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/8877/17989263/e8bc44d8-6ae0-11e6-8ff8-11201f912aa3.png)

Should be "Connection Manager"

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f58f1a115e9a17547093899236a0887d806cf578
