### ISSUE TITLE
Connection Manager should populate with the current local R interpreter

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2213]
Right now, it appears that it only shows up if you have R Client installed and are using it. If you are using another R (e.g., MRO or CRAN R) it doesn't show up at all in the list - it is blank.

**Comment by AlexanderSher** [comment]
What is "Current"? The one that is installed?

**Comment by jflam** [comment]
More specifically, the R that is used when you startup the R Interactive Window

**Comment by MikhailArkhipov** [comment]
Folding into #2222

**Comment by AlexanderSher** [comment]
Restoring as a separate task
