### ISSUE TITLE
Switching to the broken remote link doesn't allow to switch back

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2214]
REPL becomes frozen

**Comment by AlexanderSher** [comment]
`ConnectionManager.ConnectAsync` throws `RHostDisconnectedException` that should be handled

**Comment by MikhailArkhipov** [comment]
#2239 may fix this

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/fff25f88abe22f5a6df42ca02e4b7c298fcf4a2f
