### ISSUE TITLE
Unable to recover and switch to local

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2217]
Killed VS via Debug | Terminate. Started anew. REPL no longer works.

![image](https://cloud.githubusercontent.com/assets/12820357/17989467/535dfa38-6ae2-11e6-8b04-1b1f6eda606f.png)

**Comment by MikhailArkhipov** [comment]
#2214

**Comment by MikhailArkhipov** [comment]
Still broken. Switching back throws

```
            if (Interlocked.CompareExchange(ref _initializationTcs, new TaskCompletionSourceEx<object>(), null) != null) {
                throw new InvalidOperationException("Another instance of RHost is running for this RSession. Stop it before starting new one.");
            }
```

need to dig around more.

**Comment by MikhailArkhipov** [comment]
Hopefully gets fixed by the transactions

**Comment by MikhailArkhipov** [comment]
However, this reproes only after 'Test connection' to a invalid remote. Attempt to switch to local fails, but actually the new setting is saved so restarting VS recovers.

**Comment by AlexanderSher** [comment]
I've fixed a batch of issues related to the R host switching, but can you give exact steps for the last repro?

**Comment by MikhailArkhipov** [comment]
1. connect to local
2. Create broken remote connection such as enter 'foo' in path.
3. Save and try connecting

Now you are broken and can't connect back to local (connect button does nothing):

![image](https://cloud.githubusercontent.com/assets/12820357/18321192/cce31240-74e1-11e6-8916-5b11012a765d.png)

**Comment by MikhailArkhipov** [comment]
Or rather, it doesn't work first time. if you click few times more it finally connects
