### ISSUE TITLE
Connection Manager should have an explicit edit mode

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2218]
Right now it's too easy to start editing a connection. Instead, the edit fields should be hidden or read-only until the user clicks on an edit icon next to an entry on the list. Then show the edit fields.

Both @karthiknadig and I both ran into this today.

**Comment by AlexanderSher** [comment]
In this case it can be a modal dialog

**Comment by MikhailArkhipov** [comment]
#2222
