### ISSUE TITLE
Connection Manager should show status while connecting to a session

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2219]
I know you guys know about this, but opening an issue here to track the fact that we need to show progress during the initial connection phase to the broker/host.

**Comment by MikhailArkhipov** [comment]
Part of #2222. Modal dialog can have Connect... button with progress and cancellation. This way user won't be able to click around and create more connections or reset REPL while connection is still being established.

**Comment by MikhailArkhipov** [comment]
@AlexanderSher - was it part of #2222 ?

**Comment by MikhailArkhipov** [comment]
The process is now modal with appropriate message
