### ISSUE TITLE
REPL should show some status about which session you're using

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2220]
The current UI in the bottom right corner of VS is a bit too subtle. Perhaps consider having the REPL command prompt show the identity of the machine that you're connecting to?

e.g., 

jflam-xlabvm1:5000 > 3 + 3

**Comment by MikhailArkhipov** [comment]
We can change title text such as

R Interactive [Local: R version]  
R Interactive [Machine:port  R version]

**Comment by smortaz** [comment]
still too subtle unless the color can be changed or something.

**Comment by MikhailArkhipov** [comment]
We can implement view adorner depending on the user feedback. Currently it is not clear if status bar and Workspaces window are insufficient.

**Comment by MikhailArkhipov** [comment]
Folding into #2284
