### ISSUE TITLE
Opening a project on a remote connection attempts to call setwd() against the local directory which may not exist on the server

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2223]
In this case it's trying to set the working directory to c:\users\jflam\src\demo directory which doesn't exist on the server.

![image](https://cloud.githubusercontent.com/assets/8877/17989817/1250cc2a-6ae5-11e6-9fd5-7be9c3bcfc5f.png)

**Comment by int19h** [comment]
We should be using the remote directory that is going to be mapped for that project... the catch is that until you do F5, that directory probably doesn't even exist.

I can unblock this for now by not doing setwd on project load if connection is remote, but we need to figure out what is the right thing to do here for a proper fix.

**Comment by int19h** [comment]
This was unblocked by #2225, but we still need to decide if there is some working directory that we do need to set here, and if so, what it is; otherwise, this is fixed. @jflam?

**Comment by int19h** [comment]
Any updates on the desired behavior?

**Comment by MikhailArkhipov** [comment]
Probably just skipping setwd for now

**Comment by int19h** [comment]
Sounds good. I'll close this one then, and we can open a new one if some other desired behavior emerges in testing.
