### ISSUE TITLE
Working directory is wrong for remote connections

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2224]
When we connect, we set current working directory to "C:\Users\...\Documents". The problem is that we determine that path on VS side of things, so it is not necessarily valid for the remote machine. And if that path doesn't exist, setting the working directory fails, and then everything that tries to get the working directory also fails (and crashes VS).

**Comment by int19h** [comment]
Also see #2223 - probably same root cause.

**Comment by int19h** [comment]
So, the problem is that right now we actually let the user specify the default working directory in R Tools | Options, and then just blindly apply that setting to all connections. Obviously this isn't working for remote.

First question: do remote connections even need a user-settable working directory? Or do we just assume that it's always `~`, so that users remain boxed in their own folders? If so, we can just stop applying this option to remote connections.

We could go one step further, and have this become a per-connection setting. And then either only allow it for local connections, or for both local and remote - but in the latter case, we need to figure out what it actually means for remote, and how it should be constrained.

I'm going to do #1 for now because it's very easy and fixes the immediate problem. But we need to discuss were we go from there. @jflam?

**Comment by MikhailArkhipov** [comment]
I think #1 is fine. We will see if users need to set the directory differently from usage/feedback.

**Comment by int19h** [comment]
Sounds good, then https://github.com/Microsoft/RTVS/pull/2225 was the fix.
