### ISSUE TITLE
Create broker monitoring process

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2226]
So it starts and runs without having user to log on and start it manually

**Comment by int19h** [comment]
To be more specific, it should be capable of working both as a console app (for local mode, so that VS can start it), _and_ as a service (for remote).

**Comment by MikhailArkhipov** [comment]
http://www.c-sharpcorner.com/UploadFile/naresh.avari/develop-and-install-a-windows-service-in-C-Sharp/

**Comment by karthiknadig** [comment]
Bulk of the service is done. Currently blocked on CreateProfile.

**Comment by MikhailArkhipov** [comment]
Can you split CreateProfile into a separate item and merge the service part so we can complete and test the setup?

**Comment by karthiknadig** [comment]
https://github.com/Microsoft/RTVS/issues/2383 that is the one that corresponds to CreateProfile

**Comment by karthiknadig** [comment]
Monitoring process and Profile service have been created. Pending adding it to remote MSI.

**Comment by MikhailArkhipov** [comment]
Is is done per most recent PR merge?
