### ISSUE TITLE
R interactive is activated when debugging Python

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2229]
When I'm debugging a Python program using PTVS, executing some code in Immediate window and then activating Python Editor activates R Interactive window.

**Comment by MikhailArkhipov** [comment]
Probably same as #983 which should be fixed in 0.5, but need to verify.

**Comment by MikhailArkhipov** [comment]
Actually, side effect of #1938

**Comment by MikhailArkhipov** [comment]
Workaround is not to start R before Python (i.e. close R Interactive, restart VS).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e52124fac6645fe888e6d45d3dac98f50d8c9420

**Comment by Marchen** [comment]
Thanks for the fix!
