### ISSUE TITLE
Broker should not crash when VS is terminated

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2232]
Every time on Debug | Stop Debugging 

![image](https://cloud.githubusercontent.com/assets/12820357/18097871/a0e39136-6e94-11e6-9da3-d66d9a930811.png)

**Comment by int19h** [comment]
This might be related to https://github.com/Microsoft/RTVS/issues/2198

**Comment by MikhailArkhipov** [comment]
I am going to change this one to FailFast in release and just trace to log in debug.

**Comment by int19h** [comment]
I would suggest just changing it to Environment.Exit. That way it will still terminate, but not in a quite so spectacular way.

(Long-term, ideally, we should figure out why something doesn't respect the cancellation token and sticks around. But we still need the failsafe here either way, to ensure that process doesn't stick around.)

**Comment by MikhailArkhipov** [comment]
OK, I'll do that

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16bbfb33f3c03917ba44003ed507f46f3920cfac

**Comment by MikhailArkhipov** [comment]
It came back

**Comment by int19h** [comment]
Are you sure it's actually crashing? It may print some exceptions out in the console log, which is fine (they're exceptions from outstanding aborted connections). But this doesn't cause the process itself to crash for me, with Watson etc - it just exits.

**Comment by MikhailArkhipov** [comment]
I am getting the same dialog.

![image](https://cloud.githubusercontent.com/assets/12820357/18400909/b87e1438-768c-11e6-86a9-ddfbcb4f089d.png)

**Comment by int19h** [comment]
Okay, this is a different stack though (and I couldn't readily repro that).

Judging by the stack, looks like a bug in Kestrel itself? None of our code is on the stack, and they're basically throwing an exception in the finalizer, which is a big no-no.

I'll think about what can be done to work around this.

**Comment by MikhailArkhipov** [comment]
Seems to be OK now
