### ISSUE TITLE
Correctly handle reconnection to the previously connected broker

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2247]
Scenario:
1. Connect to broker A
2. Start long-running calculations
3. Connect to broker B
4. Connect to broker A

**Actual** Result is unpredictable, new instance of RHost won't be able to handle response for the request that was created by another instance of RHost
**Expected** Interactive Window prints output from the calculation, all evaluation requests

**Comment by MikhailArkhipov** [comment]
This is generally same as a network disconnect in a middle of calculations

**Comment by MikhailArkhipov** [comment]
Folding into #2176
