### ISSUE TITLE
Workspace Window: Cannot edit the name of an existing local workspace

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2257]
I cannot click on the text box. Clicking selects the entire connection and winds up attempting to connect if I double click on it.

![image](https://cloud.githubusercontent.com/assets/8877/18320701/c96677b2-74df-11e6-8bfb-14b2e05c83d3.png)

**Comment by MikhailArkhipov** [comment]
By design. Maybe we can add something to the name.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2e62ba12bb572cfadfafa58536ed607d89cc51f5
