### ISSUE TITLE
Workspace Window: Trying to connect to a remote machine where the broker is not running fails silently

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2258]
In the screenshot below, I tried to connect to the remote and the remote wasn't running. In this case we need to inform the user that the connection was not successful:

![image](https://cloud.githubusercontent.com/assets/8877/18321040/37344214-74e1-11e6-897c-2f74867447a7.png)

The message should say:

Could not connect to <name of connection>. For troubleshooting tips please see https://aka.ms/rtvs_troubleshooting_remote

**Comment by MikhailArkhipov** [comment]
Probably same or part of #2219

**Comment by MikhailArkhipov** [comment]
Also #2264

**Comment by AlexanderSher** [comment]
Output to the REPL is provided
