### ISSUE TITLE
Auto-detection of interpreters fails occasionally

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2262]
![1](https://cloud.githubusercontent.com/assets/12820357/18321833/9e7bb008-74e4-11e6-9c6b-e5c3e1ed41e7.jpg)

**Comment by MikhailArkhipov** [comment]
Also #2255

**Comment by MikhailArkhipov** [comment]
Broker correctly reports 'Failed to retrieve R installation data for interpreter'. The path passed from VS points to R 3.2.2 folder where R files are actually missing. So the issue is why this path was not filtered out.

**Comment by int19h** [comment]
We do, however, need to improve reporting from the broker for when a session is requested with non-existing interpreter ID (including blank ID when no interpreters are available). Right now we just throw, which gets reported to the client as HTTP 500 error with no body, so it's not possible to distinguish this particular error from any other failure on the broker side. 

Probably the easiest way to do this is to add an extra HTTP X-header to the response, that would contain our own error code, if it's an anticipated error (and not a general failure). The client can then check that header if it receives an error response, and display the appropriate error messages.

**Comment by int19h** [comment]
Also, in many cases, we can just use more specific HTTP status codes instead of 500 (when an exception is unhandled, it's always reported as HTTP 500). This catalog will be helpful:

http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

For the situation when an entity (e.g. an interpreter in this case) is requested, but is not found, it seems that HTTP 422 might be the appropriate status code.

**Comment by MikhailArkhipov** [comment]
Or we could use something from unassigned ranges like 512-599.
`428	Precondition Required` or `417	Expectation Failed` sound reasonable.

**Comment by MikhailArkhipov** [comment]
The issue is that when R was found in the registry but files were missing on disk and code ended up with zero engines, it resorted to probing `Program Files\R` and actually found the folder - but code does not check for file existence. Since this is a very old fallback, I guess we've never encountered this case before.

**Comment by MikhailArkhipov** [comment]
Splitting broker error returns to #2264

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/2e62ba12bb572cfadfafa58536ed607d89cc51f5
