### ISSUE TITLE
Visual studio is reset after running idle for sometime

### ISSUE THREAD

**Issue by Han-Up** [Microsoft/RTVS#2265]
Please briefly describe what you were doing that led to the issue, if applicable:

having used VTS and leaving it idle sometime, I find all Visual studio is reset as if someone shut and re-run the problem with empty am empty workspace.
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.1

**Comment by MikhailArkhipov** [comment]
Please try 1.0 RC, 0.4 is very old. Thanks.
