### ISSUE TITLE
Detect remote broker version and handle compatibility

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2272]
B/c of the fact that remote setup is separate there may be situations when RTVS with one version attempts to connect to a machine where broker is not compatible. We need to be able to inform the user.

**Comment by smortaz** [comment]
in fact in the UI, please display broker, rhost, R versions (perhaps in a
detail tab?)

**Comment by MikhailArkhipov** [comment]
Basically broker needs to be able to return JSON with system and broker information

**Comment by MikhailArkhipov** [comment]
Same as #2931
