### ISSUE TITLE
Error on adding Nuget package to solution

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2276]
Is it possible to add packages to an RTVS solution?

I’m trying to add [Secure-File](https://www.nuget.org/packages/secure-file/) to a solution, and the Package Manager console is giving me an error:

```
PM> install-package secure-file
install-package : Project 'Default' is not found.
At line:1 char:1
+ install-package secure-file
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

```

**Comment by MikhailArkhipov** [comment]
No, it is not possible. Nuget is more or less for adding dependencies to projects that do support references. Technically nuget does can be used for general case of adding files... How would you like to use nuget with R?

**Comment by Hong-Revo** [comment]
This is to support Appveyor CI for the RSQLServer project.

I worked around this by adding the package manually via the Windows command line.
