### ISSUE TITLE
Excel seems to be not installed

### ISSUE THREAD

**Issue by Charmatzis** [Microsoft/RTVS#2279]
Hi, and nice job.... In the Variable Explorer window I try to view results with the excel button but the VS shows a error "Unable to open CSV file. Extension: this action is only valid for products that are currently installed"

I have installed in my machine excel 2016 x64 version.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.1

**Comment by Charmatzis** [comment]
I fixed it with instuctions from this [link](https://www.raymond.cc/blog/automatically-diagnose-and-repair-office-2007-problems/)

**Comment by MikhailArkhipov** [comment]
OK :-). We do not actually check for Excel. We launch by file extension (CSV) so if user has another app that can handle tables, it will work too.
