### ISSUE TITLE
Some remote connections are non-removable

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2280]
![image](https://cloud.githubusercontent.com/assets/1175142/18402281/92ceca8c-7693-11e6-85ee-a2aeef375cab.png)

Note how two out of three connections in the Remote section have delete icon disabled. When hovering over it, the tooltip gives the usual message about auto-detected R etc.

These connections were created on an earlier build, however.

**Comment by MikhailArkhipov** [comment]
They might not had IsUserCreated flag set in settings in earlier builds. There is an issue that we just serialize class into settings so when it changes new fields are not populated.

**Comment by MikhailArkhipov** [comment]
No longer applies since we changed connection storage.
