### ISSUE TITLE
Switching from local to remote connection disconnects

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2281]
RTVS launched with the default local session, then told to switch to remote:
```
Switching R Workspace completed
Start switching to the 'pmin-vm-w7-vs14': http://pmin-vm-w7-vs14:5000/
Connecting sessions (2) to the new R Workspace...
R Host process is stopped. Click Reset to start a new one.Restarting sessions (2)...
> 1+2
Interactive Window is disconnected from R Session.
Try connecting to a remote machine in the Workspaces window or
click Reset to restart local R interpreter.Starting R Session...
```
To fix this, I had to Reset - that reconnected and worked.

Also, the message is misleading: "click Reset to restart local R interpreter" - it actually restarts the active connection, local or remote.

**Comment by MikhailArkhipov** [comment]
Probably same as #2217

**Comment by AlexanderSher** [comment]
Ok, I have a repro for this one. It happens when you double-click on the connection icon - it initiates connection to the same broker with the same parameters which isn't handled.
That kills the RHost and may leave one of the locks in the invalid state.
