### ISSUE TITLE
Remoteness should be displayed visibly at all times

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2284]
for example on tool window names:

Remote - PavelRemote:5000

R Pkg Manager - Fatbox:4000

etc.

**Comment by int19h** [comment]
Users likely won't care about anything other than hostname for this purpose, so we can skip the port (technically it's possible to have two different brokers on the same hostname, but realistically this isn't likely). Or better yet, use connection name.

Also, "X - Y" format is used for document windows in MDI (i.e. "foo.txt - Notepad"), so we should probably use something else. E.g. "R Package Manager (Remote1)".

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5dea54595b7ca024c580e38dd8e1ca76d9d1071d
