### ISSUE TITLE
Variable Explorer: Importing Files from URI fails on remote session

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2286]
Repro:

1. Bring up variable explorer and click on the top-left toolbar button (Import DataSet)
![image](https://cloud.githubusercontent.com/assets/8877/18403694/1af2c826-769b-11e6-8957-75d784b72a34.png)

2. Enter a URI. This one works: https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat

3. RTVS will download the file to the client; it doesn't exist on the server, so when we attempt to run this line of code interactively it fails because the server cannot read from the file (tmp621C.tmp.utf8) on the client machine.

`airlines` <- read.csv(file="C:/Users/jflam/AppData/Local/Temp/tmp621C.tmp.utf8", header=TRUE, row.names=NULL, encoding="UTF-8", sep=",", dec=".", quote="\"", comment.char="")

We will need to move the file from the client to the server, or have the server download the file from the URI.

**Comment by MikhailArkhipov** [comment]
#2097

**Comment by MikhailArkhipov** [comment]
Disabled on remote
