### ISSUE TITLE
remote msg improvements

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2290]
> Start switching to the 'PavelRemote': http://pmin-vm-w7-vs14:5000/
Connecting sessions (2) to the new R Workspace...

instead:

**Switching from 'xxx' to 'yyy' http://blahblah:5000
Please wait...**

<some time passes>

**Successfully connected to 'yyy'**

----R intro msgs
----R intro msgs
----R intro msgs

**R @ 'yyy' ready...** 

**>>**

![image](https://cloud.githubusercontent.com/assets/742484/18403874/2d999bde-769c-11e6-99bd-7718e4805e50.png)

**Comment by MikhailArkhipov** [comment]
This has been working for a while, added machine info
