### ISSUE TITLE
closed/opened laptop got rhost crash

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2292]
![image](https://cloud.githubusercontent.com/assets/742484/18405017/5084392c-76a3-11e6-9886-b23d6c3f0208.png)

**Comment by int19h** [comment]
Need to look up crash dump in Watson to diagnose.

**Comment by MikhailArkhipov** [comment]
May be related to #2232

**Comment by MikhailArkhipov** [comment]
Folding into #2385
