### ISSUE TITLE
RTVS cannot be installed standalone

### ISSUE THREAD

**Issue by fmms** [Microsoft/RTVS#2303]
Hi,

I think it would be a very worthwhile feature to be able to install RTVS standalone. In most BI projects we just use the integrated and isolated shell of visual studio. This is supported very nicely by SSDT (e.g. https://msdn.microsoft.com/en-us/mt186501.aspx). However the RTVS setup requires a "real" edition of VS.

![rsetup](https://cloud.githubusercontent.com/assets/908734/18469968/98dfc5c4-79aa-11e6-964e-31b0de73e8ea.PNG)

I have a Visual studio 2015 Update 2 shell installed.

![2016-09-13 12_06_39-microsoft visual studio](https://cloud.githubusercontent.com/assets/908734/18469995/c8e5690e-79aa-11e6-8bbe-35944410ebb9.png)

regards
Felix

**Comment by MikhailArkhipov** [comment]
We'll see if ISO shell has enough components for RTVS. Thanks!

**Comment by MikhailArkhipov** [comment]
SSDT doesn't ship interactive window...

**Comment by MikhailArkhipov** [comment]
Neither it has project system components. CPS will also need MSBuild... This may get complicated.

**Comment by MikhailArkhipov** [comment]
RTVS will be integral part of VS 2017 so this issue goes away
