### ISSUE TITLE
Help window should reset when switching sessions

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2321]
If help for something is brought up in a remote session, and then session is switched to local, the Help window continues to show the original topic from remote session. Furthermore, any links in the window will also open pages from remote session. This is observable when remote and local R versions differ (help pages include R version in the footer). 

Help should listen to session connected/disconnected events, same as other toolwindows, and reset itself accordingly.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/7235095f9d8517e3b869ea588d95700b8ac8fdf3
