### ISSUE TITLE
Active session indicator is out of sync

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2322]
After switching from a remote session to local:
![image](https://cloud.githubusercontent.com/assets/1175142/18495120/223ed3c6-79d0-11e6-9dda-86307876cfbc.png)
Note that both the Workspaces tool window and the status bar indicator say that the current session is the remote one, but the REPL has already switched to local, and reflects this in its title bar.

**Comment by AlexanderSher** [comment]
Did it finally switched to the local?

**Comment by int19h** [comment]
When I clicked on the arrow on "Local" to activate it (again), the switch was properly reflected everywhere. From there, it seems to be tracking everything fine.

Before I got into this stage, I started VS with Local, added a new connection (perhaps that is somehow important?), and switched to that remote connection and used it for a bit. Then switched back to local to get to the screenshot.

**Comment by MikhailArkhipov** [comment]
#2288
