### ISSUE TITLE
Adding a project to existing solution fails with COR_E_EXCEPTION

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2327]
Repro steps:
1. Create a blank solution and open it.
2. File > New > Project 
3. Select R Project
4. Select "Add to Solution" Option 

![image](https://cloud.githubusercontent.com/assets/3840081/18522883/c110feca-7a66-11e6-8399-e2fff7805762.png)

**Comment by MikhailArkhipov** [comment]
No longer reproes. Reactivate if you still see it.
