### ISSUE TITLE
CM should not be restoring remote connections automatically 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2336]
@ VS startup. User may or may not intent to connect or even use R.

**Comment by AlexanderSher** [comment]
Ok, so restore connection when first RSession is created?

**Comment by MikhailArkhipov** [comment]
Actually switch to local or, if none, just leave it disconnected. I have a fix.

**Comment by MikhailArkhipov** [comment]
@AlexanderSher - I believe you've merged my changes, right?

**Comment by AlexanderSher** [comment]
You have actually merged them yourself, so yes - this one is closed.
