### ISSUE TITLE
Connection progress doesn't dismiss when it can't connect

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2354]
The progress bar dialog stays there forever, despite the connection error in REPL.

![image](https://cloud.githubusercontent.com/assets/1696845/18689216/e5d40934-7f3c-11e6-923d-9c62b9fa246f.png)

**Comment by AlexanderSher** [comment]
R Interactive is missing a message that it is restoring connection: 
```
Connecting to the new R Workspace failed, restoring connection to 
'Microsoft R Client' : C:\Program Files\Microsoft\R Client\R_SERVER\
```
There also should be a message from the second RSession, so it definitely didn't finish waiting for it.

So the issue is that we don't need to wait for other sessions to fail and just cancel them.
