### ISSUE TITLE
Status bar R Workspaces switcher not synchronized with Workspaces window

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2358]
There are two separate issues here:
1. If I change the name of a workspace in the workspaces window, that change is not reflected in the status bar switcher (see screenshot)
2. I was unable to connect to my jflam-x250vm remote workspace - that was the first remote workspace in the workspaces window. When I look at the workspace taskbar switcher, I don't see it listed anymore. Not sure if it was ever there.
3. Elaborating on #2, the list of workspaces is definitely not the same (I have 8 in the screenshot and there are only 5 in the switcher).

![image](https://cloud.githubusercontent.com/assets/8877/18690227/fe0942d0-7f41-11e6-8399-06eccad8ff8a.png)

**Comment by AlexanderSher** [comment]
Switcher shows only the last 5 connections that user has used

**Comment by MikhailArkhipov** [comment]
@jflam : Should it be showing all available? It was intended to me MRU list rather than general connection list.

**Comment by AlexanderSher** [comment]
@jflam : Is there still an issue or we can close this one?

**Comment by MikhailArkhipov** [comment]
I haven't seen this for a long while.
