### ISSUE TITLE
While switching between connections I can type under the modal window

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2360]

**Comment by AlexanderSher** [comment]
UI thread has to blocked explicitly

**Comment by MikhailArkhipov** [comment]
This was done AFAICS

**Comment by MikhailArkhipov** [comment]
Still not blocked

![image](https://cloud.githubusercontent.com/assets/12820357/19135937/5d2e5ebc-8b1d-11e6-95cb-f55a1f9ec596.png)

**Comment by MikhailArkhipov** [comment]
Try https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivsuishell.enablemodeless.aspx
