### ISSUE TITLE
Workspaces window doesn't allow multiple connections that differ only by URL fragment

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2361]
Try adding two remote connections like so:
- http://localhost#foo
- http://localhost#bar

The second one ends up overwriting the first. This shouldn't be happening, since fragment is a meaningful part of the URL (it designates which version of R to use, if broker has more than one configured).

**Comment by AlexanderSher** [comment]
Are you sure that fragment identifiers are sent to the server?

**Comment by int19h** [comment]
They are not sent as part of the request URL, nor they should be - fragment is a client-side thing. There's code somewhere in BrokerClient that extracts the fragment from the URL, and uses it as CreateSessionRequest.InterpreterId.

**Comment by AlexanderSher** [comment]
Pulling back to Sprint 9 cause it is related to #2807 and #2823

**Comment by AlexanderSher** [comment]
Right now fragment is actually trimmed
