### ISSUE TITLE
Failing the fallback for remote connection failure leads to a unconnected REPL

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2368]
Chain of events:
1. connected to machine 1 (working)
2. initiated switch to machine 2 
3. machine 2 connection failed (with the following message): 
 Starting R Session has failed, please restart it manually. Restoring connection to the 'machine-1'
4. machine 1 connection failed.

may be connect to local if it exists?

**Comment by AlexanderSher** [comment]
There maybe several locals or no locals at all, so IMO we should leave a decision to the user. But we need to change messages: #2372
