### ISSUE TITLE
"matrix" doesn't show up in completion list on MRO

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2371]
`matrix` function is not showing up in the completion list when typing "matrix" in the REPL. The completion list is there, but it only shows a single entry "Matrix" (note capitalization), corresponding to a library with the same name. The function is there and can be called, though.

**Comment by int19h** [comment]
It appears that we have some issue with case sensitivity in completion lists in general. Do this:
```r
aaa <- 123
AAA <- 456
```
Only "aaa" shows up in the list, not "AAA". Now do:
```r
Aaa <- 789
```
Now only "Aaa" shows in the list.

**Comment by MikhailArkhipov** [comment]
Regression after #2165

**Comment by MikhailArkhipov** [comment]
Change ported
