### ISSUE TITLE
Don't restore connection when new connection failed

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2372]
- Connecting to remote machine make take time
- User may not necessarily want this
-  It is confusing: we restore local and if user missed the message, repl shows R header and user may have an impression that switch succeeded.

Just output:

'Connection failed. Open Workspaces window and select local R or create another remote connection'.

**Comment by AlexanderSher** [comment]
Here is how it works right now:
1. New instance of broker client is created.
1. All sessions start their switching transactions.
1. All sessions create new instances of RHost, which includes start of the local broker (if required) and connection to the web socket. After this step has succeeded, we know that broker is working. At the end of this step all sessions are still alive, their interaction and evaluation requests are valid, old RHost instances aren't disposed or stopped. 
1. All sessions are restarted using new RHost instances. If anything happens during this step, RSession instances will be in broken state, so here is when user input is required: he may want to either restart the old session or try to switch to a different one. It is a question though what should we do if user has canceled a switch during this stage - should we switch to the old broker or leave him with the new one. Current implementation leaves him with the new one. After this step old broker is still alive.
1. Old broker instance is disposed.

Right now we show separate messages between these steps and notify user about all errors that happen. We probably need to change text of those messages.
@jflam , @smortaz , what do you think?
