### ISSUE TITLE
Reconnect to existing session

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2385]
For remote connections, users should be able to reconnect to an existing session, instead of recreating a new one.

**Comment by MikhailArkhipov** [comment]
So I assume #2386 is now future?

**Comment by int19h** [comment]
#2386 is basically implemented already, and I would like to merge that part, because it comes with a few bugfixes, and to avoid bitrot for unmerged changes. Other than bugfixes, all the new functionality is gated on command line switches, so we will simply avoid exercising it for now.

#2387, and therefore #2176 (since it depends on it), we can move to Future.

**Comment by int19h** [comment]
https://github.com/Microsoft/RTVS/pull/2413
