### ISSUE TITLE
Fail to connect to remote machine, then couldn't connect to anything, including local

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2401]
Tried to connect to ddhuvalo083:5000, which didn't respond, progress bar dialog stayed up for 3-5 mins.
That's a machine that has an older build of remote services, which was lacking the VC CRT.
I hit cancel.
Now when I click connect for another remote or for local, nothing happens, as if I didn't click at all.

**Comment by huguesv** [comment]
Alternative repro:
Connect to local R.
Type `q()`
You can't connect to anything else by clicking on connections in Workspace windows.

**Comment by MikhailArkhipov** [comment]
Same as #2397 I believe

**Comment by AlexanderSher** [comment]
No, the root cause of this bug is different from #2397.
