### ISSUE TITLE
When switching between connections, plots of previous connection remain

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2403]
Right now we're cleanup up in the RSession.Disconnected event, so maybe we're not getting that event anymore when we switch between remote/local?  I suppose I can do it in RSession.Connected instead.

Note that this is not the same as https://github.com/Microsoft/RTVS/issues/2314, which is about supporting returning to an existing session.

**Comment by MikhailArkhipov** [comment]
As happens to Help in #2321. Not sure about package manager though. @AlexanderSher - does it have facilities to refresh on new connection?

**Comment by MikhailArkhipov** [comment]
Actually we should only clear when connecting to another session. Disconnecting and reconnecting to the same session should keep everything intact. Network reliability or the fact that they have to leave WiFi coverage should not be destroying user work.

@AlexanderSher  - is there a good even for this?

**Comment by AlexanderSher** [comment]
If you mean switching from one broker to another - `BrokerChanged` will suffice.

**Comment by huguesv** [comment]
Is there also a way to distinguish between lost connection + reconnect, versus the user hit Reset in the REPL?

Because we need to clear plots if they hit Reset, but we don't want to if they lose connection and reconnect.
