### ISSUE TITLE
Create DB connection in a separate environment

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2409]
And perhaps other settings?

```
I’m not really sold on creating objects in the global environment though. 
That’s not supposed to happen with well-behaved packages, and the same 
principle should apply for IDEs. Eg what happens if the user already has 
an object called dbConnection? Does it just get overwritten silently?

I think it would be better to make a custom environment for settings, 
and attach it to the search path. That way anything that RTVS creates 
will still be visible, but not affect user-created objects.
```

**Comment by Hong-Revo** [comment]
Thinking about it some more, you probably shouldn’t even attach the settings environment. Instead, refer to all settings objects with the namespace-qualified name, `settings:::dbConnection`.

The risk with attaching the environment is that you can change the meaning of user code that doesn’t have explicit namespace references. Not using namespaces is a bad habit among many R programmers (me included).
