### ISSUE TITLE
Keyboard support to invoke context menu in plot device window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2410]
Right now it's mouse right-click only, can't invoke the context menu with keyboard.

**Comment by MikhailArkhipov** [comment]
Shift+F10

**Comment by huguesv** [comment]
I can't get any keyboard events in the plot device user control.  The control contains just an `Image` (the plot) or `Label` (please plot something). I tried various solutions with marking the user control Focusable, calling Focus() on it in Loaded event, but I've never seen any Key event (PreviewKeyDown, PreviewKeyUp, KeyDown, or KeyUp).
Apparently, in those cases you're supposed to attach to the Window's PreviewKeyX events, instead of user contorl. If I call `Window.GetWindow(this)`, it looks like I get the main VS window.  Good news is that I now get key events. Bad news is that I get them from anywhere inside VS. There has to be a better solution than this.

**Comment by MikhailArkhipov** [comment]
I don't think we need this since all commands are available on toolbar
