### ISSUE TITLE
Rendering error on existing plots create new entries in plot history for each error

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2418]
`plot(mtcars)`

Keep resizing it too small so it says "Error rendering plot".

Every time you resize, a new blank entry is added to plot history.

You'll end up with a plot history like this:
![image](https://cloud.githubusercontent.com/assets/1696845/19050986/d983fb7a-8965-11e6-9cf1-122b09d48249.png)

Problem is that host is calling `render_empty()` and doesn't pass in the plot identifier.

**Comment by smortaz** [comment]
should this be fixed before sending to EA?

**Comment by huguesv** [comment]
Turns out there was more to it than I initially anticipated.  Since it's not a crash, and mostly just an annoyance, I'm not sure it's worth fixing in 0.5
