### ISSUE TITLE
Do not silently overwrite sessions that are in the process of saving their state

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2426]
#2425 means that sessions can be in a "currently live, but saving state after connection was lost" state. There's a possibility of a race condition there whereby the user might try to reconnect when session is still in that state; currently, we just kill & restart the session, thus losing any data it might have been saving.

VS needs to recognize this new state, and prompt the user whether they want to reconnect right now (and lose the state), or wait until the state is fully saved.

**Comment by AlexanderSher** [comment]
Do we need to save state of Intellisense or Package Manager sessions?

**Comment by int19h** [comment]
Good point. I can't think of any reason why we'd want to. Which means that there needs to be a flag on session creation to specify whether this particular session is save-on-disconnect or not.
