### ISSUE TITLE
Solution explorer gets out of sync with file system

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2428]
It's probably going to be impossible to repro, but see how my `ggplot2test` folder appears empty in solution explorer but has files in windows explorer.  In fact, I created those in that same session of VS, and they are opened in the editor!

![image](https://cloud.githubusercontent.com/assets/1696845/19092571/28a056e6-8a3c-11e6-872f-fc18199836ed.png)

**Comment by MikhailArkhipov** [comment]
#2475

**Comment by MikhailArkhipov** [comment]
After the fix for #2475 please reopen if still reproes
