### ISSUE TITLE
Failed to connect to remote, it connected to local instead

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2436]
I clicked on connect next to ddhuvalo086.  It didn't complain, but it connected to local instead.  See how the title bar of REPL disagrees with status bar/connection mgr.

![image](https://cloud.githubusercontent.com/assets/1696845/19134265/d8ab23ec-8b11-11e6-963c-e513950ffe37.png)

RTVS is on latest sources from master.  ddhuvalo86 remote services is from yesterday's build.

**Comment by AlexanderSher** [comment]
What is showing the truth? Is it local or remote?

**Comment by huguesv** [comment]
It's really local.
