### ISSUE TITLE
Add R syntax highlighting/Intellisense in SQL scripts

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2437]
At the moment, a SQL script is treated as entirely SQL, even when it contains embedded R code. It would be nice if Visual Studio could detect that it's R and treat it appropriately.

![image](https://cloud.githubusercontent.com/assets/11328890/19144670/a21045fc-8bf6-11e6-8783-721ec4173a3f.png)

**Comment by MikhailArkhipov** [comment]
This is actually for the SQL language service as we don't own SQL editor. This may help http://connect.microsoft.com/VisualStudio/content/content.aspx?ContentID=26698 or use VS feedback button

![image](https://cloud.githubusercontent.com/assets/12820357/19165919/897acce2-8bba-11e6-80bf-9b3d46f14313.png)

**Comment by MikhailArkhipov** [comment]
Closing since this is 100% external
