### ISSUE TITLE
Quota settings for broker process

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2442]
1. Limit number of users
2. Limits memory per user (set on the host process)
3. Limit CPUs per user (set on the host process)

**Comment by int19h** [comment]
I think that 2 and 3 are probably best handled by the OS itself. Setting limits on the host process alone is rather pointless, as it can spawn other processes - the quota enforcement really needs to be for the aggregate of all processes that the user is running, host or not.

The knobs that we can meaningfully implement in the broker are 1) max number of active users, and 2) max number of active sessions per user.

**Comment by MikhailArkhipov** [comment]
I think it is added to a Job object, child processes get added to the same job and quota is enforced on the job.

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
