### ISSUE TITLE
TestBrokerConnectionWithRHost unexpectedly throws OperationCanceledException

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2444]
```{csharp}
        private async Task RSessionOnDisconnectedAsync() {
            var token = await _brokerDisconnectedLock.WaitAsync();
            try {
                if (!token.IsSet) {
                    // We don't want to show that connection is broken just because one of the sessions has been disconnected. Need to test connection
                    await TestBrokerConnectionWithRHost(_brokerProxy, default(CancellationToken), default(ReentrancyToken));
                    token.Reset();
                }
            } catch (RHostDisconnectedException) {
                token.Set();
                OnBrokerDisconnected();
            } catch (Exception) {
                token.Reset();
            }
        }
```

`TestBrokerConnectionWithRHost` gets default `CancellationToken`, so it shouldn't throw `OperationCanceledException`.

**Comment by AlexanderSher** [comment]
Looks like bug is just a symptom
- `OperationCanceledException` comes from timeout, which isn't right - there should be `HttpException` in case of a broken connection
- One of the possible ways to repro the bug is to kill the remote broker and while `RSessionOnDisconnectedAsync` is executed, click Reset on interactive window.

**Comment by AlexanderSher** [comment]
https://connect.microsoft.com/VisualStudio/feedback/details/790160/httpclient-throws-operationcanceledexception-insead-of-timeoutexception

**Comment by MikhailArkhipov** [comment]
One thing I noticed and perhaps how we can detect this: it throws 'canceled' but IsCancellationRequested is false.

**Comment by AlexanderSher** [comment]
yes we can, I'm afraid that's not enough. In some cases `GetAsync` throws `HttpRequestException` (for example, when you connect from local to remote), and it happens much faster. In other cases, it throws `OperationCanceledException` and it takes 30 seconds to get it.

**Comment by AlexanderSher** [comment]
Ok, I think I've found the method with a bug:
```{csharp}
    private void HandleAsyncException(HttpClientHandler.RequestState state, Exception e)
    {
      if (Logging.On)
        Logging.Exception(Logging.Http, (object) this, "SendAsync", e);
      if (state.cancellationToken.IsCancellationRequested)
        state.tcs.TrySetCanceled();
      else if (e is WebException || e is IOException)
        state.tcs.TrySetException((Exception) new HttpRequestException(SR.net_http_client_execution_error, e));
      else
        state.tcs.TrySetException(e);
      state.requestMessage.AbortRtcRequest();
    }
```

This is from the `HttpClientHandler` (I couldn't find its pdb and source code, so this is what R# has reconstructed). While method accepts proper exception from `HttpWebRequest` it first checks `cancellationToken` and if `IsCancellationRequested == true`, exception is ignored. I don't think there is a way to extract it, so I will wrap all the calls to `HttpClient` so that OCE is converted to `System.Net.WebException` when our token isn't canceled.
