### ISSUE TITLE
If R is disconnected, editor becomes extremely slow

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2446]
B/c intellisense now depends on remote and hits timeouts.

**Comment by AlexanderSher** [comment]
Similar problem with disconnection notification. It takes quite time to check if connection is really broken.

**Comment by MikhailArkhipov** [comment]
I fixed this one by checking for `NullBrokerClient`. Or should we have `IsConnected` on the interface instead? `IsHostRunning` doesnt cut since if it is not running, code continuously trying to start it.

**Comment by AlexanderSher** [comment]
There is a property and an event. The problem is that it takes time to verify if connection is really dead or it is just a failure of a single RHost instance. On my machine, it takes about 20 seconds. Maybe we should allow `/ping` to work without security check?

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/9e05ed87299dfaa57c9a50613c7883781b18055f
