### ISSUE TITLE
User Profile service Fuzz tests

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2451]

**Comment by MikhailArkhipov** [comment]
Since we are not using hardened named pipes, do we still need to fuzz this?

**Comment by karthiknadig** [comment]
Yes, this is needed. The hardened named pipes are in the "Broker as Network Service" PR #2493 .

**Comment by MikhailArkhipov** [comment]
So it depends if we convert to NS in RTM (post preview) or we do it post release.

**Comment by karthiknadig** [comment]
#2581
