### ISSUE TITLE
'Window -> Reset Window Layout' has R windows in it

### ISSUE THREAD

**Issue by ivannp** [Microsoft/RTVS#2452]
After "Reset Window Layout", I still have "R Interactive", and "R Help" in the empty windows showing. Is this expected? I would expect that all R windows are cleaned up.

**Comment by MikhailArkhipov** [comment]
This is expected. Same happens with C# interactive or other windows you've opened. VS resets layout to default of the profile you selected, but it does not forcibly close windows that are opened by the user.
