### ISSUE TITLE
Deployment error for SQL Stored Procedure

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2455]
I'm seeing this error while deploying my stored proc:

![image](https://cloud.githubusercontent.com/assets/8877/19197715/3fc17bb2-8c70-11e6-983e-77d076c126ec.png)

**Comment by MikhailArkhipov** [comment]
Andrie saw this as well. I couldn't replicate on VM, so I want to look at the machine.

**Comment by jflam** [comment]
Here are the files:

R:

# @InputDataSet: input data frame, result of SQL query execution
# @OutputDataSet: data frame to pass back to SQL

# Test code

library(dplyr)
OutputDataSet <- mutate(
    InputDataSet, 
    concatenated_column = paste(
        medallion, 
        hack_license, 
        sep = '_'))

#OutputDataSet <- InputDataSet


SQL Query

-- Place SQL query retrieving data for the R stored procedure here

SELECT TOP 100 medallion, hack_license FROM nyctaxi_sample

SQL template:

CREATE PROCEDURE [StoredProcedure]
AS
BEGIN
EXEC sp_execute_external_script @language = N'R'
    , @script = N'_RCODE_'
    , @input_data_1 = N'_INPUT_QUERY_'
--- Edit this line to handle the output data frame.
    WITH RESULT SETS ((medallion NVARCHAR(max), hack_license NVARCHAR(max)));
END;

**Comment by jflam** [comment]
Updated SSDT from Visual Studio update and now get a different error:

![image](https://cloud.githubusercontent.com/assets/8877/19198603/d944c772-8c74-11e6-8c95-3ac4bbf6c4e6.png)

**Comment by jflam** [comment]
I get this error message when I create a DACPAC and then attempt to publish it to SQL server. The DACPAC was created successfully, but the publish step failed with this error message. Apologies for the terrible visibility of the screenshot, but I can't actually copy the string out of the error list, nor will the error list wrap the text.

![image](https://cloud.githubusercontent.com/assets/8877/19198723/7ab2e274-8c75-11e6-8cc8-c1ac868376c3.png)

**Comment by MikhailArkhipov** [comment]
Moved actual SQL/DAC operations into a separate assembly and dynamically import it via MEF. Removed DAC assemblies from setup. If SSDT is not installed, commands remain available but user will be prompted to install SQL Tools

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/fa91eee5a570f1113474126b752a58435ae341d9 in 0.5
