### ISSUE TITLE
Formatting: space inserted after ?

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2468]
Before:
```r
?x
```
After:
```r
? x
```
Since `?` is an unary operator, it should be treated like `!` and `~`, with no space between it and the operand.

**Comment by int19h** [comment]
Ditto for `??`.

**Comment by MikhailArkhipov** [comment]
What is the repro? Formatting document actually removes the space in `? x`. If will add spaces in `y ? x` though

**Comment by int19h** [comment]
This file:

https://github.com/Microsoft/RTVS/blob/a2fcf6f7a737a573add8a8a0aa344b2312dc0af5/src/Host/Client/Impl/rtvs/R/help.R

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f4755eedde9c2354cf6fdf3ca5e92ccafb40472d
