### ISSUE TITLE
Formatting: comments are not indented same as statements around them

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2470]
Before:
```r
f <- function() {
  x <- 1;
  # foo
  x <- 2
}
```
After:
```r
f <- function() {
    x <- 1;
  # foo
    x <- 2
}
```

Curiously, this doesn't happen if the initial indentation is zero - if it is, then comment is indented same as the surrounding code.

**Comment by MikhailArkhipov** [comment]
Comments were never formatted/indented, comment positioning is a bit of a matter of taste (I don't always agree with the way C# insists on) but we can add this.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f4755eedde9c2354cf6fdf3ca5e92ccafb40472d
