### ISSUE TITLE
GB18030 - RTVS Editor fails to round-trip Chinese characters embedded as comments

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2471]
Steps to repro:
1. Create an empty RTVS project
2. Open the Script.R file
3. Add a comment, and paste these characters into it (send me mail if you want the actual string ... Github chokes on this): 
   ![image](https://cloud.githubusercontent.com/assets/8877/19206873/e7a28c6a-8ca0-11e6-9d84-f9a44f2ba70c.png)
   It should look like this:

![image](https://cloud.githubusercontent.com/assets/8877/19206958/80597b8a-8ca1-11e6-973e-cd6875a5697b.png)
1. Save the Script.R file and close the file in the editor.
2. Re-open the file in the editor and you'll see this:

![image](https://cloud.githubusercontent.com/assets/8877/19206965/955d10be-8ca1-11e6-8019-367fc44cf6ca.png)

Expected to see the original characters that were pasted in.

If you manually force saving using UTF-8 without encoding format (65001) from File ... Save As:

![image](https://cloud.githubusercontent.com/assets/8877/19206990/be7fef5c-8ca1-11e6-9f36-6a9672798006.png)

You will successfully round-trip the characters.

**Comment by huguesv** [comment]
FYI we've had the same bug in PTVS for a long time: https://github.com/Microsoft/PTVS/issues/74

Whoever fixes it first can let the other know ;)

**Comment by MikhailArkhipov** [comment]
There are two odd things here.

a. VS should be popping up warning if saving to disk is descructive.
b. Templates should be in UTF-8 without BOM and that should be se on the text buffer properties.

My guess is that (b) is b/c somewhere somethings sets encoding on the text buffer.

**Comment by MikhailArkhipov** [comment]
So the answer to your question is

C#, HTML and other similar files in VS are saved in UTF-8 with BOM.

![image](https://cloud.githubusercontent.com/assets/12820357/19208411/5abbf8b4-8cae-11e6-8fd7-af6005bee83c.png)

This is a bad idea for R and I guess for Python. However, this does *not* imply GB18030-incompatibility. Since R is a plain text file, there are only 3 options, all of which VS does provide:

1. Save file in UTF-8 with BOM. Round-tripping is guaranteed.
2. Set your codepage for non-Unicode program to GB18030 codepage.
3. Use Save With... and Open With... selecting appropriate encoding.

**Comment by int19h** [comment]
Some languages are okay with a BOM (C# and HTML are both in that boat), while for others the grammar does not allow it. I'm not sure which boat R is, actually. If we end up saving with a BOM, will R interpreter even parse the file correctly?

Also, aside from "Save With...", there's File | Advanced Save Options.

**Comment by int19h** [comment]
Just checked, and R will _not_ source a file with UTF-8 BOM in it.

**Comment by MikhailArkhipov** [comment]
This works for me with Japanese

![image](https://cloud.githubusercontent.com/assets/12820357/20691282/bf395832-b584-11e6-8b86-1dbcc76e53e1.png)

**Comment by MikhailArkhipov** [comment]
I see editor throws `data loss` but it appears that CPS ignores it

```
>	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.Save(string pszFileName, int fRemember) Line 836	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.VisualStudio.Editor.Implementation.dll!Microsoft.VisualStudio.Editor.Implementation.TextDocData.SaveDocData(Microsoft.VisualStudio.Shell.Interop.VSSAVEFLAGS dwSave, out string pbstrMkDocumentNew, out int pfSaveCanceled) Line 344	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.SaveItem.AnonymousMethod__0() Line 1777	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrMutate.AnonymousMethod__0() Line 3778	C#
 	Microsoft.VisualStudio.Threading.dll!Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>> asyncMethod, bool synchronouslyBlocking, Microsoft.VisualStudio.Threading.JoinableTaskCreationOptions creationOptions) Line 661	C#
 	Microsoft.VisualStudio.ProjectSystem.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.ThreadHandlingMultithreaded.ExecuteSynchronously<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>> asyncAction) Line 145	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke.AnonymousMethod__0() Line 3715	C#
 	Microsoft.VisualStudio.ProjectSystem.Utilities.v14.0.dll!Microsoft.VisualStudio.ProjectSystem.Utilities.HResult.Invoke(System.Func<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult> action, System.IServiceProvider vsShellServiceProvider, Microsoft.VisualStudio.ProjectSystem.Designers.IProjectFaultHandlerService projectFaultHandlerService, Microsoft.VisualStudio.ProjectSystem.UnconfiguredProject project) Line 309	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrInvoke(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>> asyncAction, bool registerProjectFaultHandlerService)	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.HrMutate(System.Func<System.Threading.Tasks.Task<Microsoft.VisualStudio.ProjectSystem.Utilities.HResult>> asyncAction, bool includesFileSystemChange, bool registerProjectFaultHandlerService) Line 3769	C#
 	Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll!Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.SaveItem(Microsoft.VisualStudio.Shell.Interop.VSSAVEFLAGS saveFlag, string silentSaveAsName, uint itemid, System.IntPtr docData, out int cancelledParam) Line 1704	C#
```

**Comment by MikhailArkhipov** [comment]
VSTS 296824

**Comment by MikhailArkhipov** [comment]
This is fixed in Dev15 per ~VSIDEProj/_git/VSIDEProj.CPS/pullrequest/166454 in IDE
