### ISSUE TITLE
VS2015 ：R Host process is stopped. Click Reset to start a new one.

### ISSUE THREAD

**Issue by muguangyuze** [Microsoft/RTVS#2474]
Problem:

hello，the R code running in VS2015 experience the issue that showed "R Host process is stopped. Click Reset to start a new one. "

can any one give me some advice and help, thanks very much.
...

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO\R-3.2.5

**Comment by MikhailArkhipov** [comment]
Does the same code run normally in RGui console? If so, can we have the code sample?

**Comment by MikhailArkhipov** [comment]
Closing due to lack of details.

**Comment by mkoohafkan** [comment]
This happens to me as well, usually when I leave the computer running overnight. It has occurred multiple times with different code samples, but in general the issue occurs during large loops (hence why I'm running the code overnight). The R process usually stops after the loop completes, which is interesting. The code runs normally in the standard RGUI console.

**Comment by MikhailArkhipov** [comment]
0.6 is almost out so check it as soon as it is public. I believe this was fixed.

**Comment by muguangyuze** [comment]
I guess this is a question about Memory processing mechanism to big data which original R version will not have .
