### ISSUE TITLE
Formatting: Spaces placed around hyphen used for numeric negation 

### ISSUE THREAD

**Issue by bordecal** [Microsoft/RTVS#2480]
When a hyphen is used for numeric negation in an expression preceded by an opening parenthesis, it is wrapped in spaces as if it were being used for subtraction.  For example, the second line from the following original code

```R
x <- 5
y <- (-x + 2) / 3
```

will be reformatted as
```R
y <- ( - x + 2) / 3
```

This does not occur when the hyphen is not preceded by an opening parenthesis.  e.g.:

```R
y <- -x + 1
```

It does, however, happen even if the parentheses are used for a function call.  e.g.:

```R
y <- sqrt( - x + 1)
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f4755eedde9c2354cf6fdf3ca5e92ccafb40472d
