### ISSUE TITLE
IRSessionCallback concurrent access

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2481]
It is possible that `IRSessionCallback` methods are called when `IRInteractiveWorkflowProvider` is disposed or is going to start disposing (so that `workflow` can be acquired but can't be used). `IRInteractiveWorkflowProvider` can be disposed from any thread, so dispatching `IRSessionCallback` methods calls to the UI thread won't help.

**Comment by MikhailArkhipov** [comment]
#2464

**Comment by AlexanderSher** [comment]
Closing because of #2519, #2520, #2521
