### ISSUE TITLE
Reload .RData shows in local connection case

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2484]
Run RTVS with local connection
Debug | Terminate All
Run again

![image](https://cloud.githubusercontent.com/assets/12820357/19281307/8fe0ffba-8f9e-11e6-96fe-22dc38dd7064.png)

**Comment by AlexanderSher** [comment]
Why is it a bug?

**Comment by MikhailArkhipov** [comment]
At least the message should be appropriate - it says connectivity issues, but that was not the case.

**Comment by AlexanderSher** [comment]
Ok, got it.

**Comment by MikhailArkhipov** [comment]
And in local case it should be an option: 

![image](https://cloud.githubusercontent.com/assets/12820357/19281466/46d7bc04-8f9f-11e6-8ac6-c47e8072e6a9.png)

**Comment by int19h** [comment]
For local, about the only way to trigger this for the actual user (who won't be attaching a debugger to VS itself), is to hard kill VS or broker process (e.g. if they crash), so I think this is still useful.

The message can certainly be amended, but I'm not sure about the wording. Suggestions?

As for making it an option, how about a simple checkbox for now?

**Comment by MikhailArkhipov** [comment]
We don't have to provide option right now, no biggie. If we don't know the connection is local (so we can provide different message) How's about just remove 'due to connectivity issues'?

**Comment by MikhailArkhipov** [comment]
Or add 'due to connectivity issues or terminated Visual Studio process'
