### ISSUE TITLE
Automatically add schema and port when creating connection

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2496]
When adding a new connection in the Workspaces window, the schema is always going to be `https`, and the port is usually going to be the default 5444. We should allow users to type just the hostname in the textbox, and automatically add the schema and the port, probably in focus lost event (so as soon as user tabs away from the textbox or clicks on any button, it's added).

**Comment by int19h** [comment]
It would also be nice to automatically fill the name textbox from host URL if it's empty, using hostname as the name.

**Comment by MikhailArkhipov** [comment]
👍 

I think we should have name and port boxes, port pre-populated perhaps with 5444

**Comment by AlexanderSher** [comment]
I'm not sure this is a good idea. I'm ok with adding https, but I don't think we should add a port - users may have any kind of public URL.

**Comment by int19h** [comment]
The proposed scheme is as follows:

1. If user types what looks like a valid _absolute_ URL, we leave it alone. So if they do `http://foo`, we do *not* add the port, because the `http` schema implies port 80 per RFC.
2. If it's not a valid absolute URL, prepend `https://`, and see if that makes it a valid URL. If it's not a valid URL, leave the original input alone, but highlight it as error (the usual WPF decorator for those things).
3. If, after adding `https://`, it is a valid URL, but doesn't specify the port number, then set port to `5444`.

Some examples - user input on the left, post-validation textbox value on the right:

`https://foo:5444` -> `https://foo:5444` (no change)
`https://foo` -> `https://foo` (no change)
`http://foo` -> `http://foo` (no change)
`foo` -> `https://foo:5444`
`foo:5000` -> `https://foo:5000`
`username:password@foo` -> `https://username:password@foo:5444`

(Note that the latter case means that we shouldn't just be checking the URL for the colon to determine whether the port was specified or not, since colon is used in other cases, and doesn't necessarily indicate port - better to parse it after adding the schema, and check `Uri.IsDefaultPort`.)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ad355a956dcbea857f32db4fbd878884f3e44acf
