### ISSUE TITLE
Plot image in history changes after double-click

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2497]
Plot a few
Open plot history
Select plot by double-click

Observed: plot preview size changes (squishes vertically)

![image](https://cloud.githubusercontent.com/assets/12820357/19366973/15077fc4-914e-11e6-91bc-4698dacf1311.png)

**Comment by huguesv** [comment]
By design.  We always take the latest rendering for the thumbnail*, so its aspect ratio will change if you've changed the aspect ratio of the plot window since the previous rendering.

* The exception is when the latest rendering fails, in which case we don't update the thumbnail.
