### ISSUE TITLE
Certificate doesn't get added when testing connection

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2498]
Adding a new connection to a machine that hasn't been previously connected before, and using "Test connection" before actually adding it, I see this:

![image](https://cloud.githubusercontent.com/assets/1175142/19367224/162a85b2-914f-11e6-969b-e02c0e5e9b5a.png)

This is expected. I proceed with "Install certificate", "Current user", "Automatically select the certificate store". I get a message box saying "Import was successful". I click "OK" to close the dialog above. I get an error message in the Workspaces window:

![image](https://cloud.githubusercontent.com/assets/1175142/19367284/54e73ec6-914f-11e6-8f84-fad03ce0950c.png)

If I click "Test connection" again, I get the same dialog about certificate not being installed.

**Comment by MikhailArkhipov** [comment]
You need to import it to 

a. Local machine
b. Trusted root

**Comment by MikhailArkhipov** [comment]
We need to figure out how to simplify and make automatic

**Comment by int19h** [comment]
Importing to "Local machine" requires elevation - effectively, the user must be admin.

We should look into supporting "Current user" store.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/d438dc8cf54f4b468cdf5687d4de94cd7f754da2
