### ISSUE TITLE
Rmd code chunk incorrectly marked as syntax error

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2503]
If you have `{r eval=FALSE}`, with no comma after the `r`, it gets the squiggly red lines:
![image](https://cloud.githubusercontent.com/assets/11328890/19399273/7c3b9b18-929c-11e6-935a-13efb65283c8.png)

This is [valid syntax](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) though. Using `{r, eval=FALSE}` passes the syntax checker.

**Comment by MikhailArkhipov** [comment]
Side effect of the fact that the entire `{r expression}` is parsed as R (matches highlight). So what parser sees is `curly` - `identifier: r` - `identifier` - `operator =` and this sequence is missing operator between identifiers. R is embedded and does not know it is inside markdown hence the squiggly.

**Comment by MikhailArkhipov** [comment]
Relates to #2377, might as well just fix both

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f981c81aef6dcd32be84d6f372e40e69670feeb1
