### ISSUE TITLE
If certificate validation fails, connection is still displayed as green

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2504]
![image](https://cloud.githubusercontent.com/assets/12820357/19400976/8b49f80a-920d-11e6-9525-18c447f8fd77.png)

**Comment by MikhailArkhipov** [comment]
Also, timeout closes connection before user is able to read the warning and click OK.

**Comment by MikhailArkhipov** [comment]
The problem here is that connection turns green while it is still in progress. Example: 

Without REPL opened, try connecting to remote you've connected before. Light turns green right away. Now open REPL - no prompt. 
Few seconds later SSL certificate prompt comes up.

Looks like 'connected' state is assigned in UI too early.

**Comment by MikhailArkhipov** [comment]
ConnectionStateChanged fires when broker state changes to 'connected' - but actually connection hasn't been fully established yet. So we end up with printing null broker information and updating window title too early as well

![image](https://cloud.githubusercontent.com/assets/12820357/19582147/2433fdf8-96e7-11e6-9ccb-5b481b3f00cb.png)

**Comment by AlexanderSher** [comment]
Can't repro it anymore
