### ISSUE TITLE
File/path completion on remote doesn't work

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2511]
It always work off local. Need to implement file browsing service in host and plumb through callbacks.

**Comment by int19h** [comment]
It shouldn't need a dedicated service and any special callbacks - we can just send evals for `list.files`.

**Comment by MikhailArkhipov** [comment]
True - as long as we don't need fastest possible through C++. Although with async intellisense R might be OK too.

**Comment by MikhailArkhipov** [comment]
Rougly 75ms locally for ~70 files and 20 directories.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/66fcd82041b4ca26a5089dc31f66e91622f5653a
