### ISSUE TITLE
Remove Trace.Fail in release

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2531]
Replace with Debug.Fail ? Users are getting confused, click Abort and VS closes while often it can survive. Log it, but users should not see debug-style dialogs.

```
            } catch (Exception ex) {
                Trace.Fail("Exception in RHost run loop:\n" + ex);
                throw;
            }
```

**Comment by int19h** [comment]
We've already replaced it with `Debug.Fail` in the current code. 

Note though that this is not a place where it's safe to swallow the exception. We already have a bunch more specific `catch` blocks for exceptions that are "safe" there; this one is the catch-all, and if we get to it, process state is quite likely to be corrupt to the point where it's not a good idea to let the user just continue. So rethrow is correct.

**Comment by MikhailArkhipov** [comment]
OK. I was checking 0.5. Yes, rethrow is fine.
