### ISSUE TITLE
Plot history doesn't show devices with no plots

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2539]
Due to using a WPF list view with grouping, when there's no item in a particular group, the group doesn't appear.

This would be useful to have a quick way of navigating to a plot window that is associated with a graphics device, but has no plots yet.

We could always put in a blank entry so that it appears, and user can double-click on that entry to show the plot window.

Or change UI to use different controls.

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
