### ISSUE TITLE
library(help=foreign) fails with Microsoft R Client

### ISSUE THREAD

**Issue by revodavid** [Microsoft/RTVS#2541]
These commands, included in the exmaple "Getting Started with R", fail when using Microsoft R Client.

```
> library(foreign)
> library(help=foreign)
Error in formatDL(nm, txt, indent = max(nchar(nm, "w")) + 3) : 
  incorrect values of 'indent' and 'width'
```

My R Engine option is set to `C:\Program Files\Microsoft\R Client\R_SERVER`. 

Failure only occurs using Microsoft R Client with RTVS. `library(help=foreign)` works when using MRO or CRAN R within RTVS, and when using RGui for Microsoft R Client.

RTVS 0.5. Microsoft R Client 3.2.2, which identifies itself like this in the startup text:
```
Microsoft R Open 3.2.2
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2016 Microsoft Corporation
```

**Comment by Hong-Revo** [comment]
It works with R Server, using the same version of R (3.2.2). So this may be unique to R Client.

**Comment by revodavid** [comment]
Hmm, trying it again using R Client I can't now repro the issue. It may possibly be a conflict with library(checkpoint).
