### ISSUE TITLE
R Interactive occasionally shows System.NullReferenceException

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2546]
When I'm working with Python project, R Interactive occasionally shows System.NullReferenceException.

The error message on the interactive was:

> このフレームのコンテンツを作成しようとして例外が発生しました。この情報は "C:\Users\mic\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml" にも記録されます。

(Japanese text means "Making frame contents of this frame caused exception. This information also recorded in ActivityLog.xml")

> 例外の詳細:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.VisualStudio.Shell.Interop.IVsShell5.LoadPackageWithContext(Guid& packageGuid, Int32 reason, Guid& context)
>   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.GetPackage()
>  at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

(Japanese text means "Details of the exception")

![interactive](https://cloud.githubusercontent.com/assets/3863577/19549971/16a42fc8-96e2-11e6-917d-ee468fec216f.PNG)

I'm sorry but I did not check whether this exception also occur when working with R project.

R Tools for Visual Studio   0.5.21008.0800
Provides project system, R Interactive window, plotting, and more for the R programming language.

**Comment by Marchen** [comment]
VS occasionally shows a message like "Couldn't load 'RPackage' package".

**Comment by MikhailArkhipov** [comment]
May be the same as related to #2612

**Comment by MikhailArkhipov** [comment]
Should not be happening anymore
