### ISSUE TITLE
availability for 3.3.1

### ISSUE THREAD

**Issue by Amit2016-17** [Microsoft/RTVS#2554]
When RTVS 0.5 will be available for r3.3.1

**Comment by MikhailArkhipov** [comment]
Did you mean Microsoft R Open? I think someone at MRO forums may provide the answer: https://social.msdn.microsoft.com/Forums/en-US/home?forum=ropen 

RTVS is not tied to any particular version of R - the only requirement is R 3.1.0 or higher. It does not require MRO.
