### ISSUE TITLE
Occasional ObjectDisposedException on web socket

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2556]
So far I have seen it in tests, but we may need to look if this is a product issue.

![image](https://cloud.githubusercontent.com/assets/12820357/19656752/05f81d64-99d6-11e6-96c2-4e7137ca3549.png)

**Comment by MikhailArkhipov** [comment]
`DisconnectAsync` throws

```
>	Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.RHost.Dispose() Line 60	C#
 	Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.Session.RSession.Dispose() Line 114	C#
 	Microsoft.R.Host.Client.dll!Microsoft.R.Host.Client.Session.RSessionProvider.Dispose() Line 95	C#
 	Microsoft.R.Components.Test.dll!Microsoft.R.Components.Test.Fakes.InteractiveWindow.TestRInteractiveWorkflowProvider.DisposeInstance(Microsoft.R.Host.Client.IRSessionProvider sessionProvider) Line 98	C#
```

**Comment by AlexanderSher** [comment]
Do you have it with the latest bits?

**Comment by MikhailArkhipov** [comment]
It appears to be better now. However - I think the socket can get disposed elsewhere in the network stack. Perhaps we should still protect against it.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0c596e001c0d28b61a1be02008ee7d6deb01d21e
