### ISSUE TITLE
?plot in REPL hangs

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2573]
![image](https://cloud.githubusercontent.com/assets/3840081/19704064/22e5ea10-9abb-11e6-9916-bbb05c198ca2.png)

After showing : starting httpd help server ... done
nothing happened. I clicked Reset repel, nothing happened.

**Comment by MikhailArkhipov** [comment]
fix for the #2500 might have broken it.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f981c81aef6dcd32be84d6f372e40e69670feeb1
