### ISSUE TITLE
Workspaces tool window is missing icon

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2586]
In the screenshot below, workspaces is the 2nd tab, with no icon.

![image](https://cloud.githubusercontent.com/assets/1696845/19783132/92fb7d52-9c45-11e6-8ea3-ada3f7bf650b.png)

**Comment by AlexanderSher** [comment]
Actually, icons for our tool windows are missing

**Comment by huguesv** [comment]
These are missing icons:
R History
R Interactive
R Workspaces
R Package Manager

**Comment by huguesv** [comment]
FYI since R Interactive icon is a custom icon, and we only had PNG, I've requested an official image for it, as well as for Save as PDF and Add R Script (those are the 3 used in the .vsct file).  I've prepared the image.imagemanifest file, etc.

**Comment by MikhailArkhipov** [comment]
We don't have icon field in the `IVisualComponentContainer`

**Comment by MikhailArkhipov** [comment]
Added icons to most, custom R icon can wait until it is ready.
