### ISSUE TITLE
Request professional icons

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2600]
Need real thing for all resolutions for Dev15

**Comment by AlexanderSher** [comment]
We also need icons for Workspaces window

**Comment by jflam** [comment]
Do you have a list of all of the icons handy in a form that I can give to the DEVDIV UX folks?

**Comment by MikhailArkhipov** [comment]
We currently have icons that I made and they do not have versions for all resolutions.

![image](https://cloud.githubusercontent.com/assets/12820357/20075339/a7957cbc-a4e8-11e6-8003-4a3d65ac8d3e.png)

![image](https://cloud.githubusercontent.com/assets/12820357/20075355/b29464ca-a4e8-11e6-904b-e91a0a41b214.png)

Also, something like SProc in C# but for  R

![image](https://cloud.githubusercontent.com/assets/12820357/20075455/0b3c3418-a4e9-11e6-831a-a7c93af30478.png)

**Comment by MikhailArkhipov** [comment]
Current version are in https://github.com/Microsoft/RTVS/tree/master/src/Package/Impl/Templates

**Comment by MikhailArkhipov** [comment]
Requested, VSTS 870220 (https://mseng.visualstudio.com/DefaultCollection/DevDivDesign/_workitems?id=870220)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8aed400ddb1a0045402115119ee9575a84f09254
