### ISSUE TITLE
R_CompletionFiles fails

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2603]
Also `IntellisenseTest.R_CompletionFilesUserFolder`, `IntellisenseTest.R_CompletionFilesAbsolute`
`session.SelectedCompletionSet` is `null`

**Comment by MikhailArkhipov** [comment]
I am actually having problems with #2556

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0c596e001c0d28b61a1be02008ee7d6deb01d21e
