### ISSUE TITLE
Snippets are not respecting trailing spaces

### ISSUE THREAD

**Issue by mungojam** [Microsoft/RTVS#2610]
As an example, type =, then tab to produce the <- snippet and the cursor ends up after the - with no trailing space.

The snippet correctly uses $end$ which should make the whitespace get noticed. 

```
<Code Language="R">
        <![CDATA[ <- $end$]]>
 </Code>
```

**Comment by jflam** [comment]
@MikhailArkhipov - any update on this bug? Thx.

**Comment by MikhailArkhipov** [comment]
It is basically formatting. After snippet insertion VS IDE calls format range so snippet would appear according to the selected formatting options rather than how it specified in the snippet file. Formatter trims trailing spaces by default.  It is technically possible to special case standalone operators and suppress formatting in this particular case.

**Comment by MikhailArkhipov** [comment]
So question is: is this specifically about R operator snippets or is it general request to respect custom formatting with possible trailing spaces in all snippets. The former is doable, the latter is unclear how to handle since reformatting of snippets at insertion is standard VS IDE behavior.

**Comment by mungojam** [comment]
Thanks for explaining the cause of the issue. I've not had the same issue
with C# but perhaps that's just because I haven't needed trailing spaces in
a snippet.

Could there be a way of altering the formatting rules so that it doesn't
get rid of the space after <-  ? It's rare to put a line break right after
that token so it seems to be a reasonable exception for R code
soecifically.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/7ecfc09d1653ce711bcea3e71b30b8972016edda

**Comment by mungojam** [comment]
Thanks, just re-read your comment and realise what you meant. Your fix is a very sensible balance as presumably it will work for magrittr lines too if somebody has a snippet for that like: 

blah %>% 
select

The main motivation was specifically for <- though, so great that it works for that
