### ISSUE TITLE
VS shows error message when typing Tab in comments

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2613]
Typing Tab key after in comments  produce following error message.

>Index and length must refer to a location within the string.
>Parameter name: length

![comment-tab](https://cloud.githubusercontent.com/assets/3863577/19876619/12da91ce-a01b-11e6-9580-cd0a6599c2cd.PNG)

Repro:
1. Open VS.
2. Make new R script.
3. Type #.
4. Hit Tab.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/698b187013402962ac7ff35ccdf9ae4d321a1869

**Comment by Marchen** [comment]
Thanks!

**Comment by Marchen** [comment]
This error message is still shown in my environment (RTVS 0.6 with VS 2015 Update 3).
Please reopen the issue.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bb09d540badb5b43d02b6966880cb1315abf35f2
