### ISSUE TITLE
Incorrect instructions for setting breakpoints

### ISSUE THREAD

**Issue by revodavid** [Microsoft/RTVS#2619]
In http://microsoft.github.io/RTVS-docs/debugging.html, it says:

```
3. Source the file you can do this via R Tools/Session/Source R Script command, or by typing 
CTRL+R, CTRL+S with the input focus set to the editor. (See note [1] below.)
```

The actual keystroke is CTRL-SHIFT-S

**Comment by MikhailArkhipov** [comment]
It is correct with default VS settings but not with data science profile.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS-docs/issues/52
