### ISSUE TITLE
Dev15: interactive tests are broken

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2621]
Due to changes in test runner working directory code cannot find editor assemblies for the test MEF catalog

**Comment by AlexanderSher** [comment]
Do we have code that relies on test runner working directory? I thought we specify assembly paths explicitly.

**Comment by MikhailArkhipov** [comment]
Well, it was never recommended to figure out VS installation path so we used to load via `CommonExtensions\Editor\...` relying on the fact that runner directory is in `Common7\IDE`. This no longer works. To add insult to injury, there is no registry key for VS15 so we'd have to resort to Win32.GetModuleFileName(NULL).

**Comment by MikhailArkhipov** [comment]
Need proper nuget modules for IDE references
