### ISSUE TITLE
Double-click on machine name in 'edit connection' launches test connection

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2633]
Create connection
Open it for editing
Double-click on machine name (say, you want to paste over selection)
Observed: Test connection starts
Expected: select machine name in the edit box

**Comment by AlexanderSher** [comment]
Looks like it just closes the edit area

**Comment by karthiknadig** [comment]
It seems to trigger the double click event since, the event is set on the list view item.
