### ISSUE TITLE
Saved remote connection are not actually saved

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2636]
Create remote connection
Shut down VS
[I uninstalled R here but it prob doesnt matter]
Open VS

- No remote connections in the list

**Comment by AlexanderSher** [comment]
Happens because settings get restored after `ConnectionManager` is instantiated

**Comment by MikhailArkhipov** [comment]
This will be fixed by my upcoming PR for #2589

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0e32d5ffd6bfb6ac69a669b8238846cb564f77e3

**Comment by MikhailArkhipov** [comment]
Actually still broken

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1ee7574d76997eff0abad7bde52f4b2f3d1c6605
