### ISSUE TITLE
IInteractiveWindow.WriteErrorLine can throw NRE when VS is closing

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2637]
Not sure what we can do about it other than catching exception.

**Comment by MikhailArkhipov** [comment]
Just catch it for now

**Comment by MikhailArkhipov** [comment]
Now that I am getting https://github.com/dotnet/interactive-window/pull/23 through, do you want me to fix this in the IW?

**Comment by AlexanderSher** [comment]
Yes, that would be great.
Basically, we need to check `Dispatcher.HasShutdownStarted` inside `InteractiveWindow.UIThread` methods

**Comment by MikhailArkhipov** [comment]
Basically just do nothing if it is shutting down?

**Comment by AlexanderSher** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
I'd talk to @tmat

**Comment by MikhailArkhipov** [comment]
https://github.com/dotnet/interactive-window/issues/32
