### ISSUE TITLE
SQL Server Developer Tools (SSDT) needs new error message for Dev15

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2640]
We need to make sure that we change the message that is displayed when we detect that SSDT is not installed so that we have different messages for VS2015 and Dev15:

VS2015: You need to install SQL Server Developer Tools.
Dev15: You need to install the Data Storage and Processing workload.

**Comment by MikhailArkhipov** [comment]
They already look like

_This operation requires SQL Data Tools package. Please add SQL Data Tools to the Visual Studio 2015 setup or install SSDT from https://msdn.microsoft.com/en-us/mt186501.aspx.
    
You can modify Visual Studio installation in Control Panel -> Uninstall Program -> Right click on Visual Studio 2015 and select Change._

and

_This operation requires SQL Data Tools package. Please add Data Storage and Processing workload to your Visual Studio setup._

respectively
