### ISSUE TITLE
Indentation messed up for incomplete expressions

### ISSUE THREAD

**Issue by revodavid** [Microsoft/RTVS#2641]
(See also #2577)

In an R script window, type:

```
x <- 1 +
```

and press ENTER. The cursor appears at the beginning of the next line. Indentation should be inserted. Even if you manually add indentation, RTVS insists on REMOVING indentation and eturning the cursor to the beginning of the next line.  Type ENTER `3` at the end of:

```
X <- 1 +
  2
```

and you get

```
x <- 1 +
2 +
3
```

RStudio does this correctly: typing `x <- 1 +` ENTER `2` leaves the follwing in the editor:

```
X <- 1 +
  2
```

There are many complex expressions in R that are NOT function blocks that require indentation to be readable, and RTVS messes up the indentation. Some examples:

magrittr pipes
```
Teams %>%
 filter(teamID %in% c("CHN", "CLE") & yearID > 1900) %>%
 mutate(Team = fct_drop(fct_recode(teamID, Cubs = "CHN", Indians = "CLE"))) %>%
 mutate(RunsPerGame = R / G) %>%
 mutate(HitsPerGame = HA / G) -> CubsInd.team
```

ggplot layers
```
p <- ggplot(data = CubsInd.team, aes(yearID,RunsPerGame)) +
    geom_point(aes(color = Team)) +
    geom_smooth(aes(color = Team), method = "loess") +
    xlab("Year") +
    ylab("Runs per game") +
    ggtitle("Runs per Game")
```

**Comment by MikhailArkhipov** [comment]
This basically amounts to 

a). Providing proper smart indent in incomplete expressions.
b). Respecting user indentation inside multiline expressions.

Implemented (a). (b) actually exists but it looks like there is a but that causes #2469 and perhaps some other similar cases.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5e1a474e3a2e53241a2add081f0508da16b29ec1

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/698b187013402962ac7ff35ccdf9ae4d321a1869
