### ISSUE TITLE
Ask about saving RData while switching between sessions 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2643]
Currently we Auto-save only in cases where VS crashed/ Connection is lost/etc. But we don't save the data for the user while switching connections by-design. However, we should provide an option to save the data by asking the user if they want to save the data. This dialog should also be controllable with (Yes/No/Ask) setting.

It is very confusing to have RData saved in some cases (automatically) and for other cases user is expected to do this manually. This kind of a Must-do operation while switching between connections, hence a common enough step that we need to make it easy for the user to do so.

**Comment by MikhailArkhipov** [comment]
Looks like it is expensive?

**Comment by karthiknadig** [comment]
Moving this to next sprint.

**Comment by MikhailArkhipov** [comment]
In favor of #2811
