### ISSUE TITLE
Package manager RHost session should use the name PackageManager

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2644]
Currently it uses "IsolatedRHost" + session.ID

**Comment by karthiknadig** [comment]
This makes it easier to find logs for package manager session

**Comment by AlexanderSher** [comment]
Original idea behind this was to avoid handling RSession explicitly for a case when it is not needed. Do we have any issues because of randomly-generated names?

**Comment by MikhailArkhipov** [comment]
In case admin tries to track in the process list what is what, it is handy to have descriptive name. It still can be random but can start with "RTVS_Package_Manager" or something.
