### ISSUE TITLE
VS stuck while connecting to remote

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2645]
Karthik says all my sessions are live, but VS is with the connecting popup.

Dump on pytools R bugs share folder 2645. Build is 2016-11-03.1.

**Comment by karthiknadig** [comment]
I was experimenting with randomly killing Rhost. In one particular case there were 3 Rhost processes (REPL/Intellisense/IsolatedRHost##), I killed the REPL. But that led to a message to reset R (as expected). However, it left behind the IsolatedRHost session and the reset could not establish a new connection till IsolatedRHost was killed.

**Comment by huguesv** [comment]
Also note I had package manager window open during that time.  After Karthik killed my REPL, I tried several Reset REPL which didn't work.  I then switched to local, and got stuck when I tried to switch back to Karthik's machine.

**Comment by karthiknadig** [comment]
Also, during reset on the server side, I see all the RHost sessions (for Hugues). But he was not able to connect .
