### ISSUE TITLE
Add information on port to the connection error message

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2667]
Or default to 5444. Users may be confused when they just enter `https://machine` since we default to 443.

**Comment by int19h** [comment]
If they explicitly type "https://", the schema implies the port number to be 443 if it's not specified - if we want to change that, we should change the schema.

Alternatively, we can prohibit omitting the port number - i.e. if they type "https://machine", we autocorrect it to include the port, just like we handle schemaless names already. That way it's never implicit. And autocorrection doesn't have to follow the rules for https schema, it can insert whatever port number we deem appropriate.

**Comment by AlexanderSher** [comment]
We already autocorrect "https://machine" to "https://machine:443":

```{csharp}
[InlineData("https://host", "https://host:443")]
public void CompletePath(string original, string expected)
```

**Comment by AlexanderSher** [comment]
As for the bug, I can't find an error message that contains connection path. What are exact repro steps?

**Comment by MikhailArkhipov** [comment]
We already auto-correct
