### ISSUE TITLE
Reset REPL takes very long time

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2668]
~20 seconds. Are we performing full reconnect?

**Comment by AlexanderSher** [comment]
We restart R process on the broker side.

**Comment by MikhailArkhipov** [comment]
It is 2 seconds on local so times goes elsewhere

**Comment by karthiknadig** [comment]
I will make the change recommended by Pavel below. There might be additional changes needed.
@int19h:

> Now, one bug that I see here is that it assumes that once QuitAsync completes, hostRunTask is also immediately complete (i.e. that host process exiting will immediately propagate to VS and terminate the main host loop, which is what hostRunTask is). That’s incorrect, and is likely contribute to us moving onto TerminateSessionAsync in many cases where we don’t actually need to do it. The fix would be to issue QuitAsync, but not wait on it – wait only on the hostRunTask, with a timeout. If q() is handled within that timeout, the wait will return early, and we bail out early. If not, we move onto termination.

**Comment by karthiknadig** [comment]
Another place to improve is to avoid calling testconnection while doing reset. We need a way to let the disconnect handler know that the disconnect was intentional.

**Comment by AlexanderSher** [comment]
I have a fix for that

**Comment by karthiknadig** [comment]
Closing this task. @AlexanderSher 's fix will address this. Specific tasks should be opened as we discover performance problem.
