### ISSUE TITLE
Optimize connection testing when one of the sessions is disconnected

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2672]
`RSessionProvider` shouldn't call `TestConnectionAsync` if there is at least one Session with connected status

**Comment by AlexanderSher** [comment]
Depends on #2674

**Comment by MikhailArkhipov** [comment]
Probably can be merged with #2722 ?

**Comment by AlexanderSher** [comment]
Yes

**Comment by AlexanderSher** [comment]
Close in favor of #2722
