### ISSUE TITLE
WebSocket doesn't notify RSession that internet connection is lost.

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2674]
- Connect to remote
- Switch off internet connection on the machine

**Comment by int19h** [comment]
Were you running a debug build, by chance? We set the heartbeat timeout extremely high in debug builds, so that it doesn't get in the way of attaching the debugger to them:
```cs
#if DEBUG
            // In debug mode, increase the timeout significantly, so that when the host is paused in debugger,
            // the client won't immediately timeout and disconnect.
            TimeSpan.FromMinutes(10);
#else
            TimeSpan.FromSeconds(5);
#endif
```
In release builds, I see the connection reported as dropped in REPL after the cable is disconnected after ~10s.
