### ISSUE TITLE
"Save as" filename change not updating tab

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/RTVS#2681]
When I change the name of a file by saving it with "Save as", the name in the tab does not update. I attached a screenshot where you can see both the UI and the directory I am saving into. Note that the file it saved is the one I specified "Script1.R", but that the tab is still showing the original name "Script.1". This is quite confusing.

![image](https://cloud.githubusercontent.com/assets/7562887/20172534/c28e8dfc-a735-11e6-86f8-5dc26de516a9.png)

**Comment by MikeWise2718** [comment]
Here is some version info:
![image](https://cloud.githubusercontent.com/assets/7562887/20172691/680f309c-a736-11e6-9b9a-9838c7ba6833.png)

**Comment by MikhailArkhipov** [comment]
Same as #2070

**Comment by MikhailArkhipov** [comment]
Closing as duplicate. Primary assigned to @AlexanderSher
