### ISSUE TITLE
Use TelemetryPiiProperty

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2696]
We're currently hashing telemetry value ourselves. We should set each event property to TelemetryPiiProperty instance instead of a hashed string. VS takes care of hashing TelemetryPiiProperty, and this will make sure that all data is consistently processed across our products (PTVS already uses it).

**Comment by MikhailArkhipov** [comment]
We need predictable values. I.e. we need to know that some hash means 'utils'.

**Comment by huguesv** [comment]
TelemetryPiiProperty is predictable.

It's a built-in way of reporting PII values, and can make it possible for the server/dashboard to have tools that let you query the data more easily.  Don't know if they actually have that or not, but it is possible.

If you pre-hash it and send it like any regular value, server/dashboard doesn't know it's private info.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/9a664aa23f112177dc3747f5653a650dfcbb6aba
