### ISSUE TITLE
Variable Explorer and Workspaces tool windows need 'R' prefix

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2697]

**Comment by MikhailArkhipov** [comment]
No sure about that. Variable Explorer will be used in PTVS at some point. As may be Workspaces when we unify access to runtimes and repls.

**Comment by huguesv** [comment]
If we ever unify, and the tool windows are shared across products, we can remove the R prefix at that point. 

I very much doubt that we'll reuse the same variable explorer tool window to the point where the tool window hosts either Python or R.

A single instance variable explorer (like for example Test Explorer) doesn't work well because you can have more than one REPL open (Python and R).  What would variable explorer contain?  The R or Python variables?  That would also require us sharing common binaries between the 2 products, which I think is unlikely, just look at the trouble we have with sharing the REPL with Roslyn.

And if there's multiple instances of Variable Explorer, wouldn't you want to know which one is for Python and which one for R? If the caption has "R" or "Python" prefix, like the current REPL does, it's easy to find the right one.

Adding @zooba to comment.

**Comment by int19h** [comment]
I'm actually hoping that we would share the same window (as a multi-instance window). There's nothing particularly different between variables in Python vs R that should require the UI to be so different as to warrant separate implementations.

However, the existing implementation is very tightly coupled to R concepts, all the way to view-model and UI layer; and I don't expect that to change without very significant rewrites in that code (and then we'll need more rewrites to just generally clean it up). We'll need to develop the model interfaces that are sufficiently extensible to accommodate both R and Python etc.

So when that happens, all that new code should drop the R namespace. But until then, I don't see much point.

**Comment by zooba** [comment]
I'm also hoping we have one common extension (i.e. VSIX, etc.), or else we're going to have a terrible time trying to make the keyboard shortcuts the same.

At least for the variable explorer I put together and validated a design that would allow any provider to plug in. That design wasn't used for the RTVS one, so there is definitely work required to generalize it. But it's definitely worth us having a single implementation to interface with, especially as more languages come on board (but this time we will own it - there's nothing to gain by handing it off to another team).

**Comment by MikhailArkhipov** [comment]
And I don't want to go into 'Microsoft Windows Internet Explorer' ;-) naming scheme.
