### ISSUE TITLE
Pressing Insert key in source editor changes display in REPL

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2700]
If I press Insert in an editor pane (to toggle insert/overwrite mode), the REPL window changes:

- A grey bar appears on the side
- The line-change indicator appears whenever I submit code

Before pressing Insert:

![image](https://cloud.githubusercontent.com/assets/11328890/20319697/249c0782-ab95-11e6-9792-973f97caa18f.png)

After pressing Insert: 
![image](https://cloud.githubusercontent.com/assets/11328890/20319746/53d678de-ab95-11e6-9289-93c57f5a2ed7.png)

**Comment by MikhailArkhipov** [comment]
Same as C#. REPL window is an editor and editor modes are global, ie. going Insert -> Override changes all editor windows. There is little we can do about this, at least now.

![image](https://cloud.githubusercontent.com/assets/12820357/20430288/54bb4eb4-ad48-11e6-9e1b-91b239f01f16.png)

**Comment by Hong-Revo** [comment]
That's lol-worthy. I guess you can close this, it's not really RTVS-related.
