### ISSUE TITLE
about cat() function in RTVS

### ISSUE THREAD

**Issue by qtaa246** [Microsoft/RTVS#2704]
...
I have a problem when I use cat function which is cat("\014") or cat("\r") in R Interactive.
that function works in Rstudio but, it doesn't in RTVS. I think there is some issue.
 

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.1

**Comment by int19h** [comment]
What's your version of RTVS?

If you're on a version earlier than 0.5, then this is most likely #1130.

**Comment by MikhailArkhipov** [comment]
Might be #2571

**Comment by MikhailArkhipov** [comment]
Several fixes were made for upcoming 0.6 in https://github.com/Microsoft/RTVS/commit/e083bf16d48cbca63550deeb70ac06407475089d. We'd be happy to verify specific scenario if you can provide detailed steps. Thanks.

**Comment by MikhailArkhipov** [comment]
Closing since 0.6 is coming out soon. Reactivate if you find that in 0.6 this still doesn't work properly. Thanks.
