### ISSUE TITLE
Publish With Options - to Project not working

### ISSUE THREAD

**Issue by athafoud** [Microsoft/RTVS#2707]
Steps to reproduce

1. Create an empty Database project
2. Create an R Project
3. Add a new SQL Stored Procedure Item 
4. Write some R code
5. From R Tools Menu -> Data -> Publish With Options
6. Select Project in Publish to and the Database you previously created in Target
7. In R code Replacement select "In stored procedure @script parameter"
8. Hit Publish

The "R" folder is created in the selected Database project, but it is empty

If in step 7, instead of "In stored procedure @script parameter", we select "In a separate table", the created "RCode.PostDeployment" is invalid. The content of "RCode.PostDeployment" are
`INSERT INTO RCodeTable`
the rest of the script is missing. The "CreateRCodeTable" is created as expected.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e083bf16d48cbca63550deeb70ac06407475089d
