### ISSUE TITLE
Connection manager (workspaces) doesn't respect VS theme

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2708]
![image](https://cloud.githubusercontent.com/assets/1696845/20402188/8fd907e0-acb0-11e6-9802-0a2d70dcbaa2.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e083bf16d48cbca63550deeb70ac06407475089d

**Comment by MikhailArkhipov** [comment]
Now light theme is not quite good.

![image](https://cloud.githubusercontent.com/assets/12820357/20542474/96d1753c-b0b6-11e6-9b9a-6ae52dd64eaf.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/0c7df6d1552c3a36e431fad30fc338dd80acc2b9

**Comment by huguesv** [comment]
Still bad in dark theme:
![image](https://cloud.githubusercontent.com/assets/1696845/20690727/1a9188c0-b581-11e6-87c1-cce66c1fa78b.png)

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/20690772/6724e470-b581-11e6-8a76-3a73139ffe22.png)

**Comment by MikhailArkhipov** [comment]
Looks like `Add` template is missing theme

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e223045a9636ce7a070e28485d5ef629305c6b90
