### ISSUE TITLE
Variable Explorer Window not working 

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2718]
Discovered this while trying to get it working on remote, but verified that it doesn't work locally either.

Repro:

1. Open Interactive Window
2. Type z = 42
3. Open Variable Explorer (CTRL+8) - nothing shows.

Other implications: View() command doesn't work either which is normally a workaround for a busted VE.

Screenshot:

![image](https://cloud.githubusercontent.com/assets/8877/20443986/1696c226-ad84-11e6-962e-b5d2d9e8061e.png)

**Comment by karthiknadig** [comment]
Tried this with the latest master, I am able to see stuff in Variable Explorer
and View() works for me, both from VE and REPL

**Comment by int19h** [comment]
Make sure that you have the right frame selected in the VE dropdown (and note that it doesn't automatically select the topmost frame).

**Comment by MikhailArkhipov** [comment]
Probably same as #2729

**Comment by MikhailArkhipov** [comment]
Closing, please reopen if there is a repro.
