### ISSUE TITLE
Workspaces window is not shown by default in Data Science profile

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2726]
This leads to a rather confusing initial experience, because the REPL is there, but it tells you to connect to something in Workspaces - and there's no Workspaces. You have to know it's under R Tools | Windows.

**Comment by MikhailArkhipov** [comment]
#2769 may alleviate this

**Comment by MikhailArkhipov** [comment]
#2769 and #2826 will fix this

**Comment by int19h** [comment]
Since we no longer show REPL by default, we need to revisit this. The easiest fix is to make Workspaces window visible by default in the Data Science profile.
