### ISSUE TITLE
Too much code leaking into context menu?

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/RTVS#2730]
This context menu looks pretty strange. Hong Ooi pointed out it might be by design and is simply too much code being copyied in there - maybe it should be limited:

![contextmenu](https://cloud.githubusercontent.com/assets/7562887/20525544/3e6a5814-b0c0-11e6-8d13-8098bc0967ad.png)

**Comment by MikhailArkhipov** [comment]
Yes, you have large selection and it goes into the menu. This is fixed post 0.5 limiting amount of data.
