### ISSUE TITLE
Create infrastructure for #2733

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2734]
- References between method fixtures
- `ConnectionInfoFixture` that starts "remote" broker locally if no URL is provided
- bat or ps file to run tests from command line

**Comment by MikhailArkhipov** [comment]
So is it going in this week or is it going to be Sprint 9?

**Comment by AlexanderSher** [comment]
Most of the work is done, so let's leave it in this sprint. I can update estimate to reflect the progress.

**Comment by MikhailArkhipov** [comment]
It's OK. Updating estimate for progress then screws up velocity calculations :-(

**Comment by MikhailArkhipov** [comment]
Do we still need this in S9? I'd rather avoid major code restructuring at this point in cycle.

**Comment by AlexanderSher** [comment]
Those are mostly test code changes (product changes are in the pull request #2738 ).

**Comment by MikhailArkhipov** [comment]
Move to the future? Doesn't look like it is going to fit into 1.0

**Comment by AlexanderSher** [comment]
I've actually checked in this one yesterday.
The other one though can be moved to the next sprint.
