### ISSUE TITLE
Icons in connection manager don't have proper background

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2737]
Background color appears to be white. Compare Delete icon in dark theme in the editor and in the CM:

![image](https://cloud.githubusercontent.com/assets/12820357/20542566/f72c0bcc-b0b6-11e6-89e6-6415d4599845.png)

**Comment by AlexanderSher** [comment]
![before vs after](https://cloud.githubusercontent.com/assets/8933858/20545415/bcec861c-b0d4-11e6-8b9b-1a0fb516e147.png)

**Comment by MikhailArkhipov** [comment]
BTW it also should be using CrispImage with KnownMoniker.Cancel
