### ISSUE TITLE
401 (Unauthorized) connecting to remote

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2739]
I was able to connect, then went local then tried to connect to remote and got 401. No password dialog was presented. Note that my password DID change since last time I worked with the machine.

![image](https://cloud.githubusercontent.com/assets/12820357/20543018/1b62f9ae-b0b9-11e6-94bb-1816417a528a.png)

**Comment by karthiknadig** [comment]
I had created a bug on this (#2688), I was not able to repro this last time. There are cases where server returns 404 as well.

**Comment by MikhailArkhipov** [comment]
This is probably #2754
