### ISSUE TITLE
Switching sessions should only be switching primary (REPL)

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2749]
Intellisense session will be re-created as needed. Package manager should auto-close (simpler) when targets switch or should auto-update itself.

**Comment by AlexanderSher** [comment]
That brings us in a very unpleasant state when different sessions are connected to different brokers. We already had a bug prone because of that before.

**Comment by MikhailArkhipov** [comment]
Non-REPL sessions should remain but host doesn't need to start. Editor doesn't need the host, it properly starts as needed, there is no reason to start the host when switching. I bet PM should be able to do the same. Besides, PM state should be reflecting new R so currently displayed list of packages would be out of date anyway.

**Comment by AlexanderSher** [comment]
Ah, got it. So all sessions are switched, but other RHost's are just stopped and switch is considered completed when REPL session is restarted. Others will wait until lock is released and will restart after that

**Comment by MikhailArkhipov** [comment]
Yes. In fact, others may restart when asked explicitly. Editor checks if host is running and start it if is not up.
