### ISSUE TITLE
Occasional deadlock in ValidateX509CertificateAsync

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2753]
`ValidateCertificateHttpHandler` wants to show the dialog, but `SwitchToMainThreadAsync` never completes. 

I think this might happen if first thread enters the lock and then second call to ValidateCertificateHttpHandler comes on the main thread which gets blocked on the lock and `SwitchToMainThreadAsync` deadlocks.

**Comment by MikhailArkhipov** [comment]
May be mitigated by #2749

**Comment by AlexanderSher** [comment]
Do you have a stack trace with deadlock?

**Comment by MikhailArkhipov** [comment]
I've seen it twice so far. Trying to repro.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ef304d2a88ec47c2dc2ddd5b383415832e75c7b5
