### ISSUE TITLE
Changing file content type causes NRE in RSuggestedActionSource.HasSuggestedActionsAsync

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2757]
- Create new R project 
- Rename `script.r` to file with no extension
- Rename to R file again

Changing file extension causes change of content type and disposes `RSuggestedActionSource`, but `Dispose` doesn't remove `RSuggestedActionSource` from `ServiceProvider`. As a result, instance is reused when file is renamed again.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e223045a9636ce7a070e28485d5ef629305c6b90
