### ISSUE TITLE
Shiny app is missing in current RTVS.When can we expect Shiny app library. How can we plot  the graph dynamically

### ISSUE THREAD

**Issue by chandu406** [Microsoft/RTVS#2758]
Shiny app is missing in current RTVS.When can we expect Shiny app library. How can we plot  the graph dynamically

**Comment by MikhailArkhipov** [comment]
Can you please elaborate what is missing? Shiny is not part of RTVS, did you mean 'run shiny app' button disappeared?

**Comment by chandu406** [comment]
I can see the shiny app button but i got the error message saying that
shiny library is missing. My requirement is to plot dynamic data to be
plotted
This can be done through shiny app .currently is there any way to plot
dynamically and easy to modify the graph in RTVS. Please help me by
suggesting some solution for my issue.

Thanks,
Jaya Chandra

**Comment by MikhailArkhipov** [comment]
You need to install the package then. RTVS does not preinstall all possible packages. If you had different version of R and installed new one you may have to install shiny again since R packages are specific to the R engine version. Try

```
install.packages("shiny")
```

**Comment by chandu406** [comment]
Can i use the same shiny package in RTVS . I installed 5.01 version
RTVS.how to install shiny package in rtvs environment

**Comment by MikhailArkhipov** [comment]
RTVS is not specific to R version. You can use any R you like as long as it is higher than 3.2.*. You can install packages either via Packages window or directly from interactive window (see my comment above). All of

[Shiny tutorial](http://shiny.rstudio.com/tutorial/)

applies to RTVS

**Comment by chandu406** [comment]
Thanks for the information .
