### ISSUE TITLE
Log verbosity setting is ignored

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2765]
When starting the broker, `--logging:logHostOutput` and `--logging:logPackets` switches correspond to `IActionLog.LogVerbosity`. However, when the session is created at VS startup, that property is set to `LogVerbosity.None`, and so no logging takes place. regardless of what is specified in R Tools | Options | Log events.

**Comment by int19h** [comment]
Ultimately, this setting is supposed to come from `LoggingPermissions.CurrentVerbosity` according to the code. But running it under the debugger, the setter for this property is never actually called during startup. @MikhailArkhipov, could this be related to the recent refactoring of settings handling?

**Comment by MikhailArkhipov** [comment]
This should be fixed in master. Tools | Options had property that didn't match property on the settings interface (LogLevel rather than LogVerbosity). Since settings persistence uses reflection this setting was never saved or loaded.
