### ISSUE TITLE
REPL doesn't accept alist with blank ... element

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#2768]
This works:

    a <- alist(x=, y=1, z=)

This also works:

    a <- alist(x=, y=1, ...=2)

But this doesn't work (REPL keeps prompting for more input):

    a <- alist(x=, y=1, ...=)

All 3 statements are accepted by rgui.exe. Prompted by [StackOverflow question here](https://stackoverflow.com/questions/40866951/modify-s3-generics-with-dots-using-formals).

**Comment by MikhailArkhipov** [comment]
This is fixed as #2248
