### ISSUE TITLE
remote is green, but repl window say not connected

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2772]
this happened during a bunch of remote plotting

![image](https://cloud.githubusercontent.com/assets/742484/20729804/7aa80f88-b638-11e6-968f-f82619fee232.png)

**Comment by AlexanderSher** [comment]
This is expected. Connection is alive, only one of the sessions (REPL) is stopped.
Btw, have you tried to do what it tells you?

**Comment by Hong-Revo** [comment]
Completely unrelated, but that green colour is pretty lurid. Maybe tone the saturation down a little?

**Comment by MikhailArkhipov** [comment]
Give us you favorite hex RGB :-)

**Comment by MikhailArkhipov** [comment]
Correct, green == connected. We have #2398 to add yellow as 'connected but stopped' but it is fair amount of work (not just an hour).

**Comment by smortaz** [comment]
ok, got it.  to me green == "all is ok!".   perhaps yellow?  but not a huge deal since the msg is clear.

**Comment by MikhailArkhipov** [comment]
OK, upvote #2398 then. Closing this one.

**Comment by int19h** [comment]
#228B22 is "forest green", should be more calm looking.

**Comment by MikhailArkhipov** [comment]
Kinda dark 
![image](https://cloud.githubusercontent.com/assets/12820357/20779718/13a55126-b72b-11e6-9349-e36596b82636.png)

**Comment by AlexanderSher** [comment]
Good on purple, but too dark on white.
Btw, didn't we order professional icons?

**Comment by int19h** [comment]
#4CBB17 ("Kelly green") is similar in hue, but brighter.

**Comment by MikhailArkhipov** [comment]
OK, this one looks good
