### ISSUE TITLE
pkg mgr says disconnected

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2773]
1.  connected to remote, works fine.  tried installing pkg, got:

![image](https://cloud.githubusercontent.com/assets/742484/20730212/0928907e-b63a-11e6-97f0-4a8932642c9b.png)

2. the msg should be in RED and BOLD if in fact we are connected to remote but pkg mgr is connected to local or unconnected.  perhaps not allow pkg mgmt.

3. i dismissed the msg, switched to local, got the error again using a local interp:

![image](https://cloud.githubusercontent.com/assets/742484/20730302/6fd78136-b63a-11e6-8af4-1ccc28cd942d.png)

UPDATE: 

when switching back & forth between local Rs, the msg appears and disappears.  it should probably instead:

"Currently not connected to an R interpreter" 

(because failed implies something else and RHost isnt a known entity for users)

**Comment by MikhailArkhipov** [comment]
I also think PM should auto-close when changing connections. List of packages is per engine so PM should either auto-refresh or just close.

**Comment by smortaz** [comment]
yes, it was rather unclear what it was connected to.

and since we dont show anything on the repl path field, i have no idea
where things are getting installed.  it's too black boxy for me :(.

**Comment by AlexanderSher** [comment]
PM is updating itself already, there is another bug in the session provider that causes such behavior
