### ISSUE TITLE
intellisense session never gets removed

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2774]
Looks like RTVS does not issue a 'stop' for the intellisense session specifically.

**Comment by AlexanderSher** [comment]
There are couple of issues that I've found. Will have a fix soon.

**Comment by karthiknadig** [comment]
I see that it gets removed only after VS is closed.

**Comment by MikhailArkhipov** [comment]
When switching connections REPL session should be re-established while intellisense can just close. For the package manager, your call, see #2773

**Comment by AlexanderSher** [comment]
Are you talking about client or broker session?

**Comment by MikhailArkhipov** [comment]
I think this is about R.Host.exe for the intellisense

**Comment by karthiknadig** [comment]
@MikhailArkhipov is right, this is about the R.Host.exe (specifically intellisense process) gets left behind (on the remote machine) when we switch from remote to local.

**Comment by MikhailArkhipov** [comment]
See also #2770

**Comment by int19h** [comment]
The suspicion however is that this is due to something that is done (or, more likely, not done) on VS side.

**Comment by AlexanderSher** [comment]
@ karthiknadig we have made several fixes during last 3 three days that may affect this bug.
Can you please check if it still there?

**Comment by karthiknadig** [comment]
As of yesterday it was still there. I will test with the latest build, and let you know.

**Comment by karthiknadig** [comment]
As of latest build (from master) this issue does NOT repro.
