### ISSUE TITLE
Replace Package Manager errors with user-friendly state

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2779]
Currently, package manager just outputs underlying exception messages and cleans them up if they aren't relevant. This isn't very helpful and may confuse users.
Proposition:
- Add several expected states (broker connected, broker switching, broker disconnected) and change the view of the PM accordingly (i.e., don't show any errors when broker is disconnected, probably disable buttons)
- Display errors only if broker is connected
- When broker switches, clear all previous errors, cause they aren't relevant anymore.

**Comment by MikhailArkhipov** [comment]
No necessary if PM closes when connection goes away

**Comment by smortaz** [comment]
My ideal is that my window layout does not change when I switch
interpreters. It should perhaps go blank for a second or two and then
repopulate itself with the information from the remote interpreter/package
manager. Rehydrating all my windows on every interpreter switch will be
somewhat annoying

**Comment by MikhailArkhipov** [comment]
Repopulation is expensive on remote (will hog machine cycles and network bandwidth) and we'd have to be dealing with disconnects and what happens if user switches to another session in the middle. Switching interpreter is like switching projects.
