### ISSUE TITLE
Simplifying the connection switching experience

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2790]
There are three things that we need to do to simplify the connection switching experience:

1. Remote the test connection button from the Workspaces window
1. Extend the duration of the modal dialog box during connection establishment to not return until all secondary sessions (e.g., IntelliSense) are established
1. Remove the transactional nature of switching connections. We first terminate the existing session (with prompt to user to save state) before establishing a new connection. Yes, this introduces a new state "no connection established" into the process in the case where a new connection cannot be established. This applies to both local-local, local-remote and remote-local switches.

This issue references #2643 as well as #2736 which will be closed when this issue is complete.

**Comment by AlexanderSher** [comment]
#2736 is closed

**Comment by AlexanderSher** [comment]
> Remote the test connection button from the Workspaces window

For the last 2 month, there are only 3 recorded issues with test connection: #2747, #2633, and #2742 (not really a test connection issue - it is a bug on UI that was reproduced on many buttons). None of those looks critical. So can you describe what's the problem with the button?

**Comment by MikhailArkhipov** [comment]
General reduction of ability to interact with the modeless UI. We'd rather not chase hard to repro reports from users. It is generally better not to distribute feature rather than remove it after it is already became public.

**Comment by AlexanderSher** [comment]
Ok, should we cut the whole code path or just hide it from UI?

**Comment by MikhailArkhipov** [comment]
hiding from UI is probably OK

**Comment by MikhailArkhipov** [comment]
We actually want to 

a). Disconnect first. Also disconnect on Save of edited connection. 
b). Connect REPL session only. If fails, remain disconnected, no attempts to reconnect to previous.
c). No test connection functionality.

So I think transaction code can be removed as well as there won't be transaction with rollback anymore.

What's the timeline for this? We should have this done before the public distribution or Dev15 integration.

**Comment by AlexanderSher** [comment]
Transaction code can't be removed completely because we can't leave the system in the middle of nowhere. If one session is stopped and user click canceled, we need to stop all other sessions. If new RHost is created but connection isn't finished and he clicked `Cancel`, we need to stop that RHost. And so on.

We had no bugs in `RSessionProvider` for couple of weeks now. I'd rather not touch anything related to the switch (to avoid introducing any new bugs) and just hide the Test Connection button

**Comment by MikhailArkhipov** [comment]
I meant we first stop everything (as if package was just loaded) - no cancellation. Then create connection with one session only. Complete disconnect should be part of #2845 I think.

**Comment by AlexanderSher** [comment]
If host is executing some native code, `q()` may not work and `IRSession.StopAsync` make take up to 20 seconds for that session. What should we show to the user during that process?

It is actually the same question with #2845.

**Comment by MikhailArkhipov** [comment]
Can we just abandon the session and create new one or blindly kill the process? There is no particular reason to wait for it to terminate.

**Comment by MikhailArkhipov** [comment]
I guess reducing to just hiding test connection
