### ISSUE TITLE
First time connection displayed in red

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2797]
Although it is connected

**Comment by MikhailArkhipov** [comment]
`IsConnected = eventArgs.IsConnected && _interactiveWorkflow.ActiveWindow != null;`

REPL is not up yet

**Comment by AlexanderSher** [comment]
Requested by #2736

**Comment by MikhailArkhipov** [comment]
Yeah but it doesn't change b/c (a) there is no `UpdateActiveConnection` in  `ActiveWindowChanged` and (b) ` _sessionProvider.IsConnected` is still false when REPL becomes active and CM is not listening to `Connected`

**Comment by AlexanderSher** [comment]
` ActiveWindowChanged` is raised only after RSession is connected:

```cs
            if (!RSessions.HasBroker) {
                var connectedToBroker = await Connections.TryConnectToPreviouslyUsedAsync();
                if (!connectedToBroker) {
                    Connections.GetOrCreateVisualComponent().Container.Show(focus:false, immediate:false);
                }
            }

            await interactiveWindow.InitializeAsync();

            ActiveWindow = window;
            ActiveWindow.Container.UpdateCommandStatus(true);
            _visualComponentTcs.SetResult(ActiveWindow);
            ActiveWindowChanged?.Invoke(this, new ActiveWindowChangedEventArgs(window));
```

**Comment by MikhailArkhipov** [comment]
`_sessionProvider.IsConnected` is false

**Comment by AlexanderSher** [comment]
That is a regression from #2793 - event is raised but property isn't updated

**Comment by MikhailArkhipov** [comment]
Because host info really should not have been used for the connectivity and broker state tracking in the first place.
