### ISSUE TITLE
Simplify MEF dependencies in CoreServices

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2801]
We are constantly getting MEF composition bugs because of the increasing complexity of this type dependencies (which originally was designed as lightweight entry point). It makes harder to write tests as well.

**Comment by MikhailArkhipov** [comment]
The proper answer is to review use of MEF and actually stop using it where appropriate. MEF is 'extensibility' framework and is not intended to manage internal dependencies.

**Comment by AlexanderSher** [comment]
Exactly. At least, we shouldn't export `CoreServices` by itself (and I think it isn't hard to do).

**Comment by MikhailArkhipov** [comment]
Sort of. Point in exporting `ICoreServices` was to avoid providing `ICoreShell`.

**Comment by AlexanderSher** [comment]
Looks like we don't have to. In #2816, there are only two places where I have to pass `ICoreShell` - `CoreServices` constructor (though it also can be avoided) and `RToolsSettingsImplementation` constructor, which is in `Package` assembly, where it doesn't really matter.
