### ISSUE TITLE
Ability to import remote connections from file

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2803]
And export. Admin can set up everything and then basically e-mail file to the group. JSON or something.

**Comment by MikhailArkhipov** [comment]
Another feature could be to store connections in a roaming profile so they auto-appear on all machines logged with the same Microsoft account.

**Comment by smortaz** [comment]
+1.

**Comment by MikhailArkhipov** [comment]
Roaming is on, so this one is now lower priority. I'd rather not make major changes to this area at this time.

**Comment by MikhailArkhipov** [comment]
This will be replaced by feeds for containers and connections
