### ISSUE TITLE
Package manager should close when connection is switching 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2809]
And stop refreshing. Even on local if user closes it it shouldn't be eating CPU cycles.

**Comment by AlexanderSher** [comment]
The second part is more a global issue. There are `mutated` event listeners (in PM, VE, etc.). Probably those listeners should react on event only when corresponding UI is visible.

**Comment by MikhailArkhipov** [comment]
If this is too complicated, we may leave it alone and document

**Comment by MikhailArkhipov** [comment]
With fix for #2808 another issue becomes prominent: async update of the package list causes odd behavior: in remote, library link is plain text but on local it is a clickable link. After switching remote -> local or the other way around and then clicking on various packages the link retains old appearance for some time and then eventually updates as view model is rebuilt.

**Comment by MikhailArkhipov** [comment]
The last one appears by design since fetching package info takes time. Closing for now.
