### ISSUE TITLE
Switching workspaces during a long-running operation gets stuck

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2810]
While connected to a remote machine, do:
```r
plot(1:1000000)
```
Then, while it's doing that (should take on the order of dozens of seconds), switch from remote to local.

VS gets stuck on the "Switching connection" dialog, even long after the plot should have completed. Clicking "Cancel" in that dialog hangs VS outright (window not being redrawn).

**Comment by int19h** [comment]
It reproed fairly consistently, but not 100%. One thing that is obvious from the logs is that the switch operation is 1) canceling all, and 2) trying to eval `q()`. But, it does not do 2 until 1 is complete (i.e. until the host says that it completed canceling. So it looks like the timeout on `q()` eval is not being handled right.

**Comment by AlexanderSher** [comment]
A bit of investigation:
- Hanging happens on `CancelAllAsync`. So it is not related to session switching logic or recent changes in `StopHostAsync`.
- Deadlock happens because plots are trying to draw themselves on the UI that is blocked by progress bar. Plots are blocking RHost loop (#2521), so further messages can't be received.
- Cancel button on progress bar doesn't work because `CancelAllAsync` awaits for `_cancelAllTcs` that can't be cancel by incoming token (that's a bug - has to be fixed).
- Even if host dies, `RHost._cts` remain canceled. `WebSocket.State == aborted`. @int19h , how does `RHost` get notified that socket is aborted?

**Comment by int19h** [comment]
It's supposed to fail next time it tries to receive a message from the socket. See `WebSocketMessageTransport.ReceiveAsync`. So if plot is blocking the message loop in `RHost`, that would explain failure to observe closure as well.

**Comment by MikhailArkhipov** [comment]
It may be worth checking if R is busy or blindly send InterruptR command before attempting to enter progress dialog.

**Comment by int19h** [comment]
`CancelAllAsync` is the code behind "Interrupt R", so this is already what's done here :)

**Comment by MikhailArkhipov** [comment]
Right, but before the progress dialog is up. I.e. when user tries to switch we a) show warning that session is canceled and ask if user wants to save the workspace (optionally with 'never ask again') and then cancel before starting switching.

**Comment by MikhailArkhipov** [comment]
In line with #2790 and #2811. May also help with #2782

**Comment by AlexanderSher** [comment]
> and then cancel before starting switching.

That won't help in general case. Even with UI thread unblocked, cancellation may not work if RHost executes some C library that doesn't care about the loop, and user won't be able to switch to another host until operation is completed.

Separate from #2521 and #2811 (#2521 is out of the scope anyway), I'm going to:
- Make cancellation in `CancelAllAsync` work. Cancel button on progress bar should work no matter what.
- Add a timeout. If `CancelAllAsync` takes more than 10 seconds, just don't wait for it anymore and call `RHost.DisconnectAsync`. `RHost` loop is disconnected from RSession at that moment already, so there will be no old plots coming up after operation is complete.
