### ISSUE TITLE
Give warning that session will be terminated when user tries connect to another R

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2811]
Otherwise users may think they can go local while remote is still doing calculations.

**Comment by AlexanderSher** [comment]
Should we show it every time user switches?

**Comment by Hong-Revo** [comment]
It would actually be REALLY cool if you could have multiple R sessions active. No idea how feasible this is, though.

**Comment by smortaz** [comment]
What Hong said.  tho not for 1.0.  PTVS allow multiple repls live connected
to multiple pythons in vs2017.

**Comment by int19h** [comment]
We certainly keep this scenario in mind. There's a lot of plumbing for it already, in fact. It's mostly the "last mile" - the actual VS windows that connect to those sessions - that need some serious work to make it happen.

And, obviously, we'll need some more controls to actually manage all those sessions - in 1.0, we'll have the Workspaces window that allows you to switch between sessions, but switching is implied stop old / start new operation. If we can have multiple live sessions, then that window will need buttons to start/stop, not just switch.

**Comment by MikhailArkhipov** [comment]
It should be possible to turn off the notification in options.
