### ISSUE TITLE
Ability to evaluate from Variable Explorer

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2814]
When I look at the Datasets package:
![image](https://cloud.githubusercontent.com/assets/1696845/20853783/466ee652-b8a3-11e6-8a5e-ac43a441ae10.png)

I can't view any of them from Variable Explorer until I evaluate them in REPL, ie. 
```
datasets::airmiles
```

Then I can use Variable Explorer to view that dataset.

![image](https://cloud.githubusercontent.com/assets/1696845/20853858/e8709338-b8a3-11e6-893d-a3799e03777c.png)

I wish I could force that evaluation directly from Variable Explorer, because Show item details is not present on those lazyLoadDBFetch.

**Comment by int19h** [comment]
I suspect this is basically https://github.com/Microsoft/RTVS/issues/751. When you hover over the icon for the variable, the tooltip should give the type and the class - I expect it to be "active binding" for these. Is that right?

**Comment by huguesv** [comment]
Tooltip for icon says `<promise> (<promise>)`

**Comment by int19h** [comment]
Ah, indeed, that makes more sense. But it's still #751. :)
