### ISSUE TITLE
Cannot edit an existing Remote R Workspace entry

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2815]
I'm trying to click on the gear to edit an existing entry in R Remote Workspace window. Sometimes the edit controls appear but then disappear right away.

**Comment by huguesv** [comment]
+1

**Comment by MikhailArkhipov** [comment]
Click may be coming as 2 clicks or double click. Are you folks on touchpads?

**Comment by jflam** [comment]
No. 

What's worse is that after editing a remote entry today, it vanished from the list of remote entries after completing the edit.

**Comment by MikhailArkhipov** [comment]
Yes, #2829
