### ISSUE TITLE
Occasionally help stuck on remote

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2818]
For some people `?abcde` never populates help, `Starting httpd...` completes but help doesn't come back.

**Comment by int19h** [comment]
It appears that the host process handled everything fine, responded with `!WebBrowser` message, and followed up with the new prompt. But in VS, REPL is not showing the new prompt.

**Comment by karthiknadig** [comment]
<== #121# !+ []

<== #123# !! ["starting httpd help server ..."]

<== #125# !! [" done\n"]

<== #127# !WebBrowser ["http:\/\/127.0.0.1:11763\/library\/base\/html\/cat.html"]

<== #129# !- []

<== #131# ?> [[0],4096,true,null,"> "]

**Comment by karthiknadig** [comment]
#2896

**Comment by huguesv** [comment]
Still seeing it blocked and help not coming up (wait cursor in repl)
![image](https://cloud.githubusercontent.com/assets/1696845/21280539/6ab000fc-c39b-11e6-8cf1-76d4a6b5cc18.png)

**Comment by MikhailArkhipov** [comment]
So, any chance we get this fixed or.... ?

**Comment by karthiknadig** [comment]
Unfortunately, there isn't enough info yet to fix this.
