### ISSUE TITLE
Idea: shortcut for jumping to "R Interactive" and back to editor.

### ISSUE THREAD

**Issue by mvacha** [Microsoft/RTVS#2820]
Usually when I use R I jump back and forward between the open file in editor and the R Interactive window. It would be cool, if I could do this jumping just by using single keyboard shortcut. Right now I can only use ALT+F7 to jump into Interactive and CTRL+TAB for selecting the file in editor, which is a bit cumberstone.

**Comment by int19h** [comment]
Ctrl+2 is the current shortcut to activate REPL (same as in RStudio).

Note that you can assign arbitrary shortcuts to commands in VS, if you would prefer a different combination, go to Tools | Options | Environment | Keyboard, and search for command named View.RInteractive.

**Comment by MikhailArkhipov** [comment]
And Ctrl+1 takes you back to the editor

**Comment by mvacha** [comment]
Fantastic! Thank you, guys!
