### ISSUE TITLE
Cannot edit workspace item after creating it

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2823]
Repro steps:
1. Click add to create works space item.
2. Type some URL and hit save.
3. Edit the URL for the same item again and hit save

Expected:
The item must have updated URL.

Actual:
The item remains unchanged.

**Comment by karthiknadig** [comment]
Issue seems to be specific to editing the URL

**Comment by MikhailArkhipov** [comment]
Probably similar to #2807. May be just checking if connection is identical just by name or something.
