### ISSUE TITLE
install.packages pulling down old versions

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#2827]
_> sessionInfo()_
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

_> install.packages("dplyr")_
Installing package into `xxxxxxxx/R/win-library/3.2'
(as `lib' is unspecified)
trying URL **'https://mran.revolutionanalytics.com/snapshot/2015-11-30/bin/windows/contrib/3.2/dplyr_0.4.3.zip'**
Content type 'application/zip' length 2551975 bytes (2.4 MB)
downloaded 2.4 MB

package `dplyr' successfully unpacked and MD5 sums checked

_> sessionInfo()_
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.437     LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] **dplyr_0.4.3**         RevoUtilsMath_8.0.3 RevoUtils_8.0.3     RevoMods_8.0.3      RevoScaleR_8.0.3    lattice_0.20-33     rpart_4.1-10       

**Current version is 0.5.0** -> https://mran.microsoft.com/package/dplyr/

**Comment by MikhailArkhipov** [comment]
This is MRO issue rather than RTVS. RTVS is not controlling install.packages and is not tied to any specific R version. I will met MRO team know.

**Comment by renebouw** [comment]
This is by design and a feature of MRO. MRO uses a snapshot of packages on a specific date to ensure reproducibility. https://mran.microsoft.com/documents/rro/reproducibility/#reproducibility  
If you want to change this behavior, see: https://mran.microsoft.com/faq/#change-repos

**Comment by ebs238** [comment]
thank you. i was able to get what i wanted working. 

I would note however that the default RTVS 0.5 installed  MSRO **3.2.2** pinned to 'https://mran.revolutionanalytics.com/snapshot/2015-11-30'. I would have expected the default install to install the latest MSRO **(3.3.2)** and pin to the latest snapshot

**Comment by Hong-Revo** [comment]
> I would note however that the default RTVS 0.5 installed MSRO 3.2.2 pinned to 'https://mran.revolutionanalytics.com/snapshot/2015-11-30'. I would have expected the default install to install the latest MSRO (3.3.2) and pin to the latest snapshot

This is a good point, actually. RTVS should point to the latest MRO, rather than the one that was current at the time of release.

**Comment by MikhailArkhipov** [comment]
RTVS points to fwlink which MRO team updates as needed.
