### ISSUE TITLE
Auto-fill of connection name works oddly

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2831]
Add new remote connection
Type URL without https:// 
- Connection name auto-fills with machine name
Type `:` after the machine name
- Connection name clears
Type port number
- Connection name is now the same as the port

Expected: connection name always remain as machine name unless non-empty (entered by the user)

**Comment by huguesv** [comment]
See this test in `ConnectionViewModelTest.cs` `CompletePath`
```
[InlineData("host:4000", "host:4000")] // host == scheme in this case and 4000 is actually a host name
```

That's how completion worked before the auto-naming functionality, so I kept it as it was designed.  Based on that, the behavior you saw was correct.

**Comment by MikhailArkhipov** [comment]
Yeah, but it is confusing. I think we can do better and actually grab the machine name.
