### ISSUE TITLE
can't connect msg needs machine name

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2832]
I thought agree to be verbose and include machine names...

Connecting to R Workspace failed.
Reason: Host [XXXXX] did not respond to a ping.
The machine may be offline or the network has been disconnected.
Error: An error occurred while sending the request.

also - i'm not a big fan of "An error occurred" type msgs :(.   what error?  can the user do anything about it?  the previous msgs seem to indicate that connection didnt happen anyway.

**Comment by MikhailArkhipov** [comment]
The message that comes from .NET Exception. Sometimes it is descriptive, but not always.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ac40aff1f3257c43913274f8f11d3daa7eb6c1de
