### ISSUE TITLE
SwitchToTheSameBroker test hangs cosistently

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2837]
on `await Task.WhenAll(switch1Task, switch2Task);`

**Comment by AlexanderSher** [comment]
Never seen it hanging on my machines.
Can you change this line to `await ParallelTools.WhenAll(30000, switch1Task, switch2Task)` so that next time we know which task is hanging?

**Comment by AlexanderSher** [comment]
Nvm, now I see it too. Looks like it is somehow dependent on call sequence.
