### ISSUE TITLE
How to update R for RTVS

### ISSUE THREAD

**Issue by rthomaskelly** [Microsoft/RTVS#2842]
RTVS is currently using R version 3.2.2. How do I update the R to the latest version 3.3.1?

**Comment by MikhailArkhipov** [comment]
RTVS is not linked to any specific R. You can install most recent R Open (3.3.2) from https://mran.microsoft.com/news/ or stock R from https://cran.r-project.org/bin/windows/base/

**Comment by rthomaskelly** [comment]
Thank you. I changed the R Engine in the R Tools -> Options menu.
