### ISSUE TITLE
When connection is deleted it is not really disconnected

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2845]
Deleted connection to the server (while connected). Operation on REPL says disconnected, but title of the window still lists the URL and attemts to reset REPL actually tries to reconnect.

![image](https://cloud.githubusercontent.com/assets/12820357/20987246/bdd9b2a4-bc80-11e6-9a8c-da534358945d.png)

**Comment by AlexanderSher** [comment]
Should we also disconnect if user changes URL of the currently used connection? Or should we reconnect in this case?

**Comment by MikhailArkhipov** [comment]
Yes, we should disconnect_

**Comment by AlexanderSher** [comment]
Do we want to delete user profile on server when connection is deleted? I think we should do it.

**Comment by AlexanderSher** [comment]
On the other hand, user may want to remove connection that he has temporary created on some machine that isn't his personal. In this case, profile and all the files should not be deleted.

**Comment by AlexanderSher** [comment]
Instead of waiting for `RSession.StopHostAsync`, we may just remove `RHost` instance from `RSession` and call `RSession.StopHostAsync().DoNotWait()`. The problem may happen if user rename on of existing connections and start it before old one is stopped.
@int19h , @karthiknadig , what will happen on the broker side if user tries to start session that is already running?

**Comment by karthiknadig** [comment]
we kill already started old sessions, (forcibly).

**Comment by MikhailArkhipov** [comment]
I think the experience we've discussed is to show a message box that tells that deletion of the connection does not delete remote files and if user wants to do it they need to connect and delete the profile. Probably with 'Dont show this again'. Or as simple as add option to Tools | Options (new Security category or something) so suppress the warning.

**Comment by AlexanderSher** [comment]
Ok
