### ISSUE TITLE
Variable Explorer doesn't show stack frames at breakpoint

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2848]
```r
(function() {
    x <- 1;
    browser();
})()
```
Source the file. Note the `Browse>` prompt when it hits the `browser()` call. At this point, VE should be showing the stack frame for the function we're in, in the environments dropdown. But it only shows `.GlobalEnv` and packages. 

Same thing happens with debugger attached, and a breakpoint on the same line.

Call Stack window in debugger, on the other hand, shows the stack correctly.

**Comment by int19h** [comment]
The real issue here is that `RSession.Mutated` is not being raised. This affects everything that depends on it - e.g. VE is not getting updated at all (including new variables etc).

Under debugger, I see that we get to this code in RSession.cs:
```cs
        private void OnMutated() {
            if (_disableMutatingOnReadConsole.Count == 0) {
                Mutated?.Invoke(this, EventArgs.Empty);
            } else {
                _delayedMutatedOnReadConsole = true;
            }
        }
```
and `_disableMutatingOnReadConsole.Count` is 2. Looking at the code in `RInteractiveEvaluator` that calls `DisableMutatingOnReadConsole`, it's not clear how this could be triggered - it's in a `using` block, so I would expect the counter to always be 0 or 1. Unless there's some kind of weird scenario in which `ExecuteCodeAsync` can be re-entered? @AlexanderSher, what do you think?

FWIW, this only consistently repros in one particular VS session on a VM. I couldn't repro it on any of my three other machines, and I suspect that it might not repro anymore if I restart that VS. It does, however, survive session restart.

**Comment by AlexanderSher** [comment]
I can imagine that one of the awaiters inside `ExecuteCodeAsync` is still waiting. What is the value of `RInteractiveEvaluator._evaluatorRequest.Count`?

**Comment by int19h** [comment]
Immediately prior to entering the `using` block, it is 1.

**Comment by int19h** [comment]
I do not observe any reentrancy for that code under debugger. I think it happened once under some weird condition, and now I'm just stuck with counter being one more than it should, and hence `Mutated` not being fired.

**Comment by AlexanderSher** [comment]
I think I know how it happened. Here is a test:
```cs
            [Test]
            [Category.R.Session]
            public async Task CancelAll_Cancel_Stop() {
                var testMrs = new AsyncManualResetEvent();
                var plotMrs = new AsyncManualResetEvent();
                _callback.PlotHandler = (message, ct) => {
                    testMrs.Set();
                    // ct is ignored on purpose
                    return plotMrs.WaitAsync();
                };

                var cancelAllCts = new CancellationTokenSource();
                Task responceTask;
                using (var interaction = await _session.BeginInteractionAsync()) {
                    responceTask = interaction.RespondAsync("plot(1)\n");
                }

                await testMrs.WaitAsync().Should().BeCompletedAsync();
                var cancelAllAsyncTask = _session.CancelAllAsync(cancelAllCts.Token);

                await cancelAllAsyncTask.Should().NotBeCompletedAsync();

                cancelAllCts.Cancel();
                await cancelAllAsyncTask.Should().BeCanceledAsync();

                _session.IsHostRunning.Should().BeTrue();
                await _session.StopHostAsync().Should().BeCompletedAsync();

                await responceTask.Should().BeCanceledAsync();
            }
```

You probably called `View`, that hanged because of the #2846, and then you've clicked `Reset`.

**Comment by int19h** [comment]
I experimented a bit (after reverting the fix for that bug locally), and it appears that it is actually "Interrupt R" that is causing it. In fact, there are other bugs lurking there - if I interrupt `View()`, and then immediately try to use the REPL, the host goes down, because VS sends a response to the wrong `ReadConsole` message.

Do you think any of this is worrisome, given that now we no longer await any callbacks?

**Comment by int19h** [comment]
This is another manifestation of https://github.com/Microsoft/RTVS/issues/2521. The exact scenario (that was actually moderately likely to repro) is since fixed. However, it can manifest in other cases of re-entrancy possible (but much less likely) until #2521 is fully fixed.

Closing as a dupe, but we should look at the priority of the other bug in the next triage.
