### ISSUE TITLE
When broker dies connection remains green

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2849]
Stop broker on remote machine. We get 'host process stopped'. Indicator is green and host load indicator is there (albeit showing last known state). Reset REPL. Now you get 'R Services is not running' but the connection is still green. And there is no 'connect' button obviously.

![image](https://cloud.githubusercontent.com/assets/12820357/20988675/92dd254e-bc86-11e6-8fa6-fd6c4f97a218.png)

**Comment by AlexanderSher** [comment]
Is it debug or release build?

**Comment by AlexanderSher** [comment]
Nvm, I've found the cause
