### ISSUE TITLE
Session (host) information is not reported with some remote

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2854]
On my VM host load indicator works, but about host does not. Host Information command doesn't work either.

![image](https://cloud.githubusercontent.com/assets/12820357/20989501/b5ea3b0a-bc89-11e6-90a4-e450df59e9be.png)

**Comment by MikhailArkhipov** [comment]
Seems to be specific to VMs.

**Comment by MikhailArkhipov** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.R.Host.Broker.About.AboutController.GetVideoControllerInformation(AboutHost& a)
   at Microsoft.R.Host.Broker.About.AboutController.Get()
```

**Comment by AlexanderSher** [comment]
Lack of permissions?

**Comment by MikhailArkhipov** [comment]
No, it looks like on VM `ManagementObjectSearcher.Get("AdapterRAM")` returns null.
