### ISSUE TITLE
Use aka.ms link for MRS

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2856]
Our banner for MRS (if you're running CRAN R) currently uses a rather unwieldy fwlink URL:
```
Check out Microsoft's enhanced R distribution at http://go.microsoft.com/fwlink/?LinkId=734720. 
```
We should replace it with something like `http://aka.ms/mrs`, or something similarly short and memorable that is available.

**Comment by MikhailArkhipov** [comment]
https://aka.ms/mrclient
