### ISSUE TITLE
Attempt to connect to non-existent remote connects to local

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2859]
Mistype remote port such as `54444`. Try connecting. After some time you get connected to local R.

```
                await TrySwitchBrokerAsync(connection, cancellationToken);
                await _shell.SwitchToMainThreadAsync(cancellationToken);
                var interactiveWindow = await _interactiveWorkflow.GetOrCreateVisualComponentAsync();
                interactiveWindow.Container.Show(focus: false, immediate: false);
```

`TrySwitchBrokerAsync` actually returns false but code proceed with `GetOrCreateVisualComponentAsync` which, I guess, picks best local R.

**Comment by AlexanderSher** [comment]
Ok, what is expected? Just leave everything unconnected?

**Comment by MikhailArkhipov** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
Oh, and there was no error shown either.

**Comment by AlexanderSher** [comment]
> Oh, and there was no error shown either.

#2732

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c9fd701c9712d2b8e7f674578c78b15ad398d3c7
