### ISSUE TITLE
RTVS & PTVS cannot coexist

### ISSUE THREAD

**Issue by PterosDiacos** [Microsoft/RTVS#2863]
I have VS 2015 (community ver.) and both R tool for VS (0.5) and Python tool for VS (2.2.5) installed.
It turns out to be the case that upon startup, the Python interactive window (or any Python project) cannot be loaded _before_ the R interactive window (or any R project) is loaded. Otherwise, VS would crash.

Just wondering if anyone else has experienced the same incompatibility issue.

**Comment by MikhailArkhipov** [comment]
Is is a know issue, see https://github.com/Microsoft/RTVS/issues/983. It will be fixed in upcoming VS 2017. Thanks.
