### ISSUE TITLE
Coloring problem in R interactive

### ISSUE THREAD

**Issue by Masutani** [Microsoft/RTVS#2864]
We found coloring problem that occur in interactive windows.
![colorpob](https://cloud.githubusercontent.com/assets/4596707/21035442/729356be-be02-11e6-9ac9-e195f3427394.PNG)
Visual Studio 2017 RC + RTVS 0.5 + Windows 10 Ann

**Comment by MikhailArkhipov** [comment]
Looks like same as https://github.com/Microsoft/RTVS/issues/2571. This will appear in future update for 2017 RC as well as in RTVS 0.6 for VS 2015.
