### ISSUE TITLE
First time connection to a remote server puts VS in "hung state"

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2870]
This happened the last time I connected to a new server, and today again with yet another new server.  It will ask for credentials, then the VS window eventually goes white.  Progress bar still up, but nothing happens even after several minutes of wait.  There's another window you can switch to, which says VS may be in hung state.

![image](https://cloud.githubusercontent.com/assets/1696845/21066480/a631425c-be1a-11e6-8a06-576ebfd83ddd.png)

You can't see both progress bar and hung state message at the same time, you have to switch with task bar:
![image](https://cloud.githubusercontent.com/assets/1696845/21066504/ba0fc974-be1a-11e6-82a4-dddaba72b299.png)

**Comment by AlexanderSher** [comment]
What happens if you click cancel?

**Comment by huguesv** [comment]
I got the SSL certificate warning message.  But it took a long time to get it, could have been because of machine rebooting.

**Comment by MikhailArkhipov** [comment]
This was fixed - cert window was showing under the VS
