### ISSUE TITLE
Credentials dialog isn't modal

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2871]
When it appears, user can switch back to VS without closing the dialog and interact with UI

**Comment by MikhailArkhipov** [comment]
`IVsUIShell.EnableModeless` is your friend

**Comment by AlexanderSher** [comment]
No, it is actually _coreShell.AppConstants.ApplicationWindowHandle is invalid.
We call AppConstants.Initialize too early.

**Comment by MikhailArkhipov** [comment]
Ah. then it can go to `CheckVsStarted` and to the `shell started` notification callback
