### ISSUE TITLE
While connected to remote I can delete it but cannot reconnect on add.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2873]
Repro steps:
1. Add a new connection.
2. Connect to the machine.
3. While connected delete the connection.
4. Add the same connection again.
5. Hit the connect button.

Actual: 
After deleting the connection, the user is not disconnected from it.

Expected:
On deleting the connection user should be disconnected. User should be able to add and connect if they add the same remote machine back.

**Comment by MikhailArkhipov** [comment]
#2845

**Comment by AlexanderSher** [comment]
Fixed in #2900
