### ISSUE TITLE
remote error msg format + machine name.

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2875]
remote error msgs should be more informative and
have a blank line between them.    

most important, the name of the connection/machine should be in the error msg.

![image](https://cloud.githubusercontent.com/assets/742484/21075079/3641ba90-bebe-11e6-8b7d-e1ab07f961e2.png)

**Comment by MikhailArkhipov** [comment]
Which one do we show?

1. Connection name
2. Machine name
3. Full URL

(1) gives some information, but not much. Full URL may be very long, 50-60 characters (check Azure URL). REPL does not wrap lines so if we show long URL rest of the message won't be visible unless scrolled. We could theoretically add line breaks depending on window width/font used...

**Comment by smortaz** [comment]
#1 plus a blank line after the msg group is fine for now.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ac40aff1f3257c43913274f8f11d3daa7eb6c1de
