### ISSUE TITLE
RTVS installation fails for VS 2015 Update 3 on Windows 10

### ISSUE THREAD

**Issue by jjkane** [Microsoft/RTVS#2877]
When trying to install RTVS using RTVS_2016-10-08.1.exe, the installation stops because the file RHost_2016-10-08.1.msi is missing.

**Comment by MikhailArkhipov** [comment]
Are you online? This MSI has to be downloaded for legal reasons with GPL. If you have to install RTVS offline you can try and download it first from `https://rtvs.azureedge.net/download/RHost_2016-10-08.1.msi` and place it next to RTVS.msi

**Comment by jjkane** [comment]
I downloaded the file and the installation succeeded.
Thanks,

John J. Kane, Ph.D.
Member, Research Staff
Cost Analysis and Research Division
Institute for Defense Analyses
4850 Mark Center Drive
Alexandria, Virginia 22311-1882
703-575-4688

**Comment by MikhailArkhipov** [comment]
Glad to hear you are set up :-)
