### ISSUE TITLE
Select() brings signature help on lm.ridge

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2879]
Not sure about the case since select() is not in the intellisense list

![image](https://cloud.githubusercontent.com/assets/12820357/21151136/3ff7baee-c116-11e6-8a60-4ac5ed4767c8.png)

**Comment by MikhailArkhipov** [comment]
```
\name{lm.ridge}\alias{lm.ridge}\alias{plot.ridgelm}\alias{print.ridgelm}\alias{select}\alias{select.ridgelm}\keyword{models}\description{
Fit a linear model by ridge regression.
```
The signature is correct. However, we should probably be showing actual typed alias name rather than the primary.

**Comment by int19h** [comment]
Isn't this the wrong `select`? I thought this was about the one from `dplyr`?

**Comment by int19h** [comment]
Which, speaking of - what happens when there are several packages installed that offer the same function name? Execution-wise, you get the one that you've attached last (e.g. via `library`). What about Intellisense?

**Comment by MikhailArkhipov** [comment]
Currently completion search picks first in the list of packages, unrelated to the attachment list.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c9fd701c9712d2b8e7f674578c78b15ad398d3c7
