### ISSUE TITLE
Write remoting arch / overview / admin doc

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2883]
We need to write down a doc for admins who will be installing the server component of RTVS. The goal of this document is to:

1. Explain how the system works at a high level; e.g., we use SSL, we require your credentials, we cache them using Windows cred manager, we transmit them securely to the server and log you in there etc.
2. The detailed step-by-step instructions for installing / running the product. There are pages in OneNote that describe how to do this. Will add link in comment.

**Comment by smortaz** [comment]
+1.

**Comment by jflam** [comment]
Details for installation here: https://microsoft.sharepoint.com/teams/data_science_tools/SiteAssets/Data%20Science%20Tools%20Notebook/?Web=1 

Under RTVS/Creating a DS VM for Azure

**Comment by MikhailArkhipov** [comment]
Also #2850

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS-docs/issues/53
