### ISSUE TITLE
Auto R Client detection fails for latest Microsoft R Client

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2886]
Just installed the latest R Client from: https://msdn.microsoft.com/en-us/microsoft-r/r-client-get-started#installrclient

When restarting RTVS, it didn't auto-detect it. The install directory is:
C:\Program Files\Microsoft\R Client\R_SERVER\bin

Do we need updated detection logic?

**Comment by MikhailArkhipov** [comment]
What is in the registry? We don't look directly into the disk path

**Comment by jflam** [comment]
Don’t know. Where do I look in the registry for this?

**Comment by MikhailArkhipov** [comment]
Just installed, detected perfectly fine

![image](https://cloud.githubusercontent.com/assets/12820357/21199620/16385496-c1f9-11e6-95dd-cd8a2090a084.png)

Are you on 0.5 or 0.6 ?

**Comment by jflam** [comment]
0.6.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/21200250/69ee23ca-c1fb-11e6-8840-c31330ccf9bb.png)

**Comment by MikhailArkhipov** [comment]
May be related to #2807 or #2361

**Comment by MikhailArkhipov** [comment]
I managed to repro this. I think what happens is that roaming settings come later and overwrite detected installation. I'll take care of this.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/27e2df12c3e58a8c4f2fe236e4d9c2278357563a
