### ISSUE TITLE
Handle non-unique names in completion as R does

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2887]
For `select` we need to be able to fetch correct description depending if `MASS` or `dplyr` was loaded last.

**Comment by Hong-Revo** [comment]
This would apply to any situation where the same object is exported by different packages. dplyr just happens to be a notorious offender.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/52cf566ee7726979fa6a15cfd414cab922b25a0a
