### ISSUE TITLE
cannot render .rmd file

### ISSUE THREAD

**Issue by IvanKosyakov** [Microsoft/RTVS#2895]
I cannot render .rmd file.
Right-click commands "preview in HTML/Word" are not available.

...

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.4.20623.1711, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by IvanKosyakov** [comment]
P.S. I am using standard Azure Data Science virtual machine.

**Comment by MikhailArkhipov** [comment]
Could you please update to 0.5. https://aka.ms/rtvs-current

**Comment by IvanKosyakov** [comment]
I have installed the update.
It did not fixed the issue.

Also I have error message (see attachment).
Probably this is related to the issue.

![error001](https://cloud.githubusercontent.com/assets/10847278/21243452/da95588a-c310-11e6-8cc3-b572616ad762.png)

**Comment by IvanKosyakov** [comment]
Here is the log: 

  <entry>
    <record>464</record>
    <time>2016/12/15 21:54:08.986</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Entering function CVsPackageInfo::HrInstantiatePackage</description>
    <guid>{C194969A-A5B1-4AF2-A9DF-ECF7CE982A05}</guid>
  </entry>
  <entry>
    <record>465</record>
    <time>2016/12/15 21:54:08.986</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Roaming Profiles Package]</description>
    <guid>{C194969A-A5B1-4AF2-A9DF-ECF7CE982A05}</guid>
  </entry>
  <entry>
    <record>466</record>
    <time>2016/12/15 21:54:08.986</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Roaming Profiles Package]</description>
    <guid>{C194969A-A5B1-4AF2-A9DF-ECF7CE982A05}</guid>
  </entry>
  <entry>
    <record>467</record>
    <time>2016/12/15 21:54:09.033</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.Languages.Editor.BraceMatch.BraceHighlighter..ctor(ITextView view, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Languages.Editor.BraceMatch.BraceHighlightProvider.CreateTagger[T](ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>

**Comment by IvanKosyakov** [comment]
From the log: "System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.Languages.Editor.BraceMatch.BraceHighlighter..ctor(ITextView view, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Languages.Editor.BraceMatch.BraceHighlightProvider.CreateTagger[T](ITextView textView, ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
![error002](https://cloud.githubusercontent.com/assets/10847278/21243681/c472db62-c311-11e6-8784-2e7cc51b613b.png)"
![Uploading error002.png…]()

**Comment by MikhailArkhipov** [comment]
I believe the assert is ignorable. I think you can avoid it if you have all editor windows closed before starting VS. Back to the HTML - is the command disabled or invisible?

**Comment by IvanKosyakov** [comment]
The command is invisible.

**Comment by IvanKosyakov** [comment]
Installing and loading library "rmarkdown" solved the issue.
===
Visual Studio with R Tools, menu: R Tools -> Windows -> Packages; search for "rmarkdown"; click "Install" on Available tab; enable on Loaded tab.
