### ISSUE TITLE
Package manager does not update after uninstall

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2898]
I installed 'shiny' in REPL. Opened package manager, searched for 'shiny' hit uninstall. After the package was removed, package manager did not update. I verified that the package was removed.

**Comment by AlexanderSher** [comment]
Can't repro so far. What tab was open? Was it local or remote?

**Comment by karthiknadig** [comment]
This was remote. I opened Package manager after installing the package.

**Comment by AlexanderSher** [comment]
Do you have a stable repro?

**Comment by karthiknadig** [comment]
Yes, it repros every time.
