### ISSUE TITLE
rtvs::fetch_file does not report progress

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2904]
if you try to fetch a large remote file, e.g.:
```r
write.csv(matrix(1:1000000, 1000), "foo.csv")
rtvs::fetch_file("foo.csv")
```
it just blocks the REPL for the duration of the operation. There's no indication that anything goes on. Perhaps we can implement a progressbar in the REPL, using `\r`?

**Comment by MikhailArkhipov** [comment]
Better pop cancellable progress dialog?

**Comment by MikhailArkhipov** [comment]
Looks like instead of sending file as blob, it would need to send file name instead and use `DataTransferSession` with progress on the client.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bb79a02f9e3524d38068fcf3d26df05174df271b
