### ISSUE TITLE
Long name in ConnectionManager hides control buttons

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#2906]
- Create new connection
- Give it long name
- Save

![image](https://cloud.githubusercontent.com/assets/8933858/21281137/286aa002-c3b0-11e6-8f34-beef9e8ee666.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8de1e26b844cb341ffc08044aa4950412d7dd7a5
