### ISSUE TITLE
Project setting for Transfer files to server should be checked by default to enable no-surprise F5

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2907]
Pressing F5, if you just created a new project using the defaults, will result in nothing happening if you try to F5 the project because, by default, we do not copy files to server on F5. Changing this setting will fix this.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/27e2df12c3e58a8c4f2fe236e4d9c2278357563a
