### ISSUE TITLE
Any # added to the server URL is immediately removed when you save

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2908]
In workspaces window, Add new remote server
Try to add a # in the URL, and click save.
Result: The # and anything after is removed

The use case for this is to specify the interpreter guid on the remote machine when multiple interpreters are available. While we don't plan on documenting this, being able to specify it lets us test it and may be able to help customers on case-by-case basis.

**Comment by AlexanderSher** [comment]
Part of #2361
