### ISSUE TITLE
Remote HTTP server messages need to be fixed

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2917]
![image](https://cloud.githubusercontent.com/assets/12820357/21368926/6c6fb006-c6b9-11e6-925d-0af15283c12b.png)

Machine address is incorrect (shows localhost instead of the actual IP)
'HTTP server allows you to connect' is probably not quite right. Maybe `HTTP server transfers data from remote machine...'

**Comment by AlexanderSher** [comment]
> Machine address is incorrect (shows localhost instead of the actual IP)

Do we really need an IP at that moment, or `https://myserver:5444` is enough?

**Comment by MikhailArkhipov** [comment]
No IP needed.
