### ISSUE TITLE
Display warning dialog with "don't show me this again" checkbox when switching Workspaces.

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2920]
We were going to do this as part of the larger work around simplifying the semantics of switching behavior, but we didn't implement all of that feature. This was lost somewhere along the way.

From: Hong Ooi's mail:

"There should be a message/warning somewhere that switching workspaces means your old workspace will be closed. Maybe a separate dialog box with the option “don’t show this again” so it won’t get too disruptive."

**Comment by AlexanderSher** [comment]
#2811
