### ISSUE TITLE
resizing plot window redirects active output to the plot window

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#2925]
I have a long script which writes about 10 plots to a pdf. If the plot window in VS is resized while this script is running, the remaining plots  are output to the plot window, instead of the pdf.

**Comment by huguesv** [comment]
Thanks for the report!

This was fixed not long after we released 0.5. The active graphics device wasn't restored after several operations, including resize.
https://github.com/Microsoft/R-Host/commit/8cc1bf9ee8a8c10e7f37ae7c3fdff5635204311a

Our upcoming release (which should be soon now) will have the fix.
