### ISSUE TITLE
cannot use RTVS with VS2015 on Windows 10

### ISSUE THREAD

**Issue by OlafEichstaedt** [Microsoft/RTVS#2933]
I am at a loss ...

Installation seems to run smoootly.

I start VS2015 ... it says it is scanning some new components ...
Then
![image](https://cloud.githubusercontent.com/assets/24755597/21468028/854bc5b6-ca3c-11e6-983f-786518fef36c.png)

The activity log does nothelp me ... but maybe you can find a clue.

[ActivityLog.txt](https://github.com/Microsoft/RTVS/files/671849/ActivityLog.txt)

Can it be an interaction with the Python add-ons?

Looking forward to your feedback.
Any ideas whata I can try to debug this issue?

**Comment by MikhailArkhipov** [comment]
I don't see anything RTVS related in the attached log. However, VS seems to be 14.0.25420.1 which, I think, is Update 2. Try updating to 3 which is 14.0.2543*.

**Comment by OlafEichstaedt** [comment]
Hello Mickhail,
thanks so much for your reply ... good catch, but it is weird: when I view "Help/About Microsoft Visual Studio" I get
![image](https://cloud.githubusercontent.com/assets/24755597/21469715/8120b94a-ca9d-11e6-9817-2a0965e19d7b.png)
I.E. it tells me it is update 3 and version 14.0.2543*.* ... that's why I though I was safe on this frontier.
So VS seems to be confused about which version it is? 
That cannot be good.
I might need to consider a reinstall ... mind you ,nothing I am looking forward to, as the "acquisition" of the components over Wifi took about 2h last time.

**Comment by MikhailArkhipov** [comment]
Also, if you dismiss the message - do you see `R Tools` menu? If yes, does opening `R Tools -> Windows -> R Interactive` brings up proper REPL with R prompt?

**Comment by OlafEichstaedt** [comment]
sorry for the delay ...
* I re-installed RTVS
* started VS, error was still there
* tried to open interactive Window, did not work (none of the R Tools options did anything)
* stopped VS
* started VS ... no more error!
* was able to open interactive R window => it seems I am up and running now ;-)

No idea why it suddenly works. Is it possible it has to do with location? 
My first attempts were from China. Now I tried from Switzerland.

Thanks for chipping in to help. I am happy it works now. But also frustrated that it seems to arbitrary ... hope the system stays stable.

Have a good start into a healthy, successful, and totally amazing 2017!

**Comment by OlafEichstaedt** [comment]
... not stable.

**Comment by MikhailArkhipov** [comment]
This happens on some machines if you had R Interactive open when you closed VS. Workaround is to close REPL before shutting down VS. This is fixed in upcoming 0.6 and next VS 2017 update as #2806

**Comment by MikhailArkhipov** [comment]
Closing since 0.6 is not being distributed and included into VS 2017.
