### ISSUE TITLE
REPL window title doesn't display full URL

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2936]
Not sure it it is important

![image](https://cloud.githubusercontent.com/assets/12820357/21530628/eac11a56-ccf6-11e6-84f1-8aaff10b7e30.png)

**Comment by smortaz** [comment]
i think it's important.  i'd skip the http:// to get more room.

On Wed, Dec 28, 2016 at 12:12 PM, Mikhail Arkhipov <notifications@github.com

**Comment by MikhailArkhipov** [comment]
OK, included in upcoming merge for Dev15

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/51de46d315fc0e0cc89fd3e795bbb409f39b4db1
