### ISSUE TITLE
radialNetwork graph crash - R tools feedback report

### ISSUE THREAD

**Issue by MikeWise2718** [Microsoft/RTVS#2947]
Please briefly describe what you were doing that led to the issue, if applicable:

See Issue:"radialNetwork graph crash #2945" for a description. This is in response to a request there to report the issue via R Tools feedback as that apparently attaches logs (although I don't see any so far).
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21008.800, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\R\R-3.3.2

**Comment by Hong-Revo** [comment]
When you click on the frown menu item, it should create a zipped log file in your temp folder, and open an Explorer window with the file selected. The file is called RTVSlogs.zip by default.

**Comment by MikeWise2718** [comment]
I see, didn't try the frown. Ok, attached the RTVSLogs.

[RTVSLogs.zip](https://github.com/Microsoft/RTVS/files/682833/RTVSLogs.zip)
 zip file.

**Comment by MikhailArkhipov** [comment]
The call stack does not apply to 0.6 since code path changed a lot. Please reactivate if you encounter this in 0.6.
