### ISSUE TITLE
REPL directory doesn't show current directory

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2951]
On VS 2017 with RTVS 0.6

I changed it to a different folder using the select working directory button (last one on the toolbar) and the combo box doesn't get updated.

![image](https://cloud.githubusercontent.com/assets/1696845/21624015/f7517b40-d1b9-11e6-95ec-3a810623cbb7.png)

**Comment by MikhailArkhipov** [comment]
Fallout from filtering `setwd` activities

**Comment by MikhailArkhipov** [comment]
#2312

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1e553fc7584a9c6be107baf4d4e76debe5610218
