### ISSUE TITLE
Can't connect to custom local interpreter

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#2954]
In Workspace window, click Add.
Click on the browse button next to the path text box, and pick the same folder R Client\RSERVER folder as in the picture below:
![image](https://cloud.githubusercontent.com/assets/1696845/21625279/c41a3a18-d1bf-11e6-9c60-83bf8898a4e0.png)
Save and click connect.  Progress bar appears and it never connects.
If you cancel VS hangs. Dump here: \\pytools\r\Bugs\2954

**Comment by MikhailArkhipov** [comment]
Reproes for me as well.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16f3e664e51f2f88e8ad7220eed50bcff3358709
