### ISSUE TITLE
Fix inconsistencies in our dialog boxes for yes / no and ok / cancel

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2955]
Pavel has a task dialog implementation that we will likely look at using post-1.0. Today we have minor inconsistencies in how we ask the user OK / Cancel vs. Yes / No: Here's an example from the switching Workspaces:

![image](https://cloud.githubusercontent.com/assets/8877/21625551/0d424874-d1c1-11e6-9f52-efc200a9e2b2.png)

![image](https://cloud.githubusercontent.com/assets/8877/21625561/184e8d7c-d1c1-11e6-96ac-170f3fbd9a61.png)

**Comment by int19h** [comment]
The implementation is taken from PTVS, where it's used already to display dialogs like these:

![](https://github.com/Microsoft/PTVS/wiki/Images/ReplaceRequirementsTxt.png)

**Comment by int19h** [comment]
So in this case, the first dialog would be something like this:

- Connect with self-signed certificate
  - The security of this connection cannot be guaranteed. Choose this option if you are sure that the certificate is valid.
- Do not connect

And the second one:

- Switch to new session
  - Your current session will be terminated, and any unsaved data in it will be lost.
- Remain in existing session

**Comment by jflam** [comment]
Yes - that looks great!

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/47aea657ddcba93ecede67a555f4f01015b557be
