### ISSUE TITLE
Interactive window needs to be a dependency on Dev15

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#2957]
If some other workload (e.g. C#) doesn't install the Interactive window component in Dev15, we don't do that either. But we do depend on it, so our package fails to load:

> Could not load file or assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

So installing just the data science workload would result in a broken RTVS install.

**Comment by MikhailArkhipov** [comment]
It is a red herring. I installed Dev15 + DS workload on VM and the interactive window is there. I think what happened is that if you install min VS (i.e. just core) and then add RTVS manually through VSIX then it fails since min VS does not install IE assemblies.
