### ISSUE TITLE
SendToRemote command needs a way to cancel.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#2961]
Also show progress.

**Comment by smortaz** [comment]
more than just cancel - it needs a clear display of each file as it's xfered in the REPL.  currently it's batched and VS gets a "VS non-responsive" pop which will make ppl think it's crashed.   after the pop goes away eventually you get the flushed list of file xfers.   it should be as they're happening.

**Comment by MikhailArkhipov** [comment]
Actually no, it needs to show standard VS progress with cancellation as `rtvs::fetch` does now.

**Comment by smortaz** [comment]
so if i do Send on the Project with 50 files, i see no xfer progress until
they're all xfered?

**Comment by MikhailArkhipov** [comment]
You will see gradual progress bar with file names.

**Comment by smortaz** [comment]
ah ok.  that'll be fine.  would be nice to include file size after the name
so ppl realize why some take much like (like bigger data files)
