### ISSUE TITLE
Add indication that connection name is invalid

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2967]
Currently we only disable buttons. Need some way to tell user why name is invalid and what characters are permitted.

**Comment by karthiknadig** [comment]
![image](https://cloud.githubusercontent.com/assets/3840081/21728475/403e6b18-d3fb-11e6-979e-e852b11de227.png)

**Comment by smortaz** [comment]
another option is to use all that white space under "save/cancel" to say something like:

Invalid characters in name: please use letters, numbers, -, //, :, $  blah blah

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1416437443ba5ef0b28a2700eb9cebd5240a7b38
