### ISSUE TITLE
Go To Definition does not work

### ISSUE THREAD

**Issue by dlealv** [Microsoft/RTVS#2969]
Hi,

After right click on the function or F12, I get an error sound and nothing happened. I am using Microsoft Visual Studio Community 2015 version 14.0.25.0.25123.00 Update 2 and R Tools for Visual Studio 0.3.20427.2043. 

Thanks in advance,

David

**Comment by MikhailArkhipov** [comment]
Couple of suggestions:

1. Please update RTVS - 0.3 is very old. Current is 0.5 with 0.6 incoming. https://aka.ms/rtvs-current 
2. Goto definition working within single file only. It does not take you to other file or to code in packages.

Thanks

**Comment by dlealv** [comment]
Mikhail, thanks for your rapid response...I updated the MVS and RTools and
it works!!! thanks. David


*___________________________*

*David Leal, MBA,PMP®, **CSM®*
dleal67@gmail.com
+1 786 342 4153
<https://www.linkedin.com/in/davidlealvalmana>
