### ISSUE TITLE
poor formatting of the r session switch msg box

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2970]
1. the R interp name is split in the middle
2. it's easier to read if key info is on separate lines (especially since remote names might be long)

ie:

```
Are you sure you want to switch from:
   Microsoft R client (3.3.2)
To:
   RTVS-DevServer1 ?
<blank line>
Switching will stop your current session.... 

This prompt can be suppressed ...
```

![image](https://cloud.githubusercontent.com/assets/742484/21735772/1e68d002-d421-11e6-9ad2-629eb590a979.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/47aea657ddcba93ecede67a555f4f01015b557be
