### ISSUE TITLE
bad english for host switch

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#2971]
also see my previous bug filed on formatting these host change msgs.  this one should follow the same pattern.

![image](https://cloud.githubusercontent.com/assets/742484/21737904/a627ee68-d432-11e6-85c3-b54ecf0fb3a5.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/47aea657ddcba93ecede67a555f4f01015b557be
