### ISSUE TITLE
Can not input line break between " and other command.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#2974]
Between the " and 'x' in the following code, hitting Return key doesn't insert line break between them and insert line break next line.
```R
test <- function() {
	for (i in 1:10) {
		"
		Test string.
		"x <- 1
	}
}


```

**Comment by MikhailArkhipov** [comment]
So the caret does not move

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/c0da9ce1d309332d3a115d8d5a74b0ee3e0cdf75

**Comment by Marchen** [comment]
Thanks!
