### ISSUE TITLE
Azure Server is not showing the computer stats red text when starting session

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#2987]
![image](https://cloud.githubusercontent.com/assets/8877/21788825/abea18b2-d685-11e6-9898-51f825734d8c.png)

**Comment by MikhailArkhipov** [comment]
Does `Session -> Host Info` show it?

**Comment by karthiknadig** [comment]
I seem to be able to get it:
![image](https://cloud.githubusercontent.com/assets/3840081/21788969/a26b8482-d686-11e6-9346-e6193fd48f67.png)

**Comment by MikhailArkhipov** [comment]
This may be async issue. `OnBrokerChanging` and `OnRSessionInteractive` may be fired from different threads so `OnRSessionInteractive` may come before `OnBrokerChanging`. There is a flag that prevents printing if you just reset REPL.

@AlexanderSher - is there a better way to track this? See `SessionInformationCommand`

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/47aea657ddcba93ecede67a555f4f01015b557be
