### ISSUE TITLE
Credentials dialog does not offer PIN 

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#2991]
![image](https://cloud.githubusercontent.com/assets/12820357/21827174/5d3d8694-d73f-11e6-9e80-e63a1c602250.png)

#2966 called for

![image](https://cloud.githubusercontent.com/assets/12820357/21827199/771d3488-d73f-11e6-9d6e-55b66b6fee2e.png)

**Comment by karthiknadig** [comment]
The prompt is updated to show device pin/smart card. However, the credential blob obtained from those will not work on other machines.

**Comment by MikhailArkhipov** [comment]
What does `CredUnPackAuthenticationBuffer` returns for the pin?

**Comment by MikhailArkhipov** [comment]
So we are switching pin off
