### ISSUE TITLE
Viewer cannot fill data

### ISSUE THREAD

**Issue by Victsz** [Microsoft/RTVS#2996]
Please briefly describe what you were doing that led to the issue, if applicable:
View(x) method not working, only display an empty R Data tab.
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

![image](https://cloud.githubusercontent.com/assets/8154646/21836809/e9a53eec-d802-11e6-8a67-4076da314a1c.png)

Additional information:
![image](https://cloud.githubusercontent.com/assets/8154646/21836849/1181285e-d803-11e6-95b6-0082d568ee25.png)

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21201.1213, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by Victsz** [comment]
Clean install and tried repair but not working.

**Comment by MikhailArkhipov** [comment]
Same as #2561, should be fixed in 0.6 (coming with the next update of VS 2017)

**Comment by Victsz** [comment]
Thank you for your response. I read that thread 2561 and found the behavior is slightly different on my machine where I failed to view the data by drag-and-drop or hide-and-show as  #2561 described.

**Comment by smortaz** [comment]
@Victsz - send an empty mail to rtvs-invite at microsoft . com to get on
the early access list, including 0.6 if youd like.

**Comment by MikhailArkhipov** [comment]
Can you please try https://aka.ms/rtvs-1.0rc1

**Comment by Victsz** [comment]
For 2015? I`m using 2017 VS15-RC4 and notice the data science module has been removed.

**Comment by smortaz** [comment]
The Data Science workload (R, Python, F#) has been removed from VS2017 but
will be back with hopefully update 2 around May.

Meanwhile, RTVS 1.0 RC1, RC2, and final will be available only for VS2015.
We apologize for that.

As to why, we could not finish some Localization & Accessibility work in
time.

So RTVS for all practical purposes is VS2015 only until around VS2017
update 2.

thx.

**Comment by MikhailArkhipov** [comment]
Consolidating into #3235
