### ISSUE TITLE
LoadLibrary failure for locally installed R package

### ISSUE THREAD

**Issue by CodEFouR** [Microsoft/RTVS#3001]
I have a package that is installed in my personal library and it loads correctly in RStudio. But it fails to load in RTVS. Please see the screenshot below:
![1](https://cloud.githubusercontent.com/assets/594939/21920194/7a77bb46-d99a-11e6-9167-8bef8399a5eb.png)
The error in Chinese above reads "LoadLibrary failure: Dynamic link library initialization failed". 
Environment:
1. Windows 10 X64 with latest update.
2. MSRO 3.3.2.
3. VS 2015 Community Edition with Update 3.
4. The problematic R package could be downloaded [here](http://www.myquant.cn/downloads/sdk/r/gmsdk_r_2.9.1_windows.zip).

**Comment by MikhailArkhipov** [comment]
The path to R.dll is set, dependencies appear to be OK

![image](https://cloud.githubusercontent.com/assets/12820357/21940200/16e3d15e-d978-11e6-9af5-7c3df6f47a5c.png)
![image](https://cloud.githubusercontent.com/assets/12820357/21940317/a3550a5e-d978-11e6-8b6c-1380b9fb9975.png)

**Comment by int19h** [comment]
It's not failing because of missing dependencies. It's failing because `DllMain` function of `gmsdk.dll` crashes during execution with an access violation (hence why the error message says "initialization routine fails").

**Comment by int19h** [comment]
Is the source code for this package available anywhere? Diagnosing this properly will require debugging it.

**Comment by CodEFouR** [comment]
Sorry I don't think the source is available...
