### ISSUE TITLE
VS progress bar hang when connecting to remote

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3004]
This usually happens to me the first time i'm connecting to a new server.

Click on connect, accept all message boxes and it eventually hangs in progress bar.  It's not able to transition to the UI thread when it wants to show the unsigned SSL warning message box.

Sometimes I can hit cancel, then it's able to continue (it shows the SSL warning).

**Comment by MikhailArkhipov** [comment]
We can try and p/invoke to Win32 MessageBox which doesn't need UI thread

**Comment by huguesv** [comment]
I have a devenv dump here: pytools\r\Bugs\Huguesjan13

**Comment by MikhailArkhipov** [comment]
Native message box appears to work if parent window is NULL (otherwise hangs inside Windows since VS is already modal I guess)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/acac40bbfcbfcac00ec963194b99f38cf46be091
