### ISSUE TITLE
Feature Request: Multi-file navigation

### ISSUE THREAD

**Issue by serkankalay** [Microsoft/RTVS#3006]
Hi RTVS team,

I have an R project that has 20+ R script files. When I need to debug some part of the code that refers to functions from other files, it becomes a pain to search the function name in the entire solution. Hence, I really think that this is an important feature. Besides, you encourage users to send a feedback on it [here](http://microsoft.github.io/RTVS-docs/code-navigation.html) :)

**Comment by MikhailArkhipov** [comment]
#1364 :-). closing this one as duplicate.
