### ISSUE TITLE
Some tests always fail in a group

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3009]
![image](https://cloud.githubusercontent.com/assets/12820357/22041485/e6de75bc-dcbb-11e6-9566-20c54cacee51.png)

![image](https://cloud.githubusercontent.com/assets/12820357/22041502/f9358e1c-dcbb-11e6-96da-1bf38c7d97cd.png)

Pass on rerun

**Comment by AlexanderSher** [comment]
Looks like they fail on timeout. Probably because `ConnectionManagerTest` exclusively acquires UI thread.
