### ISSUE TITLE
Way to navigate through history

### ISSUE THREAD

**Issue by crokusek2** [Microsoft/RTVS#3019]
Hi!  I hate to say copy but please have a look at the history feature in RStudio.  It is vastly superior to having a separate history window.

It works within the R Interactive Prompt window.  Just type a few letters of a prior command, then press Ctrl-UpArrow.  A live popup appears with the history in order **and filtered** to commands that begin with the typed letters.  The last item highlighted ready to select.

This is a mouse-free solution, about 2 keystrokes, and all the action is from within the interactive window.  

I can only get about 30% of the same feeling in MSVS, I press Ctrl-4, and then tab 5 times to get the search box.  Type some letters. Press tab again only to land on the first item instead of the last.  Thenplay with down arrow or end.  Select it by pressing return (and then can't see it run) and then press Ctrl-2 to hide the history.  The next time the Ctrl-4 is pressed the tab sequence changes because it remembers the position in the list. 

If this is already available please provide the hotkey.   Thanks for your consideration!

P.S. I see Alt-UpArrow would work great if it would simply match against any already-typed letters.

**Comment by smortaz** [comment]
+1.  i had filed a feature request to basically provide csh like history
recall.  sadly we didnt get to it & had to focus on other things, but i
agree with you fully about the importance of a good, repl-integrated
history feature.

**Comment by AlexanderSher** [comment]
@jflam , @smortaz , I need some kind of a spec to work on this feature, cause there are several related user requests and they all propose different ways of implementation

**Comment by smortaz** [comment]
I'll be happy to. But my bias is to go with the Matlab / csh style
