### ISSUE TITLE
RHost crashes when plotting

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3020]
Please briefly describe what you were doing that led to the issue, if applicable:

The RHost consistently crashed when plotting images, especially if I am plotting a few in quick succession. 
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

<img width="709" alt="rtvs-error" src="https://cloud.githubusercontent.com/assets/6426710/22151272/773748d8-deeb-11e6-8b3d-176785a51241.PNG">

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21019.1228, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.2

**Comment by huguesv** [comment]
This particular error should no longer occur in RTVS 0.6 (shipping very soon, already available via early access).

**Comment by Neil-Schneider** [comment]
This was resolved in RTVS 0.6.  Thanks!
