### ISSUE TITLE
Tab key produces errors in comment lines

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3021]
Please briefly describe what you were doing that led to the issue, if applicable:

When writing comments in the RTVS editor. (Either normal comments `#` or Roxygen comments `#'`) The following error popup occurs when you hit the `TAB` key when I would expect it to insert a tab character. 

(Or bonus functionality when `TAB` is pressed after `@` in a Roxygen head show autocomplete list of Roxygen tags.)
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

<img width="297" alt="rtvs-taberror" src="https://cloud.githubusercontent.com/assets/6426710/22154366/3b93b7f4-def9-11e6-84fa-6f37c802e667.PNG">

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21019.1228, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.2

**Comment by huguesv** [comment]
Thanks!  The error is already fixed for RTM: https://github.com/Microsoft/RTVS/issues/2613
You may want to file a feature request for `@` completions in roxygen comments, doesn't look like it's in our list (we have a few roxygen related features filed such as colorization, etc).
