### ISSUE TITLE
Auto Completion of Roxygen Tags

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3024]
When writing Roxygen documentation, it would be helpful to have autocompletion (tab completion) of Roxygen tags. 

Likely the trigger for this would be the `@` symbol in a roxygen comment line.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/f654cfd573f15c2fbf477393bfb6675359d9422e
