### ISSUE TITLE
Saying NO when prompted to install R client should mean NO

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3025]
Brand new VM, I installed RTVS, created my first project.
I get the following prompt:
![image](https://cloud.githubusercontent.com/assets/1696845/22159817/8e952458-def7-11e6-997c-520b31101be0.png)

I am 100% certain that I clicked No.

Next I see this:
![image](https://cloud.githubusercontent.com/assets/1696845/22159851/b592e39c-def7-11e6-927b-b8d0be940b49.png)

I thought this happened a week ago, but I figured I must have clicked Yes accidentally.  Now I know it wasn't my fault ;)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/6fbd45c85fbd9a94903268b8bebb8b1d5f56e7e4
