### ISSUE TITLE
Package member completion doesn't respect search order

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3035]
The following two snippets should produce different completions. This one:
```r
library(dplyr)
library(MASS)
select(
```
should show `select` from `MASS`, and this:
```r
library(MASS)
library(dplyr)
select(
```
should show `select` from `dplyr`. Basically whichever library is attached to the search path last, should get priority. In fact, `library` prints out the list of shadowed identifiers in this case, which we should be consistent with.

In practice, we show `select` from `MASS` in both of these cases. The only way to get it for `dplyr` is to not have `MASS` loaded at all.

**Comment by MikhailArkhipov** [comment]
Second case appears correct

![image](https://cloud.githubusercontent.com/assets/12820357/22168303/b1b29d5c-df20-11e6-9291-23916b3da2bd.png)

I think if you did 

```
library(MASS)
library(dplyr)
...
library(MASS)
```

you'd still get `select()` from dplyr. If you detach `dplyr` then `select` comes again from `MASS`

![image](https://cloud.githubusercontent.com/assets/12820357/22168358/010f5bd8-df21-11e6-8d62-7ffeaad7792b.png)

**Comment by int19h** [comment]
In my case, what I did was load the libraries via Package Manager. I don't know if that makes any difference, but it shouldn't. 

The other thing that maybe makes a difference is that I loaded MASS first, then tried completion, then loaded dplyr, then tried completion. Could it possibly have cached the result from the former?

**Comment by MikhailArkhipov** [comment]
Theoretically in remote case this might happen since session mutated event is processed asynchronously and hence for some [short] period of time index may still think select is coming from `MASS` until it fetches new data from the remote machine.

**Comment by MikhailArkhipov** [comment]
Haven't been able to repro so far.

**Comment by MikhailArkhipov** [comment]
Closing for now. Most probably the case when package/function cache is still being updated when intellisense was triggered so data came from a stale cache.
