### ISSUE TITLE
First connection pops up CRT installation on remote machine

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3038]
I was missing the VC++ redist, so I couldn't connect.  Log wasn't showing enough info.

**Comment by MikhailArkhipov** [comment]
We should package CRT in installer.

**Comment by MikhailArkhipov** [comment]
RTVS\lib\14.0 folder

**Comment by MikhailArkhipov** [comment]
I think this is related to missing 4.6. If 4.6 is installed, proper CRT should be there. Please try new build with #3032 fixed (22.4+).

**Comment by MikhailArkhipov** [comment]
Might be `ucrtbase.dll`

**Comment by karthiknadig** [comment]
There is a race condition that leads to missed logging. I have a fix for that, will send a PR in the morning.

**Comment by karthiknadig** [comment]
The VC runtime pop-up comes while loading RBLAS.dll. I have highlighted the dll that the loader was not able to find. It worked after installing VC++ 2015 redist. 
![image](https://cloud.githubusercontent.com/assets/3840081/22234385/addf791e-e1ac-11e6-881a-2a87abae8cef.png)

**Comment by MikhailArkhipov** [comment]
Let's just chain the installer then. Download VCRT installer, check it in in RTVS-pr and add it to the bundle like we do with the R Host.

**Comment by MikhailArkhipov** [comment]
Closing, letting MRO folks know.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/issues/3038
