### ISSUE TITLE
Rhost Assertion Failure: Masking Key

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3047]
Please briefly describe what you were doing that led to the issue, if applicable:
I had just completed a file search using grepwin and was returning to VS. This error message popped up once I had made VS the active window again. Please let me know if I can provide you with any additional information.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

<img width="340" alt="rtvs-maskingkey" src="https://cloud.githubusercontent.com/assets/6426710/22223155/d2bb4800-e187-11e6-8b7d-71937d789ac4.PNG">

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.10586.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21019.1228, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.2

**Comment by MikhailArkhipov** [comment]
Could you try https://aka.ms/rtvs-1.0rc1

**Comment by Neil-Schneider** [comment]
I have not seen this behavior again.
