### ISSUE TITLE
RTVS won't change help browser to external

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3050]
1. Go to RTools -> Options -> change "R Help Browser" to "external"
2. Restart VS+RTVS
3. Open REPL
4. Type `?lm`

The help still shows up in an internal browser pane.

**Comment by MikhailArkhipov** [comment]
The issue is not in options or help code but rather in persistence of settings.

**Comment by MikhailArkhipov** [comment]
Settings loading assigns stored connections, and connection manager saves connections when they are getting assigned and that causes semi-loaded settings to be saved back overwriting stored values with initial (default) settings.

```
>	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.Options.R.RToolsSettingsImplementation.Connections.set(Microsoft.R.Components.ConnectionManager.ConnectionInfo[] value) Line 114	C#
 	[External Code]	
 	Microsoft.R.Common.Core.dll!Microsoft.Common.Core.Extensions.SettingsExtensions.LoadPropertyValues(Microsoft.Common.Core.Shell.ISettingsStorage settings, object o) Line 14	C#
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.Options.R.RToolsSettingsImplementation.LoadSettings() Line 201	C#
 	Microsoft.VisualStudio.R.Package.dll!Microsoft.VisualStudio.R.Package.Shell.VsAppShell.Initialize() Line 93	C#

```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/987fbe62be3353d269c2cc507cec1d32a078d4de
