### ISSUE TITLE
Can't open pdf when using internal help browser

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3051]
This might actually be an interaction with Adobe Acrobat Reader.

R packages often have vignettes which are pdf files. Trying to open these from the internal help fails. An example is the Matrix package:

    library(Matrix)
    ?Matrix

In the internal help, navigate to the main Matrix help page, then go to the vignettes link (2nd from top). Click on any of the pdf links. The help pane goes blank, and when I try to go back (click on the Back button), VS spins its wheels for a few seconds. Acrobat Reader also starts up in the background, and then disappears.

**Comment by MikhailArkhipov** [comment]
By design. internal browser is IE and has limitations. For complex content external browser is the only option.

**Comment by Hong-Revo** [comment]
Would it be possible to display an alert at least, if this happens? Or is it unrelated to RTVS?

**Comment by MikhailArkhipov** [comment]
I have simple solution

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/1e205ba4476f9703a1e00bc5c2c17907255b7e50
