### ISSUE TITLE
REPL becomes unusable after inputting malformed text

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3052]
At the prompt, type:

    f("a")")

Press Enter. REPL displays continuation prompt, but pressing Enter and Esc do nothing, and the inputted text can't be edited.

![image](https://cloud.githubusercontent.com/assets/11328890/22246310/587bc7c0-e288-11e6-9268-e93750e235a7.png)

**Comment by Hong-Revo** [comment]
Actually, on testing this some more, typing `"` (ie, closing the string) fixes this. I think pressing Esc should immediately break back to the prompt, though; that's what rgui.exe does.

**Comment by MikhailArkhipov** [comment]
`ESC`: #1066. REPL appears alive (enter works). If I do `Up Arrow` it bring up original expression from the history and it can be edited (or executed which brings back `>`)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/6dfa10c44d8fd01bd13400c9188d3bc631b9099e
