### ISSUE TITLE
Separate platform-specific code into conditionals

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3060]

**Comment by karthiknadig** [comment]
Same as #2458

**Comment by MikhailArkhipov** [comment]
No, this is about R Host (C++) rather than Microsoft.Common.Core

**Comment by int19h** [comment]
I don't think we need a separate binary for this - it'll just mean more hassle when building and deploying it.

#ifdef should work fine for one-liners (like when you just need to call a single function that's currently Win32, but there's a POSIX equivalent). For stuff that's platform-dependent and complicated, like e.g. event loop or detouring, we can just have a header file define the common interface, and platform-specific implementations in .cpp files that are entirely conditionally compiled. Kinda like R does that.

**Comment by MikhailArkhipov** [comment]
Yes, agreed. We discussed this with @karthiknadig

**Comment by karthiknadig** [comment]
https://github.com/Microsoft/R-Host/commit/76480debd135a08f8f6c077c39d7f6f96114811b
