### ISSUE TITLE
The play button does not attach & source debugger

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#3067]
may be a regression per pavel.

normal setting of bkpoint, attaching & sourcing works and bkpoints are hit

1.0 candidate, VS2015

**Comment by int19h** [comment]
To be more specific, the Start Debugging button was behaving as if there is no active project, or the project is not runnable. Even though there is a project with a startup file etc.

**Comment by int19h** [comment]
Can't repro this on Dev15.

**Comment by int19h** [comment]
Can you share the project file (just post the contents as a comment, it should be short)? Does it come from some older (esp. particularly older) version of RTVS?

I can't repro it on new projects. But for Start Debugging to light up, the project file (.rxproj) needs to have certain things in it. If it's a project from before the time where we first added this feature, it won't have the requisite stuff in it.

**Comment by int19h** [comment]
@smortaz ping.

**Comment by smortaz** [comment]
yes, it's definitely an older project.

sadly i dont know which was as i have 84.

**Comment by int19h** [comment]
Then it's almost certainly for the reason described above. If you hit it again, ping me and I can double-check for that project.

**Comment by smortaz** [comment]
thumbs up.
