### ISSUE TITLE
Packages loaded on remote machines which popup UI will cause RTVS to hang

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3069]
An example of this is the `rattle` package.

If you do this:

*> library(rattle)

You will get the screenshot below, where the REPL is hung. The reason why is that during load of this package the first time, it tries to popup a dialog box to ask the user whether they want to install GTK+ on their local machine.

![image](https://cloud.githubusercontent.com/assets/8877/22351525/46006e70-e3cd-11e6-9b41-7df999cbc68a.png)

**Comment by jflam** [comment]
We should consider starting R in non-interactive mode to work around this issue.

**Comment by int19h** [comment]
Non-interactive mode affects a lot of other stuff, though, even some subtle REPL behavior, and I think history?

RGui and RS both run in interactive mode, so that's what we've always used. Need to do some thorough testing to make sure everything still works if we switch.

Unrelated question: did Interrupt R button work to get you out of this state?

**Comment by jflam** [comment]
Nope, Interrupt R fails to get out of this state; it's still deadlocked. 

What this means is that if a user ever encounters this, they are guaranteed to lose their session. 
Also, in the case of the rattle library (and who knows what other libraries); this means that they will never be able to install the GTK+ downstream library. The workaround presumably is to get an admin to install globally on the machine so they can click the dialog in a GUI.

The larger problem is that we don't know what other kinds of popping of UI behavior exists.

BTW, how does RStudio Server deal with this? They clearly have exactly the same problem as we do.

**Comment by int19h** [comment]
Ultimately, since R exposes Tk as part of its standard library, any library can pop any kind of UI at any time.

**Comment by MikhailArkhipov** [comment]
I think we could detour `CreateWindow`, drop message into REPL that the package is not supported in remote and bail.

**Comment by karthiknadig** [comment]
@AlexanderSher Has this regressed?

**Comment by AlexanderSher** [comment]
No, I don't know why it became opened again ¯\_(ツ)_/¯

**Comment by MikhailArkhipov** [comment]
`AlexanderSher reopened this 2 hours ago`

**Comment by AlexanderSher** [comment]
No idea. I don't even know anything about this bug.

**Comment by karthiknadig** [comment]
Figured it out:
![image](https://cloud.githubusercontent.com/assets/3840081/22906907/964cf790-f1fb-11e6-960e-000dca693acc.png)
