### ISSUE TITLE
Getting the class of an object after a failed View() hangs the REPL

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3076]
Following on from my comment in https://github.com/Microsoft/RTVS/issues/3075

    tib <- tibble::as_tibble(mtcars)
    View(tib)
    class(tib)

Can't stop execution or reset the R session.

**Comment by int19h** [comment]
It's an effect of tibble's weird behavior when using `lapply`.

What we do in this case is fetch the columns one by one using `tib[,i]`, and then process the element in each column with `lapply`. The assumption is that if you index using `[,i]`, the returned value is a vector, or at least one-dimensional - so `lapply` goes element by element. This is the case for matrices and dataframes, e.g.:
```
> col <- mtcars[,1]
> typeof(col)
[1] "double"
> print(col)
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3
[25] 19.2 27.3 26.0 30.4 15.8 19.7 15.0 21.4
> length(col)
[1] 32
> lapply(col, function(x) print(x))
[1] 21
[1] 21
[1] 22.8
[1] 21.4
...
```
However, for tibbles, when you index using `[,i]`, you get back another tibble! i.e. the data is still 2D. And then when `lapply` is executed on it, it iterates over the columns in the resulting tibble (of which there's just one, so there's only one iteration happening). And that entire column is then processed as a single element:
```
> col <- tib[,1]
> typeof(col)
[1] "list"
> print(col)
# A tibble: 32 × 1
     mpg
   <dbl>
1   21.0
2   21.0
3   22.8
4   21.4
5   18.7
6   18.1
7   14.3
8   24.4
9   22.8
10  19.2
# ... with 22 more rows
> length(col)
[1] 1
> lapply(col, function(x) print(x))
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3
[25] 19.2 27.3 26.0 30.4 15.8 19.7 15.0 21.4
$mpg
 [1] 21.0 21.0 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3
[25] 19.2 27.3 26.0 30.4 15.8 19.7 15.0 21.4
```
I would say that the weirdest thing here is that `length(tib[,1])` will always give you 1, not the number of elements in a column. 

I don't know if it's a bug, or intended behavior. R itself doesn't really set any particular semantics for indexers, so the convention established by matrix and data.frame - that indexing with one fewer index produces an object with one fewer dimension - is technically just that, a convention. But it's still weird that it's broken like that.

That said, it looks like we can work around in a generic fashion by applying `as.list()` to the column before using `lapply`. 

The other, unrelated bug here is that an error in grid code brings the grid viewer and REPL both into an unusable state. This seems to be a generic error handling issue in grid viewer code.

**Comment by int19h** [comment]
Reading the docs for tibble confirms that this behavior is by design, so we need to adapt to it as described above.

**Comment by Hong-Revo** [comment]
lol, the tibble strikes again!

The idea behind tibbles is that the semantics for column extraction via `[` with data frames is inconsistent. Sometimes it returns a vector; sometimes it returns another data frame. This leads to error-prone code, where you expect one but get the other. I've been bitten by this a few times, although going in the opposite direction: you write something like `df[, x]` expecting that you get another df, but if `x` is a scalar, you get a vector instead.

Since `[` on a tibble always returns another tibble, this should lead to fewer bugs in the long run. It's the result of Hadley trying to bring ideas from software engineering to the R community. Whether this is the best way he could have done it is the subject of debate.

If you want a single column out of a tibble, `[[` will do it: `tib[[i]]` should always be the same as `df[[i]]`, assuming `i` is a scalar.

**Comment by int19h** [comment]
The problem is that what we really want is "a single column out of that 2D thing, whatever it is, and preferably without making too many copies of it" (for perf reasons - i.e. copying the whole thing is really bad, copying just one column is slightly better, no copies is perfect). This is so that it can handle as many different types as possible, preferably in such a way that we don't need to special-case anything (and later update it as new versions of packages get released etc).

This is what we do right now:

https://github.com/Microsoft/RTVS/blob/7d25458852ebfa77269c4598eba7e409d49f9de1/src/Host/Client/Impl/rtvs/R/grid.R#L31

When you scroll it around, we invoke it like e.g. `rtvs:::grid_data(tib, 1:32, 1:11, )` (where the arguments are corresponding to your viewport).

So `[[i]]` will do the right thing here for tibbles and dataframes, but not for matrices (where it'll return the element with this index, rather than the column).

It looks like we can do `[,i]` to obtain the column regardless of the type still, but we need to make sure that the result is 1D. So we can check `dim()`, and if it's not 1, then apply `as.list`. For matrices and dataframes, it'll do exactly the same as what we do now. For tibbles and types with similar semantics, it'll create a copy of the column, but at least it'll handle it properly from there.

**Comment by Hong-Revo** [comment]
Hm, that is tricky. Especially the no-copying part.

Here's one way that you could do it. Split out the body of the `lapply` into a separate function. Then check if the object is a list, and then use list- or matrix-style indexing.

    format_col <- function(col)
    {
        if (is.atomic(col)) {
            # For atomic vectors, we want to apply format() to the whole thing at once,
            # so that it can determine the number of decimal places accordingly - e.g.
            # for c(1.5, 2, 3.04), we want the output to be "1.50 2.00 3.04".
            col <- format(col, trim = TRUE, justify = "none")
        }

        lapply(col, function(s) {
            # If it's already a string, use as is (this also will be the case if format was already applied above).
            # If it's something else, try format() on this individual value.
            # If that fails (e.g. for externalptr), try str().
            # If that also fails, give up and display the value as <?>.
            if (!is.character(s) || length(s) != 1) {
                s <- tryCatch({
                    # Preserve the behavior of format() for list elements, documented as follows:
                    # If x is a list, the result is a character vector obtained by applying format.default(x, ...)
                    # to each element of the list (after unlisting elements which are themselves lists), and then
                    # collapsing the result for each element with paste(collapse = ", ").
                    paste(format.default(unlist(s), trim = TRUE, justify = "none"), collapse = ', ')
                }, error = function(e) {
                    tryCatch({
                        make_repr_str(max_length = 100)(s) 
                    }, error = function(e) {
                        "<?>"
                    })
                })
            }

            if (is.na(s)) { 'NA' }
            else if (nchar(s) <= max_length) { s }
            else { paste0(substr(s, 1, max_length), '...', collapse = '') }
        })
    }

    data <- c(if(is.list(x)) {
        lapply(x, format_col)
    }
    else {
        apply(x, 2, format_col)
    }, recursive=TRUE)

This replaces the assignment at line 54 onwards. Caveat: untested.

**Comment by Hong-Revo** [comment]
How will your current code handle a matrix that's also a list? Eg

    m <- numeric(9)
    l <- as.list(m)
    dim(l) <- c(3, 3)
    l[[2, 2]] <- "foo"

**Comment by int19h** [comment]
The approach seems to be working fine with 2D lists - you can do `l[,1]`, and you get back a (1D) list for the first column.

**Comment by int19h** [comment]
It looks like using `apply` still causes a copy to be made if input is not a vector (internally, it'll try to coerce it to a vector in this case, which will create a copy for tibble). 

For the time being, I'll just directly coerce to list. This is not ideal perf-wise, but we have already sliced the input data to the viewport, so this should copy at most the number of elements that are visible.
