### ISSUE TITLE
Plot Size

### ISSUE THREAD

**Issue by nimamaleki** [Microsoft/RTVS#3081]
I think that resizing the plot windows in order to resize the plot itself is not enough.
There had been several situations in which I needed to save or copy my plot with dimensions like (2900:450). My display is much smaller than that, and I found no way to change my plot to an arbitrary size. In RStudio however, it is easily possible using the "save plot as image" button.
![image](https://cloud.githubusercontent.com/assets/25179687/22399391/c395eeda-e59b-11e6-9e4e-d9d3190adf83.png)

**Comment by MikhailArkhipov** [comment]
#1083

**Comment by MikhailArkhipov** [comment]
#1083 added the functionality.
