### ISSUE TITLE
Running R Script as Executable 

### ISSUE THREAD

**Issue by chandu406** [Microsoft/RTVS#3094]
Hi , 

Im new to RTVS . Im trying to run the R Script with the windows application . please help me in resolving this . Actually when i press one button in windows application this r script need to executed automatically

**Comment by chandu406** [comment]
I mean to say is there any way to run the R Script as like as exe ..

**Comment by MikhailArkhipov** [comment]
Have a look here https://github.com/MikhailArkhipov/RTVS-cs
