### ISSUE TITLE
RHost: MAKEFILE should support Debian

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3113]

**Comment by smortaz** [comment]
are these the linuxes that MRS supports?

**Comment by karthiknadig** [comment]
I added this because cran r supports it. We can decide on which ones we support. https://cran.r-project.org/bin/linux/debian/

**Comment by smortaz** [comment]
ok.  priority wise, i'd start w MRS support and within that in popularity
order.

**Comment by int19h** [comment]
This is more of a list of things to test. In practice, it should build and run on any Linux system that has the requisite dependencies. There aren't really any substantial differences between distros that would prevent it from doing so.
