### ISSUE TITLE
Exception encountered

### ISSUE THREAD

**Issue by DolanDack** [Microsoft/RTVS#3114]
I installed R tools for visual studio and when I launch the VS 2015 I get this message: 
An exception has been encountered this may be caused by an extension. 

When I dismiss the error and try to launch an R project, then I receive this:
Invalid pointer (Exception from HRESULT 0x80004003 (E_POINTER))

I have attached the VS logfile, the lines of interest (I think they are of interest) contain the words 'R TOOLS FOR VISUAL STUDIO' and 
'Extension will not be loaded because an extension with the same ID'

Any suggestions? Thanks
[ActivityLog.txt](https://github.com/Microsoft/RTVS/files/751274/ActivityLog.txt)

**Comment by MikhailArkhipov** [comment]
Can you please send us logs via R Tools | Feedback | Frown?

**Comment by DolanDack** [comment]
I can't unfortunately, the R Tools toolbar is unresponsive. I have updated VS 2015 and followed the installation guide to the letter. When I uninstall R Tools everything works smoothly again.

**Comment by MikhailArkhipov** [comment]
Could you try https://aka.ms/rtvs-1.0rc1
