### ISSUE TITLE
Accessibility test pass: Grid viewer

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3134]
High contrast white and black
Large fonts
Keyboard access (sorting, navigation)
Screen reader (reads row and column names and the cell content)

**Comment by int19h** [comment]
It is not high contrast aware currently. Grid lines and text are always black, so on black background nothing is visible.

**Comment by MikhailArkhipov** [comment]
I thought it works in dark theme

**Comment by int19h** [comment]
I mean the high contrast Windows theme:

![image](https://cloud.githubusercontent.com/assets/1175142/22714733/a8b1c3ec-ed42-11e6-8ee4-e143b1eff03a.png)

**Comment by int19h** [comment]
This is a 1000x1000 matrix. You can see that it's actually loaded by the scrollbars. But the view is all black, I'm assuming because it's black text/grid on black background:

![image](https://cloud.githubusercontent.com/assets/1175142/22714760/ce4ce9ec-ed42-11e6-9e8c-3272fe7b4210.png)

**Comment by huguesv** [comment]
Looks ok on Win 10, high contrast mode activated via ALT+LEFT SHIFT+PRINT SCREEN
![image](https://cloud.githubusercontent.com/assets/1696845/22715561/445da7cc-ed46-11e6-8e2c-e2898cdb6505.png)

**Comment by MikhailArkhipov** [comment]
#3143 - I can't repro on Win10 and styling in XAML seem to be default/VS.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/issues/3173 primarily. High contrast should be working now.
