### ISSUE TITLE
Debug mode: After executing code in command window the cursor (and fokus) jumps to breakpoint in editor

### ISSUE THREAD

**Issue by enicklas** [Microsoft/RTVS#3135]
When I execute a command in the R Interactive window while debugging a script, the cursor (and the focus) jump to the break point in the editor window. This is inconvenient when trying to interactively debug an issue in the command window.

I am using 0.6.30105.2202

**Comment by MikhailArkhipov** [comment]
I can'r repro with post 0.6 in a basic scenario (i.e. define a function, set bp in body, call function from REPL). Does it repro always or just in some cases?

**Comment by int19h** [comment]
Also, which VS version is this?

**Comment by enicklas** [comment]
I am using Visual Studio 2015 Update 3 Community Edition (14.0.25431.01)

I can reproduce this behaviour on a current Azure Data Science VM (with the same version of VS and RTVS 0.5) with the following steps:

- create a simple function in the editor and call this function later on in the script
- set a break point in the function
- attach the debugger
- source the script with echo (or without)
- it stops at the breakpoint
- execute something in the R interactive windows
- the focus jumps to the breakpoint in the editor

I hope this helps

**Comment by enicklas** [comment]
By the way, I am using R Server 9.0.1 as the R runtime, in case this is relevant

**Comment by MikhailArkhipov** [comment]
Can you try https://aka.ms/rtvs-1.0rc1 please? Thanks

**Comment by enicklas** [comment]
I could not reproduce the bug with 1.0rc1 and will close the issue now. Thanks a lot for fixing this!
