### ISSUE TITLE
Move message text from R code to C#

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3140]
So we can localize them in a regular way. Perhaps pass some form of ID like `#125` similarly to what VS SDK does? Or more readable `#message_id` similar to `Resources.message_id`

**Comment by int19h** [comment]
I'd rather have meaningful names rather than numeric IDs - easier to track (and we could map them straight to resource string names)

Some kind of prefixed naming convention maybe? Like if it starts with @, it's a resource string name rather than a literal string to display.

**Comment by MikhailArkhipov** [comment]
Bumping up priority since we'll need it before we'll send resources for localization.

**Comment by int19h** [comment]
On it.

**Comment by MikhailArkhipov** [comment]
Not super pressing, 1.0 is more important but POR is to get files to loc some time end of this or early next week, pending PTVS readiness.
