### ISSUE TITLE
Grid viewer does not work on high contrast

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3143]
At least in HC black. #3134 for details

**Comment by MikhailArkhipov** [comment]
I can't repro on Win10 and styling in XAML seem to be default/VS.

**Comment by int19h** [comment]
My repro was on Win7.

**Comment by MikhailArkhipov** [comment]
OK, most probably fix for #3145 will resolve this one as well unless this is something with WPF on Win7. In any case, it is not very high priority since things appears OK on Win10.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/953ce796947f6a11f334ab12f49cefbb30b382fa, reopen if there are issues
