### ISSUE TITLE
Text boxes in 'Import Data from URL' dialog have odd background in HC

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3145]
![image](https://cloud.githubusercontent.com/assets/12820357/22716856/adb3507c-ed4c-11e6-8206-993dc65a8c5b.png)

**Comment by MikhailArkhipov** [comment]
Also search in the package manager as well

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/953ce796947f6a11f334ab12f49cefbb30b382fa

**Comment by jflam** [comment]
I still see this odd color (is this expected) in the build:

![image](https://cloud.githubusercontent.com/assets/8877/22951818/6e0058bc-f2bf-11e6-908b-321946f30d49.png)

**Comment by MikhailArkhipov** [comment]
Yes it is expected. Click in, say, 'Search' field in a toolwindow. Or do `Ctrl+F`. This is default VS 'focused edit field` color.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/22952452/fabc5e98-f2c1-11e6-81ec-9aa348bcbca0.png)
