### ISSUE TITLE
Keyboard navigation in history window is difficult

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3148]
![image](https://cloud.githubusercontent.com/assets/12820357/22717469/249ec47a-ed50-11e6-932d-191ae12abb1a.png)

TAB curculates through toolbar buttons. If I set focus with the mouse to the window, Up/Down work and `Ctrl+Up` take me back to the toolbar. However, `Ctrl+Down` does not to take focus into the window content.

It is unclear how to get inside the window without mouse

**Comment by MikhailArkhipov** [comment]
Same problem in REPL

**Comment by AlexanderSher** [comment]
How do we want it to work? TAB switch from toolbar to the text view?

**Comment by MikhailArkhipov** [comment]
Since Ctrl+Up takes from content to the toolbar I guess Ctrl+Down should take user to the content

**Comment by MikhailArkhipov** [comment]
C# interactive has no means either BTW

**Comment by MikhailArkhipov** [comment]
I can look at this if you haven't started
