### ISSUE TITLE
can't view the table

### ISSUE THREAD

**Issue by GreenEric** [Microsoft/RTVS#3150]
was trying to move project to RTVS, but just can't find the most important function - view the table in detail.
![baidushurufa_2017-2-8_16-18-1](https://cloud.githubusercontent.com/assets/24875340/22729916/b36b9e60-ee1f-11e6-93ac-99dbb28825ed.png)
Pls help.
Greeneric001@126.com

**Comment by MikhailArkhipov** [comment]
#2996

**Comment by MikhailArkhipov** [comment]
Could you try https://aka.ms/rtvs-1.0rc1

**Comment by MikhailArkhipov** [comment]
Closing for #3235
