### ISSUE TITLE
.Net Standard 2.0 Dependencies

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3158]
This issue contains a list of types that have to be revised when .Net Standard 2.0 is published. NETSTANDARD1_6 conditional symbol is used for `#if` directive. 
- `Microsoft.Common.Core.Threading.BackgroundThreadAwaiter` - `ThreadPool.UnsafeQueueUserWorkItem` doesn't exist
- `Microsoft.Common.Core.Security.Credentials` - `NetworkCredential` doesn't have a ctor that accepts secure string
- `Microsoft.Common.Core.ExceptionExtensions` - `StackOverflowException`, `ThreadAbortException` and `AccessViolationException` don't exist 
- `Microsoft.Common.Core.Logging.FileLogWriter` - `AppDomain.CurrentDomain` is excluded from .Net Standard build
- `Microsoft.Common.Core.IO.IUserProfileNamedPipeFactory` - `NamedPipeServerStream.MaxAllowedServerInstances` doesn't exist
- `Microsoft.Common.Core.TaskUtilities` - `Thread.IsThreadPoolThread` doesn't exist

**Comment by AlexanderSher** [comment]
- `Microsoft.Languages.Core.Text.CharacterStream` - `ExcludeFromCodeCoverage` is missing.
- `Microsoft.Languages.Core.Text.TextChangeEventArgs` - `ExcludeFromCodeCoverage` is missing.
- `Microsoft.Languages.Core.Text.TextRange` - `ExcludeFromCodeCoverage` is missing.

**Comment by MikhailArkhipov** [comment]
Yeah, I was going to remove these attributes. In fact, I have a branch where it is sort of done.

**Comment by AlexanderSher** [comment]
So I can just remove them as well?

**Comment by MikhailArkhipov** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
Folding into #4086
