### ISSUE TITLE
Automatic space insertion when copy code between files.

### ISSUE THREAD

**Issue by Masutani** [Microsoft/RTVS#3160]
I experienced unpredictable space insertion like,
original : "hoge"
copied : " hoge "
Is this VS editor's bug or RTVS ?

**Comment by MikhailArkhipov** [comment]
Are spaces appear in inapproriate places or is it simple reformatting? On paste editor performs automatic formatting. It is controlled in editor options

![image](https://cloud.githubusercontent.com/assets/12820357/22796060/d1591798-eead-11e6-9089-2a7555cb1b32.png)

**Comment by Masutani** [comment]
I tried some settings, Turning off "Format on paste" works for this problem. Thank you !
