### ISSUE TITLE
Dismissing signature help with ESC adds line break in REPL

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3163]
Since it also propagates to REPL as 'Cancel'. See also #1066 and #3052. Most probably side effect of https://github.com/Microsoft/RTVS/commit/6dfa10c44d8fd01bd13400c9188d3bc631b9099e

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a5c501548e392c0352a850cd2ddcd00f3f4968dd

**Comment by jflam** [comment]
I still see this issue if I hit ESC on an empty line in the REPL - a blank line is inserted.

**Comment by MikhailArkhipov** [comment]
By design. Same as in RGui and RStudio. The bug was NOT to do it when user dismissed intellisense list or signature help.
