### ISSUE TITLE
CancelAll_CancellableHangingLoop test fails

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3168]

**Comment by AlexanderSher** [comment]
Related to #3096 - test has no way to specify that session is interactive except for the session name which is auto-generated in many test cases.

**Comment by karthiknadig** [comment]
There is `--rhost-interactive` command line argument. May be you can use that?

**Comment by MikhailArkhipov** [comment]
Looks like we need a parameter to `RSession` ctor

**Comment by AlexanderSher** [comment]
No, it should be in `RHostStartupInfo`, but the idea is the same.

**Comment by MikhailArkhipov** [comment]
But when creating `RSession` with 'new' how do I specify I want interactive?

**Comment by AlexanderSher** [comment]
From `RInteractiveEvaluator`:

```
var startupInfo = new RHostStartupInfo(_settings.CranMirror, _settings.WorkingDirectory, _settings.RCodePage, _terminalWidth, !isResetting, useRHostCommandLineArguments:true, isInteractive:true);
await Session.EnsureHostStartedAsync(startupInfo, new RSessionCallback(CurrentWindow, Session, _settings, _coreShell, new FileSystem()));
```

**Comment by MikhailArkhipov** [comment]
In nuget API I do

```
var bc = new LocalBrokerClient(name, ci, new CoreServices(), new NullConsole());
new RSession(0, name, bc, new NullLock(), () => { })
```

I need to tell if it is should be interactive or not. Currently `RSessionApiTest.OutputAsync` is broken too since host dies on error output (I guess it is started as non-interactive)?

**Comment by AlexanderSher** [comment]
You have `StartHostAsync` method for it.
I can add this as a parameter to this method with default value `true`, or just make it interactive all the time.
