### ISSUE TITLE
Feature request: highlight other occurrences of the word under the cursor

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3180]
This is something that other languages supported by VS have, eg Javascript:

![image](https://cloud.githubusercontent.com/assets/11328890/22855470/2f36da2a-f0d5-11e6-9a9f-f65291dc4090.png)

**Comment by MikhailArkhipov** [comment]
#1059

**Comment by MikhailArkhipov** [comment]
Folding into #1059.
