### ISSUE TITLE
Shortcuts don't show up in menus RTools > Windows 

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3186]
![image](https://cloud.githubusercontent.com/assets/3840081/22950577/ee830368-f2ba-11e6-993a-8b74a0877fdc.png)

Ignore High-contrast.

**Comment by MikhailArkhipov** [comment]
We only bind `Ctrl+2` in global. But I think we should bind `Workspaces` in global too.

**Comment by smortaz** [comment]
in mtg, cant participate.  do people switch between R versions that
frequently or mainly when new versions show up?

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/79e4ef08a4dfc226d3f293f8ebd813eca2756d76
