### ISSUE TITLE
Narrator in plot history reads class names

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3188]
Issue a few plot commands.
Open plot history and click on a plot

It will read Microsoft.VisualStudio...

It's hard to describe the plot, maybe we can have it mention the pixel width and height. In any case, don't have it say the name of the view model class.

**Comment by MikhailArkhipov** [comment]
May not be high pri since narrator is more or less useless in plots

**Comment by MikhailArkhipov** [comment]
Override ToString() on the model and narrator will read it

**Comment by AlexanderSher** [comment]
> Open plot history and click on a plot

Can we get to the plot using keyboard?

**Comment by huguesv** [comment]
Yes the keyboard works well.

**Comment by AlexanderSher** [comment]
PR was submitted to Release/1_0
