### ISSUE TITLE
High contrast in package manager has invisible text

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3189]
Using `High Contrast #1` theme on Windows 10.

The mouse hover text is white on white.

![image](https://cloud.githubusercontent.com/assets/1696845/22951034/96febc2a-f2bc-11e6-8565-fb3a29e221ea.png)

**Comment by huguesv** [comment]
For comparison, using the same theme:
![image](https://cloud.githubusercontent.com/assets/1696845/22951324/9f599baa-f2bd-11e6-9e89-aff1362e0726.png)

**Comment by MikhailArkhipov** [comment]
Looks like it is package manager, not plot manager

**Comment by MikhailArkhipov** [comment]
This actually works for me. I think it maybe same as #3144 which reproes ONLY if window is visible and theme is switched on the fly.

![image](https://cloud.githubusercontent.com/assets/12820357/23187595/46d521e2-f840-11e6-87b7-1b27137d9d81.png)

**Comment by MikhailArkhipov** [comment]
Actually is weird. If I switch theme while VS is up, I get good experience as above. BUT #3144 reproes. If I restart VS #3144 goes away, but this one reproes.

![image](https://cloud.githubusercontent.com/assets/12820357/23187770/eec14d54-f840-11e6-843c-e51e14b95550.png)

**Comment by MikhailArkhipov** [comment]
Flipping back regular theme yields

![image](https://cloud.githubusercontent.com/assets/12820357/23187857/45b841b2-f841-11e6-90fe-2118df957bd4.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a068c51d930f91f4c1b5d277c46d8faa2478803f
