### ISSUE TITLE
Download location dosn't match the most recent build bits

### ISSUE THREAD

**Issue by ralphke** [Microsoft/RTVS#3197]
When checking for Updates in VStudio 2015 R-Tools 0.5 the landing page is http://microsoft.github.io/RTVS-docs/checkforupdate.html which stats that build 1.0.30202.2203  is recommended. When clicking on the download link https://aka.ms/rtvs-current this is redirected to the old binary of the 0.5 build from RTVS_2016-10-08.1.exe . Is this by intention or an accident?

**Comment by smortaz** [comment]
No, ralph is right.  rtvs-current (public) is still pointing to an old
version.

we'll update it in a couple of days to point to 1.0 RC1.

**Comment by impaktbuilder** [comment]
If you cannot update the link in a timely manner, is it possible to share an alternate Url to the download location?

**Comment by MikhailArkhipov** [comment]
Try https://aka.ms/rtvs-1.0rc1

**Comment by impaktbuilder** [comment]
Thanks for the speedy reply!
