### ISSUE TITLE
large print operations lock up UI

### ISSUE THREAD

**Issue by mkoohafkan** [Microsoft/RTVS#3198]
Probably related #3000 

When printing a large object (e.g. a large dataframe) the standard R console typically truncates the number of lines that printed. RTools does this too, but it seems like it processes every line that *could* be printed before truncating according to the R console. Any chance that Rtools can do this truncation *before* processing every line? Alternatively, is there a way to cancel the operation?

example code:

```
seq(1, 1e4)
```

You can see the line counter in the status bar chugging along as it prepares to print to the console.

**Comment by int19h** [comment]
We don't process it in a way that could deviate from how R does it - we just hook up to R printing callbacks, and print when it tells us to. So it's likely that this is just another manifestation of #3000, as you pointed out - i.e. it's just that there are so many individual print operations (R invokes the print callback once per *element*, not once per line), that the result is so slow in the absence of batching.
