### ISSUE TITLE
Intellisense sometimes shows packages that may not be available

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3200]
This happens when you switch between sessions. 
![image](https://cloud.githubusercontent.com/assets/3840081/23036250/f64c9c58-f436-11e6-839e-51b286c9fcc3.png)

**Comment by MikhailArkhipov** [comment]
Essentially #3194

**Comment by MikhailArkhipov** [comment]
Got it fixed, but need more testing and figure out automated test

**Comment by MikhailArkhipov** [comment]
Folding into #3194
