### ISSUE TITLE
[R] mrsdeploy library not found on microsoft visual studio

### ISSUE THREAD

**Issue by peerapong123** [Microsoft/RTVS#3206]
I'm newbie about R language, I try to use library 'mrsdeploy' for connect to Microsoft R server but when I deploy the library , it will show error 'no package called mrsdeploy' . How can I call mrsedploy library in RTVS ? However I enclose picture of the problem in this question (https://i.stack.imgur.com/Tivlv.png) and server environment in this detail below.

Server side:
Microsoft R server & R open version : 8.0.5
Microsoft R server installed on Redhat 7.3

Thank you in advance

**Comment by Hong-Revo** [comment]
That package is part of R Server 9, not 8.0.5.
