### ISSUE TITLE
No workspaces window

### ISSUE THREAD

**Issue by rdilla** [Microsoft/RTVS#3211]
I cannot see the workspaces window within Visual Studio 2015 update 3. 

Workspaces does not appear under R Tools/Windows either.

Therefore, I cannot connect to my remote server.

Your help would be much appreciated.

Thanks.

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.1.7601 Service Pack 1

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=0.5.21008.800, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

R Install path:
    C:\Program Files\Microsoft\MRO-3.3.2\

**Comment by smortaz** [comment]
hi please try https://aka.ms/rtvs-1.0rc1

workspace window started w version 0.6
