### ISSUE TITLE
RHost runs continuously in the background

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3214]
After an extended period of time, including inactivity, one of the RHost.exe task begins to run continuously in the background. (Utilizing ~1-1.5CPUs) From the discussion on #3209, this is probably the intellisense. I can kill the process from the task manager and I do not loss the interactive session. I have to kill this process when running multi-thread scripts to free up CPU utilization.

RTVS: 1.0-rc1
MRO: 3.3.2

**Comment by karthiknadig** [comment]
If you look at "Command Line" column in Task Manager > Details, you should be able to tell if it is an abandoned REPL or Intellisense that is taking all the resources. There should be only 1 REPL and at most 1 Intellisense process.
![image](https://cloud.githubusercontent.com/assets/3840081/23188149/83ba194e-f842-11e6-8a22-39beaa9e0522.png)

Note: You may have to make the column visible, "command line" column is usually hidden by default.

**Comment by AlexanderSher** [comment]
Here is what I got just now:

`"C:\USERS\ALSHER.REDMOND\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_8CFCE2F4EXP\EXTENSIONS\MICROSOFT\R TOOLS FOR VISUAL STUDIO\1.0\Microsoft.R.Host.exe" --rhost-interactive --rhost-name "REPL_" --rhost-log-dir "C:\Users\alsher.REDMOND\AppData\Local\Temp" --rhost-log-verbosity 3`

**Comment by Neil-Schneider** [comment]
I can confirm that the `...Microsodt.R.Host.exe" --rhost-name "IntelliSense_" ...` is the processes taking all the resources.

**Comment by MikhailArkhipov** [comment]
I think I found the problem. if caret is left inside some function call like in abcd(|) and the function is user-defined or otherwise unknown, there was an endless loop attempting to fetch function signature.

**Comment by Neil-Schneider** [comment]
I can confirm the behavior mentioned by Mikhail. Additionally, I noticed that the "loop" continues no matter what script is active in the editor, but if you close the script with custom function that began the loop, it will stop.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a068c51d930f91f4c1b5d277c46d8faa2478803f
