### ISSUE TITLE
R Session stopped on error: VECTOR_ELT()

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3215]
```
> loss.rate = (charge_off - recovery) / balance
Error: VECTOR_ELT() can only be applied to a 'list', not a 'NULL'

R session is stopped. Click "Reset" to start a new one.
```

Running the above command crashed the session. All objects should've been vectors, but I believe one was not initialized resulting in the error that followed.

RTVS: 1.0-RC1
MRO: 3.3.2

**Comment by MikhailArkhipov** [comment]
Does it happen in RGUI or it does work normally?

**Comment by Neil-Schneider** [comment]
I am unable to repro the error so far. Feel free to close it, if you believe this is an R issue and not an RHost issue. Otherwise, I will let you know if it happens again.

**Comment by MikhailArkhipov** [comment]
OK, feel free to reopen. R itself may terminate b/c of specifics of the code, that's why I asked if you've seen the same in RGui or RStudio. Thanks!
