### ISSUE TITLE
Can't continue demo(Japanese) after caret moves off input line

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3218]
`demo(Japanese)`
Hit Enter
Hit Enter (observe plot appears)
Move caret off the `Hit <Return> to see next plot: `
Move it back
Hit enter

Nothing happens. You have to reset REPL.
Changing connections STILL doesn't bring prompt back. You have to reset REPL in the new connection.

**Comment by MikhailArkhipov** [comment]
ESC doesn't bring the prompt back either.

**Comment by int19h** [comment]
For Enter (or other input ) to work, the cursor needs to be on the line *after* the prompt (and it's where it is when the prompt is displayed, before starting to move the cursor around).
