### ISSUE TITLE
CURL failed to conncet

### ISSUE THREAD

**Issue by peerapong123** [Microsoft/RTVS#3222]
Hi All

I try to install package via RTVS client that connect to microsoft R server. After that i got some error messages in this picture below 
![r_err_rtvs](https://cloud.githubusercontent.com/assets/25877653/23209532/268ff71c-f92c-11e6-9b76-f0d483c44c6c.PNG)

In the other hand, I can download and configured library in R server without any error appeared 
![r_package_server](https://cloud.githubusercontent.com/assets/25877653/23209601/7c0a76fe-f92c-11e6-9e8d-ded239e19033.PNG)

Furthermore, I configure R server for download package through proxy  and allow source URL below 
https://cloud.r-project.org/
https://mran.microsoft.com/
https://cran.revolutionanalytics.com/
https://mran.revolutionanalytics.com
https://cran.r-project.org/

How can I fix the problem ? or Force change to URL  instead of IPv6 ? 

PS. 2001:4800:7813:516:be76:4eff:fe04:4c9b is address of 'https://mran.revolutionanalytics.com'

**Comment by Hong-Revo** [comment]
This isn't an RTVS-related issue.

The `REMOTE>` prompt indicates that you're working in a remote session started by R Server operationalisation (previously known as DeployR). Your remote server apparently doesn't have Internet connectivity, so you can't download packages from CRAN. You should talk to your sysadmin about getting your packages installed.
