### ISSUE TITLE
Add ability to publish R stored proc to script file

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3223]
_Hi there.  I wanted to send some quick feedback on R Tools for Visual Studio.  I've been using it off and on since 0.1, and am currently on the 0.6 preview.  I appreciate the work you have put into this product and, at least in my case, I'm seeing my usage move from 100% R Studio to closer to 50-50, particularly when I'm doing anything with SQL Server R Services.

This leads to my feature request.  When it comes to SQL Server R Services, I like the ability to piece together stored procedures, and now that I've done it a couple times, I think the mechanics are straightforward.  One thing I do wish I could get, though, would be an option to glue together the components into a script which generates a CREATE OR ALTER stored procedure statement when I build the project.

I know I can use the Data sub-menu to generate these procedures in a database or in a database project today, but we don't use database projects here (for a few reasons, mostly due to environmental complexities).  My ideal would be that I could right-click and build the project and get the generated T-SQL script in a bin folder.  I could work around it by creating a dummy database project just for script generation, but that feels a little clunky._

**Comment by Hong-Revo** [comment]
This functionality is actually provided by the sqlrutils package, which ships as part of R Server 9. Use the `StoredProcedure` function to generate T-SQL code to create a stored proc out of an R function. Then use `registerStoredProcedure`  to run the generated code.

https://msdn.microsoft.com/en-us/library/mt790484.aspx

**Comment by MikhailArkhipov** [comment]
This item is basically add ability to place .sql file we generate into R project rather than into a database project.

**Comment by Hong-Revo** [comment]
Not sure what that entails...? I know that I can run the sqlrutils code to generate a stored proc, and load the resulting script into VS without problems. Note that `StoredProcedure` has an option to save the generated code as a SQL script.

**Comment by Hong-Revo** [comment]
From `?StoredProcedure`:

```
Usage
StoredProcedure (func, spName, ..., filePath = NULL ,dbName = NULL,
connectionString = NULL, batchSeparator = "GO")

Arguments

filePath 
A character string specifying a path to the directory in which to create the .sql. If NULL the .sql file is not generated.
```

**Comment by MikhailArkhipov** [comment]
RTVS has integration with SQL tools. https://microsoft.github.io/RTVS-docs/sqlserver.html

**Comment by Hong-Revo** [comment]
Sure, I guess I'm just saying that you can leverage the existing feature in R Server 9. It uses RevoScaleR to access the database instead of RODBC, but that should be okay since you need SQL Server 2016 to run the stored proc anyway.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5dee4c50b69ccd0d8a73b45767f2d3a953838b98
