### ISSUE TITLE
Can't change R Engine in R Tools for Visual Studio

### ISSUE THREAD

**Issue by afadallah** [Microsoft/RTVS#3224]
Hi,

I have a previous installation of base R v3.3.1 with Rstudio. After manual download and installation (with default configuration) of Visual Studio, RTVS, and MS R Client, I discovered that the R Engine was still set up with Base R. 

When I checked <mark>R Tools > R Tools > Advanced > R Engine </mark>, I can only find "Code Page" as an attribute to change. Scrolling up and down, I can find below the header "General", the attributes "CRAN Mirror" and "Survey/News Check" to change. I've looked at https://msdn.microsoft.com/microsoft-r/r-client-get-started#step-2-configure-your-ide but it didnt help.

My question, how can I change the R Engine within RTVS to use Microsoft R Client?

Thanks in advance,

**Comment by MikhailArkhipov** [comment]
Try R Tools | Windows | Workspaces. It shows all available R engines you can use. The window is not visible in VS general profile but if you switch to Data Science layout in R Tools | Data Schience Settings you'll get it on top.

**Comment by MikhailArkhipov** [comment]
http://microsoft.github.io/RTVS-docs/remote-execution.html

**Comment by afadallah** [comment]
@MikhailArkhipov 
Its worked! Thanks!!
