### ISSUE TITLE
Ctrl + arrow keys not working in interactive window

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#3229]
Ctrl + right/left arrow used to move between text delimiters. now just generates and interactive popup error.  this applies to left/right arrow with Ctrl and Ctrl+Shift

1.0.30213.1900 RC1

**Comment by MikhailArkhipov** [comment]
Could you give specific example? Ctrl+Left/Right are 'previous word' and 'next word'. Some sample code I tried appears to be OK in both interactive and editor.

**Comment by ebs238** [comment]
just reloaded a session and tried to repro. seems to only trigger after executing a plot.new()

**Comment by MikhailArkhipov** [comment]
Can you send us logs via R Tools | Feedback | Send Frown? I might be able to get call stack from there. Thanks!

**Comment by ebs238** [comment]
sent. here's a screen cap of the error, incase that helps
![capture](https://cloud.githubusercontent.com/assets/24379655/23243960/78523d90-f93f-11e6-816a-e48dd3c43e46.PNG)

**Comment by MikhailArkhipov** [comment]
Sorry, didn't get the logs :-(

**Comment by MikhailArkhipov** [comment]
Specific file is `ActivityLog.xml` in `C:\Users\[NAME]\AppData\Roaming\Microsoft\VisualStudio\14.0`

**Comment by MikhailArkhipov** [comment]
Made some changes in https://github.com/Microsoft/RTVS/commit/a068c51d930f91f4c1b5d277c46d8faa2478803f.

There are no exceptions recorded in the activity log though

**Comment by MikhailArkhipov** [comment]
Also, #3244. If you see the exception again, could you please grab the log file right away? It gets overwritten every time you start VS so the information could have been lost.

**Comment by MikhailArkhipov** [comment]
Might also be related to #3214 - exception could have happened trying to fetch signature for unknown function if package was not loaded.

**Comment by ebs238** [comment]
Sorry, been a bit busy. here is what I have found from the last few days: 

- this does not happen after a fresh start of VS 2015, before I have executed any r scripts
- Once this first happens, restarting the R session does not eliminate the problem. it lasts until I restart VS
- It does not generate an exception in ActivityLog.xml
- Some of the caret location symptoms seem to start showing up after I execute my first `source()` command, The symptoms  they seem to get much worse over time and eventually start producing the error dialog ( specific argument was out of range... ) in the screen capture above.

**Comment by ebs238** [comment]
unfortunately, my system died and i had to do a complete fresh install of Windows+VS2015+RTVS (RC2). 
fortunately, I have not encountered this issue at all since then (about 3 days), when it used to be a regular problem. I suspect its not worth chasing

**Comment by MikhailArkhipov** [comment]
OK :-)
