### ISSUE TITLE
Still Can't view the table

### ISSUE THREAD

**Issue by SenZHANG-GitHub** [Microsoft/RTVS#3235]
I know it's a repeated issue (same as #3150, #2996). But this issue still exists after I try https://aka.ms/rtvs-1.0rc1

![image](https://cloud.githubusercontent.com/assets/25522404/23295132/f427011a-faa9-11e6-9c7d-db921bb18458.png)

The version of the VS and R tools I'm using is:
![image](https://cloud.githubusercontent.com/assets/25522404/23289407/4eac97ba-fa84-11e6-80aa-434d80e51b02.png)

I can still view the table using the excel button. But it would be much better that I can view it directly in VS. 

Thanks in advance!

**Comment by int19h** [comment]
Could you run this code:
```r
rtvs:::grid_data(sigma, 1:2, 1:2)
```
and post the output here?

**Comment by iRoss2007** [comment]
Exactly the same problem I and my friends encountered. Viewing data within VS has never been a success since the first public version of RTVS. Tricks as in #3150, #2996 did nothing to it. 
@int19h Could you please tell me where to run the grid_date code? I run it in R interactive and it prompted "Error in as.vector(x, mode) : cannot coerce type 'closure' to vector of type 'any' ". 
Thanks.

**Comment by SenZHANG-GitHub** [comment]
@int19h 

Thanks for your reply! The output is shown as below

![image](https://cloud.githubusercontent.com/assets/25522404/23292366/457c2f14-fa9a-11e6-8f5c-98d0bc3c7497.png)

Seems OK though...

**Comment by SenZHANG-GitHub** [comment]
@iRoss2007 I just run  rtvs:::grid_data(sigma, 1:2, 1:2) in R intearctive (Microsoft R Client (3.2.2.803)). And it works

**Comment by SenZHANG-GitHub** [comment]
@iRoss2007

The following link showed a similar error,

https://stat.ethz.ch/pipermail/r-help/2010-December/261939.html

I guess maybe this happens when you assign the row and col parameters in an improper way  to the function grid_data()

Could you plz show the data.frame you wanted to investigate and the command you used?

Thanks

**Comment by int19h** [comment]
Yep, the output is correct, and seems to indicate that the R backend is working as it should and retrieving the data correctly. This narrows down the area where the bug is occurring to the presentation layer. I wonder if the real issue here is that the grid doesn't refresh properly after it gets the data.

What happens if you change the value of `sigma` after the grid tab is visible? Try doing something like this:
```
sigma <- c(1, 2, 3)
rm(sigma)
sigma <- mtcars
```
and see if any of those cause the grid to render.

**Comment by iRoss2007** [comment]
@SenZHANG-GitHub 

I think I've found what's the problem. The "sigma" in "rtvs:::grid_data(sigma, 1:2, 1:2)" is a built-in data.frame right? It seems that my MRO 3.3.2 doesn't come with that, however, if i switch sigma to iris, such as "rtvs:::grid_data(sigma, 1:2, 1:2)", everything works as expected.

Actually, Any type of of data.frame or data.table failed to show up in data viewer since the very first version. Is it the situation with you?

**Comment by SenZHANG-GitHub** [comment]
@int19h

I started from the page shown below,
![image](https://cloud.githubusercontent.com/assets/25522404/23293108/3a602626-fa9f-11e6-90d3-fc662a38542b.png)

And I tried to change the value of sigma. But the tab R Data: sigma is still blank...

**Comment by SenZHANG-GitHub** [comment]
@iRoss2007  sigma is generated from the following code "sigma <- matrix(c(4,2,3,1), ncol = 2)" . I also encountered this error when I tried to "rm(sigma") In R 3.3.2. But this error disappeared when I switched to Microsoft R Client (3.2.2.803). But currently I'm not sure what causes this difference.

I also tried several other data.frames from the example and self-generated, and currently none can be viewed. But for daily debug, showing the table in .csv is a good alternative.

**Comment by iRoss2007** [comment]
@int19h @SenZHANG-GitHub 

I also noticed an interesting thing: despite blank viewer, the scroll bar indicate the representation layer is somehow working. For example, if I set tt to the rather short 32 obs mtcars, there is no vertical scroll bar:

However, if I  change the value tt to iris, a relative long data.frame with 150+ obs, the vertical scroll come back! It seems that the grid viewer is at least working to some extent.

**Comment by SenZHANG-GitHub** [comment]
@iRoss2007 Actually when I switched back to R 3.3.2, the error disappeared again... I'm a little bit confused

**Comment by SenZHANG-GitHub** [comment]
@int19h 
I tried again, and this time I found when I rm sigma, a message("object sigma is missing") will be displayed. But this message will not disappear if I reassign value to sigma. 
![image](https://cloud.githubusercontent.com/assets/25522404/23293629/307c3070-faa2-11e6-8df8-a04f140496a1.png)

![image](https://cloud.githubusercontent.com/assets/25522404/23293705/a55aae58-faa2-11e6-84e6-1b2205b4165f.png)

@iRoss2007 

Yes! I tried and I also observed the scroll bar if the data dimension is large.

**Comment by int19h** [comment]
Hmm... when you observe the scrollbar, can you actually move the handle on it with the mouse?

I wonder if it's some kind of WPF rendering bug.

**Comment by iRoss2007** [comment]
Yes, the scrollbar handle is movable.

**Comment by SenZHANG-GitHub** [comment]
@int19h

Yes I can play with the scrollbar : ) 

![image](https://cloud.githubusercontent.com/assets/25522404/23300454/98696144-fac0-11e6-81c3-2c5983325cfa.png)

The version of the WPF in my PC is,
![image](https://cloud.githubusercontent.com/assets/25522404/23300600/3f834dbe-fac1-11e6-9788-df4c634bb7ed.png)

And the .net framework is also updated to 4.6.1 in my PC
![image](https://cloud.githubusercontent.com/assets/25522404/23301004/112a1bb2-fac3-11e6-859f-a0c0f01b04ba.png)

**Comment by MikhailArkhipov** [comment]
Changed in https://github.com/Microsoft/RTVS/commit/efc838ed541c5960a137442cde1b42fc40559c16 will post link to RC2 when it is out

**Comment by SenZHANG-GitHub** [comment]
@MikhailArkhipov
 
Thanks! But I rebuilt the src and found that I still cannot view the data under the new codes...

**Comment by MikhailArkhipov** [comment]
Well, if it is not too much to ask ;-).... 

If you are building and familiar with C#... You can try and run via F5, set breakpoint in `TextVisual.Draw()` in `src\Package\Impl\DataInspect\VisualGrid and see if it is actually being rendered and if `Text` and `formattedText` properties are set.

**Comment by MikhailArkhipov** [comment]
You can also try and see if the following VS settings make a difference

![image](https://cloud.githubusercontent.com/assets/12820357/23342726/545ce93a-fc14-11e6-9716-6f3cfdf7fadc.png)

**Comment by SenZHANG-GitHub** [comment]
@MikhailArkhipov 

Thanks a lot for your suggestions! I got some trouble when rebuilding the project again. Will return to this later.

**Comment by mugofjoe** [comment]
Hello, I'm the poster of issue #2561.  I just installed 1.0.30225.1011 RC2.  Unfortunately, this is still an issue.

**Comment by iRoss2007** [comment]
I hope so but unfortunately it doesn't work out foe me.


-------- Original message --------

**Comment by MikhailArkhipov** [comment]
OK, it does appear to be the locale issue... Are you using CHS or CHT locale? I am going to spin up a VM and test.

**Comment by mugofjoe** [comment]
i tried the settings above, Mikhail, but the problem remains.

**Comment by MikhailArkhipov** [comment]
It appears locale-specific. I am working on verification.

**Comment by mugofjoe** [comment]
Just fyi, I'm in the United States.

**Comment by MikhailArkhipov** [comment]
Do you see the same effects? Screenshot above shows that data is there (scrollbars work) and actually column and row headers are there, just empty. This means text was not rendered.

**Comment by MikhailArkhipov** [comment]
Got repro on CHS Windows

![image](https://cloud.githubusercontent.com/assets/12820357/23520808/4fc44b8c-ff31-11e6-9615-95374b121764.png)

**Comment by MikhailArkhipov** [comment]
Here is fixed version. Will be submitting PR soon.

![image](https://cloud.githubusercontent.com/assets/12820357/23521313/49583fae-ff33-11e6-9695-950e7bce5e9b.png)

**Comment by mugofjoe** [comment]
Hi Mikhail, will your fix apply to the ENU locale as well?

**Comment by MikhailArkhipov** [comment]
It depends what fonts are available on the machine. The issue was in the fact that grid code tried to fetch typeface with some specific characteristics that are not always available. They are certainly not available on Far East locales. Not entirely sure about ENU, but it is possible technically to have OS with different font set.

The plan is to have updated build for verification soon. I'll provide the link when it is available so you can try it as well.

**Comment by iRoss2007** [comment]
Sounds great! Can't wait to try RC3!


-------- Original message --------

**Comment by mugofjoe** [comment]
Splendid. Thanks, Mikhail.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bd30fdccb5ad88a13db543cf9be4d5150a8152c2

**Comment by SenZHANG-GitHub** [comment]
@MikhailArkhipov 
Great job! Many thanks. Looking forward to the new version!

**Comment by MikhailArkhipov** [comment]
T

**Comment by MikhailArkhipov** [comment]
Try https://aka.ms/rtvs-1.0rc3

**Comment by mugofjoe** [comment]
Hi Mikhail,  1.0rc3 did it! It works both from the interactive window (View(mtcars) and the Variable Explorer panel as well (when you click on the magnifying glass associated with the dataframe). Thanks a lot for your solution.

![mtcars](https://cloud.githubusercontent.com/assets/14941750/23564342/14e2cf24-0018-11e7-835c-d36ccc27d0e6.png)

**Comment by MikhailArkhipov** [comment]
Great! Closing then :-)
