### ISSUE TITLE
Error installing R Tools v1.0 RC1 on VS 2015 Ent w/ Update 3

### ISSUE THREAD

**Issue by sqlaz** [Microsoft/RTVS#3237]
Getting an error on installing RC1.  

![r2vs_rc1_error](https://cloud.githubusercontent.com/assets/25693291/23315168/ff768a5c-fa92-11e6-85c4-7cbea0d067fa.JPG)
![vs_update3](https://cloud.githubusercontent.com/assets/25693291/23315169/ff7bb126-fa92-11e6-8be0-3885235ebeae.JPG)

**Comment by MikhailArkhipov** [comment]
The setup checks standard VS registry entry in

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\DevDiv\vs\Servicing\14.0\devenv`

Can you please look there and see if it exists and what the values are? Here is my machine 

![image](https://cloud.githubusercontent.com/assets/12820357/23317928/41a63a02-fa85-11e6-83e4-31fe488ac6bf.png)

**Comment by sqlaz** [comment]
Looks like one of the past installation didn't go through well - I see a ..\vs\Servicing\14.0 hive, and then a ..\vs\Servicing\14.0_old one.  Went ahead, deleted the partial \14.0, and made the \14.0_old \14.0, and re-attempting the installation ran to completion.  Thank you for your help!  RTVS rocks - hoping I don't have to use RStudio going forward!  

![vs_reghives](https://cloud.githubusercontent.com/assets/25693291/23319990/ddef8cbc-faa6-11e6-91db-a7bf2e674f52.JPG)

![rtvs_rc1_installed](https://cloud.githubusercontent.com/assets/25693291/23320051/2c3984d6-faa7-11e6-9a35-4da1db828c49.JPG)

**Comment by MikhailArkhipov** [comment]
Glad you are all set up :-)
