### ISSUE TITLE
R project template is not available while creating project from VS 2015

### ISSUE THREAD

**Issue by Chittapriya** [Microsoft/RTVS#3243]
I installed latest version of RTVS RC1. I am not seeing R option is not available under VS template.

**Comment by MikhailArkhipov** [comment]
Do you see R Tools menu? Does R Tools -> Windows -> R Interactive work?

**Comment by jayrowme** [comment]
I'm also having this issue. I see the R Tools menu and I'm able to open R Interactive. I'm using Microsoft R Client.

**Comment by MikhailArkhipov** [comment]
You can try this:

1. Check that `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates\R` is populated (`EmptyProject` folder with 4 files)

2. Open admin command prompt
3. Go to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`
4. run `devenv /InstallVsTemplates`

You can also try `devenv /setup` but it is more drastic as it resets VS to defaults and re-builds components and template catalog from scratch.

**Comment by MikhailArkhipov** [comment]
Feel free to reopen if you are still experiencing problems.
