### ISSUE TITLE
Some autoformatting annoyances

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3248]
These are with Automatic Formatting = On in the Editor Options.

When creating a dplyr chain, the editor keeps unindenting lines that I indent because they're part of the chain. Desired formatting:
```
df <- df %>%
    verb1(...) %>%
    verb2(...)
```
Actual formatting:
```
df <- df %>%
verb1(...) %>%
verb2(...)
```

Also, my preferred style is not to have spaces between argument names and values inside a function call (or a function header). The editor inserts spaces when I press Enter. Desired formatting:
```
func(x=1, y=2, z=something, ...)
```
Actual formatting:
```
func(x = 1, y = 2, z = something, ...)
```

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bd30fdccb5ad88a13db543cf9be4d5150a8152c2

**Comment by MikhailArkhipov** [comment]
Please try https://aka.ms/rtvs-1.0rc3
