### ISSUE TITLE
Remote help crash

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#3250]
used remote machine:

https://rtvs-devserver1:5444#1

not sure if the #1 param is involved.

tried "?help", then typed in some search terms.  crashed:

![image](https://cloud.githubusercontent.com/assets/742484/23483857/6c818508-fe89-11e6-8785-ad47ce2282ba.png)

frown data sent already.

**Comment by MikhailArkhipov** [comment]
Works for me in both forms of the URL

![image](https://cloud.githubusercontent.com/assets/12820357/23520281/184959b0-ff2f-11e6-93b9-3557e1266938.png)

**Comment by smortaz** [comment]
did you type stuff in the search window?

**Comment by MikhailArkhipov** [comment]
Yes

**Comment by MikhailArkhipov** [comment]
No user reports on this. Closing.
