### ISSUE TITLE
Error connecting to Remote Workspace

### ISSUE THREAD

**Issue by kesso1** [Microsoft/RTVS#3251]
##Reason: Machine servername appears to be online, but the Remote R Service is not running. Cert is installed, services are running, .NET version is 4.6.2, Port is listening on 5444. Any ideas?

**Comment by MikhailArkhipov** [comment]
You can check logs at

`C:\windows\serviceprofiles\networkservice\appdata\local\temp`

1. Make sure the certificate name does not match the actual machine name.
2. Make sure NETWORK SERVICE is granted access to the certificate.

**Comment by MikhailArkhipov** [comment]
Here is long version on the remote setup 

http://blogs.u2u.be/u2u/post/2017/03/02/Using-Azure-VMs-as-remote-R-workspaces-in-R-Tools-for-Visual-Studio.aspx

**Comment by karthiknadig** [comment]
On the server machine check if R Remote Service is running. If it is stopped then look in Event Viewer > Windows Logs > Application logs on the server machine. Make sure that Microsoft.R.Host.Broker.exe and Microsoft.R.Host.exe are allowed in the advanced firewall settings.

**Comment by kesso1** [comment]
NETWORK SERVICE has access to the cert, cert name match to machine name and both services are running. No errors in the log, but not even a connection attempt is appears in the log. Is there another port used beside 5444? Thanks.

**Comment by karthiknadig** [comment]
This might be a firewall issue. Can you remove the firewall rules for Microsoft.R.Host and Microsoft.R.Host.Broker. Add them back and restart? Also make sure that there are no other firewall rules with exceptions for Microsoft.R.Host.exe and Microsoft.R.Host.Broker.exe.

**Comment by karthiknadig** [comment]
You can change the port by updating the config file: 
`%ProgramFiles%\R Remote Service for Visual Studio\1.0\Microsoft.R.Host.Broker.Config.json`
change this line to use the port you like: `"server.urls": "https://0.0.0.0:5444"`

Note: If there is no connection attempt logged. This is usually due to firewall blocking the broker. Be sure to restart windows after making firewall changes.

**Comment by kesso1** [comment]
Firewall is completely disabled on the server, but the issues' the same.

**Comment by kesso1** [comment]
And the port is accessible via telnet...

**Comment by karthiknadig** [comment]
@kesso1 Windows services have another layer of protection. Turning of firewall does not disable blocking services.
http://windowsitpro.com/systems-management/understanding-windows-service-hardening

**Comment by kesso1** [comment]
Well, the service starts without any errors... if the service is blocked it should appear in the log, shouldn't it?

**Comment by MikhailArkhipov** [comment]
Windows doesn't know if service doing remote or not. So it starts it regardless. OS by default hardens from remote access but not from local. So there won't be any errors logged if remote request is rejected at the network stack level.
