### ISSUE TITLE
History entries selected by keyboard are unsynced with selected by mouse

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3256]
- Add 4 entries to history
- Click third entry with mouse (third entry is selected)
- Press up arrow 2 times (first entry is selected)
- Shift+Click on the fourth entry

**Actual:** third and fourth entry are selected
**Expected:** all entries are selected

**Comment by MikhailArkhipov** [comment]
I don't think this is accessibility issue. The problem is with mixed use or mouse and keyboard and not with 100% keyboard. Or is it? If keyboard alone works OK, we can look into this later.
