### ISSUE TITLE
Making a pipeline marks other code sections as touched

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3260]
Thanks for the quick turnaround on #3248 guys! I'm testing out RC3 now. I just ran into this:

![image](https://cloud.githubusercontent.com/assets/11328890/23575115/2f7d9cf0-00dc-11e7-8a77-a1d05d7ac8ae.png)

When I type the code at the bottom, it marks several other (untouched) sections of the file as edited.

**Comment by MikhailArkhipov** [comment]
This is might happen in the current implementation. In order to format properly formatter is actually looking at a bigger range. At some point we should look into extracting smaller, original range from the formatted scope when applying change back to the document.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16149bd35ee00d90b6c942b59447030db52da752
