### ISSUE TITLE
Inconsistent formatting of spaces around =

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3261]
Following on from #3260... the way RC3 treats spacing for `=` seems flakey.

If I type the following code in the editor:
```
data <- data %>%
    mutate(a=f(a),
           b=f(b),
           c=f(c))
```
The result is (note spaces around `=`):
```
data <- data %>%
    mutate(a=f(a),
           b = f(b),
           c = f(c))
```
However, if I continue with a `%>%`[enter]`group_by`, the spaces magically disappear:
```
data <- data %>%
    mutate(a=f(a),
           b=f(b),
           c=f(c)) %>%
    group_by(d) %>%
```

**Comment by MikhailArkhipov** [comment]
(3) is expected as complete statement is formatted. (2) appears to be a bug.

**Comment by Hong-Revo** [comment]
Yes, this would also seem to be the root cause of #3260: I've noticed that code throughout a file will have spaces appear and disappear as I type.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16149bd35ee00d90b6c942b59447030db52da752
