### ISSUE TITLE
Typing ::: sometimes gets messed up

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3262]
When I want to get an unexported function from a package via `:::`, the cursor jumps to the end of the line after I type `::`. Eg `stats:::AIC`, becomes `stats::AIC:`.

This seems to happen only if:

1. I type the function name first, then move to the start of the line and type the package name followed by `:::`
2. The completion list contains exactly one member, eg it happens with `AIC`[home]`stats:::` but not with `lm`[home]`stats:::`.

I can avoid this behaviour by pressing Esc to dismiss the completion list when it pops up, but I'd rather not have to.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16149bd35ee00d90b6c942b59447030db52da752
