### ISSUE TITLE
After installing R Tools, VS toolbar icons have disappeared

### ISSUE THREAD

**Issue by beneuto** [Microsoft/RTVS#3263]
Uninstalling R Tools has not restored icons.

**Comment by MikhailArkhipov** [comment]
Which particular toolbar/icon disappeared? Did you use Data Science profile? You can restore any UI profile (standard or custom) via Tools | Import/Export settings.

**Comment by beneuto** [comment]
This was resolved after PC updated with Windows 10 Anniversary Update.
