### ISSUE TITLE
R Interactive steals focus when debugging Python.

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#3264]
After updating RTVS to 1.0.30302.1431, R interactive steals focus from Python debug Interactive .
Maybe related with #2229.

![animation](https://cloud.githubusercontent.com/assets/3863577/23598828/65e607dc-0280-11e7-911a-a6c420af1789.gif)

Repro:
1) Start python debugging with a breakpoint.
2) At the break point, activate Python Debug Interactive. 
3) Push F10 to step over.
4) R Interactive is activated.

Python Tools for Visual Studio   2.2.50113.00
R Tools for Visual Studio   1.0.30302.1431

**Comment by int19h** [comment]
The code we have to restore focus in VS 2015 probably doesn't check whether it's R being debugged, or something else. It should do so, by checking engine GUIDs (probably via DTE.Debugger).

This shouldn't be a problem in VS 2017, since we rely on VS itself to handle focus properly there.

**Comment by MikhailArkhipov** [comment]
Yes, this is resolved in 2017. Unfortunately, interactive window component won't be updated for 2015.

**Comment by MikhailArkhipov** [comment]
Code check if current active project is R project or that there is no project. We probably should also check for

1. If R is actually running so `R Tools | Session | Terminate R` would stop RTVS code.
2. For the debugger type

**Comment by Marchen** [comment]
Additional information, the solution I tested this issue had both Python and R projects and Python project was start up project. I hope this will help you.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/16149bd35ee00d90b6c942b59447030db52da752
