### ISSUE TITLE
Function "View" don't work

### ISSUE THREAD

**Issue by Usos** [Microsoft/RTVS#3269]
Thesedays, I found that function `View()` didn't work. For example, I have a dataframe named `summary`,:

```
> mode(summary)
[1] "list"
> summary
                sample_name node_counts MDS_counts rMDS_counts cMDS_counts iMDS_counts   MDS_time rMDS_time cMDS_time total_time
1            BA200_POW1H_S1         200       59.0          NA        22.0          NA 0.04001498        NA 1.4042511   1.488271
2            BA200_POW1H_S2         200       31.0          NA        11.0          NA 0.02300191        NA 0.9691679   1.025184
3            BA200_POW1H_S3         200       53.0          NA        22.0          NA 0.02300215        NA 1.2212090   1.277218
4            BA200_POW1H_S4         200       48.0          NA        21.0          NA 0.02400398        NA 1.1246860   1.189694
5            BA200_POW1H_S5         200       45.0          NA        18.0          NA 0.02801490        NA 1.2622092   1.322735
6            BA200_POW1H_S6         200       45.0          NA        19.0          NA 0.02000189        NA 1.0521920   1.109196
7            BA200_POW1H_S7         200       56.0          NA        19.0          NA 0.02501202        NA 1.2882540   1.347268
8            BA200_POW1H_S8         200       51.0          NA        19.0          NA 0.02850485        NA 1.2100539   1.273066
9            BA200_POW1H_S9         200       43.0          NA        13.0          NA 0.02501297        NA 1.2511930   1.306204
10          BA200_POW1H_S10         200       48.0          NA        18.0          NA 0.02200103        NA 1.1611910   1.219192
11                     Ave.         200       47.9          NA        18.2          NA 0.02585707        NA 1.1944410   1.255803
12 Tue Mar 07 13:13:05 2017          NA         NA          NA          NA          NA         NA        NA        NA         NA
``` 

And in excel, it can be displayed correctly.

![default](https://cloud.githubusercontent.com/assets/5370174/23643827/0984bcf8-033f-11e7-8f61-37698682e28e.PNG)

but, use `View(summary)`to display it in Data Grid, it displayed nothing.  The effect of click the  magnifying glass icon in Variable Explorer is same.

![default](https://cloud.githubusercontent.com/assets/5370174/23643887/70d68940-033f-11e7-8e79-30c70419990e.PNG)

I tryed serval tables and all of them can't be displayed. This problem is fully confused me, looking forward to your  reply.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.0.30228.1316, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Open (3.3.2): C:\Program Files\Microsoft\MRO-3.3.2\

**Comment by smortaz** [comment]
Please try: https://aka.ms/rtvs-1.0rc3 and let us know if that works for you.  thx.

**Comment by Usos** [comment]
Ok, the problem has been solved, thx. 
In addition, hope add a fliter in Data Gird such as RStudio, so  that user can seek intrest data quickly.
