### ISSUE TITLE
Feature request: leave R session active when closing VS

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3277]
Right now, when you close VS, any workspace you have active is terminated. It would be really nice if you had an option to leave it running, maybe as a background process.

This would be similar to the RStudio Server behaviour where you can close your browser, then reopen it and the R session is is still alive. It lets you treat RStudio like a poor-man's batch scheduler: start a heavy-duty number-crunching job, logoff and go to sleep, then come back the next morning and it's finished.

**Comment by MikhailArkhipov** [comment]
#2176

**Comment by MikhailArkhipov** [comment]
Closing in favor of #2176
