### ISSUE TITLE
Feature request: add button "show plot at full screen"

### ISSUE THREAD

**Issue by unlimitedbeer** [Microsoft/RTVS#3281]
Just like R-Studio "Zoom" button:
1) Full screen new window (or save size and position)
2) Closed by "Esc" button.

**Comment by smortaz** [comment]
Thanks for the suggestion.  I assume you are aware of the existing VS
mechanism which approximately does that:

1. tear off the plot window
2. click maximize (top right)
3. re-dock

?

**Comment by Neil-Schneider** [comment]
<img width="66" alt="float" src="https://cloud.githubusercontent.com/assets/6426710/23772335/9c1290e0-04e8-11e7-8559-c85193f67035.PNG">

Under the down arrow is `Float`. This will peel off the plot window and leave the other tabs behind (if you share the plot window with other tabs.) 

When doing data exploration, I will peel off the plot window and put it on its own monitor (full screen) while using RTVS on the other.

**Comment by unlimitedbeer** [comment]
Yes, I know about re-docking. I was trying to resize window by one click. Thanks to **Neil-Schneider** I can do it for now. Thank you! 

Can you add possibility to restore maximized window to normal state by pressing Esc and make this solution absolutly perfect? :)

**Comment by MikhailArkhipov** [comment]
Also, double-click on the window title bar maximizes it. If it maximized, it restores the size.

**Comment by MikhailArkhipov** [comment]
You can also leave feedback to VS IDE team via standard 'Send Feedback' feature since tool window behavior and docking is a common code and we can't add features directly to it.
