### ISSUE TITLE
Auto-completion is overzealous

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#3298]
When writing code the auto-completion functionality is jumping to conclusion that I wish it wouldn't. I do not recall this issue in previous version of RTVS.

Repro:
This would be example code I am trying to compose.
```
library(devtools)
check("lightgbm")
```

But the intellisense suggests `checkpoint` once you have typed `check` and then when you type `(` it will auto complete to `checkpoint()`. 

This behavior happens for more than just the `check()` function. I am currently use v1.0-rc3. (1.0.30302.1431)

Let me know if I can provide any additional information.

**Comment by MikhailArkhipov** [comment]
When I type

![image](https://cloud.githubusercontent.com/assets/12820357/23907279/da45d0cc-088d-11e7-9164-4ef11e9a6512.png)

`(` completes to `check`. Do you see different list and selection?

**Comment by Neil-Schneider** [comment]
Somehow I did not have the default setting on for Intellisense. 

Options -> Text Editor -> R -> Advanced -> Intellisense -> Match Partially typed augment name 

This option was set to `Off` and was bold. Switching it to `On` solved the problem. I am not sure how it got set to `Off`.

**Comment by MikhailArkhipov** [comment]
Great, thanks :-)
