### ISSUE TITLE
Create a .zip file of RTVS installation files with an aka.ms redirect link

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3303]
To enable air-gapped machines to install both VS and RTVS.

Also need to update setup instructions to reflect an air-gapped install.

**Comment by MikhailArkhipov** [comment]
Still needs work?

**Comment by jflam** [comment]
The links have been created already - https://aka.ms/rtvs-current-zip and https://aka.ms/rtvs-remote-zip. However, we need to update the docs to point to the offline zip files for installation. https://docs.microsoft.com/en-us/visualstudio/rtvs/installation#offline-installation-of-visual-studio-and-rtvs . 

@kraigb - can you please update item 3 at the above doc page to instead point to the two links above? Thx!

**Comment by kraigb** [comment]
This is in https://github.com/Microsoft/vsdocs/pull/506. It'll probably take a few days for it to get out to live, but it's in the queue.
