### ISSUE TITLE
File completion on remote workspace duplicates directory entries

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3305]
Here's a screenshot - note that directory entries are duped.

![image](https://cloud.githubusercontent.com/assets/8877/23970630/b2884010-0987-11e7-87c9-61446c2e673d.png)

**Comment by MikhailArkhipov** [comment]
Apparently `list.files(path = '.', include.dirs = FALSE)` returns directory names anyway

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/170e8d3586a1fa42f7a81f9144948921adaa5675
