### ISSUE TITLE
Reinstalling multiple packages that contain DLL fails

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3306]
```r
install.packages(c('shiny', 'ggvis', 'dplyr', 'RSQLite'))
```
Retry this several times. On some machines it's a reliable repro, with the second install (when packages already exist, and it's installing on top) giving the error. On my VM it doesn't reproduce reliably.

The error you get is "cannot remove prior installation of package 'dplyr'" etc. The errors only happen for packages that contain DLLs. Inspecting the file system shows that the packages are removed entirely, except for the DLL file.

It does not reproduce in RGui on machines on which it reliably reproduces in RTVS.

It doesn't have to be that particular set of packages, but the important part seems to be that it must be multiple packages in a single `install.packages` call, and that more then one of them includes a DLL. In this example, `dplyr` and `RSQLite` are the ones that include DLLs.

**Comment by int19h** [comment]
My theory is that this has something to do with the checks that we have for DLLs being in use to safeguard against inappropriate removal. Perhaps that check happens asynchronously as the package is actually being removed by R, locking the DLL file briefly just as R tries to delete it.

**Comment by int19h** [comment]
Screenshot from @smortaz repro of this:

![image](https://cloud.githubusercontent.com/assets/1175142/23971445/38ad6a96-098b-11e7-97a8-a373ff984f6b.png)

**Comment by smortaz** [comment]
I see this reliably on my machine

**Comment by int19h** [comment]
I was trying to repro on a VM, which does have much slower I/O among other things. So perhaps package removal is just that much slower there, which is why I cannot reliably hit it. You were doing it directly on your laptop, right?

**Comment by smortaz** [comment]
Yep. Sometimes when I install them individually it doesn't happen. But all
together, repros almost all the time

**Comment by AlexanderSher** [comment]
`install.packages` override looks like this:
```r
install.packages <- function(...) {
    utils::install.packages(...)
    invisible(rtvs:::send_notification('!PackagesInstalled'))
}
```
I wasn't able to repro it so far. @int19h , what dll safeguard do you mean?

**Comment by int19h** [comment]
We expose an R function from the host called `get_file_lock_state` that does that check (the actual implementation is in `rstrtmgr.cpp`). It's then wrapped in `rtvs:::package_lock_state`. I thought that was used by package manager somewhere.

@smortaz has a reliable repro on his laptop. @MikhailArkhipov also had one with different packages on remote server (I believe that one was for `devtools` and `Rcpp` - correct me if I'm wrong).

**Comment by AlexanderSher** [comment]
I was able to repro it several times in a row and now I can't repro it again.
DLL is locked by the IntelliSense RHost, and that isn't briefly:
![image](https://cloud.githubusercontent.com/assets/8933858/23981958/3d972da6-09d8-11e7-8edb-6dfbdfc55360.png)
When IntelliSense doesn't lock it, everything works fine.

**Comment by int19h** [comment]
Ohh, Intellisense. I guess that makes some more sense. @MikhailArkhipov, do we do any sort of asynchronous package scanning (while the user isn't typing anything) in the background, perhaps after packages get installed? Maybe the problem is that when they get installed, it starts scanning, and then when you try to install again they're still being loaded in the Intellisense session?

Also, do we unload them after we finish scanning members? Otherwise DLLs will get stuck around permanently...

**Comment by MikhailArkhipov** [comment]
Looks like side effect of #3194. Yes, package/function index is listening to packages installed/removed/loaded/unloaded.

**Comment by MikhailArkhipov** [comment]
``rtvs:::package.functions.names` is called on newly added packages which relies on `getNamespaceExports`. It does unload after inspecting AFAICT since `search()` does not show the inspected package as loaded. But it should be locking it for some period of time.

I think problem might be that `PackagesInstalled` and `PackagesRemoved` events are bound to the same code. Let me try and separate. At least `PackagesRemoved` won't be locking.

**Comment by MikhailArkhipov** [comment]
So `getNamespaceExports` loads native binary and never unloads it.

in RStudio if I do `getNamespaceExports('Rcpp')` and then `install.packages('Rcpp')` I get

![image](https://cloud.githubusercontent.com/assets/12820357/24008920/7cd8eb5a-0a30-11e7-887d-f7d7650852d5.png)

**Comment by MikhailArkhipov** [comment]
Couple things we can do: 

a). If anything is locked, kill intellisense session before installing. It is generally safe to do.
b). Implement warning like above for the interactive session if user happened to call `getNamespaceExports` or loaded the package in some other way.

**Comment by AlexanderSher** [comment]
> If anything is locked, kill intellisense session before installing

Does it mean we need a hook inside `install.packages`?

**Comment by MikhailArkhipov** [comment]
I am trying to replace `PackagesInstalled` by `BeforePackagesInstalled` and `AfterPackagesInstalled` and see if that helps. But we probably still need (b)

**Comment by MikhailArkhipov** [comment]
Seems to work better now with separate notifications.

**Comment by MikhailArkhipov** [comment]
`GetPackageLockStateAsync` appears to only used in tests

**Comment by int19h** [comment]
Note that in this repro, the user invoked `install.packages`, and it did indeed install a bunch of packages, it's just that install involved removal of older packages. So if we lock on install, I think we'll still hit it if the next step is remove, and it happens fast enough.

**Comment by MikhailArkhipov** [comment]
So I added stopping intellisense host before `install.packages` commences. I guess if multiple packages are added/removed, it does can restart before install completes if it receives PackagesChanged. Need to chase that path and see if that indeed may happen. If so, then we need to suppress intellisense operations until `install.packages` completes and `AfterPackagesInstalled` fires.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/170e8d3586a1fa42f7a81f9144948921adaa5675
