### ISSUE TITLE
Use stock R headers to build RHost

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3312]
Rapi.h uses windows definitions of some of the functions used. On linux some of those definitions lead to SIGSEGV fault. Trying to replace every function with a linux definition makes Rapi.h riddled with ifdef. Building RHost with gcc and stock R headers seems like the cleanest way.

**Comment by MikhailArkhipov** [comment]
What's the status?

**Comment by karthiknadig** [comment]
This builds on linux now. I have to do a similar change in windows, but after the change likely that RHost will not build with VC++. It will have to be built with gcc.

**Comment by karthiknadig** [comment]
Since this work item is linux specific. I am closing the item, since work remains to be done on the windows side.

**Comment by Hong-Revo** [comment]
If only VC++ was C99 compliant....
