### ISSUE TITLE
Option to set language on remote process

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3317]
In order to load proper satellites broker needs to know UI culture. Should it be in the config file? See also #3316

**Comment by AlexanderSher** [comment]
Should it be an option for single connection or for the whole broker?

**Comment by MikhailArkhipov** [comment]
We need to discuss this. I think it would be per user. It is possible to have several clients in different languages working with the same broker. So they should be getting messages etc in their language. Like Windows Server which has OS language but also each TS session may have different UI language.

This may be complicated. We can delay until Wave 2.

**Comment by AlexanderSher** [comment]
It is not a big deal to pass another parameter from VS to RHost, but I don't know what has to be done on the RHost side.

**Comment by MikhailArkhipov** [comment]
Same as #3363
