### ISSUE TITLE
Rmd syntax highlighting issue with <number><dot> in text

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3318]
RTVS thinks there is a numbered list in the following:

![image](https://cloud.githubusercontent.com/assets/11328890/24120717/aea47596-0e09-11e7-9ec9-81ba26197e98.png)

I can make the highlighting disappear by adding text immediately after the first period, so it isn't followed by a space.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/3899f4e70e0ce43eb4468d86de940aec2c0f3c4d
