### ISSUE TITLE
Update documentation for Workspace names to reflect in-place upgrades of MRC, MRS, MRS-SQL

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3327]
There are three Microsoft R Client flavors:

1. Microsoft R Client
1. Microsoft R Server
1. Microsoft R Server for SQL Server

These all upgrade in-place. Therefore, we will always update the name with the name of the newer version that was just installed **regardless of whether the user changed the name**. Update the documentation to reflect this.

**Comment by MikhailArkhipov** [comment]
Names changed again... We may want to re-file this in docs repo.
