### ISSUE TITLE
remoting feature: R session crashes on syntax error

### ISSUE THREAD

**Issue by samuel100** [Microsoft/RTVS#3328]
The R Session crashes when an R syntax error is incurred.

For example....

![image](https://cloud.githubusercontent.com/assets/9161628/24197893/6d7bc23e-0efb-11e7-8bf6-0bd0db094b74.png)

**Comment by MikhailArkhipov** [comment]
Most probably same issue as #3329 - please see comment there.

**Comment by MikhailArkhipov** [comment]
Closing per #3329
