### ISSUE TITLE
Remote feature: R Session crashes on ESC Key

### ISSUE THREAD

**Issue by samuel100** [Microsoft/RTVS#3329]
When in a remote session, the ESC-Key quits the R session rather than return to the R prompt.

**Comment by MikhailArkhipov** [comment]
Which version is it (build number)? Does remote mach client version-wise? Did you set up your own machine or used one of the test boxes? I just tried rtvs-server1 as well as dev test machine and both appear to be OK.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/24206541/c078bc28-0edb-11e7-93f5-58c65b859a6b.png)

**Comment by samuel100** [comment]
Build number of server (which I downloaded from the GH documentation link).

R Services Information:
       Remote workspace 'SQL on Azure' : https://skdsvm.westeurope.cloudapp.azure.com:5444/
       Version: 1.0.30228.1316
       Operating System: Microsoft Windows NT 6.2.9200.0
       CPU Count: 4
       Physical Memory: 28671 MB, 25152 MB free
       Virtual Memory: 33023 MB, 28547 MB free
       Video controller: Microsoft Hyper-V Video
       Connected users: 0

Installed R versions:
       [0] Microsoft R Server (3.3.2.0) (Default)

**Comment by MikhailArkhipov** [comment]
1.0.30228.1316 looks old, 0228 == Feb 28th, almost a moth ago. @jflam - do we need to fix doc link?

**Comment by samuel100** [comment]
Is the upgrade as simple as installing the latest version? Or do you also need to reconfig?

**Comment by jflam** [comment]
There is a doc fix that I'm queuing up for the 1.0 release docs.

**Comment by samuel100** [comment]
Having upgraded RTVS (client) and R Remote Services (Server).... all is well.

**Comment by MikhailArkhipov** [comment]
Good :-)
