### ISSUE TITLE
Some ConnectionManagerViewModelTest fail if there are no user created connections

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3336]
`AddLocal_Connect_Rename`and `AddLocalWithSameName_ConnectToSecond` assume

`var connection = _cmvm.LocalConnections.First(c => c.IsUserCreated);`

**Comment by MikhailArkhipov** [comment]
Also, `StateChanges` fails intermittently since `ConnectionStateChanged` calls `Post` to UI thread and often next test check happens _before_ the `ConnectionStateChangedOnMainThread` is executed.

**Comment by MikhailArkhipov** [comment]
Basically any test that is non UI bound. Perhaps set flag on UIThreadHelper to always to `Send` rather than `Post` in tests? This is more or less fallout of removal of the `DispatchToUIThread`

**Comment by AlexanderSher** [comment]
I will look into it after you submit the change. There shouldn't be significant difference between `DispatchToUIThread` and `Post`

**Comment by MikhailArkhipov** [comment]
I think old test shell was translating `DispatchToUIThread ` to just `action()`
