### ISSUE TITLE
Make package manager message more friendly

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3348]
![22](https://cloud.githubusercontent.com/assets/12820357/24308622/f31edeae-1085-11e7-8e99-cd613a7c330b.png)

Something like 'Open R interactive window or restart R session...`

**Comment by AlexanderSher** [comment]
Suggestions?

**Comment by MikhailArkhipov** [comment]
@jflam or @smortaz ?

**Comment by MikhailArkhipov** [comment]
How's about

`R session is not running. Use Workspaces window to start new R session`.

**Comment by jflam** [comment]
How's about:

`Your R session is not running right now. Use the Workspaces window to start a new R session.`

**Comment by MikhailArkhipov** [comment]
Next localization pass, can't be adding new strings right now.

**Comment by smortaz** [comment]
Include the menu path or better, shortcut in msg:

... use the Workspaces window (Ctrl-N)...

**Comment by MikhailArkhipov** [comment]
Putting shortcuts is not recommended since they depend on the current profile and user customizations.

**Comment by smortaz** [comment]
Ok. R Tools | Workspaces
