### ISSUE TITLE
Graphic window appears every time I start Visual Studio

### ISSUE THREAD

**Issue by lebelinoz** [Microsoft/RTVS#3354]
I created a new R project in **Visual Studio with R Tools 1.0**.  Now, every time I open the solution from Visual Studio, a separate "Graphics" window appears.  How do I stop this from happening?

Projects created with **Visual Studio with R Tools 0.5** do not have this problem. _(erratum: yes it does)_

**Comment by huguesv** [comment]
Hi Alain, could you please paste a screenshot that shows this window?

**Comment by lebelinoz** [comment]
![image](https://cloud.githubusercontent.com/assets/10016385/24379722/0886c9bc-1394-11e7-88dc-44c90a8ce800.png)

**Comment by huguesv** [comment]
I don't really know what that thing is. I suppose it reappears when you click Reset on the Interactive Window?  Could it be part of your R profile startup script?
http://www.onthelambda.com/2014/09/17/fun-with-rprofile-and-customizing-r-startup/

**Comment by huguesv** [comment]
You would see it in R-Gui too if it's from your startup script.

**Comment by lebelinoz** [comment]
No, there's no .Rprofile file.  None was created when I let R Tools 1.0 create a new R project for me, and I didn't add one.

**Comment by MikhailArkhipov** [comment]
Could you post high res image? I can't tell hat are menu items there. Does the window close when you close VS or does it stay? If it stays, is there a process in task manager that can be associated with it? I.e. task that has same icon, for example?

**Comment by lebelinoz** [comment]
The menu items are

- Deducer
- Data
- Analysis
- Plots

There is something in Task Manager:  it's **Microsoft R Host**.  Ending that task makes the window go away without any consequences (though, to be fair, so does clicking the **X** in the corner of the window.

The window disappears on its own the instant I start closing Visual Studio.  In fact, it (and its task in Task Manager) disappears _before_ I get the "Save changes?" dialog.

**Comment by lebelinoz** [comment]
**Erratum:**  Actually, that Graphics window appears whenever I open an R project in Visual Studio, regardless of whether I created the project with R Tools 0.5 or 1.0

**Comment by MikhailArkhipov** [comment]
R Host is RTVS process which loads R.dll. The window appears to be something that may be coming from one of R packages automatically loaded by R. http://www.deducer.org/pmwiki/pmwiki.php?n=Main.DeducerManual perhaps?

**Comment by lebelinoz** [comment]
Thanks.  I just uninstalled Deducer from my machine by going `remove.package("Deducer")` and this seems to make the problem go away.  I don't even know why I had Deducer on my machine:  some random R package must have made me install it.

I do find it strange the R Tools 1.0 was invoking it, though.

**Comment by MikhailArkhipov** [comment]
RTVS does not invoke any particular package. My *guess* is that deducer does some profile modification or autoloads under certain conditions. We'll check it out, see if we can reproduce. Thanks for reporting.

**Comment by MikhailArkhipov** [comment]
I can repro with Deducer, rJava and Java 64. Apparently on call to `getNamespaceExports` (intellisense does it) Deducer attempts to create UI. RStudio outputs bunch of

```
> getNamespaceExports('Deducer')
Error in winMenuAdd : function not supported in RStudio
Error in winMenuAddItem : function not supported in RStudio
Error in winMenuAddItem : function not supported in RStudio
```

and this is why window does not appear there.

**Comment by MikhailArkhipov** [comment]
Probably just need to hook/override/suppress in the intellisense session

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/3899f4e70e0ce43eb4468d86de940aec2c0f3c4d
