### ISSUE TITLE
Error "Specified startup file does not exist" when I update my RTVS project to 1.0RTM

### ISSUE THREAD

**Issue by Masutani** [Microsoft/RTVS#3368]
Error "The specified startup file does not exist: " occurs when debug is started.

After I updated my RTVS to 1.0 RTM the debug session cannot start. Start up path seems to be set as $(SolutionDIr)$(SolutionName)\script.R which doesn't exist. It should be $(SolutionDir)$(ProjectName)\script.R. It cannot be fixed in a project file in the target project.

In interactive session, "script.R" can work properly.

**Comment by MikhailArkhipov** [comment]
May be related to #3371. Looking into it.

**Comment by MikhailArkhipov** [comment]
Most probably https://github.com/Microsoft/RTVS/commit/88d29bfd5198ec58edd1a7c3503c08ddf2b75a24 fixes this, but I will keep it open until we publish the update for verification

**Comment by Masutani** [comment]
Ok. I understand this issue allows only first project in solution.
I found work around to activate R project to run http://stackoverflow.com/questions/2244765/project-order-in-visual-studio-solution.
You can reorder target project to top in your solution by editing sln file.
Thank you.
