### ISSUE TITLE
Is it possible to exclude files/folders in rxproj?

### ISSUE THREAD

**Issue by mvacha** [Microsoft/RTVS#3370]
I'm working on a project that has some c++ files in it, but I do not want these to clutter up the Solution explorer. Is there a way to do that for rxproj? Or the oposite - set the root path of the project to be different from the folder containing the rxproj file?

Thanks.

**Comment by MikhailArkhipov** [comment]
No. R project is not typical VS project that lists files. It only reflects what in the project folder - so one can move R work between VS and RStudio as needed. In fact, rxproj file is not required. The file stores some targets, but does not store file list. One option may be to place files you don't want to see in a separate folder.

**Comment by mvacha** [comment]
Unfortunately I cannot change the project structure to fit VS (rxproj), so I'm trying to do the oposite.  
I tried excludes in the .rxproj files, but it didn't work. So next I tried symlinking (hard) the folders, but rtvs ignores [symlinks ](0d7eee975e63be577e5f94283d875e2fc3189559/src/ProjectSystem/Impl/IO/MsBuildFileSystemWatcher.DirectoryCreated.cs#L49):(  

This is how my Solution explorer looks like: so cluttered...
![solexp](https://cloud.githubusercontent.com/assets/2319571/24559572/80b4f0e6-163f-11e7-89f1-cc5b624f379c.png)

**Comment by MikhailArkhipov** [comment]
Perhaps you can do it the other way around. Add R files to C++ project in a folder. RTVS does not need R project to operate. You can open and work on R files in any project.

**Comment by mvacha** [comment]
Thank you for pointing me in the right direction. I ended up using empty c# project (see this [SO answer](http://stackoverflow.com/a/21695488/4591040)), because it uses proper folders, instead of c++ filters. Now everyhing is nice and tidy and I can use the awesome intellisense from RTVS :)

![solution](https://cloud.githubusercontent.com/assets/2319571/24581263/80e9f97e-1718-11e7-9fc3-5c409a693820.PNG)
