### ISSUE TITLE
Package installation messages show up in REPL (Linux)

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3373]
⚹> install.packages("shiny");
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in utils::install.packages(...) :

 
 'lib = "/usr/local/lib/R/site-library"' is not writable
Would you like to use a personal library instead?  (y/n) 
y

Would you like to create a personal library
~/R/x86_64-pc-linux-gnu-library/3.2
to install packages into?  (y/n) 
y

**Comment by MikhailArkhipov** [comment]
Is this wrong?

**Comment by karthiknadig** [comment]
This is different behavior than on windows. To me for a user on windows connected to a linux/windows server, there should be no difference (ideally). This to me is a parity issue.

**Comment by int19h** [comment]
I think this might be a difference inherent to R itself? Basically it doesn't use GUI prompts on Linux?

BTW, when the package gets installed, how does the progress bar look like?

**Comment by karthiknadig** [comment]
```
Content type 'application/zip' length 2649191 bytes (2.5 MB)
downloaded 2.5 MB
=
=
=
=
=
=
=
=
=

```

**Comment by karthiknadig** [comment]
Removed this by mistake.
