### ISSUE TITLE
R Plot History windows slowing down Visual Studio

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3374]
![image](https://cloud.githubusercontent.com/assets/3840081/24565370/d95116fc-1609-11e7-99a1-0f277300795c.png)

**Comment by MikhailArkhipov** [comment]
These are all BS warnings. VS is working on improving them. I've seen 'C# is slowing down'. Basically anything at startup time longer than certain amount is flagged. Ignore.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/24724675/e1bb0a6e-1a00-11e7-9f3e-cec9dfe7ca52.png)

**Comment by karthiknadig** [comment]
I am closing this issue, since it doesn't look like RTVS bug.
