### ISSUE TITLE
R Markdown publish command fails on linux with pandoc not available.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3376]
This is after installing pandoc and pdflatex. The check in the command specifically looks for "pandoc.exe"  and "pdflatex.exe". On linux it should look for "pandoc" and "pdflatex"

**Comment by MikhailArkhipov** [comment]
Should we be checking for both? Or perhaps session should be telling if it is on *nix? Or maybe add special method like `CheckExecutableExistsOnPath` to the session commands instead of code doing 

`Session.EvaluateAsync<bool>(Invariant($"rtvs:::exists_on_path('{fileName}')")` directly?
