### ISSUE TITLE
Autocompletion for ::: should contain all of the functions from the package namespace environment, not just the exported ones.

### ISSUE THREAD

**Issue by mvacha** [Microsoft/RTVS#3379]
I know it's not very common to use ::: for calling not exported functions but it still would be nice to show proper intellisense for it. RBox for Sublime "supports it" (on the other hand the autocomplete for :: is wrong in the RBox).

I have found relevant issue #2507, but it seems to me, that it got fixed only for the rtvs "special package".

RBox:
![namespace](https://cloud.githubusercontent.com/assets/2319571/24581495/ec4c830e-171c-11e7-9b38-70aacb9f1c1e.PNG)

RTVS:
![rtvs](https://cloud.githubusercontent.com/assets/2319571/24581500/f0cc7a24-171c-11e7-941a-c6b85e096e26.PNG)

**Comment by MikhailArkhipov** [comment]
We currently use 

```
package.functions.names <- function(packageName) {
    as.list(union(
		tryCatch({
			getNamespaceExports(packageName)
		}, error = function(e) {
			return(c())
		}), 
		tryCatch({
			ls(paste0('package:', packageName))
		}, error = function(e) {
			return(c())
		})
	))
}
```
located in packages.R in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\R Tools....\rtvs

We could try

`ls(getNamespace("testthat"), all.names = TRUE)`

instead. You can change it directly in the RTVS package and try :-)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/eab57cd565512d22dce04fa67733bdc386591dd0
