### ISSUE TITLE
Add OS specific instructions for pandoc and tex installation for remote

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3383]
If pandoc or miktex(windows)/texlive(liinux) is not installed then we current show messages relevant to windows. we need to show instruction based on the remote OS.

Pandoc:
all platforms: http://pandoc.org/installing.html

Tex
Windows: https://miktex.org/download
Ubuntu/Debian: https://www.tug.org/texlive/debian.html
RHEL:
SLES:

**Comment by MikhailArkhipov** [comment]
You may want to file doc bugs at https://github.com/Microsoft/RTVS-docs

**Comment by karthiknadig** [comment]
This is also to change the resources, in RTVS, to provide the platform specific message (in the message box).

**Comment by karthiknadig** [comment]
Added a doc bug to provide documentation as well:
https://github.com/Microsoft/RTVS-docs/issues/69

**Comment by MikhailArkhipov** [comment]
Closing in favor of the doc repo bug
