### ISSUE TITLE
Windows: Use LoadLibrary to load R library instead of linking to it

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3386]
LoadLibrary/dlopen

**Comment by karthiknadig** [comment]
Windows side is done. Reducing the estimate.

**Comment by MikhailArkhipov** [comment]
Since this is marked as Windows, I guess it is done?

**Comment by karthiknadig** [comment]
There is broker side change pending. did not make that since we were refactoring everything.

**Comment by karthiknadig** [comment]
I will close this since the main work is done. However, thee is some impact due to R 3.4 which i will handle separately.
