### ISSUE TITLE
Where is the template "SQL R Stored Procedure" ? 

### ISSUE THREAD

**Issue by tja2000** [Microsoft/RTVS#3389]
I installed the necessary tools, but do not see the template..

**Comment by MikhailArkhipov** [comment]
Do you see R node? Is there R Tools menu?

![image](https://cloud.githubusercontent.com/assets/12820357/24724113/d30abc32-19fe-11e7-8c55-04ba40478437.png)

**Comment by tja2000** [comment]
I see all except the Stored Procedure with R. Re-ran the setup but no change. Do I need to connect to a SQL 16 maybe first?

**Comment by MikhailArkhipov** [comment]
Do you have SQL Tools installed?

**Comment by tja2000** [comment]
I did, but not sure how to check. Maybe something went wrong there? I do have an older version of SQL enterprise manager installed... Thx anyway!

**Comment by MikhailArkhipov** [comment]
What is in Help | About installed products list?

**Comment by tja2000** [comment]
See attached screenshots.
![rtools_1](https://cloud.githubusercontent.com/assets/11030714/24851376/afb0859a-1dd3-11e7-90b2-a6f1d87be543.PNG)
![rtools_2](https://cloud.githubusercontent.com/assets/11030714/24851383/b29918da-1dd3-11e7-8bdb-74143610a187.PNG)

**Comment by tja2000** [comment]
closed too soon.

**Comment by tja2000** [comment]
OK, I am getting a bit further now. In my situation there is no "SQL SP with R" when adding a new **FILE**. However when adding a new **ITEM** it is there.  Is this the way it should behave?
