### ISSUE TITLE
Microsoft R Open 3.3.3

### ISSUE THREAD

**Issue by impressio** [Microsoft/RTVS#3394]
I am getting multiple errors when testing codes initially written with R Studio. 

E.g. `package 'limma' was built under R version 3.3.3 `

Also, Microsoft R Open 3.3.3 was released today.

Are the errors and the new MRO 3.3.3 release related? Did installation of packages built under the new MRO 3.3.3 version cause the error (the new 3.3.3 version packages were also "released")? Could It be ignored?

However MRO 3.3.3 fails to install ([MSDN Forums: Windows microsoft-r-open-3.3.3 Installation Error](https://social.msdn.microsoft.com/Forums/en-US/4e1cf648-61af-41fe-8ace-0725fdb12427/windows-microsoftropen333-installation-error?forum=ropen), [MSDN Forums: ropen](https://social.msdn.microsoft.com/Forums/en-US/home?forum=ropen)).

Will there be an R Client 3.3.3 för VS2015 or is it aimed at VS2017 or both?

**Comment by Hong-Revo** [comment]
> `package 'limma' was built under R version 3.3.3`

That's not an error, it's just a message. Unless you actually see your code fail, you can ignore it.

**Comment by MikhailArkhipov** [comment]
RTVS is not linked or anyhow tied to MRO or the other way around. MRO is standalone and not related to VS and RTVS can be used with any R, Microsoft or CRAN. So there is no 'MRO for VS 2015' really.

And yes, the message is a basic warning. It is unlikely that minor version difference will cause problems. MRO questions is better to ask in the MSDN forum, it is monitored by the proper people :-)
