### ISSUE TITLE
Get tooltip for nested function call

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3398]
In the screenshot below, my mouse pointer is on top of `cos`. Is there a way to make the tooltip for the inner function show up, instead of the outer one?

![image](https://cloud.githubusercontent.com/assets/11328890/24812024/d38dbee8-1c0b-11e7-833e-071c1b19d877.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/49c60b01937430798d1f6218947741d875be2189
