### ISSUE TITLE
rmarkdown and relative paths?

### ISSUE THREAD

**Issue by tja2000** [Microsoft/RTVS#3404]
I reference files using a relative path, e.g. read.csv2("../data/file.csv"). It works interactively but when using the code in r markdown I always get Error in file(file, "rt") : cannot open the connection.
When I execute using ctrl+enter it does work fine, the working directory is correctly set. Is there a specific setting for the rmarkdown startup directory?

**Comment by Hong-Revo** [comment]
I guess the error occurs when you try to Preview HTML/PDF/Word? If so, that's because RTVS runs the knitting from a temporary directory. It should work if you knit the document manually with `rmarkdown::render()`.

**Comment by tja2000** [comment]
Yes, this works. Is there a way to default knitr to the current workdirectory?
Thanks!

**Comment by MikhailArkhipov** [comment]
You can try and change working directory explicitly before reading file with 'setwd'
