### ISSUE TITLE
No Quick Info tooltips from functions from imported packages

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3414]
```r
library(dplyr)
select()
```

Note that `select` is in the completion list, but 1) it doesn't show the signature, 2) there's no signature help after typing '(' and, 3) hovering over `select` does not produce any tooltip.

On the other hand, functions from standard packages that are implicitly imported (e.g. `base` and `utils`) work as expected.

Possibly related to https://github.com/Microsoft/RTVS/issues/3398

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/25058455/67f02022-212e-11e7-907b-5ab9a73fdb01.png)

![image](https://cloud.githubusercontent.com/assets/12820357/25058460/75f62b62-212e-11e7-8ef7-0ab43bb7b6c3.png)

this may happen if timeout expires while waiting for the information from R. Editor is not async so it drops wait after ~500ms it it wouldn't block UI. Does it 100% repro or shows up eventually?

**Comment by MikhailArkhipov** [comment]
So it reproes after

```
library(dplyr)
library(MASS)
```

The reason is that
```
                    var request = await EvaluationRequest.SendAsync(this, expression, kind, cancellationToken);
                    return await request.Task;
``` 

never returns executing `"rtvs:::signature.help2('select', 'MASS')"`

**Comment by int19h** [comment]
This is interesting, but I'm not sure it's what I hit - I didn't have `library(MASS)` anywhere, it was just `dplyr` and `tcltk`.

**Comment by MikhailArkhipov** [comment]
I can't repro again, but when could, I tried killing intellisense host in the task manager and it never restarted. Calls to start host went to the lock acquisition code which then decided the host was already running.

**Comment by MikhailArkhipov** [comment]
Lack of tooltip or signature means the call above failed and editor could not get the RD description. so I am pretty sure it was same thing.

**Comment by MikhailArkhipov** [comment]
I believe it was same as #3424. https://github.com/Microsoft/RTVS/commit/e3472df2a6a339a66a77633c803a0dfa4439f7b4
