### ISSUE TITLE
Available packages missing description

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3415]
I am using Microsoft R open 3.3.3.0

![image](https://cloud.githubusercontent.com/assets/3840081/25056867/7a3c298c-2120-11e7-9e79-70c7969a903a.png)

**Comment by MikhailArkhipov** [comment]
This info is not instantly available and populated asynchronously AFAIR.

**Comment by karthiknadig** [comment]
It shows up correctly on MRO 3.3.2

**Comment by karthiknadig** [comment]
Looks like the RDS merge seems to generate two rows with the same name. We try to set the row names and that is failing and hence the description data is not merged with available packages.

**Comment by MikhailArkhipov** [comment]
![image](https://cloud.githubusercontent.com/assets/12820357/25058508/eea064d8-212e-11e7-9da2-22839b9ac878.png)

**Comment by MikhailArkhipov** [comment]
I've been using 3.3.3 for a while now... @AlexanderSher may comment on how exactly this is populated.

**Comment by karthiknadig** [comment]
I think the issue is with MRO 3.3.3.

**Comment by MikhailArkhipov** [comment]
Interesting. MRO is supposed to be identical to CRAN, it is only different in linked libraries. Yes, I can repro with MRO 3.3.3 in Available tab only.

**Comment by karthiknadig** [comment]
Isn't this a bug on MRO?

**Comment by AlexanderSher** [comment]
Not sure if they promised us anything about compatibility.

**Comment by Hong-Revo** [comment]
This may be due to a glitch with MRAN. The site was actually [down for a few hours](https://stackoverflow.com/questions/43386602/microsoft-r-open-package-install-issue) last week.

**Comment by MikhailArkhipov** [comment]
I can actually repro with stock 3.3.3. AFAIK MRO says it is 100% compatible with stock except that it is using Intel libraries for performance. BTW package manager doesn't see to reload when switching between different workspaces. It really should. Also, 

![image](https://cloud.githubusercontent.com/assets/12820357/25143382/0bed60fc-241f-11e7-81dd-6d3caf97e2ca.png)

**Comment by MikhailArkhipov** [comment]
Bumping up priority. Need to investigate and handle before the next 2017 15.2 preview.

**Comment by MikhailArkhipov** [comment]
Reverting didn't help. Actually, it reproes for me even with 3.3.2

**Comment by MikhailArkhipov** [comment]
So initial error message happens b/c PM is created by VS as tool window is persistent. I think it either should not be persistent (it affects perf so we get 'PM is slowing down VS' gold bar). Still need to handle reconnection.

**Comment by AlexanderSher** [comment]
I've checked the VS part - it does everything as expected, so we need to dig R code

**Comment by AlexanderSher** [comment]
> BTW package manager doesn't see to reload when switching between different workspaces.

Just checked, it reloads both Installed and Loaded panes. Do you have a specific repro?

**Comment by AlexanderSher** [comment]
Ok, I've found the regression. It is in XAML.

**Comment by MikhailArkhipov** [comment]
OK. what changed?

**Comment by huguesv** [comment]
The original bug, as filed by @karthiknadig occurred only on MRO 3.3.3.0. We investigated it together and found that the merge code was producing 2 rows for the restfulr package.
https://github.com/Microsoft/RTVS/blob/564b8b4851fc042227d071601976b439436e0594/src/Host/Client/Impl/rtvs/R/packages.R#L73

Then the next line, https://github.com/Microsoft/RTVS/blob/564b8b4851fc042227d071601976b439436e0594/src/Host/Client/Impl/rtvs/R/packages.R#L76, was failing because it tried to assign the same name for 2 entries in the same list.

**Comment by MikhailArkhipov** [comment]
I am on 3.3.2 and I am seeing partial data

![image](https://cloud.githubusercontent.com/assets/12820357/25145758/b4eba400-2426-11e7-969c-741767e0898a.png)

**Comment by AlexanderSher** [comment]
Ok, but there is also a XAML issue :)

**Comment by AlexanderSher** [comment]
@huguesv , what do you think about original bug? Should we do something on our side or should we notify MRO?

**Comment by MikhailArkhipov** [comment]
You'd need to have reliable repro specific to MRO 3.3.3.

**Comment by AlexanderSher** [comment]
Here is the minimal repro:
```r
url <- gsub("src/contrib", "web/packages/packages.rds", "https://mran.microsoft.com/snapshot/2017-03-15/src/contrib")
path <- tempfile('pkg', fileext = '.rds')
suppressWarnings(download.file(url, destfile = path, quiet = TRUE, mode = "wb"))
fields <- c('Package', 'Title', 'Description', 'Built', 'URL', 'Author')
details <- readRDS(path)
details <- as.data.frame(details, stringsAsFactors = FALSE, rownames = extra[, 'Package'])
details <- details[fields]
restfulr <- subset(details, Package == "restfulr")
```

`restfulr` contains two records.

**Comment by MikhailArkhipov** [comment]
So this is MRO 3.3.3 only right?

**Comment by AlexanderSher** [comment]
No, it is specific to https://mran.microsoft.com, to all snapshots starting from https://mran.microsoft.com/snapshot/2017-03-08/src/contrib

**Comment by MikhailArkhipov** [comment]
But don't we use standard mirror by default?

**Comment by AlexanderSher** [comment]
https://mran.microsoft.com is a default for MRO

**Comment by huguesv** [comment]
We can remove duplicates just like we do for `installed.packages` (3rd line added, in `add.details` ):
```
        pkg.rds.path <- download.packages.rds(repo.url)
        repo.details <- read.packages.rds(pkg.rds.path)
        repo.details <- repo.details[!duplicated(repo.details[, 'Package']),]
        repo.available.with.details <- merge(repo.available, repo.details, by = 'Package', all.x = TRUE)
```

**Comment by AlexanderSher** [comment]
We can filter that manually using package name or call `unique`, but the later will have some perf implications:
```r
> microbenchmark(unique(details))
Unit: milliseconds
            expr      min       lq     mean   median       uq      max neval
 unique(details) 28.95504 30.05033 31.75493 30.50633 31.95296 72.15795   100
```
```r
> microbenchmark(details[!duplicated(details$Package),])
Unit: milliseconds
                                    expr      min       lq     mean   median
 details[!duplicated(details$Package), ] 1.495571 1.771408 2.285385 1.929763
       uq     max neval
 2.352957 5.72752   100
```

**Comment by AlexanderSher** [comment]
Ok then, added to PR
