### ISSUE TITLE
Sorting indicator in Grid View is wrong

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3416]
```r
View(mtcars)
```
then click on `mpg` column:
![image](https://cloud.githubusercontent.com/assets/1175142/25056971/36bd5946-2121-11e7-9ff7-d216ff575f0d.png)

Note that the arrow indicates that sorting is descending, but it's actually sorting ascending. If you click on the column again, the arrow will show ascending sort, but actual sorting is descending. Basically, it's always the opposite of what it should be.

In addition, I would expect the first click to sort the rows ascending, rather than descending (as is the usual behavior for sortable lists and tables). It might be that this is the actual root cause here - that the UI flag is simply in the incorrect initial state.

**Comment by MikhailArkhipov** [comment]
Hm interesting. Been like this since the beginning...

**Comment by smortaz** [comment]
ouch :)
