### ISSUE TITLE
Allow mouse wheel scroll in any area of View() window

### ISSUE THREAD

**Issue by ebs238** [Microsoft/RTVS#3417]
mouse wheel scroll only  works when the mouse is positioned over the horizontal or vertical scroll bars. Ideally, this scrolling would work if the mouse is positioned over any area of the grid window produced by a call to `View()`. It appears that the scrolling also works if the mouse is over a grid line, but not if the mouse is over the data area of a cell in the grid

Also, it would be nice to be able to select/highlight a row or multiple rows in the grid

**Comment by smortaz** [comment]
+1
