### ISSUE TITLE
VS2015+RTVS on Win 10 not setting working directory of a project

### ISSUE THREAD

**Issue by virusme** [Microsoft/RTVS#3426]
I have VS2015(Enterprise) + RTVS installation on a Win7 and a Win10 machine.

I have an r-project with a main RMD file that needs to be converted to HTML (using "preview HTML"). RMD file has "source()"commands to source multiple R files.  When i "preview HTML" on WIn7, it works fine. But on Win10, it gives "cannot open connection" error.  After lots of head scratching, it boils down to - on Win10 somehow opening a RPROJECT does not set the working directory to the project directory when processing RMD file!  It always reverts to "ÄppData/Local/Temp/xxxxxx" as working directory!

To re-create this error:
1. create a /YOUR_LOCATION/RPROJ with a "test.RMD" inside the project, on Win 7 machine
2. inside "test.RMD" include "getwd()" (to display working directory)
3. run "preview HTML" 
4. generated HTML file will show "YOUR_LOCATION"

1. Open /YOUR_LOCATION/RPROJ on Win10 machine
2. run "preview HTML"
4. generated HTML file will show "ÄppData/Local/Temp/xxxxx"

Happy to elaborate further, if required.

Note: I have tried contacting Microsoft Visual Studio Enterprise support, got kicked around like a football   for just creating the ticket (which by the way has not been created yet!) and they had not even started with the actual problem. Hopeless!

**Comment by smortaz** [comment]
Sorry about that! For Python and R you should use github to file bugs and
you will be directly taken care of by the development team :-)

**Comment by virusme** [comment]
I am under the impression that with bulk licensing+support agreement, we will get premium support irrespective of the product.

**Comment by smortaz** [comment]
It would eventually route to us. That's why in the product's R menu we
direct you straight to github to avoid getting passed around. I will check
into why it did not route to us quickly. Thanks for the heads up

**Comment by MikhailArkhipov** [comment]
Also #3404

**Comment by virusme** [comment]
Thanks @smortaz and @MikhailArkhipov for including this in your next sprint.

**Comment by MikhailArkhipov** [comment]
It is actually current one :-) We hope to fix it for when 1.1 goes out with 2015 ans 2017. Which is very soon.

**Comment by virusme** [comment]
@MikhailArkhipov. Thank you. Do you have a date for v2017?

**Comment by MikhailArkhipov** [comment]
Data Science workload should be in 2017 early May. About same time we'll update 2015 to 1.1

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/364065d9db534e8935bd3b9bd61e9214052606c5

**Comment by virusme** [comment]
@MikhailArkhipov is this version ready to ship/download?

**Comment by MikhailArkhipov** [comment]
https://aka.ms/rtvs-current

**Comment by virusme** [comment]
@MikhailArkhipov It appears that this issue has not been resolved in the update. Erratic behaviour still persists. I was unable to re-open this issue hence created a new one here: https://github.com/Microsoft/RTVS/issues/3569
