### ISSUE TITLE
Parts of package manager UI not localized

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3431]
Tested with French language.

Available, Installed, Loaded
Licensing warning + Do not show this again checkbox
Labels in the details page

![image](https://cloud.githubusercontent.com/assets/1696845/25214139/82168750-254a-11e7-9c82-598fb70b806b.png)

**Comment by AlexanderSher** [comment]
No repro in latest build:

![image](https://cloud.githubusercontent.com/assets/8933858/25311364/a13f1382-27c4-11e7-9652-21f5afa9f6ad.png)
