### ISSUE TITLE
Parts of plot, plot history window not localized

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3433]
Tested with French language.

These words appear in tool window caption / content. They are correctly localized in the menu item (circled blue).

RPlot
Device
Active

![image](https://cloud.githubusercontent.com/assets/1696845/25214752/dd0c1974-254d-11e7-8918-ac4504f44f53.png)

**Comment by huguesv** [comment]
Here's additional text from plot and plot history.

![image](https://cloud.githubusercontent.com/assets/1696845/25215296/6eb0bbf2-2551-11e7-93ed-dbf8af0f1dbe.png)

**Comment by AlexanderSher** [comment]
All strings are in resx files already

**Comment by AlexanderSher** [comment]
No repro in latest build:

![image](https://cloud.githubusercontent.com/assets/8933858/25311377/e850f8da-27c4-11e7-87b3-bb4ff01e5323.png)
![image](https://cloud.githubusercontent.com/assets/8933858/25311379/ef4df8e0-27c4-11e7-8df4-7486cb785382.png)
![image](https://cloud.githubusercontent.com/assets/8933858/25311382/f4057f16-27c4-11e7-94f0-b6ed7ca72e8b.png)
