### ISSUE TITLE
Terminating R message box not localized

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3435]
Tested with French language.

```
---------------------------
Microsoft Visual Studio
---------------------------
Terminating R will immediately abort calculations and all workspace objects will be discarded. This action cannot be undone.



Are you sure you want to terminate R session?
---------------------------
Yes   No   
---------------------------
```

**Comment by AlexanderSher** [comment]
Text is in resource file. @MikhailArkhipov , do we need to do anything else to make it localized?

**Comment by MikhailArkhipov** [comment]
file a bug in the loc db.

**Comment by MikhailArkhipov** [comment]
@huguesv should open bug there or I someone - just register there for access. Then you can close this one.

**Comment by AlexanderSher** [comment]
No repro in latest build:

![image](https://cloud.githubusercontent.com/assets/8933858/25311374/cc7d98e8-27c4-11e7-9bea-3613d4ffb7d1.png)
