### ISSUE TITLE
Source startup file command caption not localized

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3437]
Tested with French language.

"Source startup file" is the caption for F5 on the toolbar.

For reference, I've circled the "Set As Startup R Script" which has been localized already.

![image](https://cloud.githubusercontent.com/assets/1696845/25215205/cf55b0d0-2550-11e7-883d-d62bc293e9ca.png)

**Comment by MikhailArkhipov** [comment]
Still needs fixing? Looks like a loc bug rather than code bug
