### ISSUE TITLE
RTVS not installing

### ISSUE THREAD

**Issue by emveevee** [Microsoft/RTVS#3440]
![rtvs block](https://cloud.githubusercontent.com/assets/18753286/25306288/f2ce8450-2781-11e7-8052-18d4798a473f.PNG)
I have installed 
1. SSDT  -Community edition of Visual Studio 2015
2. Microsoft R
3. R GuI
When I attempt to install the R tol for Visual Studio I get above error message.
Also this tool is missing when I search from the menu Tools>Visual Studio Gallery>tools>Programming languages in the above Visual Studio 2015. So I am nable to add it this way either.
Any help appreciated greatly and thanks in advance for your time.

**Comment by MikhailArkhipov** [comment]
This is by design SSDT is reduced version of visual studio (it is based on integrated shell) and misses many components RTVS needs. Please install full Community edition, it includes SSDT functionality.

**Comment by emveevee** [comment]
Thanks
