### ISSUE TITLE
Not working with R 3.4.0

### ISSUE THREAD

**Issue by cg31** [Microsoft/RTVS#3441]
Maybe others already found out, RTVS+VS2015 is not working with latest R3.4.0, there is a exception in R.dll.

**Comment by MikhailArkhipov** [comment]
```DllInfo *dll = R_getEmbeddingDllInfo();```

**Comment by MikhailArkhipov** [comment]
May need #3386. @karthiknadig ?

**Comment by MikhailArkhipov** [comment]
```
		CharacterMode = LinkDLL;
		setup_Rmainloop();
		CharacterMode = RGui;
		
		DllInfo *dll = R_getEmbeddingDllInfo();
```

I seems that `R_getEmbeddingDllInfo` must be called after `setup_Rmainloop` since the latter calls `InitDynload` which allocates `LoadedDll` via `initLoadedDLL`

**Comment by cg31** [comment]
This brings up another question, when I have both R3.4 and R3.3 installed, how can I choose a version? If I know correctly,  in Python tools, you can choose between Python 2 or Python 3.

**Comment by smortaz** [comment]
To choose between Rs use the R Tools | Workspaces window

**Comment by MikhailArkhipov** [comment]
Will be publishing update soon

**Comment by MikhailArkhipov** [comment]
Needs more work. Plotting API has changed.

![image](https://cloud.githubusercontent.com/assets/12820357/25404200/d93f4496-29b3-11e7-9a5c-9cf2da1de750.png)

**Comment by huguesv** [comment]
Unfortunately, the `_DevDesc` struct in GraphicsDevice.h, which we redefine in RGraphicsapi.h, now has a new field added to it around the middle of the struct:
```
    Rboolean canGenIdle;      /* can the device generate idle events */
```

We're going to have to define both versions, and dynamically pick the right one at runtime.

**Comment by int19h** [comment]
We might need to revisit the decision to use R headers directly. If we're going to be defining different versions of structs for different R versions, we'll have to curate our own header again.

Alternatively, we can build a separate host binary for every R version with a different API.

**Comment by karthiknadig** [comment]
@int19h I had made the build "RHost by R version" suggestion, for the future.

**Comment by MikhailArkhipov** [comment]
Works now. Will appear in RTVS 1.1 and VS 2017 next preview.
