### ISSUE TITLE
RTVS Verson 1.0.30321.1407 with VS 2015 Community edition does not save R

### ISSUE THREAD

**Issue by TheBharath** [Microsoft/RTVS#3442]
The latest version of RTVS does not save the workspace when this is enabled via Tools ->Options see screen shot.  I have managed to do a workaround by typing the following in the R Interactive Windows

save.image(file = ".RData")

![image](https://cloud.githubusercontent.com/assets/17170159/25316167/8e376e5e-2816-11e7-8628-e4241d771f92.png)

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02046

R Tools for Visual Studio   1.0.30321.1407

R Version 3.3.2

**Comment by MikhailArkhipov** [comment]
I assume you do have project correct? If there is no project settings do not apply.

**Comment by sdgilley** [comment]
I have this problem as well.  We do have a project which was created from a previous version of RTVS.

**Comment by MikhailArkhipov** [comment]
@AlexanderSher - any news?

**Comment by AlexanderSher** [comment]
Yes, I think I've found the reason, though I'm not sure how to fix it.
`UnconfiguredProject.ProjectUnloading` may be executed after `VsAppShell.OnApplicationClosing`, and so RSession get disposed before its data is saved. 
There is no issue if solution is closed without closing VS itself.

**Comment by MikhailArkhipov** [comment]
`OnApplicationClosing` is generate by IDE for registered OLE components. Yes, it is `OLE 2`. One option is to listed to WPF dispatcher shutdown (not sure if happens before or after the OLE event). Another is try [DTE ](http://stackoverflow.com/questions/14679217/how-to-detect-if-visual-studio-ide-is-closing-using-vspackage)instead.

**Comment by AlexanderSher** [comment]
I'm currently digging into CPS sources to find out when `ProjectUnloading` is called

**Comment by MikhailArkhipov** [comment]
The problem here is that it is async and technically async (and idle) methods can be executed after the shutdown event. I already seen this in the new code base and had to remove throwing of object disposed from service manager and just return null of some code asks for a service after the shutdown event.
