### ISSUE TITLE
Tooltip is rendered at the wrong location in VS 2017 (version 15.2 (26419))

### ISSUE THREAD

**Issue by mvacha** [Microsoft/RTVS#3443]
![tooltip](https://cloud.githubusercontent.com/assets/2319571/25334282/53034f28-28ee-11e7-9507-e4acaa80a1a0.PNG)

IntelliSense for the function name (alist) was shown as you would expect (at the normal location), but tooltips/intellisense for arguments is few hundred pixels below the cursor.

**Comment by MikhailArkhipov** [comment]
It looks like there is a missing closing brace for the `alist(`? I see red squiggle at the `}`. It might be that incomplete structure means position is still in the `alist` list of arguments that spans several lines. RTVS calculates argument positions and span of the argument list and the VS editor may show tooltip at the end of the argument list. I can't see the end of the second line after the `alist(` - do you think the function argument list is closed?

**Comment by mvacha** [comment]
I wanted to dig a bit deeper, but I'm unable to reproduce it now :(

You are right, that the closing brace is missing, but the cursor is just after the opening brace of alist, so I assumed VS knows it's "in the process of writing" and it always shows tooltip near the cursor.

![tooltip2](https://cloud.githubusercontent.com/assets/2319571/25348772/a44a2ba0-291f-11e7-8664-bfb091d03fba.PNG)

**Comment by MikhailArkhipov** [comment]
R in that sense is a bit hard to handle since syntax technically allows any expression in arguments, arbitrarily long. C# at least requires { }.
