### ISSUE TITLE
Don't reference Microsoft.VisualStudio.Text.Internal from Private Assemblies

### ISSUE THREAD

**Issue by JoshVarty** [Microsoft/RTVS#3447]
I'm about to move `Microsoft.VisualStudio.Text.Internal.dll` out of `/PrivateAssemblies` and into `/CommonExtensions/Microsoft/Editor` with the rest of the editor team's assemblies. 

I noticed that your project will be affected by this move as you've referenced the DLL here: https://github.com/Microsoft/RTVS/blob/3cb1216547a8e8c5dac885a9f6a8a6b01958c258/src/EditorTestApp/Microsoft.Languages.Editor.Application.csproj#L85-L87

Consider either:
 - Referencing the Roslyn team's [NuGet package](https://www.nuget.org/packages/RoslynDependencies.Microsoft.VisualStudio.Text.Internal/) for this DLL
 - Using the editor team's MyGet feed. It's still being created but will have nightly builds of the editor team's DLLs. ([Text.Data](https://www.myget.org/feed/vs-editor/package/nuget/Microsoft.VisualStudio.Text.Data), [Text.UI](https://www.myget.org/feed/vs-editor/package/nuget/Microsoft.VisualStudio.Text.UI) etc.)

If you let me know which option you prefer, I can submit a PR with the change.

**Comment by JoshVarty** [comment]
Here as well: https://github.com/Microsoft/RTVS/blob/3cb1216547a8e8c5dac885a9f6a8a6b01958c258/src/Windows/R/Components/Test/Microsoft.R.Components.Test.csproj#L38-L40

**Comment by MikhailArkhipov** [comment]
OK, thanks. We reference it b/c of some types otherwise unavailable. Will switch ASAP.

**Comment by MikhailArkhipov** [comment]
Test code only

**Comment by MikhailArkhipov** [comment]
Looks like `RoslynDependencies.Microsoft.VisualStudio.Text.Internal` is deprecated and is only for VS 2017. We need the reference for 2015 as well as we support both.

Nightly references are a bit scary. We don't normally use nightly builds. I may try and just check in 14.0 and 15.0 assemblies for now.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bff548f912c9de6aaa6fead99c6378b72c20c20b
