### ISSUE TITLE
Intellisense for Parameters not working?

### ISSUE THREAD

**Issue by vykhand** [Microsoft/RTVS#3455]
Hi! I am trying to use intellisence to autocomplete function parameters and it seems it is not working.
For example, I am typing:

`rxImport(inData = infile, outFile = "airExample.xdf", strin`

and it does not propose stringsAsFactors as a parameter. 

Screenshot is attached.
![2017-04-27 23_43_10-rproject1 - microsoft visual studio](https://cloud.githubusercontent.com/assets/498481/25505770/a0657202-2ba3-11e7-989a-a7fb5198430b.png)

**Comment by MikhailArkhipov** [comment]
Looks like it is not working when close brace is missing. If it is auto-inserted, it does. We'll see if this can be improved.

![image](https://cloud.githubusercontent.com/assets/12820357/25630026/87233e48-2f20-11e7-848e-6148908e2139.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/a58b77c543da89568f119d66266f924e75c520b0
