### ISSUE TITLE
Error in project settings UI Run page

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3459]
Add value to collection of type 'System.Windows.Controls.ColumnDefinitionCollection' threw an exception.

![image](https://cloud.githubusercontent.com/assets/1696845/25548317/9abc983a-2c20-11e7-9eae-ed3fc536e8a1.png)

Microsoft Visual Studio Enterprise 2017 Int Preview
Version 15.2 (26424.2-Preview) d15rel Internal Preview - Dogfood
VisualStudio.15.IntPreview/15.2.0-Preview+26424.2.d15rel
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017   00369-60000-00001-AA743
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA743
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA743
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30404.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17114.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   4.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17114.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17114.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17114.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17114.1
Profiling support for Python projects.

R Tools for Visual Studio   1.1.30428.1005
Provides project system, R Interactive window, plotting, and more for the R programming language.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
TypeScript tools for Visual Studio

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/690cfa4067dcf020400c62c83b61839d0f360860
