### ISSUE TITLE
Variable Explorer consistently crashes with an exception

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3464]
Fresh install of VS 2017 RTM + today's bug bash bits. Repros with both R 3.3.3 and 3.4.0.

Just hit CTRL+8, and you'll get our generic exception message.

**Comment by MikhailArkhipov** [comment]
Same as https://github.com/Microsoft/RTVS/issues/3460, fixed

**Comment by MikhailArkhipov** [comment]
build in progress
