### ISSUE TITLE
Remote session sometimes loses R_LIBS environment setting when reset

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3466]
This is with RTVS remoting installed in a local VM. `R_LIBS` is a system env var set to `c:\rlib`, a directory I've created for installing third-party packages.

The problem cropped up when trying to install RSQLServer from Github, which depends on a number of other packages; installing rlang borked, and after resetting the session to try again, the environment variable was no longer found. The only solution so far is to reboot the VM.

**Comment by Hong-Revo** [comment]
One contributing factor I can think of: VS was idle for a length of time, maybe half an hour, before I tried the install. Maybe something went to sleep that didn't wake up?

**Comment by MikhailArkhipov** [comment]
Original issue was that installation of packages triggered rebuild of intellisense index and the rebuild loads packages and locks them causing conflicts. A notification was added so index would only start rebuilding after all dependent packages installed. However, this only applies to a single install.packages command (and its dependencies). If one executes multiple in sequence index update theoretically can start between commands. We can add some more throttling, but it won't be complete solution.

**Comment by Hong-Revo** [comment]
I'm confused; did you mean to reply to #3467? Or are you saying both bugs are aspects of the same underlying issue?

**Comment by Hong-Revo** [comment]
Also, it just happened again, this time after I'd left the PC idle for a few hours. I also got the socket error on trying to access help:
```
⚹> ?system2
starting httpd help server ...
Error in startDynamicHelp(TRUE) : unable to create socket
```

**Comment by MikhailArkhipov** [comment]
Yes, wrong bug. Moved comment to the right place.

**Comment by MikhailArkhipov** [comment]
@karthiknadig  can have a look

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/04af8fe0140dfe75dcac4ecb2b9bdd6630de951c
