### ISSUE TITLE
ESC key in Interactive Window cancels session

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3474]
We think that we'll need to handle waiting for input differently and prevent ESC from binding to Visual Studio Cancel command which is its usual behavior.

Repro:

Microsoft R Open 3.3.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft

Loading Microsoft R Client packages, version 3.3.3.0059. 
Microsoft R Client limits some functions to available memory.
See: https://msdn.microsoft.com/en-us/microsoft-r-client-windows for information
about additional features.

Type 'readme()' for release notes, privacy() for privacy policy, or
'RevoLicense()' for licensing information.

Using the Intel MKL for parallel mathematical computing(using 2 cores).
Default CRAN mirror snapshot taken on 2017-03-15.
See: https://mran.microsoft.com/.

Deleting autosaved workspace image '~/.Autosave.RData'.
> library(swirl)

| Hi! Type swirl() when you are ready to begin.
> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did
| then. If you are new, call yourself something unique.
What shall I call you? 
Tim

| Would you like to continue with one of these lessons?

1: R Programming Sequences of Numbers
2: No. Let me start something new.

Selection: Hit <Esc>

| Leaving swirl now. Type swirl() to resume.

**Comment by Hong-Revo** [comment]
I'm not sure if this is the same underlying bug, but for me, pressing Esc at an interactive prompt leaves the REPL in a wedged state:
```
m <- lm(mpg ~ ., mtcars)
termplot(m)
# press Esc
```
Resetting the workspace is the only way to recover. This is RTVS build 1.1.30423.1752.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/b4dc0762f6f834a72930255df499d7197ba264f3
