### ISSUE TITLE
R tools for visual studio now is not compatible with R 3.4.0

### ISSUE THREAD

**Issue by dasiav7** [Microsoft/RTVS#3494]
I installed R 3.4.0, and the Visual studio is just cannot be opened.

**Comment by karthiknadig** [comment]
This has been fixed #3441. Look for an update soon.

**Comment by MikhailArkhipov** [comment]
1.1 will be out next week. Also in VS 2017 15.3 Preview 1

**Comment by swayson** [comment]
I haven't been able to install the Microsoft R Client via the offline install method, as documented on Microsoft either. Keeps failing, not sure if it is related. 

It appears via conda it installs fine.
