### ISSUE TITLE
zoo objects are not sortable in Grid View

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3503]
```r
library(quantmod)
getSymbols('IBM')
View(IBM)
```
Then try clicking on headers. The row labels change according to the sort order, but actual data in the cells remain static.

**Comment by int19h** [comment]
This is because the standard way of sorting data in R containers doesn't work for zoo. The usual way is to do something like this:
```r
foo[order(foo$Column)]
```
The way this works, `order` returns the list of row indices, reordered according to the sort order. So the above might expand into something like:
```r
foo[c(3, 1, 2)]
```
Vectors, lists, data frames etc all respect this order, and will return the new data according to it.

But `zoo` objects are special in that regard, and it seems that they ignore order, and always return rows in order of their indices (e.g. for `quantmod` objects, it's dates). So `foo[c(1,2)]` is the same as ``foo[c(2,1)]` for them, and `order` simply doesn't work.

(The row labels are ordered properly because they're sorted separately from the data.)

Need to find out the proper way of doing sorting by column for `zoo`, or if one doesn't exist, then disable sorting for them altogether.

**Comment by int19h** [comment]
Looks like `coredata()` should do the trick.

**Comment by MikhailArkhipov** [comment]
It was done, right? Close?

**Comment by int19h** [comment]
No, it was a different bug related to this package. I opened this one after the fix for that other bug went in.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/235d2372fc802648005bd71d2291feaf7c2f84f4
