### ISSUE TITLE
Cancel editing of database connection removes it from the project settings property grid

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#3505]
Create new R Project
R Tools->Data->Add Database Connection
Click OK
Go to project settings
It should look like this:
![image](https://cloud.githubusercontent.com/assets/1696845/25766039/efcf47ee-31a4-11e7-9878-3815d88d138a.png)

Click the `...` button
Cancel out of the dialog

Result:
The entry is gone from the list.

![image](https://cloud.githubusercontent.com/assets/1696845/25766075/1f65d57c-31a5-11e7-99d6-61854c2492b9.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/5dee4c50b69ccd0d8a73b45767f2d3a953838b98
