### ISSUE TITLE
Unable to install R through Data Science Work Loads 

### ISSUE THREAD

**Issue by udayguntupalli** [Microsoft/RTVS#3521]
All, 
    I have 2 issues I am struggling with . 
1. Installing R using the Data Science Work Loads - I have tried to follow the instructions provided here (https://blogs.msdn.microsoft.com/visualstudio/2016/11/18/data-science-workloads-in-visual-studio-2017-rc/) but surprisingly for step (3) - I don't see any of the components listed for installing R . Please see attached picture 
![data science and analytical workload screenshot](https://cloud.githubusercontent.com/assets/16611561/25928535/96db76ec-35b1-11e7-809e-0a8bb83dc38b.png)

2. I have tried to use RTVS using Visual Studio 2015 and every time I close and re-open Visual Studio , my project throws up an error . 

![visual studio 2015 rtvs error](https://cloud.githubusercontent.com/assets/16611561/25928587/d64b14d6-35b1-11e7-8a06-7b1e7262921c.png)

I have spent considerable time just to try and get the installation going . Any help will be greatly appreciated. 

Best 
Uday

**Comment by Hong-Revo** [comment]
RTVS was pulled from Visual Studio 2017 for initial release, due to delays in localisation. It should be part of the next update, hopefully this week or next week.

**Comment by udayguntupalli** [comment]
@Hong-Revo : Thank you . I will look out for the next release . Can you kindly explain how I can solve (2) in case it persists into Visual Studio 2017 ?

**Comment by MikhailArkhipov** [comment]
The message is rather odd since opening project does not really start debugging. You can try

a) Open `admin` command prompt
b) Go to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE`
c) run `devenv /setup`

**Comment by udayguntupalli** [comment]
@MikhailArkhipov : I believe your suggestion is for Visual studio 2015 ? Will the same solution (with an updated path) be applicable in Visual Studio 2017 since I have moved to VS 2017

**Comment by MikhailArkhipov** [comment]
Yes, just use the appropriate path

**Comment by udayguntupalli** [comment]
@Hong-Revo  : I installed the new Visual Studio 2017 update that was published this morning. It does not solve the problem yet. it still does not feature the R installation like I notified earlier . Can you please guide on next steps ?

**Comment by MikhailArkhipov** [comment]
What does Help | About say (i.e. VS version)? In order to add DS you need to run installer again and select 'Modify'.

**Comment by udayguntupalli** [comment]
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.6) Release
VisualStudio.15.Release/15.2.0+26430.6
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

@MikhailArkhipov  : I have already done that and did not see "R" as an option

**Comment by MikhailArkhipov** [comment]
So you don't see

![image](https://cloud.githubusercontent.com/assets/12820357/26068781/8c4236bc-3953-11e7-9e70-60bf0248609a.png)

**Comment by udayguntupalli** [comment]
@MikhailArkhipov : 
After selecting the Data science and analytical applications workload - I see this 
![image](https://cloud.githubusercontent.com/assets/16611561/26068889/ef7fb31c-3953-11e7-8fdd-206ce3e51f59.png)


Instead of 

![image](https://cloud.githubusercontent.com/assets/16611561/26068918/16b0fe82-3954-11e7-9994-dc4dbb798125.png)

**Comment by Hong-Revo** [comment]
From that screenshot, it looks like you're installing a very old preview version of VS 2017. You should download the latest from https://www.visualstudio.com/downloads/

**Comment by udayguntupalli** [comment]
@Hong-Revo : 

Release Date: May 12, 2017 - Visual Studio 2017 version 15.2 (26430.06) - https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes

![image](https://cloud.githubusercontent.com/assets/16611561/26069300/3eef177a-3955-11e7-9e55-ad88364a073e.png)


In the release notes and documentation , the version number that is listed in the link provided matches with the version I have installed as shown in the screenshot - I dont think I have an old version ?

**Comment by MikhailArkhipov** [comment]
VS has several update delivery channels. As @Hong-Revo said - if you installed some preview, VS will update this preview. But it will not update it to real release. You need to install release from the visualstudio.com.

**Comment by Jax89** [comment]
I'm experiencing the exact same problem. I can install the Data Science Work Load but "R language support" and "Runtime Support for R Development" are missing on the right site selection window.  Only Microsoft R Client is visible. Logically RTools can not be found later on when starting Visual Studio.

**Comment by Hong-Revo** [comment]
@Jax89 , do you have R installed on your machine? Maybe installing it first might solve the problem. Just a stab in the dark.

**Comment by Jax89** [comment]
@Hong-Revo , R is installed. Running Win7 and a VS 2017 Community Edition. 
Installing RTVS with VS 2015 works perfectly fine.

**Comment by udayguntupalli** [comment]
@Hong-Revo @MikhailArkhipov : 
1. I uninstalled my Visual Studio 2017 using this link (https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes) 

2. https://www.visualstudio.com/vs/community/ 

Irrespective of the source link , the problem persists . Can you please provide the exact link to where I can find the Visual Studio 2017 Community with R in the "data science workload" 

Please

**Comment by udayguntupalli** [comment]
@jflam : Please kindly see if you can provide the right documentation to fix this problem ?

**Comment by jflam** [comment]
We are tracking issue #3561 where we are blocking installation of R in the VS 2017 Data Science Tools workload. To be clear, this is a bug, and we are working on fixing it in the next update. You should not have this issue on more recent operating systems.

**Comment by MikhailArkhipov** [comment]
Which OS it is? There is a but that prevents install on Win7. We are releasing patch soon, maybe next week.

**Comment by udayguntupalli** [comment]
@jflam : Thank you 

@MikhailArkhipov  : I am on Windows 7 . When an update is released , what is the correct delivery channel to pick the installer from ?

**Comment by MikhailArkhipov** [comment]
You should get regular update notification on the toolbar. It is normal VS update channel.

**Comment by udayguntupalli** [comment]
> VS has several update delivery channels. As @Hong-Revo said - if you installed some preview, VS will update this preview. But it will not update it to real release. You need to install release from the visualstudio.com. 

Referring to your previous quote , I did not want to be worried about having to deal with a preview version. How do I know I am not installing a preview ? Can you point to one location for a fresh installation that anyone could always rely on as the correct source if it is not too much to ask for

**Comment by jflam** [comment]
https://www.visualstudio.com/ is the best place to go.
