### ISSUE TITLE
Cannot open the R interactive window

### ISSUE THREAD

**Issue by dasiav7** [Microsoft/RTVS#3522]
As I said, I cannot open the R interactive window. And I cannot open the .sln which I built under visual studio 2015.

**Comment by MikhailArkhipov** [comment]
Which version of VS is it? Which version of R is it?

**Comment by dasiav7** [comment]
VS2017 and  R3.4.0  I just used the updated R tools for VS2017. And I cannot open the R interactive window  as well as  the .sln which I built under visual studio 2015 before.

**Comment by MikhailArkhipov** [comment]
3.4.0 is not supported yet (R changed plotting API). Next 15.3 update will have the support. 
https://github.com/Microsoft/RTVS/issues/3441
