### ISSUE TITLE
VS2017 hangs on new R project

### ISSUE THREAD

**Issue by DustinEwers** [Microsoft/RTVS#3525]
Please briefly describe what you were doing that led to the issue, if applicable:

I recently added the data science workload to try out R tools in VS 2017. When I try to create a new R project, the application just hangs. I tried doing a repair install and making sure I had all the latest updates. These things did not help. This is happening on two of my machines, so it's not a local VS issue. 
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

![capture](https://cloud.githubusercontent.com/assets/466287/26041498/fbee83e6-38f2-11e7-9417-d055631e69d7.PNG)

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by smortaz** [comment]
Hi. Sorry about that. Can you do a send frown from R Rools menu and attach
the logs? Thx

**Comment by MikhailArkhipov** [comment]
Which version for R are you using? Does File | New | R Script work? If it is R 3.4.0, it is not yet supported in VS 2017 15.2. (support comes in 15.3).

BTW, R Tools do not require projects you can just work with files if you want. R Project is not a typical VS project, it just a display of what is in the project folder.

**Comment by DustinEwers** [comment]
File -> New R Script gives me a script, but it doesn't look like there's any way to open it. Additionally it will not bring up the R interactive Window. 

I have three versions of R on my computer. 

From the logs: 

Installed R Engines (from registry):
Microsoft R Client (3.3.2.0) 3.3.2.0 C:\Program Files\Microsoft\R Client\R_SERVER\
Microsoft R Open (3.3.3.0) 3.3.3.0 C:\Program Files\Microsoft\R Open\
R 3.4.0 3.4.0 C:\Program Files\R\R-3.4.0

------------

That being said, I figured it out. Hat tip to @MikhailArkhipov for the version reminder. Once I uninstalled R 3.4.0, it worked again. 

Ideally, there would be some better error handling around that one 'cause a) that's a nasty error, and b) lots of people who are using RStudio and 3.4.0 are going to be trying this same thing. 

Thanks a bundle for the quick response. Have a good night.

**Comment by smortaz** [comment]
Yep we should have a better error. 3.4 came out just after VS lock down.
The new update has a fix. Out in ~ 2 weeks.

**Comment by MikhailArkhipov** [comment]
You don't have to uninstall 3.4. Start VS, open   R Tools | Windows | Workspaces. Select R 3.3.3 or below. After you made the selection, RTVS will remember and use it. It only uses latest when no selection was ever made.

Unforrtunately R 3.4 changed C++ API so there is no good way to know if it was compatible. 15.2 was already out when R 3.4 got published.

**Comment by MikhailArkhipov** [comment]
Alternatively, there is 15.3 available in preview channel https://www.visualstudio.com/vs/preview/. It installs side by side and does not affect main VS install. I, in fact, have 3 different ones :-)
