### ISSUE TITLE
switch from "microsoft r client (3.3.2.0)" to "r 3.4.0" hangs ide

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3529]
Please briefly describe what you were doing that led to the issue, if applicable:
i'm running w10 15063.296 and vs17 26430.6 with rtools 1.1.30413.0947 and am finding that when i attempt to switch from "microsoft r client (3.3.2.0)" to "r 3.4.0" the ide displays a progress circle and never completes.  I eventually have to force a close and restart of the ide.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Client (3.3.2.0): C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by MikhailArkhipov** [comment]
Please see release notes https://www.visualstudio.com/en-us/news/releasenotes/vs2017-knownissues - R 3.4.0 is not yet supported in 15.2. It is supported in 15.3 which is currently in preview.

**Comment by Hong-Revo** [comment]
Might want to update the readme on the front page :)

**Comment by myusrn** [comment]
Thanks for pointer to release notes coverage of this issue that i overlooked.  Is there a way for me to install the 15.3 preview at this time as my vs17 notifications pane has not offered it to me?

**Comment by MikhailArkhipov** [comment]
https://www.visualstudio.com/vs/preview/

This not an update over existing VS. Previews are installed in parallel. They never get updated to 'release' state. I.e. main line VS is updated to main line updates when they become available. Preview remains preview and continue receiving preview updates.
