### ISSUE TITLE
is vs17 rtools / data science workload supported in vs17 for mac

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3531]
Please briefly describe what you were doing that led to the issue, if applicable:

i'm currently working through a data science course and started using the vs17 rtools / data science workload in lieu of rstudio for assignments. i'd like to be able to refer other students to this experience but am wondering if the vs17 for mac installation also provides the rtools / data science workload.  I don't have a mac setup to test it on, any insights on this as i couldn't determine if its in there or not in vs17 for mac release notes.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Client (3.3.2.0): C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by MikhailArkhipov** [comment]
Visual Studio for Mac is totally different IDE that does not share code base with the Windows Visual Studio. Hence there is no R Tools (or Python) available there. At some point we are planning to provide R tools for VS Code which is cross-platform.
