### ISSUE TITLE
R interactive window does not open

### ISSUE THREAD

**Issue by tnguyen124893** [Microsoft/RTVS#3537]
![image](https://cloud.githubusercontent.com/assets/27941014/26103264/dcbbe790-3a62-11e7-888f-1e5993852488.png)
![image](https://cloud.githubusercontent.com/assets/27941014/26103410/73685246-3a63-11e7-9d4a-3d0d9c93bdef.png)

I cannot open R interactive window. Click it and nothing happens. Above is some information I believe will be useful. I use visual studio 2017 for R and it is connecting to R.3.4.0 on my computer

**Comment by MikhailArkhipov** [comment]
R 3.4 is not yet supported in 15.2 sorry. You can either install preview from https://www.visualstudio.com/vs/preview/ or wait for 15.3 update. Or select lower version from workspaces window.

https://github.com/Microsoft/RTVS/issues/3441

**Comment by Victsz** [comment]
Cannot open on VS 15.2 as well
![image](https://user-images.githubusercontent.com/8154646/26911130-ff1ec90a-4c3d-11e7-8a2b-30c81cb4ed69.png)

Microsoft Visual Studio Community 2017 
版本 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
版本 4.6.01055

已安装的版本: Community

Visual Basic 2017   00369-60000-00001-AA625
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA625
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA625
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA625
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio 包   8.6.00404.2
Application Insights Tools for Visual Studio

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

ASP.NET 和 Web Tools 2017   15.0.30503.0
ASP.NET 和 Web Tools 2017

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Cookiecutter   3.0.17114.1
提供以 cookiecutter 格式查找、实例化和自定义模板的工具。

JavaScript 语言服务   2.0
JavaScript 语言服务

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC 软件包   1.0
Microsoft Visual Studio VC 软件包

MySQL for Visual Studio   1.2.7
Data design and management tools for MySQL.  Copyright © 2007-2015 Oracle, Inc.

NuGet 包管理器   4.2.0
Visual Studio 中的 NuGet 包管理器。有关 NuGet 的详细信息，请访问 http://docs.nuget.org/。

Python   3.0.17114.1
为 Python 开发人员提供 IntelliSense、项目、模板、调试、交互窗口和其他支持。

Python - Django 支持   3.0.17114.1
为 Django Web 框架提供模板和集成。

Python - IronPython 支持   3.0.17114.1
为基于 IronPython 的项目提供模板和集成。

Python - 分析支持   3.0.17114.1
对 Python 项目的分析支持。

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.2.2.0
用于 Visual Studio 的 TypeScript 工具

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

通用 Azure 工具   1.9
通过 Azure 移动服务和 Microsoft Azure Tools 提供通用服务。

用于 Linux 开发的 Visual C++   1.0.6
用于 Linux 开发的 Visual C++

针对 Visual Studio 的 R 工具   1.1.30523.1233
提供 R 编程语言的项目系统、R 交互窗口、绘图等。

**Comment by MikhailArkhipov** [comment]
Try adding .NET development as a workaround. It installs the missing component.

**Comment by MikhailArkhipov** [comment]
Actually it appears to be a different problem since it appears that you have C# installed. Does C# interactive window work?

**Comment by Victsz** [comment]
Debugging C#, immediate window works fine, is it the C#  interactive window

**Comment by Victsz** [comment]
I repaired via the installer but same symptom.

**Comment by MikhailArkhipov** [comment]
C# uses same component. Can you check assembly version in 
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\InteractiveWindow
```

```
Microsoft.VisualStudio.InteractiveWindow.dll
Microsoft.VisualStudio.VsInteractiveWindow.dll
```

(right click - properties - details)

![image](https://user-images.githubusercontent.com/12820357/26913064-5bc3d00e-4bcd-11e7-940c-5f5c738cd7f0.png)

**Comment by Victsz** [comment]
![image](https://user-images.githubusercontent.com/8154646/26913135-8b4a5a54-4c4b-11e7-8ea4-038ed24fd519.png)
![image](https://user-images.githubusercontent.com/8154646/26913145-9d5002a8-4c4b-11e7-9558-3082e060f9b1.png)

**Comment by Victsz** [comment]
C# Interactive is fine
Microsoft (R) Roslyn C# 编译器版本 2.2.0.61624
从“CSharpInteractive.rsp”加载上下文。
键入“#help”，了解更多信息。
> Console.WriteLine("Hello World")
Hello World
>

**Comment by tmat** [comment]
@Victsz Could you share the .failure.txt file mentioned in the error message?
![image](https://user-images.githubusercontent.com/41759/26942700-e633e6d8-4c37-11e7-8e78-8242af44bddd.png)

**Comment by Victsz** [comment]
[VsProjectFault_84cc89b3-ffe1-459f-9577-f1ab4b6757c8.failure.txt](https://github.com/Microsoft/RTVS/files/1062779/VsProjectFault_84cc89b3-ffe1-459f-9577-f1ab4b6757c8.failure.txt)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/PTVS/issues/2534

**Comment by Victsz** [comment]
Any workaround besides clean install?

**Comment by MikhailArkhipov** [comment]
DevDiv 435037

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/PTVS/issues/2534 suggests this might happen with machines that also has (or had) VS Preview installed.

**Comment by Funkrusha** [comment]
this solved my problem: [https://github.com/Microsoft/PTVS/issues/2534](url)

**Comment by MikhailArkhipov** [comment]
This might be because interop types not embedded. I changed to embedding in 1.2 (tentatively for 15.4)

**Comment by MikhailArkhipov** [comment]
Need to verify in 15.4 Preview 1 when it becomes available.

**Comment by MikhailArkhipov** [comment]
Please check 15.4, preview or when it comes out. Thanks.
