### ISSUE TITLE
enabing install of packages when using remote server workspace

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3546]
Please briefly describe what you were doing that led to the issue, if applicable:

i visited my azure dashboard and created a "R Server Only SQL Server 2016" vm which appears to be the preconfigured vm setup to use for enabling vs17 rtools remote server workspace execution.   I assigned it a dns name on the public interface and tcp/5444 hole in the network security group resource.  Then following the vs17 | rtools | setup remote r ... [ -> https://aka.ms/rtvs-remote-setup-instructions -> https://docs.microsoft.com/en-us/visualstudio/rtvs/workspaces-remote-setup ] instructions i ran the r services installer [ https://aka.ms/rtvs-services ] to get the "r remote service" and "r user profile service" installed.   After all this from my dev wks i was able to successfully execute "portqry -n myvmname.datacenterregion.cloudapp.azure.com -p TCP -e 5444" test and establish a vs17 | R workspaces | remote server connection.   

Now the issue is i can execute R commands using the remote workspace for anything provided in the R client base packages provided libraries but if i want to use something that requires an install.packages() call, e.g. install.packages("data.table"), i get back the warnings / failed to load result shown below.  

When i remote into that vm i can successfully open the noted cran package repository urls using internet explorer after applying server manager | local server | ie enhanced security configuration | administrators/users = off setting. 

Does remote workspaces story require packages for libraries not a part of base packages be loaded by administrator on that machine vs giving remote workspace caller the privileges to do so via their R interactive commands?

Warning:
 unable to access index for repository https://mran.microsoft.com/snapshot/2017-03-15/src/contrib:
  cannot open URL 'https://mran.microsoft.com/snapshot/2017-03-15/src/contrib/PACKAGES'
. . . 
Warning message:
package `data.table' is not available (for R version 3.3.3)  

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    mydssvr: https://mydssvr.eastus.cloudapp.azure.com:5444

**Comment by MikhailArkhipov** [comment]
@karthiknadig can suggest how to open outbound connection. The problem is that firewall is blocking outbound traffic.

**Comment by myusrn** [comment]
@MikhailArkhipov i went into the azure resource group's "network security group" settings and added allow-http-out [ tcp/80 ] and allow-https-out [ tcp/443 ] entries to test this as the setting that resolves the above.   

Trouble is i'm now getting the following error just trying to establish the remote workspace connection and not clear how i fix it.  I tried r remote services for visual studio 1.1 uninstall | reboot | reinstall | reboot and that didn't get me back to where i could establish connection vs getting the error below.  

Any thoughts on what i broke or what R Server or R Remote Services for Visual Studio reset command to use to get the remote connection working again so i can test thinking that enabling outbound http  & https network security group entries enables install.packages() calls to succeed?

Connecting to R Workspace failed.
Reason: Http request to 'mydssvr fqdn addr' has failed and machine did not respond to a ping.
The machine may be offline or unreachable or the network has been disconnected.
Error: An error occurred while sending the request.

**Comment by karthiknadig** [comment]
@myusrn Try removing and adding the inbound rule for Microsoft.R.Host.exe. Restart the R Service. Log out of the server (this is important). After you are connected to R service, try running `available.packages()`. See if that works.

**Comment by myusrn** [comment]
I had the vm stopped and removed then readded the network security group inbound "default-allow-rrs4vs" tcp/5444 entry.  Then i started the vm and reestablished the remote workspace connection.  At that point available.packages() worked and install.packages() execution is now working as well.  Thanks.

Not sure what the fix was here given i had previously restarted the vm after having added that nsg inbound rule.  Having an rdc connection open to the host isn't affecting the ability for install.packages() to work either.
