### ISSUE TITLE
web crawlers using the httr package is very slow compared to rgui

### ISSUE THREAD

**Issue by EricChen1248** [Microsoft/RTVS#3557]
Please briefly describe what you were doing that led to the issue, if applicable:

...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Client (3.3.2.0): C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by smortaz** [comment]
Hi, can you provide some sample code, some timing data, etc. so that we can
investigate?

thanks!

**Comment by EricChen1248** [comment]
```
library(httr)
library(XML)
library(magrittr)
library(dplyr)

startTime <- Sys.time()
data_collected <- NULL
for (yyyy in 2000:2016){
  for (mm in 1:12){
    body <- list(
      "query_year"=yyyy,
      "query_month"=mm,
      "CO_ID"=2330
    )
    
    res <- httr::POST("http://www.twse.com.tw/ch/trading/exchange/STOCK_DAY_AVG/STOCK_DAY_AVGMAIN.php", body = body)
    data <- XML::readHTMLTable(content(res, 'text'))[[1]]
    colnames(data) <- c('date', 'price')
    data <- data[1: (nrow(data)-1), ]
    data_collected <- rbind(data_collected, data)
  }
}
endTime <- Sys.time()
time.Taken <- endTime - startTime
time.Taken
```
Output:
Visual Studio with RTVS first run
`Time difference of 4.246347 mins`

RGUI with R 3.4.0 first run
`Time difference of 37.65824 secs`

VS second run
`Time difference of 4.15023 mins`

RGUI second run
`Time difference of 34.21875 secs`

Visual Studio and RGUI started consecutively (less than one second difference)
VS:
`Time difference of 4.186378 mins`
RGUI:
`Time difference of 30.94508 secs`

**Comment by smortaz** [comment]
Thanks Eric. i'm having a hard time recreating the difference... for me they're about the same.  

note i changed to 2012:2016, tho that shouldnt make much of difference.

![image](https://cloud.githubusercontent.com/assets/742484/26212167/87752e2a-3ba9-11e7-9536-a4c89d5b7a4b.png)

**Comment by smortaz** [comment]
One more: can you try with R 3.3.3 ?

**Comment by EricChen1248** [comment]
I just realized, the difference is between Microsoft R client version and the regular r. Running R Client in Rgui and RTerm
Tried again on school network, which is slower than home network
Visual Studio with Microsoft R Client 
4.216532 mins
RTerms with R Client
4.225387 mins
Rgui with R Client
4.151684 mins

RTerm with R
22.69602 secs <- Weird, but school internet is oddly fast sometimes
Second run
35.25837 secs
Rgui with R
56.51149 secs


So the difference seems to be the Microsoft R Client version and regular CRAN R. Is that still reported here?
I can't seem to get visual studio to use CRAN R as the workspace, hangs whenever I try to switch. So no speed test there.

**Comment by smortaz** [comment]
If you are using 3.4, then there is a known issue and you have to wait for
an update, or use the preview bits

 If you switch to 333 you should see the similar time is reported in both
visual studio and rgui

 I will check on Microsoft r tomorrow but I doubt if there's a difference
there either

Thx

**Comment by renebouw** [comment]
The only thing that may cause a different version of httr than you would expect from CRAN R, is the fact that Microsoft R Open and R Client use a snapshot date for packages. See more details here: https://mran.microsoft.com/documents/rro/reproducibility

**Comment by MikhailArkhipov** [comment]
Closing for now
