### ISSUE TITLE
Cannot Open R Interactive Window

### ISSUE THREAD

**Issue by smj389** [Microsoft/RTVS#3571]
I attempted to open the R interactive Window and instead I received the following error message (screenshot attached):

![image](https://cloud.githubusercontent.com/assets/12642064/26456039/ded82cde-4163-11e7-9a66-09d949877883.png)

I repaired Visual Studio 2017 and still it did not work.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.16199.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by Hong-Revo** [comment]
If you're using R 3.4, this is a [known](https://github.com/Microsoft/RTVS/issues/3537) [issue.](https://github.com/Microsoft/RTVS/issues/3441)

**Comment by MikhailArkhipov** [comment]
This means that for some reason dependency (interactive window) was not installed. As a workaround, try adding .NET workload since it installs the component.

**Comment by huguesv** [comment]
This looks identical to the error that some PTVS users are getting.
https://github.com/Microsoft/PTVS/issues/2534

**Comment by huguesv** [comment]
@smj389 please let us know if adding the .NET workload solves the issue. Some Python users have had the same issue, and uninstall/reinstall of VS 2017 was the only way to get it working (see my link above).

We haven't been able to reproduce this issue. Was this a clean install of VS 2017, or an update of a previous build?  If an update, what build did you have installed prior to this?

**Comment by MikhailArkhipov** [comment]
Merging into #3537, there is more info there.
