### ISSUE TITLE
VS 2017 CON'T connecting r workspaces

### ISSUE THREAD

**Issue by wrongzsc** [Microsoft/RTVS#3574]
如果适用，请简要说明导致此问题的操作:

...

如果有可说明此问题的任何屏幕截图，请将其一并包含在内，以帮助我们更好地诊断问题。

更多信息:

OS Information
    Version:       Microsoft Windows NT 10.0.14393.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30413.947, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Open (3.4.0.0): C:\Program Files\Microsoft\R Open\R-3.4.0\

**Comment by MikhailArkhipov** [comment]
R 3.4.0 is not supported in the build you have. Unfortunately, it was released after 15.2 update was shipped. New update is coming soon with 3.4.0 support. You can use Workspaces window to select 3.3.3 instead.
