### ISSUE TITLE
any backlog items focussed on f7 enabling r interactive window history access

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3580]
Please briefly describe what you were doing that led to the issue, if applicable:

Currently in the 15.2 (26430.12) installs r interactive window you get the up arrow support for accessing prior commands.  Are there any backlog items focused on f7 enabling r interactive window history access similar to how it works in cmd.exe prompt environment so you can visual see how far back you have to go in order to find command you want?

p.s. should i have entered a feature question like this elsewhere?

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
#3019 - people are asking more like csh rather than cmd.

**Comment by int19h** [comment]
Note that you have your visual history available immediately in the REPL itself, if you scroll up - and you can position the cursor on some earlier input entry and press Ctrl+Enter to re-use your older input. Also, there's the History window (R Tools | Windows | History).

**Comment by myusrn** [comment]
Yes the ability repl [ / r interactive ??? ] to scroll up through r interactive window and find prior command to ctrl+enter reapply at current prompt is an option provided there isn't a lot of print output to sift through.   

The r tools | windows | history view is even better than a cmd.exe f7 popup would be as the latter requires you to scroll back to command you want to reenter vs being able to select it by number or mouse click.    In the r tools | windows | history view is there any plan to wire up ctrl+enter as keyboard shortcut for the "Send selected to R Interactive Window" toolbar option?

**Comment by MikhailArkhipov** [comment]
I believe you can wire any shortcut in Tools | Options | Environment | Keyboard. @AlexanderSher can provide `RTools.*` command name

**Comment by myusrn** [comment]
Just realized that double clicking r tools | windows | history view entry inserts that item into r interactive window leaving you to just modify as desired and press enter to submit it.  That works even better.  In hindsight i guess would have been self discoverable by someone who thought to use history view of commands as quick way to easily go back a significant number of steps to repeat a prior command.

**Comment by myusrn** [comment]
So should i close this or do i leave that for you folks after you've considered whether r history pane is doing the trick as good or better than an f7 triggered popup would?   

Might be interesting to connect f7 keyboard shortcut to display of r history pane vs ctrl+4 which overlaps with sysinternals aka.ms/zoomit tsr liveZoom shortcut key.

**Comment by MikhailArkhipov** [comment]
Feel free to comment in #3019. @AlexanderSher is currently looking into it. Unfortunately, different people want different things... We are considering something that would cover most common cases. Perhaps compatible with `RStudio` or `csh` like?

**Comment by MikhailArkhipov** [comment]
I am going to close in favor of #3019
