### ISSUE TITLE
coursera jhu swirl library completion token paste not working

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3582]
Please briefly describe what you were doing that led to the issue, if applicable:

The coursera john hopkins university data science specialty [ see aka.ms/dsJhu ] classes make use of a library called swirl to walk students through exercises. when you get to the end of any exercise it asks you if you want to submit completion of the exercise at which point it asks for email address and token the latter of which you copy and paste from your course web site view for this exercise.   
In rstudio you can copy that token from browser page and paste into R interactive window at that point in swirl library routine w/o any issue.  Using vs17/dev15.2 rtools R interactive window it doesn't for whatever reason allow that token, or any alphanumeric value, paste from clipboard to happen.  It does accept you typing input which is current work around that requires you to bring up view of lengthy token and manually try and type it into that submission prompt for token.

The simplest way i can think of to repro this is to kick off one of the simple swirl exercises using the following commands and stepping through the <10min easy q&a exercise, easy that is for an experienced R programmer, at which point you can repro it not allowing you to paste any value from clipboard into R interactive window when you get to it asking you for completion submission token.

specific repro steps involve doing the following from R interactive command line
if (!require("swirl")) { install.packages("swirl"); packageVersion("swirl"); library(swirl) }
install_from_swirl("R Programming"); swirl()
# select "R Programming" option | <any option, e.g. 1. Basic Building Blocks> |
# step through <10min q&a exercises till get to point where they ask you to submit results
# at which point enter an email address and when it next ask for a token try and paste any 
# alphanumeric value from your clipboard into the line. with rstudio this works but with 
# vs17/dev15.2 rtools this doesn't accept paste from clipboard.  it does accept you typing input.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/b02ae48aefaa08d94eb1d1c97d889d474f9ddecf

**Comment by myusrn** [comment]
Thank you for looking into and fixing this.  Reviewing merge that addresses it looks like a whole lot of magic to me 8)  Would you expect the next vs17 up2 update that gets pushed out to me will contain this fix?  Asking so i know when i should retry behavior to confirm its working now.

**Comment by MikhailArkhipov** [comment]
No, this won't go into 15.2. 15.3 - _maybe_, it might be too close to release to open for a bug fix. 15.4 - certainly.
