### ISSUE TITLE
RHostSession not terminate RHostBroker

### ISSUE THREAD

**Issue by Victsz** [Microsoft/RTVS#3594]
I`m having problem to close broker process. After StopHostAsync, only R host process is terminated but RHostBroker is still there. 

_session = RHostSession.Create("Test");
  _session.StartHostAsync(new RHostSessionCallback()).Wait();
  _session.ExecuteAsync("q()").Wait();
  _session.StopHostAsync().Wait();
 _session.Dispose();

**Comment by int19h** [comment]
This is expected - the broker is a process that manages host processes, and it is running as you start and stop sessions. It will exit when it detects that the parent process that owns it has exited.

**Comment by MikhailArkhipov** [comment]
Correct. In case you'll want to start another session. It is pretty tiny process. If you really need it to go away, I think it can be killed by id - @int19h can comment.

**Comment by int19h** [comment]
I'm not sure if we expose `IBrokerClient` in that API. If we do, then calling `Dispose` on the instance of that will kill the process, if it is a local broker.

**Comment by Victsz** [comment]
Is it also expected when the main process create a new session but the old broker will not be reused?

**Comment by Victsz** [comment]
In my opinion, providing a method to close broker is quite necessary.  Some application will be long running and the R session may crash,  in current behavior,  the number of brokers will keep increasing.

**Comment by MikhailArkhipov** [comment]
Broker is normally reused, at least that what happens in the main product. I'll see what we can do in the API about this.

**Comment by Victsz** [comment]
Hi,  I`m trying to log the output from R host by override Output from RHostSessionCallback and assigned to IRHostSession. but it did not work.  Sorry in advance if it is a dumb question.
---
  _session.StartHostAsync(new HandleRSessionCallBack(), Environment.CurrentDirectory).Wait();

  var re = _session.ExecuteAndOutputAsync("cat(getwd())");
//I have to call explicitly to log
       //     this.Log().Info(re.Result.Output); 
----
 class HandleRSessionCallBack : RHostSessionCallback
    {
        public override Task ShowErrorMessageAsync(string message, CancellationToken cancellationToken = default(CancellationToken))
        {
            return base.ShowErrorMessageAsync(message, cancellationToken);
        }
        public override void Output(string message, bool error)
        {
            base.Output(message, error);
            if (error)
            {
                this.Log().Error(message);
            }
            else
            {
               //No log
                this.Log().Info(message);
            }
        }
       
    }

**Comment by MikhailArkhipov** [comment]
It comes as result
```
var result = await _session.ExecuteAndOutputAsync("code here");
// use result.Output
```

![image](https://user-images.githubusercontent.com/12820357/26893218-8e19b66c-4b6f-11e7-90f3-9b94afb31cc4.png)

**Comment by Victsz** [comment]
My broker will not be reused. Stop and Create a new R session, will get 2 brokers

**Comment by MikhailArkhipov** [comment]
Added API. Will update nuget soon

**Comment by MikhailArkhipov** [comment]
https://www.nuget.org/packages/Microsoft.R.Host.Client.API/1.1.1

**Comment by Huma-Shehwana** [comment]
Hi @MikhailArkhipov 
I am trying to use the package. I am only using C# to call a user defined R function for a project but i am not that familiar with C# much so please excuse me if its a very basic question.
The following line IRHostSession session = RHostSession.Create('Test'); returns an error         System.ArgumentNullException has been thrown
     Value cannot be null.
Parameter name: path1
Can you please help me out?
