### ISSUE TITLE
Version file generation on Linux

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#3597]
The generated header to produce version numbers currently utilizes MSBuild on Windows, so the build must be invoked via MSBuild to be successful there - otherwise the header is missing. Need to switch generation to CMake to avoid this dependency.

**Comment by MikhailArkhipov** [comment]
Last build appears OK

![image](https://user-images.githubusercontent.com/12820357/26842436-b357b75e-4aa1-11e7-8ca3-ec6d595f6ee2.png)

**Comment by MikhailArkhipov** [comment]
Are we doing it? If not, just close.
