### ISSUE TITLE
Linux: RHost process does not get killed after disconnect

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3600]

**Comment by karthiknadig** [comment]
This was fixed when we switched back to use standard io streams.

**Comment by karthiknadig** [comment]
This still repros. This is because broker runs as 'brokeruser', and hence does not have permission to kill the process running as another user.

**Comment by int19h** [comment]
While we do need to fix the ability of broker to kill processes, the host should also exit by itself when the broker closes its end of the stdout pipe. If that's not happening, it's a separate bug.

**Comment by karthiknadig** [comment]
The host seems to run until either broker kills it by calling kill or when the broker itself exits. I think there might be a bug on the broker side. I will look into it.
