### ISSUE TITLE
r plot history multiselect support

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3621]
Please briefly describe what you were doing that led to the issue, if applicable:

I find ability to scrub specific plots from r plot history view [ of "ide" graphics device ] very helpful as opposed to entering the dev.off() command in r interactive window approach that drops everything. Currently r plot history view doesn't support range multiselect, using shift+click, and arbitrary set selection, using ctrl+click, gestures for selecting set of plots to delete in one step. No idea whether enabling that involves use of some boiler plate UI code or complex view pane specific addition. Either way if others also feel it would be a nice addition to variable explorer interactions then perhaps worth considering.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/85238e4dd8a124f39674a19a60075d7b10da00bc

**Comment by myusrn** [comment]
thanks, look forward to trying this out when next update is pushed with this change in it.
