### ISSUE TITLE
Cannot change working directory while switching between linux remote and windows local

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3636]
```
Error in setwd("/home/kanadig") : cannot change working directory
```

**Comment by MikhailArkhipov** [comment]
Not a bug. What we should do is to store WD per connection rather than as single value. Single value is a remnant of the local-only R case.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/29188768-1115787c-7dc9-11e7-8847-1e08744d5432.png)

**Comment by MikhailArkhipov** [comment]
Option was removed
https://github.com/Microsoft/RTVS/commit/9043163d3cfe13c0fcf40b88e80efc60bcd21765
