### ISSUE TITLE
editor option to turn off automatic reformatting of statements to individual lines

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3638]
Please briefly describe what you were doing that led to the issue, if applicable:

When i try to enter multiple steps on one line separated by semi-colon, e.g. 
&nbsp;&nbsp;&nbsp;&nbsp;dataTidy <- copy(data); str(dataTidy); colnames(dataTidy); unique(dataTidy$eventType)
the editor automatically moves each statement to an individual line whenever you enter a semi-colon.  At that point you have to manually make use of backspace/del to get everything back on one line again in cases where that is the formatting you want.  In the c#/core ide experience it doesn't do this, e.g. i can enter the following without it automatically breaking everything out onto separate lines.
&nbsp;&nbsp;&nbsp;&nbsp;var i = 1; var j = 2; var k = 3;
&nbsp;&nbsp;&nbsp;&nbsp;if (i == 2) { i++; j++; k++; }
It would be nice to have a way to disable that automatic breaking up of semi-colon delimited statements onto individual lines w/o having to turn off all automatic formatting behaviors in the r tools | editor options settings.

The reason i often put a bunch of r statements on a single line is for exploratory data analysis reasons that i later want to comment out of script using a single # prefix.  I find it useful when i want to put a set of related statements or simple if or function stack frame on a single line versus stretching out length of script by having each statement get its own line. 

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
Gnenerally LintR doesn't recommend this but it can be done. By the way, you can comment multiple statements in a single keystroke. Select them and `^K^C` comments and `^K^U` uncomments.

**Comment by myusrn** [comment]
k, if this is considered bad practice then i can live with manually adjusting when i care for this this layout of essentially exploratory only script comments.   Thanks for heads up that keyboard shortcuts ctrl+k+c and ctrl+k+u work to comment and uncomment selected lines in this language environment, that's an option i can move to as well.

**Comment by myusrn** [comment]
. . . circling back on this as i'm now further along in the aka.ms/dsJhu data science specialization and am running into wanting to stuff multiple statements on a single line, using ';' statement separator,  with almost every assignment.  This arises from assignment requirements to keep Rmd output under a certain number of pages.  The c# style checker / fxcop i believe throws warnings in cases where you put multiple statements on same line, using ';' statement separator, but as noted earlier doesn't auto-reformat them on you.  Was watching some build 2017 talks on typescript and was noticing editor experience for it, vscode, doesn't auto-reformat multiple statements onto individual lines even though i'd expect jslint to also suggest that you keep everything on its own line.  So perhaps providing this auto-reformat multiple statements into separate lines would make sense as  settings option to align with how other language editing experiences handle this coding style related matter.

**Comment by myusrn** [comment]
On related note i'm finding that editor will auto-reformat this multiple statement line into separate lines when you hit enter at the end of it 
        install.packages("caret");  library(caret)
but it does not, thankfully, auto-reformat this multiple statement line into separate lines when you hit enter at the end of it.
        if (!require("caret")) { install.packages("caret"); library(caret) }
Not sure if having the first example not auto-reformat, and relying on R lint processing to highlight these matters unless rule is suppressed, so as to align with behavior in latter case and like noted earlier how c# and typescript editors handle this style matter.

**Comment by MikhailArkhipov** [comment]
Multiple statements on one line is not recommended by R style guide so that's why formatter breaks them. Similarly, LintR flags semicolons (and upcoming RTVS 1.2 linter has similar functionality). Might add an option though.

However, formatter does not drill into the complete scope as above.

**Comment by MikhailArkhipov** [comment]
Added option

**Comment by myusrn** [comment]
Thanks, looking forward to using it to do away with the backspace and del key workarounds I've been using.  Do you expect it to be in next update pushed out for vs17 v15.2 (26430.16)?

**Comment by MikhailArkhipov** [comment]
No. Also, 15.3 is already closed. 1.2 will appear in 15.4 starting with preview channel https://www.visualstudio.com/vs/preview/ some time early August.

**Comment by myusrn** [comment]
Thanks for clarification.  I'll look at switching over vs17 preview install in mid-august so i can start exercising this and other fixes you've made before they make their way to release update.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/30b7dcc86b562c3678d27ea21130cbbb4c34a3b8
