### ISSUE TITLE
No existe opción para cambiar la ruta del Cliente de R

### ISSUE THREAD

**Issue by ursusfelis** [Microsoft/RTVS#3648]
Después de Instalar Microsoft R Open 3.4. ,Abri visual studio community 2017, y abri una ventana de R interactivo, donde pude comprobar que aun seguía utilizando la versión anterior de MRO. Al buscar una opción para señalarle la ruta de MRO 3.4 a RTVS, no logre localizar esta opción. así que recurri al instalador de visual studio para desinstalar RTVS y el anterior MRO para volver a instalar RTVS y así tomara el nuevo MRO 3.4

Información adicional:

OS Windows 8.1 enterprise
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233

Active R URI:
    Microsoft R Client (3.4): C:\Program Files\Microsoft\R Open\R-3.4.0

**Comment by MikhailArkhipov** [comment]
After installing Microsoft R Open 3.4. , Opened visual studio community 2017, and opened an interactive window, where I could check that it was still using the previous version of MRO. Looking for an option to point out the path of MRO 3.4 to RTVS, unable to locate this option. so resorted to the visual studio Installer to uninstall RTVS and the previous MRO to reinstall RTVS and thus take the new MRO 3.4

**Comment by MikhailArkhipov** [comment]
Please use R Tools -> Windows -> Workspaces to select any R from installed locally or connect to remote machine. RTVS remembers last used version.

**Comment by ursusfelis** [comment]
Thaks, it's just as you xplain it

i got another question. if it is not a problem. 

can you tell give a link to the document that explain this option?

Only for Reference in my own document about RTVS

thanks

**Comment by MikhailArkhipov** [comment]
https://docs.microsoft.com/en-us/visualstudio/rtvs/options 
https://docs.microsoft.com/en-us/visualstudio/rtvs/workspaces
