### ISSUE TITLE
Uses of 'T'/'F' incorrectly flagged as syntax errors

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3655]
![image](https://user-images.githubusercontent.com/11328890/27566636-dbb02a54-5b29-11e7-9ddd-ba7fa4751167.png)

I guess this is because `T` and `F` are treated as reserved words? They're just normal variable names that happen to be preassigned to `TRUE` and `FALSE` respectively. You can even do something like

```r
T <- FALSE
F <- TRUE
```
and R won't complain (your coworkers might, though).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/b02ae48aefaa08d94eb1d1c97d889d474f9ddecf
