### ISSUE TITLE
Roxygen comments for S4 function not added

### ISSUE THREAD

**Issue by FelixErnst** [Microsoft/RTVS#3656]
For adding roxygen comment blocks to S4 class section the function "adding a roxygen block" can not be used. Following code is not recognized

```
setClass("Test",
    representation(
        a= "character",
        b= "character",
        c= "character"
    )
)
```

Also within a comment block with a #' tags, adding new lines is painful, since new lines in comment section are added without #' tags.

**Comment by MikhailArkhipov** [comment]
Good point. What's the complete list so I don't have to dig it up? :-)

**Comment by FelixErnst** [comment]
Upon checking, I think it just these three. It also makes sense, since this is solved in other languages with {}-blocks or similar. Class have methods, that is it.

Hadley Wickham also does not mention anything else at [http://adv-r.had.co.nz/S4.html](http://adv-r.had.co.nz/S4.html
)

Despite having nothing 100% solid, I hope the educated guess helped.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/b02ae48aefaa08d94eb1d1c97d889d474f9ddecf
