### ISSUE TITLE
R does not accept folder names with characters that windows Explorer if you accept

### ISSUE THREAD

**Issue by ursusfelis** [Microsoft/RTVS#3659]
Al intentar concetar con un archivo DBF con el comando read.dbf(), no me deja abrir el archivo, porque una carpeta que forma parte de la ruta donde esta el archivo, contiene alguno de estos caracteres:  Ñ   ¡ 
  ¿   ´   o   letras acentuadas
Esto, aun cuando el explorador de windows si acepta estos caracteres como parte del nombre de una carpeta.

"Try connecting with a DBF file with the command read.dbf () will not let me open the file, because a folder that is part of the path where this file, contains any of these characters: N!
´ or accented letters. This, even though windows Explorer if you accept these characters as part of a folder name."

![error](https://user-images.githubusercontent.com/7282166/27608589-aaf50c6c-5b4d-11e7-930d-9f7a5ff8a28c.png)

Si tiene alguna captura de pantalla que muestre el problema, inclúyala para ayudarnos a diagnosticarlo mejor.

Información adicional:

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Open (3.4.0.0): C:\Program Files\Microsoft\R Open\R-3.4.0\

**Comment by MikhailArkhipov** [comment]
Generally speaking R is not Unicode and has certain limitations on paths since it is a cross-platform. Therefore characters need to be translated from Windows Unicode to multibyte encoding and back. This, unfortunately, is not 100% guaranteed. RGui doesn't even allow typing in non-English.

However, I tried creating folder named in Unicode and it worked for me. We'll look more into this.

**Comment by ursusfelis** [comment]
Actually, i did use a workaround to open the files. Simply use a short folder Path and dind't use characters that i had detected as unaceptable.
I want to report what looks like a bug to me, because RGui (32 and 64 bit) both can open the files witout problems meanwhile MRO 3.4 can't.
thanks for your attention
![borrar](https://user-images.githubusercontent.com/7282166/27879760-4410993a-6188-11e7-9e4d-d044d3707ed3.png)

**Comment by int19h** [comment]
Could you share the output of `Sys.getlocale()` on your machine?

**Comment by ursusfelis** [comment]
of course. Here they are.

**RGui (32 and 64 bit)**
> Sys.getlocale()
[1] "LC_COLLATE=Spanish_Mexico.1252;LC_CTYPE=Spanish_Mexico.1252;LC_MONETARY=Spanish_Mexico.1252;LC_NUMERIC=C;LC_TIME=Spanish_Mexico.1252"

**MRO 3.4.0**
> Sys.getlocale()
[1] "LC_COLLATE=Spanish_Mexico.1252;LC_CTYPE=Spanish_Mexico.850;LC_MONETARY=Spanish_Mexico.1252;LC_NUMERIC=C;LC_TIME=Spanish_Mexico.1252"

**Comment by int19h** [comment]
Thanks!

@MikhailArkhipov, note the difference in `LC_CTYPE`. Effectively, this means that when we load R, we tell it to use the OEM codepage rather than the ANSI codepage. But we probably still use ANSI ourselves when converting REPL input, which is why it breaks. Whatever code is setting `LC_CTYPE` is doing it wrong.

**Comment by MikhailArkhipov** [comment]
The workaround then set it manually at the moment

**Comment by MikhailArkhipov** [comment]
So we use OEMCP by default since https://github.com/Microsoft/RTVS/pull/1750. Used to use `GetSystemDefaultLCID` but it probably didn't work for knitr/pandoc

**Comment by ursusfelis** [comment]
I did followed instructions in #1750 and it works. no more problem.

i did used Latino 3 (ISO), Latino 9 (ISO) code pages to success

**Comment by int19h** [comment]
To clarify, you still had to specify the encoding explicitly? The "OS Default" option didn't work for you?

**Comment by MikhailArkhipov** [comment]
In shipped bits OS Defaults sets OEM CP.

**Comment by ursusfelis** [comment]
"OS Default" code page didn't work for me, with that option is imposible to open the file
whilist with "Latin 3" or "Latin 9" code page, file is opened without a problem

Option remains selected after a Visual Studio restart, then this workaround is ok for me

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/3c9f070c88404ebb01031075e6000d4ca6e48223
