### ISSUE TITLE
UI for Docker containers

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3663]
- Workspaces window to get new section: `Containers (Docker)`. 
- `Add` button should be bringing [modal] list of predefined containers available from a feed (TBD), like `R 3.4.0` etc. 
- The list should have two sections: `Microsoft` and `Custom`. First one we provide, second is from feed URL that can be supplied by the customer company. If there is no custom URL, we should probably hide the section.
- In container properties user can change name and R arguments, but URL is fixed.

@karthiknadig to provide the back end

**Comment by MikhailArkhipov** [comment]
Some details to clarify:

1. Do we show different icon for Docker image vs Docker file?
2. If user needs to find container on local file system, how do they do that?
3. Container should probably have description panel where user can see extended information on the image or file (similar to package manager)

**Comment by AlexanderSher** [comment]
> The list should have two sections: `Microsoft` and `Custom.`

I believe there should be one section for every feed provider.

**Comment by AlexanderSher** [comment]
What should actually happen when user adds container?

**Comment by karthiknadig** [comment]
I feel it should go into the custom feed.

**Comment by MikhailArkhipov** [comment]
We can schedule meeting to discuss this. I've just send whiteboard mockup. Basically 

- One new section `Containers`
- Spinner showing that container is being created
- User can Delete but not editor container that is not ready yet
- User can close VS and reopen. There is a way to determine that container is still being created
- `Add` button opens modal dialog with `Azure` and `Docker` sections
- Each section has `My Templates` (or `Custom`) and `Standard`
- Azure template enables properties grid with settings like RAM, disk, etc.

**Comment by MikhailArkhipov** [comment]
Done, close?
