### ISSUE TITLE
XamlGraphicsDeviceTest.LineSolidLineType and TextXmlEscape throw 404

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3667]

**Comment by karthiknadig** [comment]
XAML code is excluded from RHost.
https://github.com/Microsoft/R-Host/commit/a394f1a3cd39b4f637368dc3a38d0b072734ffcd#diff-3cf896548a82b4dba7c02025dc3b1b82

**Comment by MikhailArkhipov** [comment]
Guess will need to disable these then

**Comment by int19h** [comment]
XAML device needs to be reworked to handle multiple R versions. But it's a waste of time until https://github.com/Microsoft/RTVS/issues/3596 is done.

**Comment by MikhailArkhipov** [comment]
I am going to turn tests off for now
