### ISSUE TITLE
Double paste when pasting 'おはよう' in REPL

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3669]
Copy and paste this 'おはよう' into REPL, it pastes twice. However, 'ABCD' does not show this behavior.

**Comment by Hong-Revo** [comment]
Works fine here....

**Comment by MikhailArkhipov** [comment]
Does not repro

**Comment by MikhailArkhipov** [comment]
Found repro. Most probably regression after #3582

**Comment by AlexanderSher** [comment]
Can you post a repro (for future reference)?

**Comment by MikhailArkhipov** [comment]
Oh, just paste :-). Bug was that command was returning `NotSupported` after paste so editor pasted second time.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/85238e4dd8a124f39674a19a60075d7b10da00bc
