### ISSUE TITLE
rtools hangs on specific swirl lesson step where rstudio does not

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3677]
Please briefly describe what you were doing that led to the issue, if applicable:

If you use the following steps to execute a specific aka.ms/dsJhu swirl lesson step in rtools it throws up a progress circle and never returns where resuming and continuing through that step in rstudio proceeds without an issue.

if (!require("swirl")) { install.packages("swirl"); packageVersion("swirl"); library(swirl) }
install_from_swirl("Statistical Inference"); swirl()

Now enter <name> and select "#: Statistical Interference" | "9: T Confidence Intervals" and work your way up to 53% mark, which should take under 10mins for R savvy person,  at which point using vs17 rtools i get a progress circle that doesn't return.   If i kill vs17 and restart using swirl's ability to resume progress from where i last left off it repros both times i tried that.   I then cut over to rstudio and used swirl's ability to resume progress from where i last left off there and it proceeded onto 55% mark w/o any issues.

I tried to isolate a repro of this matter from outside of swirl lesson environment by executing following steps which appear to be what the lesson is executing at that 53% mark, based on results i saw from it succeeding in rstudio, but issue didn't repro for me from outside of the swirl lesson environment.
setwd(file.path(Sys.getenv("userprofile"), "Documents/R/win-library/3.3/swirl/Courses/Statistical_Inference/T_Confidence_Intervals")); getwd()
source("initLession.R"); source("plot4Ttests.R")

I'd say this matter is relevant if there is an interest in ensuring one can carry out all the aka.ms/dsJhu data science specialization exercises using vs17 rtools in lieu of rstudio and/or if it arises from something that could happen elsewhere.
![rtvsswirlsitcihang](https://user-images.githubusercontent.com/3043446/27811873-82c3c2c0-601f-11e7-86eb-8aa10473e4b9.png)

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
Said place in the course is

https://github.com/swirldev/swirl_courses/blob/b3d432bfdf480c865af1c409ee0ee927c1fdbda0/Statistical_Inference/T_Confidence_Intervals/lesson
```
- Class: figure
  Output: Here's code from the slides which shows four different ways of using t.test (including the two we just went through) to find the confidence interval of this data. The code also shows how to display the intervals nicely in a 4 x 2 array. 
  Figure: plot4Ttests.R
  FigureType: new
```
https://github.com/swirldev/swirl_courses/blob/master/Statistical_Inference/T_Confidence_Intervals/plot4Ttests.R
```
# fname <- paste(getwd(),"Statistical_Inference/T_Confidence_Intervals/Tplot.jpeg",sep="/")
# temp <- readJPEG(fname)
# #img <- as.raster(temp)
# plot.new()
# plotArea=par('fig')
# rasterImage(temp,plotArea[1],plotArea[3],plotArea[2],plotArea[4],interpolate=FALSE)
fname <- fxfer("show4calls.R")
file.edit(fname)
```

**Comment by MikhailArkhipov** [comment]
`file.edit` issue

**Comment by MikhailArkhipov** [comment]
So, it does not 'hang` for me. This part opens file you are supposed to edit. REPL is blocked until you close the file.

![image](https://user-images.githubusercontent.com/12820357/27885747-e27e06fc-618d-11e7-8467-492046ae6c37.png)

RStudio opens this in modal dialog while VS opens regular editor

**Comment by myusrn** [comment]
That's good to hear.  Perhaps i experienced a hang due to something a reboot would have resolved, even though restart vs17 rtools and swirl resume didn't.  Alternatively perhaps whatever caused what i ran into doesn't exist in the newer rtools install i expect you are running vs the 15.2 (26430.14) release rtvs 1.1.30523.1233 version i'm running.

**Comment by MikhailArkhipov** [comment]
Does it open the file for you?

**Comment by myusrn** [comment]
The progress circle replaced mouse pointer and vs17 went into modal UI mode and %userprofile%/Documents/R/win-library/3.3/swirl/Courses/Statistical_Inference/T_Confidence_Intervals/show4calls.R never displayed in editor.

**Comment by MikhailArkhipov** [comment]
Here is 2015 with RTVS that is in 15.3 preview

![image](https://user-images.githubusercontent.com/12820357/27888553-762fb140-619b-11e7-97f7-e67671d26782.png)

Will try and get stock 15.2

**Comment by myusrn** [comment]
Not my call to make but I'm okay with this being closed on the basis that it can't be repro'd or doesn't repro with current rtvs in place.
