### ISSUE TITLE
Windows code page is always set to ".437"

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3686]
Perhaps we should just leave it alone and let R decide.

**Comment by int19h** [comment]
If I remember correctly, we started setting it originally because the default wasn't practical.

**Comment by karthiknadig** [comment]
```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"
> 
```
This is the default locale, as set when using R GUI.

**Comment by int19h** [comment]
It should depend on your setting for "non-Unicode applications" - the above is for "Western European".

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/3c9f070c88404ebb01031075e6000d4ca6e48223
