### ISSUE TITLE
pipe operator "%>%" cannot activate indentation

### ISSUE THREAD

**Issue by Masutani** [Microsoft/RTVS#3690]
Just like this issue in vim : https://github.com/jcfaria/Vim-R-plugin/issues/160
It is preferable to recognize %>% as multi line sentence on VS editor.

**Comment by MikhailArkhipov** [comment]
Is https://github.com/Microsoft/RTVS/issues/3248 not working for you?

**Comment by MikhailArkhipov** [comment]
RTVS preserves your indentation but does not insist on it being specific. Some people want

```
x %>%
    z %>%
    y %>% a
```

and some

```
x %>%
    z %>%
        y %>% a
```

basically RTVS works the same as C# with line continuation (this includes function arguments): preserve user indent but don't insist on specific way of indentation.

**Comment by arthur-st** [comment]
@MikhailArkhipov Could the same be said of ggplot2 code blocks through `+`, that the RTVS preserves user indentation? When I make the standard multiline `ggplot() + geom_this() + geom_(that)` the indentation stays on the root level of the line `ggplot()` was invoked at (with indentation set to `smart` in the configuration options).

**Comment by Masutani** [comment]
@MikhailArkhipov "The line continuation" is what I'd like to see on the editor. I am using RTM of RTVS1.0 (1.0.30523.1233) on VS2017 (26430.15). I am not sure what kind of installation/setting is necessary to get this right behavior.

**Comment by arthur-st** [comment]
@Masutani If you're fine with doing the first indentation yourself, then dig up (not at my VS seat at the moment) indentation controls in the R-specific editor settings, and change it from `smart` (default) to `block`. That way, all text will go on the level of indentation you've manually specified.

It's not exactly ideal, for me at least, but it beats the current inconsistencies of smart indentation.

**Comment by Masutani** [comment]
@arthur-st I confirmed setting `block` works fine as you note. It is much better than current. 
Of course I prefer `smart` works find for any R binary operators and also in "document formatting","intellisense".

**Comment by MikhailArkhipov** [comment]
I don't mind making this more convenient :-) So basically request is to auto-indent on Enter one level deeper than the current statement, like C#:

![image](https://user-images.githubusercontent.com/12820357/28029964-b534b5b6-6556-11e7-93c3-68525d08e90c.png)

BUT at the previous line indent if it is not the first line in the statement.
 
![image](https://user-images.githubusercontent.com/12820357/28030037-f538a014-6556-11e7-9e33-143cfad10f11.png)

**Comment by arthur-st** [comment]
Yes, that'd be nice. As well as that, if you don't mind further indentation convenience improvements conforming the `tidyverse` style guide:
![image](https://user-images.githubusercontent.com/29796606/28030576-008e7ab4-65ad-11e7-9b16-7fd38151b32c.png)

**Comment by MikhailArkhipov** [comment]
At some point we had the latter (align arguments by the first one). Some didn't like and preferred C# way (which is the former). So the forced alignment so it was changed to `if you align args this way, formatter will preserve the alignment but it won't align them for you`.

**Comment by arthur-st** [comment]
I see. Well, it's something that may be considered in the future, to provide some form of configuration for style guidelines the editor adheres to.

**Comment by Masutani** [comment]
Because I am also using C# so I prefer its convention (like LINQ).
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions 
Or it seems to be natural for me if it is like F# pipe one : 
https://github.com/dungpa/fantomas/blob/master/docs/FormattingConventions.md#pipeline-operators

**Comment by MikhailArkhipov** [comment]
So basically options are

Upon ENTER

First continuation line: indent one level deeper than the current expression
```
x %>%
    |
```
Subsequent lines: indent based on the previous line (respecting user selection)
```
x %>%
             y %>%
             |
```
If user wants ladder case 
```
x %>%
    z %>%
        y %>% a
```
They would have to TAB manually after each ENTER

Functions: as above with _option_ to align by the first argument on ENTER
```
x <- function(a,
                      |
```

During *document formatting* respect user indentation set as above, whatever it might be. Don't move continuation indents.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/dad3e65a0ab9ae9f936772f00a846038c3d324da

**Comment by Masutani** [comment]
Just FYI :
http://style.tidyverse.org/pipes.html
