### ISSUE TITLE
Boxplot produces 'figure margins are too large'

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3694]
`boxplot(1:10 ~ rep(1:2, 5))`

![image](https://user-images.githubusercontent.com/12820357/27976383-1ee6ddc4-631b-11e7-968e-d3dc332c8ca6.png)

**Comment by MikhailArkhipov** [comment]
1.1 works fine

**Comment by karthiknadig** [comment]
I am not seeing this error, in the latest master.

**Comment by MikhailArkhipov** [comment]
Works with F5 though. Will re-check in master

**Comment by huguesv** [comment]
Behavior is dependent on plot window size + machine dpi settings. When you compare builds, make sure that those are constant.

**Comment by MikhailArkhipov** [comment]
I think in Markdown case I need to specify image dimensions.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/dad3e65a0ab9ae9f936772f00a846038c3d324da
