### ISSUE TITLE
Drag-drop fails with: Cannot complete the drag and drop operation

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3695]
---------------------------
Microsoft Visual Studio
---------------------------
Cannot complete the drag and drop operation: Invalid FORMATETC structure (Exception from HRESULT: 0x80040064 (DV_E_FORMATETC)).
---------------------------
OK   
---------------------------

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/333d10287a8d7cebdbec9b2da4824a2727027054
