### ISSUE TITLE
Cannot enable "Syntax check in R Console"

### ISSUE THREAD

**Issue by arthur-st** [Microsoft/RTVS#3701]
Under "Options -> Text Editor -> R -> Advanced -> Interactive window" the "Syntax check in R Console" setting remains as "Off" regardless whether if I try to change it in a freshly opened, blank Visual Studio instance, or mid-session working on a project.

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

R Tools for Visual Studio   1.1.30523.1233
Provides project system, R Interactive window, plotting, and more for the R programming language.

**Comment by arthur-st** [comment]
This issue did also exist in the previous release of VS 2017, `Version 15.2 (26430.14)` if I remember correctly.

**Comment by MikhailArkhipov** [comment]
This seems to work post 1.1

**Comment by arthur-st** [comment]
Is there any additional information I can provide you to try to trace this down? Alternatively, could you describe specific conditions you confirmedly enable and disable this feature in?

To be noted though, it might be a visual issue with the toggle on my end - I rarely do anything in the interactive console alone. I've noticed that on my laptop there is a fair share of visual lag with the general VS UI under certain circumstances.

**Comment by MikhailArkhipov** [comment]
I can repro in 1.1. I think the problem was that internal name or the property didn't match name of the persistent setting and reflection-based code missed.

**Comment by arthur-st** [comment]
Oh I see, I misread your first reply as "feature working in 1.1", rather than "after 1.1". Good to hear it's solved in future releases!

**Comment by MikhailArkhipov** [comment]
OK, if it is not pressing, we won't be trying to port back to 1.1
