### ISSUE TITLE
Vs Hangs When streaming tweets

### ISSUE THREAD

**Issue by Crackz** [Microsoft/RTVS#3715]
it hangs forever i'm using vs2017 latest version

![capture](https://user-images.githubusercontent.com/12835589/28243079-c0094e22-69be-11e7-9ca7-f13676917a40.PNG)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/bb097aa92ed78b001d738ab73fac190c976d0d51
