### ISSUE TITLE
RHost name for live markdown is weird

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3716]
/usr/lib/rtvs/Microsoft.R.Host --rhost-r-dir /usr/lib64/microsoft-r/3.3/lib64/R/lib --rhost-name **(Markdown1.rmd - 635f4a7f-f70a-4a39-a193-79351d6b9b5f_** --rhost-log-verbosity 1

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8cec036b69fd0d5af1b31516b88d6d4bfa62476f
