### ISSUE TITLE
casing of extension used for new r markdown files

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3728]
Please briefly describe what you were doing that led to the issue, if applicable:

In vs17 rtools using file | new | file | R | R Markdown creates boilerplate file with ".rmd" as its extension.   In rstudio using file | new file | R Markdown creates boilerplate file that when you save it for first time gets ".Rmd" as its extension.

Not sure if casing difference is intentional or is something that should be aligned with casing rstudio defaults to using.   Switching the casing to the ".Rmd" format doesn't appear to affect any vs17 rtools ability to recognize and handle it as r markdown.

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Client (3.3.3.0): C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by MikhailArkhipov** [comment]
Looks like GIT configuration issue since it defaults to ignore file name casing

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/dad3e65a0ab9ae9f936772f00a846038c3d324da
