### ISSUE TITLE
Bunch of tests fail with fixture issue

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3738]
All that have `(IServiceContainer services, TestMethodFixture testMethod)`
```
Message: The following constructor parameters did not have matching fixture data: IServiceContainer services, TestMethodFixture testMethod
```

**Comment by AlexanderSher** [comment]
Are they from the same test assembly?

**Comment by MikhailArkhipov** [comment]
Same in master. `Host.Client.Test`

**Comment by AlexanderSher** [comment]
It misses `[assembly: TestFrameworkOverride]`.
Actually, the whole `AssemblyInfo.cs` is gone.

**Comment by MikhailArkhipov** [comment]
OK, will get it fixed

**Comment by karthiknadig** [comment]
If this is fixed we can actually add a ping test to the container tests.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/dad3e65a0ab9ae9f936772f00a846038c3d324da
