### ISSUE TITLE
Interrupt R command is always enabled

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3741]
This is b/c  `IsProcessing = contexts.Count != 1;`, there 2 contexts: one is top level and another has flag `21889608`. Reproes in 3.3.3 as well, so this is not a change in R. The flag is not stable, 3,3.3 gives `21889496`

**Comment by MikhailArkhipov** [comment]
The test is `InterruptRStatusTest`

**Comment by karthiknadig** [comment]
https://github.com/Microsoft/RTVS/pull/3742
