### ISSUE TITLE
R Markdown Challenges in RTVS 

### ISSUE THREAD

**Issue by udayguntupalli** [Microsoft/RTVS#3753]
Hello , 
         Trying to find some guidance on R Markdown in RTVS . I am unable to find any  resources with good examples . I had a pre-built R Markdown which I am unable to run / launch through RTVS . Can someone kindly provide documentation for using R Markdown in RTVS . 

Best 
Uday

**Comment by MikhailArkhipov** [comment]
RTVS uses same rmarkdown package and pandox/mklatex components. What exactly are you trying to do? Publish it as HTML? PDF?

**Comment by udayguntupalli** [comment]
@MikhailArkhipov  : I was trying to 2 types of reports 
1. HTML 
2. PDF 

What I want to do is call a function that renders the rmarkdown  ?  Can you provide any examples that guide me in this direction 

best 
Uday

**Comment by MikhailArkhipov** [comment]
Right click -> Preview-> HTML
https://docs.microsoft.com/en-us/visualstudio/rtvs/rmarkdown
