### ISSUE TITLE
rtvs rendering of leaflet map views that work in rstudio

### ISSUE THREAD

**Issue by myusrn** [Microsoft/RTVS#3756]
Please briefly describe what you were doing that led to the issue, if applicable:

Running the simple leaflet maps code below in rstudio successfully renders map in rstudio viewer pane and likewise when you click "show in new window" which flips you over to default browser and opens html file that was generated using a http://localhost:<port>/session/<temp folder for html output>/index.html url.  

Running the same code in vs17 rtools takes you directly to default browser view and opens html file using physical disk path %temp%\<r client temp folder>\<temp folder for html output>\index.html and this fails to render.  

I'm guessing this is because some of the javascript library references in leaflet generated html file will only work when page is accessed via an http web server.  That's because if i talk the rstudio generated output and try and access it using disk file path to index.html it repros the same unexpected result. 

if (!require("leaflet")) { install.packages("leaflet"); library(leaflet) }
my_map <- leaflet() %>% addTiles
my_map

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.15063.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Client (3.3.3.0): C:\Program Files\Microsoft\R Client\R_SERVER\

**Comment by karthiknadig** [comment]
#3671 addresses this issue. Although the title says remote scenario, it will handle this case as well.

**Comment by MikhailArkhipov** [comment]
#3671 is Sprint 17 == August so plan is to get this into 15.4 update. 15.4 starts appearing in the preview channel some time in August. https://www.visualstudio.com/vs/preview/

**Comment by myusrn** [comment]
Great to hear this functionality is implemented and on the way.  Will switch to preview install and try when i see 15.4 preview being offered.  Is there a way for folks looking at sprint no. defined for an issue resolution commit and determine the vs17 preview release that change is expected to show up in?

**Comment by MikhailArkhipov** [comment]
Yes, if you install [ZenHub ](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd) for Chrome

**Comment by MikhailArkhipov** [comment]
In other browsers you can also see it

![image](https://user-images.githubusercontent.com/12820357/28634055-d0df828c-71ea-11e7-973f-cffce33dfcfc.png)

![image](https://user-images.githubusercontent.com/12820357/28634076-e86df604-71ea-11e7-96d3-58c17a7e953b.png)

![image](https://user-images.githubusercontent.com/12820357/28634102-feb245f0-71ea-11e7-8f7e-2d688b8622dc.png)

**Comment by myusrn** [comment]
Thanks for response.  What you outline appears to be about how i determine the sprint ## that an issue has been associated with.  ZenHub [ khanban ] boards view of GitHub repo very cool thanks for pointer.  Under the milestones view i can see the expected due/completion date for a given sprint.  Does one then just line up that date with a vs17 preview release to determine when they can expect those sprint completed checkins to show up in a preview install?

**Comment by MikhailArkhipov** [comment]
No, our sprints do not align with VS previews. They are basically just month long milestones. VS is a large division and preview/update dates are determined by many factors and many teams. They are not generally made public and are not set in stone.

**Comment by myusrn** [comment]
p.s. Wrt chrome zenhub extension mentioned earlier found that https://app.zenhub.com/workspace/o/microsoft/rtvs/ can be used as edge browse story for zenhub GitHub issues kanban board & repots access prior to any edge specific extension becoming available.
