### ISSUE TITLE
Interactive window become slow when entering text.

### ISSUE THREAD

**Issue by Masutani** [Microsoft/RTVS#3758]
Recently I have this issue, after some debug sessions the interactive session becomes slow. Every key input takes several seconds to respond.

- restarting R doesn't recover from this
- closing solution doesn't recover from this
- erasing history recover this

VS2017 + RTVS v1.0 + Win10
--
Microsoft Visual Studio Community 2017 
Version 15.2 (26430.15) Release
VisualStudio.15.Release/15.2.0+26430.15
Microsoft .NET Framework
Version 4.7.02046
R Tools for Visual Studio   1.1.30523.1233
--
 sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by MikhailArkhipov** [comment]
Try 15.3.2 which went out. Thanks.

**Comment by jancura** [comment]
I have experienced this problem with 15.4.4 VS2017

**Comment by Masutani** [comment]
This still occurs on VS2017(15.4.4) + RTVS v1.2 + Win10 (RS3)

Microsoft Visual Studio Enterprise 2017 
Version 15.4.4
VisualStudio.15.Release/15.4.4+27004.2009
R Tools for Visual Studio   1.2.30905.1244

It is the most frastrating glitch in my environment.

**Comment by MikhailArkhipov** [comment]
This might be #4187 fixed in 15.5
