### ISSUE TITLE
Live markdown fails with NRE

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3761]
Repro markdown:
https://raw.githubusercontent.com/Microsoft/acceleratoRs/master/CreditRiskPrediction/Code/CreditRiskDeploy.Rmd

![image](https://user-images.githubusercontent.com/3840081/28654575-4427a8be-724a-11e7-9fcf-afae5c0df605.png)

**Comment by MikhailArkhipov** [comment]
Doesn't fail for me, but I have for another NRE so might be the same

**Comment by karthiknadig** [comment]
![image](https://user-images.githubusercontent.com/3840081/28811165-52fa1682-7642-11e7-9872-116eaa69b98f.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ea512475a4f87015c7a49fe2ab94f42f2b05f4ee
