### ISSUE TITLE
Add new item shows random strings

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3779]
![image](https://user-images.githubusercontent.com/3840081/28811296-14385b92-7643-11e7-895c-e6c3717ff9d4.png)

**Comment by MikhailArkhipov** [comment]
Localized Experimental instance (F5) ?

**Comment by karthiknadig** [comment]
No. This was master under F5

**Comment by karthiknadig** [comment]
Looks like it is just random strings. Every F5 results in different text there:
![image](https://user-images.githubusercontent.com/3840081/29034243-846b5618-7b4c-11e7-9f59-3c13902b3987.png)

**Comment by MikhailArkhipov** [comment]
Yes, I've seen it in F5. Never in actual install.

**Comment by karthiknadig** [comment]
You are correct. I don't see this in the actual install.
