### ISSUE TITLE
Add new should have a text file or csv file option

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3780]

**Comment by MikhailArkhipov** [comment]
R parser would need to know that `{r ...}` is a special block/syntax construct, Probably attached to AST as a separate data type since it is not a regular language syntax and then completion source could use it.

**Comment by karthiknadig** [comment]
@MikhailArkhipov i think above comment is on the wrong issue.

**Comment by MikhailArkhipov** [comment]
Right. About this - don't you get CSS/Text/XML/XSLT in Add New Item? In File | New they are in General

**Comment by karthiknadig** [comment]
You are right. I get CSS/Text/XML/XLT. I think we can close this.
