### ISSUE TITLE
VariableGridTest fails due to layout changes.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3793]
Message: Expected value to be 0 because there should be no difference at line 273.
Expected:                      "Name": "Border",
Actual:                      "Name": "ContentPresenter",
Difference at position 32
, but found 273.

**Comment by MikhailArkhipov** [comment]
Fixed that

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/97b006104e99a94b8f9d885e3a89f3cfb502a1c4
