### ISSUE TITLE
Live RMarkdown sync: need more granularity

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#3810]
Live code editing. It appears that the behavior is when you move to a new line using the cursor it will evaluate the code - unless you have preview pane sync disabled. For purely lightweight edits like editing the markdown itself, this feels like a great feature to have. However, for code blocks it feels like there's an intermediate level of granularity that is needed. i.e.,:

FULL_SYNC: sync all markdown and code edits (with existing behavior of waiting to send code edits until moving off the current code line)
MARKDOWN_SYNC: sync all markdown, but disable syncing of code edits - in this mode the user must explicitly run the code block (via a command like CTRL+ALT+C)
NO_SYNC: no sync of markdown or code

Thoughts?

**Comment by MikhailArkhipov** [comment]
I has those options. You can turn off live sync on the R toolbar. Then use same commands as in R, "Run Chunk" and "Run All Chunks Above". Or switch off preview pane completely in Tools | Options | Text Editor | R Markdown.

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/29130339-5c5247b6-7cde-11e7-8fce-8983a38da4ac.png)

![image](https://user-images.githubusercontent.com/12820357/29130376-7e792634-7cde-11e7-9f98-f88cee7722c7.png)

**Comment by MikhailArkhipov** [comment]
Closing per offline discussion
