### ISSUE TITLE
Annoying behaviour with Rmd files when code is in last line in file

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3814]
This applies when

1. The cursor is at the bottom of the editor window (or near the bottom)
2. The cursor is on the last nonempty line in the file
2. That line contains code (either a code chunk, or `inline`)

When these conditions are satisfied, the window scrolls up unexpectedly, hiding the line the cursor is on. The only way to stop this is to insert dummy lines at the end.

To reproduce:

1. Make a new Rmd file
2. Press Enter enough times so that you're at the bottom of the window
3. Type 

> This is a `code` line

You should see the behaviour described.

**Comment by MikhailArkhipov** [comment]
This happens when there is a projecting block partially visible at the top. Doesn't have to be the last line.

![image](https://user-images.githubusercontent.com/12820357/29182699-bae0dc94-7db4-11e7-9652-f767399e4f36.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ea512475a4f87015c7a49fe2ab94f42f2b05f4ee
