### ISSUE TITLE
pandoc install not detected by Visual Studio 2017

### ISSUE THREAD

**Issue by spyrokete** [Microsoft/RTVS#3815]
I've installed and re-installed pandoc several times, but each time Visual Studio is not picking it up. This makes me unable to even create a rmarkdown document. I followed the instructions given in https://docs.microsoft.com/en-us/visualstudio/rtvs/rmarkdown but I am still unable to create a new markdown document. I hope you can help. Thank you.

**Comment by Hong-Revo** [comment]
Did you include the pandoc directory in your path?

**Comment by spyrokete** [comment]
It was operator error. Thank you so much for the help.
