### ISSUE TITLE
IntelliSense not prompt global variable in [ ] 

### ISSUE THREAD

**Issue by Victsz** [Microsoft/RTVS#3816]
![image](https://user-images.githubusercontent.com/8154646/29011228-f02f49e2-7b63-11e7-9949-a50e657e69af.png)

...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 6.3.9600.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.1.30523.1233, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.3.2: C:\Program Files\R\R-3.3.2

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ea512475a4f87015c7a49fe2ab94f42f2b05f4ee
