### ISSUE TITLE
Intellisense doesn't like ! in arithmetic expr

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3818]
![image](https://user-images.githubusercontent.com/11328890/29121014-242fab9a-7d50-11e7-84ac-f8f3049e4762.png)

**Comment by MikhailArkhipov** [comment]
This comes from the fact that

http://stat.ethz.ch/R-manual/R-patched/library/base/html/Syntax.html
https://www.programiz.com/r-programming/precedence-associativity 

list `!` as _lower_ precedence to compared to `*` However, when converted to _value_ type, `!` has higher precedence than `*` (similar unary `+` or `-`) BUT it applies to the entire expression to the right. I.e. 

```
x <- 1
y <- 1
2 + !x+y
```

yields 2. This is different from typical C case (see http://www.swansontec.com/sopc.html) where `!` is plain vanilla unary.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ea512475a4f87015c7a49fe2ab94f42f2b05f4ee
