### ISSUE TITLE
Occasional REPL session termination when editing markdown

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3826]
Broker crash:

```
Failed to kill host process for session 'Markdown1.rmd - db5bb043-10ea-41a9-bb34-37b331d77b27_'.
Exception: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Microsoft.Common.Core.OS.Win32Process.Kill()
   at Microsoft.R.Host.Broker.Sessions.Session.KillHost()
```

Do we actually want to re-throw? I don't think it is worth killing the broker...

```
_sessionLogger.LogError(0, ex, "Failed to kill host process for session '{0}'.", Id);
throw;
```

**Comment by AlexanderSher** [comment]
We want to rethrow on this level. This is something that shouldn't happen if RHost isn't hanged.

**Comment by MikhailArkhipov** [comment]
OK, it is just some caller handle it and some don't

**Comment by MikhailArkhipov** [comment]
Markdown is calling `RSession?.StopHostAsync(waitForShutdown: false)` on 5 min timer stopping sessions that are inactive so user doesn't end up with 10s of sessions running since there a session per document.

**Comment by MikhailArkhipov** [comment]
There are multiple reasons in Windows why process may not be killed. Actually, if it hangs it *can* be killed. We don't know where R is at the moment. Ex async IO requests may prevent process from being killed (logging?)

https://blogs.technet.microsoft.com/markrussinovich/2005/08/17/unkillable-processes/
https://stackoverflow.com/questions/49988/really-killing-a-process-in-windows/50011#50011

We may give it a few retries but ultimately, if process is not killable, so be it.
