### ISSUE TITLE
Scrolling in data view sometimes lags heavily

### ISSUE THREAD

**Issue by arthur-st** [Microsoft/RTVS#3837]
Often, even when doing head(df) of my current dataset (~10^6 x 50), after scrolling to the last column and then just scrolling around columns in the middle, the editor at some point sort of lags out. What happens then is that the ongoing scrolling animation freezes, and eventually resumes in haphazard, sporadic manner, which takes far too long return to normal. Quick and working solution is to close the tab and open a new one, but that'll get annoying in the long run.

Sorry for not exactly helpful problem description, but I can't think of a reproducible example here. If I had to hazard a  guess as to the root cause, even with head() somehow the entire data frame is getting referred to by the viewer, which could explain the slowdown due to sheer size of the array.

**Comment by MikhailArkhipov** [comment]
Might be related to discussion in https://github.com/microsoft/rtvs/issues/3771

**Comment by MikhailArkhipov** [comment]
This probably gets fixed in https://github.com/Microsoft/RTVS/commit/235d2372fc802648005bd71d2291feaf7c2f84f4 since it switched default to snapshots.

ETA VS 2017 15.4
