### ISSUE TITLE
Interactive console duplicates "progress bar"

### ISSUE THREAD

**Issue by arthur-st** [Microsoft/RTVS#3844]
`read_csv("file.csv")` from `readr` package will cause the following output in the R Interactive:

`|=========================================================================================================================================================== |  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  292 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  293 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|============================================================================================================================================================|  99%  294 MB
|=============================================================================================================================================================| 100%  294 MB`

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/9043163d3cfe13c0fcf40b88e80efc60bcd21765
