### ISSUE TITLE
Performance issue on vs 2017 v15.3

### ISSUE THREAD

**Issue by eightrivers** [Microsoft/RTVS#3862]
We upgraded VS 2017 from v15.2 to v15.3, and the speed of typing R code in R interactive became some slowly. It always takes about 2 or more seconds to show the intellisense panel when typing some codes, such as ls(), dir(), options(), or custom variables. The same thing also happened when trying to edit a R code file. 

We had tried in several physical machines, and all machines installed the v15.3 have the same issue, while the machines with v15.2 are OK. We even try the way to uninstall the components related to R (R tools, MS R Client) and reinstall it again, but nothing happened.

The environment we tried on is:

- OS: Win 10 Enterprise x64 CHS, version: 10.0.15063
- CPU: i7-6820HQ 2.70GHz
- Mem: 64G
- Visual Studio: Enterprise 2017 v15.3.0
- R tool: version: 1.1.30623.0940
- R interpreter : Microsoft R Client 3.3.2.0, in local machine

**Comment by Hong-Revo** [comment]
I think I've seen this as well, but only in the case where I use `::` to look inside a package. Eg typing `devtools::install_github` slows down dramatically after the `::` is typed.

**Comment by eightrivers** [comment]
In my side, it is some slow when trying anything in R interactive window or code editor, Eg, typing ls(), it will be about 1-2 seconds the character 's' will be shown after typing the character 'l'.

**Comment by MikhailArkhipov** [comment]
Found it

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/379c11ee640511132851b7b2fb9f3f5b91a3b2d2

Will try and get it to 15.3.2

**Comment by eightrivers** [comment]
Today we installed a new vs.net upgrade package, and the version of RTVS has been upgraded to 1.1.30804.1005. Seems the issue is still in there. So would you please kindly let us now when the vs.net 2017 v15.3.2 could be available? Thanks!

**Comment by MikhailArkhipov** [comment]
It is available now as far as I can see.

**Comment by eightrivers** [comment]
Get it, already updated, the issue has been solved. Thanks!
