### ISSUE TITLE
Pressing Esc to dismiss tooltip in REPL also clears commandline

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3865]
I think this is new in VS 2017 update 3; I don't recall seeing it in update 2.

To repro: in the REPL, type anything that will pop up a tooltip, eg `dir()`. Press Esc. The commandline is cleared.

**Comment by MikhailArkhipov** [comment]
Reproes in PTVS too. Does not repro in 2015. Might be some subtle interactive window change.

**Comment by MikhailArkhipov** [comment]
Will try and get it to 15.3.2

https://github.com/Microsoft/RTVS/commit/379c11ee640511132851b7b2fb9f3f5b91a3b2d2
