### ISSUE TITLE
WindowsDockerService instantiation requires docker installation

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3866]
If docker isn't installed, instantiation fails with exception. This should not happen to any service.
Probably we should get LocalDocker instance later.
Also, on my machine it can't find registry entry even with installed docker.

**Comment by MikhailArkhipov** [comment]
It should work as with markdown/pandoc - detect that Docker is missing, open page with the installer.

**Comment by AlexanderSher** [comment]
If user doesn't want any docker stuff on his machine, why should we show him anything?

**Comment by MikhailArkhipov** [comment]
I mean when they actually want to invoke container construction. Similar to SQL ops when we show they need specific SQL driver or markdown publishing when it needs pandoc.

**Comment by AlexanderSher** [comment]
Got it,
