### ISSUE TITLE
R Markdown live preview

### ISSUE THREAD

**Issue by kevintxu** [Microsoft/RTVS#3883]
Is it possible to add live preview to the VS R Markdown editor? Similar to RStudio.

**Comment by karthiknadig** [comment]
#3637  :)

**Comment by MikhailArkhipov** [comment]
First version should be available via VS Preview channel https://www.visualstudio.com/vs/preview/ with 15.4 Preview 1. We'll improve, address feedback and fix bugs in subsequent 15.4 previews. I don't have final release date for 15.4 though, but VS updates are not very far between. :-)
