### ISSUE TITLE
Certificate issue with RTVS and Remote Workspace

### ISSUE THREAD

**Issue by kavarral** [Microsoft/RTVS#3887]
Steps executed this far:  Created configured Windows VM (Server 2016) using One box config using ARM Template.   Installed RTVS_Remote_2017-06-27.1 which installs (R Remote Service for Visual Studio), installed R Open microsoft-r-open-3.4.0 and have .Net Framework 4.6.1 installed.   Both my services are running successfully including R Remote Services,  R User Profile Services.  Both of these are added to inbound and outbound firewall rule (Microsoft.R.Host.exe and Microsoft.R.Host.Broker.exe)
I have changed the opened ports 5444,  463, 12800 (inbound and outbound) on both the VM firewall and the Windows Firewall.  I can ping my server on port 5444 and 12800 successfully.  I created a certificate and configuered the Microsoft.R.Host.Broker.Config.json file accordingly. I have exported the certificate from the server that I created and imported onto my machine ... when I try to connect with R Remote in Visual Studio, I get the following error from the logs on the remote R Server:  
The server mode SSL must use a certificate with the associated private key.
Authentication failed because the remote party has closed the transport stream.
Please can someone help me and tell me where I am going wrong here or what the issue could be.  It's like it doesn't see my certificate

**Comment by karthiknadig** [comment]
Can you check network service directory on the server for the logs to see if there are any error messages?
`C:\Windows\ServiceProfiles\NetworkService\AppData\Local\Temp`

The logs should be named some thing like `Microsoft.R.Host.Broker_2017725_093620_pid3800.log`

**Comment by karthiknadig** [comment]
Can you also paste the command you used to create certificate?

**Comment by kavarral** [comment]
Hi Thank you for the response.  I ran the following on the R Remote Server to create the certificate  ... New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My -DnsName "xxx.westcentralus.cloudapp.azure.com" as per the documentation, this creates the certificate in the Local Computer --> Personal certificate store.  I then right clicked on Manage Private Keys and added NETWORK SERVICE with full control as per the documentation.  I have also added this certificate to the trusted root certification store.
This is where I may be going wrong as I don't see any documentation on this, I then exported this and selected export option with Private key with default of include all certificates in the certification path if possible.  I then imported the certificate onto my local machine where I want to connect to the R Remote Server. I have tried a number of options such as adding to the Personal certificates folder and the trusted root certification folder but none of this seems to resolve the problem.  I am trying to connect via VS 2017 and the remote R server is running on Windows 2016 ... could this be a problem?  My last resort now is to connect on a different machine using VS 2015. Attached is the full log from the R Host Broker log files. I have just changed my server name to xxx for security purposes.  After a server restart, I now seem to be getting a different error "The credentials supplied to the package were not recognized". I have not joined my VM to the domain and am just using the standard credentials used to login to the VM 

[Microsoft.R.Host.Broker_2017827_122734_pid3088.txt](https://github.com/Microsoft/RTVS/files/1254397/Microsoft.R.Host.Broker_2017827_122734_pid3088.txt)

Thanks again for the help.

**Comment by karthiknadig** [comment]
Lets try this. 
1. On the client machine, start Visual Studio Command prompt as admin. 
2. Change `<server>` to your server's full DNS name (this will be `xxx.westcentralus.cloudapp.azure.com` ). It will ask for a password. Run this:
`makecert.exe -r -pe -n "CN=<server>" -sky exchange -b 01/01/2011 -e 01/01/2025 -eku 1.3.6.1.5.5.7.3.1 -sp "Microsoft RSA SChannel Cryptographic Provider" -sy 12 -sv servercert.pvk servercert.cer`
3. Change `<password>` in the command, and run this:
`pvk2pfx -pvk servercert.pvk -spc servercert.cer -pfx servercert.pfx -pi <password>`
4. Copy the generated `servercert.pfx` file to the server.
5. On the server machine import the `servercert.pfx` file using `certlm.msc` to Personal store.
6. Give NETWORK SERVICE permissions to access the imported cert.

Let me know if you get the same error message in the logs.

**Comment by kavarral** [comment]
Hi Karthnik,  Thank you for your assistance, I managed to get this setup using the script in this post of yours https://github.com/Microsoft/RTVS/issues/3315.
