### ISSUE TITLE
Pressing Esc in REPL doesn't clear commandline

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#3888]
This is in update 3.2. Looks like the fix to #3865 broke something else.

To repro: type anything in the REPL. Press Esc. What was typed remains there.

**Comment by MikhailArkhipov** [comment]
Yes, 15.3 was a tactical limited fix. Could not change much there.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/54426fb36461586ce1e7ca1e1466614ccdd69cee
