### ISSUE TITLE
Intellisense not shown for back-tick variables

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3899]
Before pressing back-tick:
![image](https://user-images.githubusercontent.com/3840081/29794495-101b3c26-8bfd-11e7-8d61-c689ddade477.png)

After pressing back-tick (no intellisense):
![image](https://user-images.githubusercontent.com/3840081/29794600-807b00b4-8bfd-11e7-8b5b-25bb4ab3c9bd.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/eab57cd565512d22dce04fa67733bdc386591dd0
