### ISSUE TITLE
Containers "start" button should be disabled for busy ports

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3938]
`IContainer` has information about its ports. We can disable "start" button for containers with same ports if one of them is running.

**Comment by MikhailArkhipov** [comment]
It is hard for the user to figure out why it is disabled. It may be better to pop up message with the explanation if they try to start it. We do disable some buttons (like delete on local connections) but at least we provide tooltip info why. However, tooltip is not very discoverable and is not accessible.

**Comment by AlexanderSher** [comment]
Ok, that's even simpler
