### ISSUE TITLE
Use dropdown instead of textbox for local docker creation

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3940]

**Comment by AlexanderSher** [comment]
@karthiknadig, can we have any kind of a feed to extract values for a drop-down?

**Comment by AlexanderSher** [comment]
https://registry.hub.docker.com/v1/repositories/kvnadig/rtvsd-ub1604/tags

**Comment by MikhailArkhipov** [comment]
Will need to handle offline or unreachable case

**Comment by karthiknadig** [comment]
For offline case we will need to show only those images that are available when we do "ListImagesAsync"
