### ISSUE TITLE
Restructure UnitTests.Core to support .NET Core projects

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3941]
Currently it has MEF and UIThreadHelper things that want desktop and VS Shell assembly. This will make writing tests for non-Windows components such as language server easier.

**Comment by AlexanderSher** [comment]
I have a changeset for that, but it isn't finished. Main thread is available in .net core projects, so there should be some kind of emulation for it. Or we can check if it is really needed in those projects

**Comment by MikhailArkhipov** [comment]
We can merge it later into mine (which is very basic so far, just to get stuff like categories).

**Comment by MikhailArkhipov** [comment]
Got 90% compiled and tests in .NET Core test assembly discovered.
