### ISSUE TITLE
Tooltip text for container connection delete needs to be updated.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3961]
![image](https://user-images.githubusercontent.com/3840081/30399539-df342526-9888-11e7-8938-d8485e181237.png)

**Comment by AlexanderSher** [comment]
Ok, suggestions on tooltip text?

**Comment by MikhailArkhipov** [comment]
`Stops and deletes Docker container including the image on disk`. ?

**Comment by MikhailArkhipov** [comment]
Appears to be fixed
