### ISSUE TITLE
Containers create should show message if docker is not found.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#3974]
```
---------------------------
Microsoft Visual Studio
---------------------------
There was an error creating the container. Please see R Containers output for details.
---------------------------
OK   
---------------------------
```

But the "R Containers" output window does not exist.
![image](https://user-images.githubusercontent.com/3840081/30502603-d6f00ea4-9a1b-11e7-9a9a-0e7aadc54d26.png)

In this case, I tried to create containers with no docker installed.

**Comment by AlexanderSher** [comment]
Should we even show "Create" button?

**Comment by karthiknadig** [comment]
I think we may have to consider discover-ability of the feature. We should show "create" but clicking it should show a message, saying "This action requires docker".

**Comment by AlexanderSher** [comment]
Sure

**Comment by MikhailArkhipov** [comment]
See also https://github.com/Microsoft/RTVS/issues/3980

**Comment by AlexanderSher** [comment]
When docker isn't found, Containers window shows watermark with link
