### ISSUE TITLE
Container dialog 'Version' field should have tooltip/watermark with explanation

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3976]
What exactly user should type: R3.4? 3.4.0? Maybe pre-fill with 'latest'?

**Comment by AlexanderSher** [comment]
Maybe just a drop-down?

**Comment by MikhailArkhipov** [comment]
Maybe... But where do we get the list? what to do with new versions?

**Comment by MikhailArkhipov** [comment]
Still reproes

![image](https://user-images.githubusercontent.com/12820357/30659090-abbd0d70-9df1-11e7-9442-27308c48a0d9.png)

**Comment by AlexanderSher** [comment]
Tooltip was overridden by Watermark. Should work after #3996 is checked in.
