### ISSUE TITLE
We should open output by default when there are container errors

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3977]
![image](https://user-images.githubusercontent.com/12820357/30503805-8128ac88-9a20-11e7-83c1-d8599bc98553.png)

We should open output by default like Build does when there are errors. Where do I find the output? There is nothing in the output dropdown

![image](https://user-images.githubusercontent.com/12820357/30503870-c49412c8-9a20-11e7-84e4-1cb68be1f13f.png)

**Comment by AlexanderSher** [comment]
Is it a dup of https://github.com/Microsoft/RTVS/issues/3974?

**Comment by AlexanderSher** [comment]
@MikhailArkhipov, what are the repro steps for this issue?

**Comment by AlexanderSher** [comment]
Fixed with https://github.com/Microsoft/RTVS/issues/4002. Now it always opens for errors.
