### ISSUE TITLE
UI issues in Create Container panel

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3978]
![image](https://user-images.githubusercontent.com/12820357/30504020-6f34213c-9a21-11e7-9709-a7f72acfa48e.png)

It says 'Workspaces' and 'Local'. The window already has 'Containers' title, so 'Workspaces' is not needed. 'Local' probably 'Local Docker'? Also, single letter name is not supported.

Entries to list of docker containers should have docker icon. Can we find small docker image or maybe just blue 'D' ? or boxes like in

![image](https://user-images.githubusercontent.com/12820357/30504188-3049342a-9a22-11e7-9799-402ed01b0d12.png)

![image](https://user-images.githubusercontent.com/12820357/30504207-4afe548a-9a22-11e7-8c6a-c64bc1f9388b.png)

**Comment by AlexanderSher** [comment]
> Also, single letter name is not supported.

It isn't supported by docker: https://github.com/moby/moby/issues/3138

**Comment by AlexanderSher** [comment]
- "Workspaces" button is removed
- "Local" is renamed to "Local Docker Containers"
- Single letter names aren't supported by docker (https://github.com/moby/moby/issues/3138 )
- Docker brand guidelines (https://www.docker.com/brand-guidelines) do not allow us to use Docker logo without 'docker' letters. With them, it looks quite ugly:
![image](https://user-images.githubusercontent.com/8933858/30663548-9d169484-9e10-11e7-8a71-b06e794a9d62.png)
Do we really need identical icon for every line in the list?

**Comment by MikhailArkhipov** [comment]
[cid:image002.jpg@01D33213.421AB3D0]

**Comment by MikhailArkhipov** [comment]
![image](https://user-images.githubusercontent.com/12820357/30665651-851d8de2-9e06-11e7-9738-82bef428b0bb.png)
