### ISSUE TITLE
Show watermark that docker isn't installed on Containers window instead of UI

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3980]

**Comment by MikhailArkhipov** [comment]
Does not show watermark. I don't have docker

![image](https://user-images.githubusercontent.com/12820357/30659346-59ebad34-9df2-11e7-8066-ca3d7af6dddb.png)

**Comment by AlexanderSher** [comment]
Yes, I've forgotten that I didn't add an event that changes VM properties.
