### ISSUE TITLE
UI changes for the Workspace/Containers

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3982]
There are some discoverability issues. So, proposal is to

1. Change 'Add' in Workspaces to 'Add Connection'.
2. Change 'Containers' (which doesn't look like actionable button) to 'Create Container...' 
3. 'Create Container...' takes you to Containers panel and auto-activates Add there.
4. Align Create Container... to the right to separate it from Add..
5. Maybe add right-hand triangle/arrow to 'Create Container.. to indicate it takes you to new UI
6. Add R Tools | Windows | Containers to the menu (docker icon. may or may not have accelerator).

**Comment by MikhailArkhipov** [comment]
See #3978

**Comment by AlexanderSher** [comment]
I don't think that "Containers" should be changed to "Create Container". Most of the time, user will want to switch to "Containers" window to start/stop existing container, not create a new one.

**Comment by MikhailArkhipov** [comment]
The name it `Go to Containers`

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/54601da3a4e4f0e7315f768e601a1f70d2bee8a3
