### ISSUE TITLE
Add link to containers docs to Containers window

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3983]
Would be useful to have a hyperlink 'Working with containers' or something that opened doc page directly.

**Comment by AlexanderSher** [comment]
@karthiknadig , do we have our own document, or should I just add a link to the docker website?

**Comment by karthiknadig** [comment]
Currently we don't have a separate docs page for containers. I am currently working on docs for the linux  connectivity, I will do the container docs after I am done with that.

**Comment by MikhailArkhipov** [comment]
Don't think we need this as much.
