### ISSUE TITLE
Can't connect to the second container after first container is stopped

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#3988]
![image](https://user-images.githubusercontent.com/742484/30565075-dbf510b8-9c7b-11e7-987d-a57f9a425493.png)

(karthik has enough context on the issue alex)

**Comment by AlexanderSher** [comment]
Ok, what's the point of switching from one connection to another which is identical to the first one?

**Comment by karthiknadig** [comment]
Repro steps:
1. Connect to container 1.
2. Create container 2 (you will see a error message indicating port is busy)
3. Stop container 1
4. Start container 2.
5. Now when you try to connect to container 2, you will see the above message.

**Comment by AlexanderSher** [comment]
Got it.
