### ISSUE TITLE
RSessionProvider.Connected == true when no connection is active.

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#3993]

**Comment by AlexanderSher** [comment]
`RSessionProvider.IsConnected`  can be set to `false` in 2 cases:
- Sessions are stopped explicitly by user when he switches between brokers
- When `UpdateHostLoadAsync` can't get broker information and fails with `RHostDisconnectedException`

**Comment by MikhailArkhipov** [comment]
What is broken for the user?

**Comment by AlexanderSher** [comment]
Connection switching, package manager update, REPL window title, etc.

**Comment by MikhailArkhipov** [comment]
I mean whats the repro? These have been working OK

**Comment by AlexanderSher** [comment]
Ok, so the problem is in the `FetchHostLoad` setting. When it is `false`, we don't ping host at all.
@karthiknadig, do you know what is the cheapest way to verify that connection to broker is alive? Checking individual session statuses won't work - sessions may be stopped while connection is still alive.

**Comment by AlexanderSher** [comment]
> I mean whats the repro? These have been working OK

For example:
- Create remote connection
- Disconnect from the network and connect back
- Try reconnect.

It will fail because RSession thinks that it is connected already.

Another scenario (with Docker):
- Start docker container
- Connect to the container
- Stop container
- Start container

User can't reconnect back.

**Comment by karthiknadig** [comment]
HTTP get on '/interpreters' will get a pre-cached list of interpreters, success of that call should indicate if the connection is alive. This does not depend on sessions or any other state of the host OS.

**Comment by AlexanderSher** [comment]
Great!
