### ISSUE TITLE
Container control buttons don't have proper background

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3997]
![image](https://user-images.githubusercontent.com/12820357/30661155-f09d279e-9df7-11e7-9eab-3ba43946fac7.png)

Also, Run is grey, should be

![image](https://user-images.githubusercontent.com/12820357/30661291-61200d4c-9df8-11e7-884a-f85cb169c745.png)

(KnownMonikers.Run)

**Comment by AlexanderSher** [comment]
Is it a high contrast theme?

**Comment by AlexanderSher** [comment]
I don't see any difference on my machine:

![image](https://user-images.githubusercontent.com/8933858/30665788-d525507a-9e17-11e7-93c5-25c5f182356c.png)

And it actually shares button styles with Workspaces

**Comment by MikhailArkhipov** [comment]
Try white background

**Comment by AlexanderSher** [comment]
Found it. It is actually not in XAML but in code.
