### ISSUE TITLE
Can't create container if Containers window is up by default

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#3998]
Make sure Containers window is up
Close and Run VS again
Try creating container

Clicking on Create button has no effect.

Go to Workspaces
Click Containers
Repeat above

Now creation starts

**Comment by MikhailArkhipov** [comment]
Actually, it doesn't work for me most of the time anyway. No messages.

**Comment by MikhailArkhipov** [comment]
Looks like Docker running detection is not finding that Docker is down. Also, not sure if Docker needs net connection?

**Comment by AlexanderSher** [comment]
I can't repro it. Without running docker, it now shows watermark. With it, everything works as expected.

**Comment by MikhailArkhipov** [comment]
Closing for now, will re-test
