### ISSUE TITLE
Start Container always activates output window

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4002]
Takes away REPL. Should only activate on error OR has an option similar to VS Build has ('always open Error list...')

**Comment by AlexanderSher** [comment]
`always open Error list` doesn't affect Output window - it will still get focus during build, error pane will just take it back after the build. We don't do anything special to activate the output window - it gets activated by `OutputStringThreadSafe` itself and I couldn't find any other method that just prints the output.

**Comment by MikhailArkhipov** [comment]
`outputWindow.CreatePane(ref _paneGuid, _windowName, fInitVisible: 1, fClearWithSolution: 1);`

`fInitVisible` probably makes it visible on the first call. But yeah, if `OutputStringThreadSafe` reactivates it, there is nothing we can do then
