### ISSUE TITLE
VS Crashes if user does not have docker permissions.

### ISSUE THREAD

**Issue by karthiknadig** [Microsoft/RTVS#4005]

**Comment by MikhailArkhipov** [comment]
Who should take this?

**Comment by MikhailArkhipov** [comment]
May no longer repro since we capture container exceptions now.

**Comment by karthiknadig** [comment]
You are correct. the crash does not repro. If users does not have docker permission, they will get that detail as a part of the error message that is obtained from docker.

**Comment by karthiknadig** [comment]
You get this message when you start docker for windows:
![image](https://user-images.githubusercontent.com/3840081/30991737-2312bbb2-a45b-11e7-8d18-5e36ed5829cd.png)
