### ISSUE TITLE
Update package index on connection change

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4030]

**Comment by AlexanderSher** [comment]
Is it on 15.3.5?

**Comment by Hong-Revo** [comment]
I reinstalled the client using the latest build that @MikhailArkhipov pointed me to, and now the index is rebuilt. It just takes a bit of time.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/89403d274d51fbb20014a1279e9c0aa36ed032d2
