### ISSUE TITLE
Rmarkdown preview should respect code chunk options

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#4046]
In particular, for something like

<pre>```{r, eval=FALSE}
# example code: do not execute
load("bigdataset.rdata")
rxNeuralNet(bigformula, data=bigdataset)
```
</pre>
it should just copy the code to the preview pane.

**Comment by Hong-Revo** [comment]
(I'm referring to the green triangle button, "Run current code chunk and update preview pane".)

**Comment by MikhailArkhipov** [comment]
It does read chunk options, just doesn't do anything with `eval`. So should then just copy output. OK. With comment or just the code?

**Comment by Hong-Revo** [comment]
Yes, it should have the comment as well. You would generally have `eval=FALSE` if the chunk is meant as an example, so the code is meant for the reader.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/54601da3a4e4f0e7315f768e601a1f70d2bee8a3
