### ISSUE TITLE
RxSpark function help wrong

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#4050]
This is with the unsigned build that @MikhailArkhipov sent me.

![image](https://user-images.githubusercontent.com/11328890/30818126-06813194-a25e-11e7-81d8-d12f0db84fbc.png)

**Comment by MikhailArkhipov** [comment]
There are probably multiple signatures and we pick the first one. We don't fully support multiple signatures at the moment. However... RD data parser should be just showing the bigger one.

**Comment by MikhailArkhipov** [comment]
This is old. The signature contains
```
hdfsShareDir = paste( "/user/RevoShare", Sys.info()[["user"]], sep="/" )
``` 
and `[[` are causing RD/R hybrid parser trouble.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/54601da3a4e4f0e7315f768e601a1f70d2bee8a3
