### ISSUE TITLE
Occasionally connection status is displayed as yellow

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4053]
Doesn't happen always, but I do see it regularly when switching local connections or when container loses and then restores connection

![image](https://user-images.githubusercontent.com/12820357/30828336-358f03b0-a1f2-11e7-8b17-c34ee3d11a70.png)

**Comment by AlexanderSher** [comment]
It looks like `ConnectionManager.IsRunning` is false at the time when `ConnectionViewModel` is created and they aren't updated later.
