### ISSUE TITLE
Colors in REPL occasionally appear off

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4065]
Specifically, red

![image](https://user-images.githubusercontent.com/12820357/30882249-37278fb4-a2bd-11e7-9ee3-7195e115badd.png)

**Comment by MikhailArkhipov** [comment]
Haven't seen it since

**Comment by Hong-Revo** [comment]
I'm still seeing this in VS 15.7 (RTVS 1.3.40208.1039):

![image](https://user-images.githubusercontent.com/11328890/37566922-c3f68010-2b13-11e8-96ab-cab54954c2a9.png)

**Comment by Hong-Revo** [comment]
Semi-related update. I also sometimes see glitches in the syntax highlighting of C++ files: comments not being coloured green, function args not being picked up, etc. Wonder if this is a VS-wide thing.
