### ISSUE TITLE
Resetting REPL changes working directory back to default

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#4078]
This is in 15.5 with RTVS build 1.2.30924.1819.

1. Open an R project with its own directory
1. The working dir is set to the project dir
1. Reset the REPL
1. The working dir is set back to "~"

I'm pretty sure this wasn't the case in 15.3 with my previous RTVS build.

**Comment by MikhailArkhipov** [comment]
Not sure if that changed since... @AlexanderSher may have a look

**Comment by Masutani** [comment]
This prevent me from smooth debug -> run loop.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ca0b76341db3f3321ca99a0a6e5bc2d82852d867
