### ISSUE TITLE
Upgrade to .NET Core 2.0

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4086]

**Comment by MikhailArkhipov** [comment]
See also #3158

**Comment by MikhailArkhipov** [comment]
Need this for Mac since `Uri.TryCreate` fails with Unix paths

**Comment by AlexanderSher** [comment]
Almost there. 7 projects left.

**Comment by AlexanderSher** [comment]
Oh, and I also need to walk through this one: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/identity-2x

**Comment by MikhailArkhipov** [comment]
Yeah I discovered that too. So, we need ` <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>`
and

````
    <TargetFramework Condition="'$(CoreBuild)' == 'true'">netstandard2.0</TargetFramework>
    <TargetFrameworks Condition="'$(CoreBuild)' != 'true'">netstandard2.0;net461</TargetFrameworks>
```

Since neither `Rider` nor `dotnet/VsCode` are able to build multitargeted projects on Mac

**Comment by AlexanderSher** [comment]
Ok

**Comment by AlexanderSher** [comment]
Btw, can we use `$(OS)`?

**Comment by MikhailArkhipov** [comment]
Oh, don't forget `<DebugType>portable</DebugType>` in .NET Core. .NET Core on Mac can't read Windows PDBs.

**Comment by MikhailArkhipov** [comment]
https://www.nuget.org/packages/Odachi.AspNetCore.Authentication.Basic/2.0.0-preview-000151 ?

**Comment by MikhailArkhipov** [comment]
Odachi seems to fit OK.

**Comment by AlexanderSher** [comment]
yes, I've copied updated sources.

**Comment by MikhailArkhipov** [comment]
I just installed nuget package.

**Comment by AlexanderSher** [comment]
We haven't used package because of the strong name issues

**Comment by MikhailArkhipov** [comment]
I have it building in https://github.com/Mikhailarkhipov/rtvs/tree/LS1 , havent tried running yet.

**Comment by MikhailArkhipov** [comment]
I am going to close this as most of the work is done. What remains is sorting out client socket connectivity with .NET Core folks, running tests and merge/PR. #4180 and #4181.
