### ISSUE TITLE
Getting object lists for '::' and ':::' very slow in REPL

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#4105]
Not sure if this is a regression, but typing things like `stats::` and `stats:::` really slow the REPL to a crawl. This is while it retrieves the list of objects to populate the dropdown.

Typing the same thing into the editor window doesn't seem to be affected.

This is with build 1.2.30924.1819, VS 15.5 prerel (2).

**Comment by MikhailArkhipov** [comment]
Yeah the query is complicated to separate all/public/internal. Need to optimize a bit.

**Comment by MikhailArkhipov** [comment]
Any specific package? `base`, `utils`, `ggplot2` seem to be OK.

**Comment by Hong-Revo** [comment]
Huh, I can't seem to reproduce it now. Maybe it was just general slowdown from leaving a session open too long.
