### ISSUE TITLE
Container window UI adjustments

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#4111]
- From containers window, have a link to bring up the dockerfile template in an editor
so that people dont have to hunt it down.  

a. usable for pointing the dockerhub url base image
b. usable for adding default pkgs
c. usable for a link to our docs

Also
- Link back to Workspaces and we have with Containers... there
- Some sort of indication that Create is clickable?
- Double click on container connects to it if it is running? Not sure if it is feasible though.

See also #4110

**Comment by MikhailArkhipov** [comment]
I don't see
- From containers window, have a link to bring up the dockerfile template in an editor
- Link back to Workspaces and we have with Containers... 
- Some sort of indication that Create is clickable? 

(From Template still has no frame)
![image](https://user-images.githubusercontent.com/12820357/31293435-03bb2df8-aa8c-11e7-85f0-b843f5402021.png)

Also, 'From Template' ... opens in current folder, should be opening where templates might be stored.

**Comment by AlexanderSher** [comment]
> From containers window, have a link to bring up the dockerfile template in an editor

You mean our docker file? I don't like this idea. If user accidentally changes something in this file, he would have to reinstall RTVS to fix it.

> Link back to Workspaces and we have with Containers...

We have just deleted it. Return it back?

> should be opening where templates might be stored

User can store his templates anywhere, even as part of the project.

**Comment by MikhailArkhipov** [comment]
It is user problem. I don't think they'd be able to overwrite it since we install under Program Files and VS is not running as admin.

Yes, @smortaz  wants Workspaces... as we have Containers...
![image](https://user-images.githubusercontent.com/12820357/31293934-e80e583a-aa8d-11e7-9699-9f1af437fb30.png)

OK, then let's open ~/Documents

Still - what about double click?

**Comment by AlexanderSher** [comment]
> Still - what about double click?

Depends on what we decide on #4041. If user has disabled a warning, he can accidentally change connection from containers window.

**Comment by MikhailArkhipov** [comment]
So be it - no different from Workspaces behavior.

**Comment by AlexanderSher** [comment]
Ok

**Comment by AlexanderSher** [comment]
> It is user problem. I don't think they'd be able to overwrite it since we install under Program Files and VS is not running as admin.

Ok, if user can't change it, then what's the point of opening it?

**Comment by MikhailArkhipov** [comment]
Let's consider this done.
