### ISSUE TITLE
Roxygen IntelliSense does not incrementally search

### ISSUE THREAD

**Issue by jflam** [Microsoft/RTVS#4119]
When you activate IntelliSense for a Roxygen comment, typing the tag name does not incrementally search the list.

![image](https://user-images.githubusercontent.com/8877/31287877-a3255cc0-aa77-11e7-9f42-6b1875d416a1.png)

**Comment by jflam** [comment]
Also, IntelliSense is way to aggressive here; it pops when I type anything in a comment. It should default to popping IntelliSense only when the user types @

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/89403d274d51fbb20014a1279e9c0aa36ed032d2
