### ISSUE TITLE
Error: "there is no package called 'rtvs'"

### ISSUE THREAD

**Issue by kamleshkshirsagar** [Microsoft/RTVS#4139]
Hello,

I am getting a bug. When executing RxExec

```
> pkgs.load <- c("AnomalyDetection", "foreach", "data.table", "zoo")
 system.time({
   detect.anom <- rxExec(FUN = DetectAnomalies,
                         xdfData = plant.result,
                         series = rxElemArg(columns),
                         max.anoms = config$Anomalies$MaxAnomalyFraction,
                         period = config$Anomalies$ObsPerPeriod,
                         window = config$Anomalies$AvgWindow,
                         packagesToLoad = pkgs.load)
})
Error in do.call(.rxDoParFUN, as.list(args)) : 
  task 1 failed - "there is no package called 'rtvs'"
Timing stopped at: 0.5 0 0.73
```
If needed i can share my screen to show the bug. Contact me on kakshirs@microsoft.com

Kind regards,

Kamlesh Kshirsagar

**Comment by MikhailArkhipov** [comment]
Is it local or remote session? `rtvs` is our package which, in this case, probably gets involved because it intercepts `install.package` call since RTVS needs to know when to update intellisense functions cache..

Workaround is probably to preinstall packages and simply call `library`
