### ISSUE TITLE
Throw separate type of exception when user must restart com.docker.service

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#4144]

**Comment by karthiknadig** [comment]
Are there particular scenarios where this is needed? There are too many possible points of failure, failed pipe between docker and docker service, Moby VM gets into a bad state, Service attempting to reconnect to Moby, etc. There is no status that can be pulled from the service or the VM.

I have added, user permission related exception, and a field in `ContainerServiceNotRunningException` with the service name.

**Comment by karthiknadig** [comment]
https://github.com/Microsoft/RTVS/pull/4145
