### ISSUE TITLE
Markdown code block - default background color

### ISSUE THREAD

**Issue by Neil-Schneider** [Microsoft/RTVS#4173]
The default background color for the `Markdown code background` option is difficult to read the text under the dark VS theme.

![capture](https://user-images.githubusercontent.com/6426710/31947778-1a52a472-b8a3-11e7-9441-8d015109285c.JPG)

VS 2017 - 15.4.1
Edit: uploaded jpg image - Github didn't like the png from snipping tool.

**Comment by MikhailArkhipov** [comment]
You can adjust it in Tools | Options | Environment | Fonts and Colors -> `R Markdown Code Background`
We'll look into default theming.

**Comment by MikhailArkhipov** [comment]
15.5 Preview 4+
