### ISSUE TITLE
REPL may become slow after large data output

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4187]
From the user
```
I have noticed that if I accidentally print a large amount of data to the screen, 
like a large data.frame or vector, the interactive window becomes extremely slow.  
If you type something, there is a long delay before it appears in the interactive window.  
However, if I clear the interactive window (CTRL-L) the problem is resolved. 
```

**Comment by AlexanderSher** [comment]
Is it somehow related to the size of the buffer?

**Comment by MikhailArkhipov** [comment]
Maybe. Or number of projections.

**Comment by MikhailArkhipov** [comment]
So it is a combination of the above. After dumping a lot of data the buffer becomes large so accessing snapshots becomes expensive. This is compounded by the fact that view is projected so accessing *view* snapshot requires buffer to construct it via the projection graph.

I'll see if we can use R document buffer instead of the view buffer. `IsPositionInNamespace` is the offender but it may not be the only one.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/8c804aa1c25c77605af1c52341ab04bbde1b70da
