### ISSUE TITLE
Error with non-English text in .R file

### ISSUE THREAD

**Issue by brezaie** [Microsoft/RTVS#4197]
Hi,
When I type non-English characters in the script.R file in VS 2017, I get the **Advanced Save Options** window and set it as the first figure shows.
Next, when running, I get the error message shown in the last figure.
Could you please help me with the error?

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.
![capture](https://user-images.githubusercontent.com/1937696/32405304-1a595b4a-c178-11e7-939a-03750fc965b6.PNG)

![capture2](https://user-images.githubusercontent.com/1937696/32405352-e70e87f0-c178-11e7-8207-87530775844a.PNG)

OS Information
    Version:       Microsoft Windows 10

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.2.30905.1244, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.4.1: D:\Program\R\R-3.4.1

**Comment by MikhailArkhipov** [comment]
The `source` command, as seen in the screenshot, expects file on disk to be in UTF-8 encoding. If you do save file in UTF-8, does it work?

**Comment by MikhailArkhipov** [comment]
Been a while without additional info, closing
