### ISSUE TITLE
invalid highlighting of syntax on quoted vector elements

### ISSUE THREAD

**Issue by ethanbsmith** [Microsoft/RTVS#4220]
when typing a character vector, if an element is added to the front, a red syntax error appears.

`x <- c("1", "2")`
if fine
![image](https://user-images.githubusercontent.com/24379655/32912318-e9beffc8-cacb-11e7-885c-dbde85eedebb.png)
but if i type an element in front of the existing elements:
`x <- c("3", "1", "2")`
I get a syntax error highlight
![image](https://user-images.githubusercontent.com/24379655/32912363-14858222-cacc-11e7-9f71-b49a6f8dc75d.png)

This only seems to be an issue with vectors with quoted elements. issue happens with both `"` and `'`

**Comment by MikhailArkhipov** [comment]
Change right before the opening quote was considered to be inside the string and change inside strings is processed as a simple change without rebuilding the AST.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ca0b76341db3f3321ca99a0a6e5bc2d82852d867
