### ISSUE TITLE
Invalid R syntax highlighting

### ISSUE THREAD

**Issue by Marchen** [Microsoft/RTVS#4221]
Following is valid R code,
```R
a <- TRUE & !TRUE
b <- 0
```
but RTVS shows syntax error like

![default](https://user-images.githubusercontent.com/3863577/32931801-8b647bf4-cba9-11e7-9599-0c29e916fc9e.PNG)

Tried on RTVS 1.2.30905.1244 on VS Community 2017 15.4.3
VisualStudio.15.Release/15.4.3+27004.2008

**Comment by MikhailArkhipov** [comment]
This is fixed as #4051 in 15.5

**Comment by Marchen** [comment]
Thanks
