### ISSUE TITLE
Visual Studio installer uses old version

### ISSUE THREAD

**Issue by alapinsk** [Microsoft/RTVS#4225]
I am using Visual Studio installer version _1.12.111.1002_ (most recent)
to install RTVS for Visual Studio Professional 2017 (15.4.4)  
and it installs version _1.2_ instead _1.3_.

**Comment by MikhailArkhipov** [comment]
This is normal. 1.3 comes with 15.5 which is currently in preview. https://www.visualstudio.com/vs/preview/
