### ISSUE TITLE
Text display overlay error when folding R code in VS2017

### ISSUE THREAD

**Issue by hszest** [Microsoft/RTVS#4245]
Display of the folded code seems a little bit odd to me

VS 2017 15.5.1
RTVS 1.3.31108.1213

![0](https://user-images.githubusercontent.com/12162979/33883623-719aef78-df77-11e7-8560-460f9d5d9805.PNG)
![1](https://user-images.githubusercontent.com/12162979/33883624-71e0e6e0-df77-11e7-88ae-535f9a61f404.PNG)

**Comment by MikhailArkhipov** [comment]
This is controlled by the core editor, RTVS only supplies text. Looks like editor expects single line only. I guess we should try and avoid showing more than a single line (i.e. remove line breaks in the collapsed rendering).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/ca0b76341db3f3321ca99a0a6e5bc2d82852d867
