### ISSUE TITLE
Remote for Windows points to old RTVS 2015

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#4250]
https://docs.microsoft.com/en-us/visualstudio/rtvs/workspaces-remote-setup#install-r-services-on-windows

Points to Remote Services 1.1 (matches RTVS 2015). We need to provide separate links to 2015 and 2017.

**Comment by karthiknadig** [comment]
@jflam I think https://aka.ms/rtvs-services should point to https://github.com/Microsoft/RTVS/blob/master/doc/rtvsd/rtvs-remote-downloads.md
That way people have access to all versions of the remote services. Anyone who needs automation can use the direct link.

**Comment by jflam** [comment]
OK. The redirect currently points to 
https://rtvs.blob.core.windows.net/download/RTVS_Remote_2017-12-18.1.exe

Changing to point to: https://github.com/Microsoft/RTVS/blob/master/doc/rtvsd/rtvs-remote-downloads.md
