### ISSUE TITLE
"Space around =" editor setting no longer recognized at an R Interactive prompt

### ISSUE THREAD

**Issue by MNRK01** [Microsoft/RTVS#4264]
Hi,

I have the RTVS editor option for "Spaces around =" set to Off. This used to also work when using autocomplete at the prompt within an R Interactive session. This behavior changed a couple of months ago (I can't say exactly when, sorry...). Can the behavior for not inserting spaces around = be reestablished for an R Interactive prompt within RTVS?

Thanks for an excellent product!

Please briefly describe what you were doing that led to the issue, if applicable:
Running a vanilla R session using R 3.4.3
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.16299.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.3.31108.1213, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    R 3.4.3: C:\Program Files\R\R-3.4.3

**Comment by MikhailArkhipov** [comment]
This option controls formatting inside function default arguments i.e. `function(a=1)`. It has no effect on operators like `x <- 1` or `z = 2`,

**Comment by MNRK01** [comment]
Thanks for the comment. I meant that it used to work at the prompt when using autocomplete with built-in functions. I was referring to built-in functions and not to operators since autocomplete would not make sense there in any case.

e.g. autocomplete used to not put a space after the row.names argument because I had turned that **Editor** setting **Off** but today it does:
```R
# previous behavior
data.frame(x=c(1,2,3), y=c(4,5,6), row.names=LETTERS[1:3])
# today
data.frame(x=c(1,2,3), y=c(4,5,6), row.names = LETTERS[1:3])
```` 

![image](https://user-images.githubusercontent.com/4283816/34633697-78947342-f243-11e7-8470-ec234d4198d3.png)


Thanks for your response.

**Comment by MikhailArkhipov** [comment]
Specific to the named arguments completion

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e83ab28203c1380dae8dbb739174cbc7efa70882

**Comment by MNRK01** [comment]
Wow, thanks!!
