### ISSUE TITLE
Feature Request: Linting

### ISSUE THREAD

**Issue by MovGP0** [Microsoft/RTVS#4265]
There should be support for R linting. There is already a project for it: 

https://github.com/jimhester/lintr

**Comment by Neil-Schneider** [comment]
There is already a linter implementation, but integration with `lintr` would be great. We have team members that code in VS, Rstudio and Atom, so being able to utilize the same `lintr` profile across the different IDEs would be helpful.

But here is how you access the current linter in RTVS.

```
R Tools > Editor Options...
```

Opens this windows with linter options for `.R` programs.

![image](https://user-images.githubusercontent.com/6426710/35000600-d1fb8d2c-fab2-11e7-9e34-1f9f1d759b24.png)

**Comment by MikhailArkhipov** [comment]
Settings above pretty much cover lintr and it runs as you type in a background. You can still run it if you want manually but you won't get squiggles and lintr runs on files so the document must be saved first.
