### ISSUE TITLE
Updating progress bar erases existing output lines in REPL

### ISSUE THREAD

**Issue by Hong-Revo** [Microsoft/RTVS#4270]
Howdy!

Just something I noticed in the latest RTVS, as of VS 15.6.2.

If I have a dplyr operation that takes more than a certain length of time, a progress bar is displayed. RTVS will now update this correctly, as opposed to inserting newlines each time the bar gets extended. Hooray! Unfortunately, when it does this, any existing output lines in the REPL are wiped.

Here is a repro:

```r
library(dplyr)
df <- rowwise(data.frame(a=1:1e4, b=1:1e4))
out <- do(df, { data_frame(.$a + .$b) })
```

If you run this, you should find that any existing output lines will be erased.

**Comment by MikhailArkhipov** [comment]
I'll look into this.

**Comment by Hong-Revo** [comment]
Possibly related: after this happens, the output text afterwards will sometimes be randomly coloured red.

![image](https://user-images.githubusercontent.com/11328890/35406205-5de5fc22-025c-11e8-9c27-f107a59973e3.png)

**Comment by MikhailArkhipov** [comment]
I didn't get output erased, so it probably relates to odd colorization - which we were able to repro but like once or twice - https://github.com/Microsoft/RTVS/issues/4065.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e83ab28203c1380dae8dbb739174cbc7efa70882

**Comment by MikhailArkhipov** [comment]
Yes, it is 15.7. Preview 1 should be public very soon.
