### ISSUE TITLE
R Package Manager does not grab latest available packages.

### ISSUE THREAD

**Issue by djm158** [Microsoft/RTVS#4272]
![image](https://user-images.githubusercontent.com/8800738/35410808-88c8e242-01e4-11e8-9f83-29867c6f7a14.png)

`devtools` is listed as latest version being 1.12.0, but [1.13.4 is the latest listed on github](https://github.com/hadley/devtools/releases/tag/v1.13.4)

[link to latest cran repository, version 1.13.4](https://cran.microsoft.com/bin/windows/contrib/3.4/devtools_1.13.4.zip)

Visual studio Enterprise 2017, Version 15.5.4
Windows 10
Microsoft Open R 3.4.1
Microsoft R Client 3.3.2.0

**Comment by MikhailArkhipov** [comment]
It depends on what is on the current CRAN mirror. The mirror can be changed in Tools | Options | R.
As far as I can see, `devtools` is still 1.12. RStudio

![image](https://user-images.githubusercontent.com/12820357/35411691-8303b8f2-01ce-11e8-9e02-648b2ab60318.png)

**Comment by djm158** [comment]
I see, thank you! I actually believe the R version I listed above was 3.3 instead of 3.4 at the time I took the screenshot, I just grabbed the latest R client from http://aka.ms/rclient/ and re opened visual studio and now my devtools version is listed as 1.13.3. I guess this updated my mirror?

**Comment by MikhailArkhipov** [comment]
It is not automatically updated (it is in Tools | Options | R) , but client may choose to map it to a different mirror. I wouldn't be surprised if MS R Client would use MRAN and not CRAN mirror.
