### ISSUE TITLE
RDotNet program after computer crash

### ISSUE THREAD

**Issue by Waglio** [Microsoft/RTVS#4274]
Please briefly describe what you were doing that led to the issue, if applicable:
Computer crashed and I had to reinstall Windows 10, thereby losing Visual Studio on which I had some programs using RDotNet within C#. I reinstalled Visual Studio and now those programs do not run because, apparently, Visual Studio cannot find the "stats" package in R. Same problem on 3 different applications.
...

If you have any screenshots demonstrating the issue, please include them as well to help us diagnose it better.

Additional information: Tried uninstalling and reinstalling RDotNet but it made no difference. The "stats" package is accessible from Visual Studio R, R-386, R-x64 and R Studio but can't be accessed via RDotNet.

OS Information
    Version:       Microsoft Windows NT 10.0.16299.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.3.31108.1213, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Comment by MikhailArkhipov** [comment]
R.Net is not Microsoft product. Please report the issue to the product owner.
