### ISSUE TITLE
RData grid view: can't select column for sorting after horizontal scroll in wide data frames

### ISSUE THREAD

**Issue by mkoohafkan** [Microsoft/RTVS#4275]
VS Pro 2017 15.5.5
RTVS  1.3.31108.1213

When `View`ing a wide data frame in the RData grid viewer, scrolling to the right seems to mess up clicking on columns with the mouse pointer. The result is mostly that you can't select a column to sort by it if you have to scroll to the right in order to bring it into view. Also, sometimes you can click on one column but the viewer will instead sort by an adjacent column (but only if you've scrolled to the right just a little bit---seems to only happen with columns that are within view when the viewer first loads).

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/e83ab28203c1380dae8dbb739174cbc7efa70882
