### ISSUE TITLE
str_view output contained to Visual Studio rather than external browser?

### ISSUE THREAD

**Issue by sadukie** [Microsoft/RTVS#4283]
Please briefly describe what you were doing that led to the issue, if applicable:

As I go through some R lessons on DataCamp, I am keeping notes in an R notebook in Visual Studio.  Going through a lesson using **stringr**, and we're using **str_view** to preview patterns.  Output is currently appearing in an external browser. 

Sample R code:
```
library(stringr)
x <- "Normal(\u03BC = 0, \u03C3 = 1)"
x
str_view(x, pattern="\u03BC")
```

Output:
![image](https://user-images.githubusercontent.com/106202/36266312-28308d2a-123f-11e8-9003-608fc19525b3.png)

The URL it loads is:
http://127.0.0.1:63640/C:/Users/saduk/AppData/Local/Temp/RtmpoNC4Eu/viewhtml369025bd3b21/index.html

Not sure if this is possible (as I don't know the underworkings), but is it possible for **str_view()** to open within Visual Studio (much like the help window and plots window) rather than an external window?

Other details:

* stringr has dependencies on htmltools and htmlwidgets.  Once dependencies were installed, I tried this in RStudio to see how they handle this.  It looks like this:
![image](https://user-images.githubusercontent.com/106202/36266668-082c9928-1240-11e8-8039-00ec7cbc301e.png)

...

Additional information:

OS Information
    Version:       Microsoft Windows NT 10.0.17093.0

RTVS Information:
    Assembly: Microsoft.VisualStudio.R.Package, Version=1.3.31108.1213, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

Active R URI:
    Microsoft R Server (3.3.3.24): C:\Program Files\Microsoft SQL Server\140\R_SERVER\

**Comment by MikhailArkhipov** [comment]
Try this option

![image](https://user-images.githubusercontent.com/12820357/36275028-89a3dbbc-123e-11e8-8b97-3e4429bff4ed.png)

However, remember that VS internal browser is not HTML5 compliant (it is IE11 engine and not Edge). So modern rendering and JavaScript may not work.

**Comment by sadukie** [comment]
Tried with these settings:
![image](https://user-images.githubusercontent.com/106202/36278232-34f54ccc-1261-11e8-9a1b-f24eb198cfa1.png)

But still loading in an external browser window:
![image](https://user-images.githubusercontent.com/106202/36278305-77a1717c-1261-11e8-9d34-c0fb9ff0c107.png)

This is what my R Interactive shows:
![image](https://user-images.githubusercontent.com/106202/36278319-81b85a7c-1261-11e8-82b1-5e934a9e28fd.png)

**Comment by MikhailArkhipov** [comment]
Try changing R Help browser to external as well. But generally I wouldn't recommend internal VS browser. It is being deprecated from the IDE anyway.

**Comment by sadukie** [comment]
Talking with @jflam at MVP Summit, this might have to deal with how the library itself was written.  Since the internal browser is going the route of deprecated and since that probably would've been the ideal approach, I'm fine closing this.  Thanks, @MikhailArkhipov, for talking with me through this as well!
