### ISSUE TITLE
Unable to view HDInsight clusters in Server Explorer with RTVS enabled

### ISSUE THREAD

**Issue by timardis** [Microsoft/RTVS#4293]
When expanding the **HDInsight** dropdown under **Server Explorer** -> **Azure**, none of our clusters show up. After disabling RTVS, all clusters are showing up.

From checking the network logs, with RTVS disabled, Visual Studio will make a call to the following URI to get all HDInsight clusters on the added subscriptions:

`https://management.azure.com/subscriptions/{subscription Id}/resourceGroups/{resourceGroup Name}/providers/Microsoft.HDInsight/clusters/{cluster name}?api-version={api-version}`

However, with RTVS enabled, Visual Studio no longer makes a call to that URI.

**Environment Info:**

OS: Windows 10
VS Community: 15.5.7
ADL & SA Tools: 2.3.2000.1
RTVS: 1.3.31108.1213

**Comment by MikhailArkhipov** [comment]
This should be fixed in 15.7 Preview 4. We had issue with conflicting binding redirects for System.Net.Http.
