### ISSUE TITLE
connect R with mdf file 

### ISSUE THREAD

**Issue by RawanRadi** [Microsoft/RTVS#4298]
I tried to connect R to mdf file (sql server mdf file) from 
R tools -> Data -> Add a database connection -> Attach a database file 
I tried it many times but the connection filed. #639

![image](https://user-images.githubusercontent.com/30637049/37788547-c12d7ac6-2e12-11e8-885a-0a4d18b5aa88.png)

**Comment by MikhailArkhipov** [comment]
This message comes from Visual Studio Data dialog that actually establishes and tests the connection. It is a shared component. Please submit issue to VS via the VS Feedback button on the app toolbar. Thanks.
