### ISSUE TITLE
R session is stopped. Click "Reset" to start a new one.

### ISSUE THREAD

**Issue by RawanRadi** [Microsoft/RTVS#4299]
every time when R calling function or executing loop this error appears
`R session is stopped. Click "Reset" to start a new one.

Interactive Window is disconnected from R session.
Click "Reset" to start a new session.`

for example this function
`usePackage <- function(p) {
    if (!is.element(p, installed.packages()[, 1]))
        install.packages(p, dep = TRUE)
    require(p, character.only = TRUE)
}`
if the package does'n exist R throw the error instead of download it 
this error appears many time in many functions

**Comment by Hong-Revo** [comment]
That means R has died in the background. Like it says, click Reset to restart R.

**Comment by RawanRadi** [comment]
I clicked on resett many times but same error appears.
Restarting VS solved it
