### ISSUE TITLE
Interactive R Exception - RTVS

### ISSUE THREAD

**Issue by daniloribeirodeabreu** [Microsoft/RTVS#4316]
That's the first time a open de VS 2017. I've installed VS 2017 just with 3 of the resources: Data Science and Analytical Applications, Python development and Node.js development. I am using Windows 10 - 64 bits. I've reinstalled the VS 2017 so many times, and the error keeps occurring. Help, please?

Exception:

System.ArgumentException: O pacote não tem um ProvideToolWindowAttribute para a janela de ferramentas c2582843-58c9-4fe7-b4bd-864c17ad7ce2
Nome do parâmetro: toolWindowType
em Microsoft.VisualStudio.Shell.Package.ThrowNoMatchingToolWindowAttribute(Object toolWindowType, String paramName)
em Microsoft.VisualStudio.Shell.Package.GetToolWindowAttribute(Guid toolWindowType)
em Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
em System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
em Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

ActivityLog.xml:

Construction of frame content failed. Frame identifier: ST:0:0:{c2582843-58c9-4fe7-b4bd-864c17ad7ce2} Frame caption: R Interativo - R 3.5.0 Exception details: System.ArgumentException: O pacote não tem um ProvideToolWindowAttribute para a janela de ferramentas c2582843-58c9-4fe7-b4bd-864c17ad7ce2 Nome do parâmetro: toolWindowType em Microsoft.VisualStudio.Shell.Package.ThrowNoMatchingToolWindowAttribute(Object toolWindowType, String paramName) em Microsoft.VisualStudio.Shell.Package.GetToolWindowAttribute(Guid toolWindowType) em Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id) em System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo) em Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

Sorry for my bad English, guys!
Danilo Abreu

**Comment by Hong-Revo** [comment]
I suspect RTVS may not yet be compatible with R 3.5, which changes a lot of the internals. Try it with 3.4.x.

**Comment by daniloribeirodeabreu** [comment]
I've already tried it on my other notebook, which has Windows 7 and R 3.4... got the same exception :(

**Comment by MikhailArkhipov** [comment]
Same as #4310

**Comment by MikhailArkhipov** [comment]
Could you locate and send us your `privateregistry.bin` which should be in 

`C:\Users\[USER_NAME]\AppData\Local\Microsoft\VisualStudio\15.0_??????`

mikhaila AT microsoft
Thanks

**Comment by MikhailArkhipov** [comment]
Just letting all know we found the problem and we will try and get the fix into the nearest VS update.

**Comment by MikhailArkhipov** [comment]
Closing, expected in 15.7.3 and 15.8.3

**Comment by MikhailArkhipov** [comment]
15.7.3 is live
