### ISSUE TITLE
Feature Request: Mac Support

### ISSUE THREAD

**Issue by 80kr** [Microsoft/RTVS#4324]
Hi Guys,

Appreciate all of the dev efforts in providing RTVS, are there any plans to incorporate RTVS on VS for Mac or the data science package on VS for Mac?

thx!

**Comment by smortaz** [comment]
Not at this time unfortunately :(.

**Comment by MikhailArkhipov** [comment]
Unlikely. If we go cross-platform, it would be VS Code.

**Comment by 80kr** [comment]
VS Code is fast, and when I used RTVS on VS, of course, it was also fast based on the tutorials on Microsofts websites. Based on the feedback that I'm seeing and hearing I'm going to be using R notebook or jupyter notebook. Unfortunately that would be outside of Microsoft's official feedback system that improves products and provides great products like the data science environment in VS and fast apps like VS Code.

There is a huge market of developers that use Macs, and if the cloud business, like Azure, would be interested in having more developers use their stack for various reasons. Then developing RTVS for Mac would be in favor of Microsoft's business. I would be curious to see what Microsoft has to say about that.

**Comment by MikhailArkhipov** [comment]
Folding into #1295. It is unlikely we'd use VS for Mac. We do Python for VS Code already.

**Comment by chrisvacc** [comment]
I’m not understanding... there are no plans for RTVS for VS, but potentially VS Code?

You have to make RTVS available for Mac and Linux. Probably the majority of Data Scientists are on those platforms.

**Comment by MikhailArkhipov** [comment]
There are couple of R extensions to VS Code. Mine https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r is based on RTVS. There is another https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r.

There is no active development in RTVS.

**Comment by chrisvacc** [comment]
> There are couple of R extensions to VS Code. Mine https://marketplace.visualstudio.com/items?itemName=Mikhail-Arkhipov.r is based on RTVS. There is another https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r.
> 
> There is no active development in RTVS.

Yes, but a development IDE is beyond the scope of those right?

![](https://i.imgur.com/jJ9qS42.png)

Or would that be possible with those plugins

**Comment by MikhailArkhipov** [comment]
No, VSC is not graphically rich and it is not indented to be an IDE.

**Comment by chrisvacc** [comment]
Well there’s this I just found 

![](https://msdnshared.blob.core.windows.net/media/2018/10/clip_image002_thumb2.png)

**Comment by MikhailArkhipov** [comment]
Yeah, I work on that extension :-). Basic static output can be done. Something like console with intellisense - no.

**Comment by chrisvacc** [comment]
I should have known haha!

It’s okay as long as you can send commands to the console.

What other plugins do you recommend for R users?
