### ISSUE TITLE
.NET Standard 2.0 Assembly Used as R Package?

### ISSUE THREAD

**Issue by JeffFerguson** [Microsoft/RTVS#4326]
Is it possible to package a .NET Standard assembly as an R package such that R scripts can call into the .NET Standard assembly? Would any additional work need to be added to the .NET Standard assembly such that this level of integration is possible?

I see documentation that references .NET code calling into an R script, but nothing that references an R script calling into an assembly. Is this possible?

**Comment by MikhailArkhipov** [comment]
The simplest probably is to run C# as a process and call it via JSON RPC. You can use [StreamJsonRpc ](https://github.com/Microsoft/vs-streamjsonrpc)library. We do exactly this calling C# from TypeScript in [VS Code Python](https://github.com/Microsoft/vscode-python).

This would save you from trouble converting data types from R to C++ to C#.

**Comment by MikhailArkhipov** [comment]
Look at
https://github.com/Microsoft/PTVS/blob/master/Python/Product/VSCode/AnalysisVsc/Program.cs how to setup JSON RPC and https://github.com/Microsoft/PTVS/blob/master/Python/Product/VSCode/AnalysisVsc/LanguageServer.cs that has bunch of methods mapped to JSON requests. The project is .NET App 2.0
