### ISSUE TITLE
How to make RTVS to run R Client ?

### ISSUE THREAD

**Issue by FCHLuk** [Microsoft/RTVS#4344]
Hi . I have Visual Studio 2017. I installed RTVS. I installed R Client in the default directory. But when I ran library(RevoScaleR) I got an error message.

library(RevoScaleR) Error in base::library(...) : there is no package called ‘RevoScaleR’

>
In the R Tools options dialog, there is no way to make R Engine point to R Client. Please see attached screenshot.
--------------------------
Then
![cannot run r client in rtvs](https://user-images.githubusercontent.com/42013060/47824290-6accbb80-dd29-11e8-8d10-f6ee4eab7e48.png)
 I uninstalled R Client. Then inside Visual Studio, under R Tools, I clicked on "Install Microsoft R Client:". Closed Visual Studio. Let R client installation finish. Restarted Visual Studio. Tried to run library(RevoScaleR) again. Got the same error message !! Nothing was changed ? How can I make RTVS use R Client ?

Thanks s million, Fred

Thanks in advance, Fred Luk

**Comment by MikhailArkhipov** [comment]
Try R Tools | Workspaces, the window should show all Rs available.

**Comment by FCHLuk** [comment]
That works. Thanks Mikhail. It looks like someone needs to update the documentation at Microsoft.
