### ISSUE TITLE
R Tools for Visual Studio 0.4 (June, 2016 release)

### ISSUE THREAD

**Issue by devwisdom** [Microsoft/RTVS#4346]
This is a question. I've been looking for old versions of RTVS for quite a few months, specifically RTVS 0.4. I've found download links that point to http://aka.ms/rtvs-current, but that gives me the most recent version of RTVS.

Does anyone know where can I get the following files?

RTVS_2016-06-23.7.exe
RHost_2016-06-23.7.msi

Thanks.

**Comment by huguesv** [comment]
https://rtvs.blob.core.windows.net/download/RTVS_2016-06-23.7.exe
https://rtvs.blob.core.windows.net/download/RHost_2016-06-23.7.msi
