### ISSUE TITLE
Call R from Visual Studio C++

### ISSUE THREAD

**Issue by vivanov879** [Microsoft/RTVS#4348]
Hi. What's the best way to call R functions from Visual Studio C++? Is it to use https://github.com/Microsoft/R-Host ? I read that neither RInside nor RCpp support visual studio.

**Comment by vivanov879** [comment]
Another option might be to use https://github.com/rstudio/websocket. Suppose the use case consists of couple scenarios. For example, C++ gets data and wants to do some maths in R every minute. Then, C++ will send some data to R, R will process it and send back. Sounds like a neat solution.

**Comment by MikhailArkhipov** [comment]
Basically load R.dll and call it :-). https://github.com/Microsoft/R-Host for example.

**Comment by vivanov879** [comment]
Thanks
