### ISSUE TITLE
Microsoft.R.Host  always making more than 100% CPU usages! 

### ISSUE THREAD

**Issue by nazrulworld** [Microsoft/RTVS#4350]
Hi 
I Installed VS Code implementation in my Ubuntu 18.0.

I saw that Microsoft.R.Host  always making more than 100% CPU usages! 
Is it normal? or something I did wrong 
[Screen Dump](https://cdn.pbrd.co/images/HRdTt5F.png)

**Comment by itssimon** [comment]
I'm seeing the same when using the "R Tools" extension for VS Code, which relies on RTVS. Two Microsoft.R.Host processes use 100% CPU each continually. This is on macOS.

**Comment by romanhaa** [comment]
I can confirm what @itssimon says.

**Comment by priscian** [comment]
This may be related to [Issue #4307](https://github.com/Microsoft/RTVS/issues/4307), which appears to stem from using too large an R library with RTVS. I'd love to use RTVS, but I can't pare down my libraries for it, & the CPU issue prevents me from making it part of my workflow.

**Comment by MikhailArkhipov** [comment]
This repo is for VS specifically, so closing since there is https://github.com/MikhailArkhipov/vscode-r/issues/10.
