### ISSUE TITLE
Connect to R local workspace failed on mac

### ISSUE THREAD

**Issue by JackHo327** [Microsoft/RTVS#4368]
[Info  - 6:58:44 PM] Available R interpreters:
[Info  - 6:58:44 PM] 	[0] R 3.5
[Info  - 6:58:44 PM] You can specify the desired interpreter index in the R settings
[Info  - 6:58:44 PM] Selected interpreter: [0] R 3.5.

[Info  - 6:58:44 PM] Starting R Process with /Library/Frameworks/R.framework/Versions/3.5/Resources...
[Error - 6:58:46 PM] Connecting to R Workspace failed.
Reason: Authentication failed for local broker

**Comment by MikhailArkhipov** [comment]
Might be TSL/SSL key expiration issue. You may try and have a look at https://docs.microsoft.com/en-us/visualstudio/rtvs/setting-up-remote-r-workspaces?view=vs-2017 and make your own keys.

**Comment by MikhailArkhipov** [comment]
Sounds like VS Code and not VS IDE. This should be fixed in https://github.com/MikhailArkhipov/vscode-r.
