### ISSUE TITLE
R 4.0 not supported

### ISSUE THREAD

**Issue by mkoohafkan** [Microsoft/RTVS#4370]
It looks like R 4.0.0 is not supported:

![image](https://user-images.githubusercontent.com/4790348/80497550-7d748080-891f-11ea-912e-b8c35f9ff15b.png)

This decision seems completely arbitrary, and will probably kill my usage of Visual Studio 2017. RTVS was a fantastic addition to Visual Studio.

Unfortunately the [plug-in version of RTVS for VS 2019](https://marketplace.visualstudio.com/items?itemName=MikhailArkhipov007.RTVS2019) hasn't worked for a long time now, and VSCode support for R just doesn't compare (I dislike the VSCode interface in general, and there are serious performance issues with R specifically).

What a disappointing end to what had become my all-time favorite IDE!

@MikhailArkhipov is this the same repository that you used to create the VS 2019 plugin? I'm wondering how people might contribute to that effort in the future to keep R support alive in Visual Studio going forward. I know I would be willing to put some time into trying to [figure out how to get it working](https://github.com/microsoft/RTVS/issues/4354#issuecomment-575390399) but it will be tough for me to wade through the source code and figure out what's relevant to the VS 2019 plugin.

**Comment by MikhailArkhipov** [comment]
It is not arbitrary. New version of R has different R.dll with potential different C/C++ API. It may need new host process executable and for RTVS to know which host to launch.

Yes, it is same repo. Master is for 2017 and `2019` branch is off master. Unfortunately, there is no extension for 2017 since package is bundled and hence has to be built internally and distributed with VS update.

For 2019 I am planning to look into 4.0 some time this week.

**Comment by MikhailArkhipov** [comment]
We are talking https://github.com/Microsoft/R-Host here.

**Comment by MikhailArkhipov** [comment]
Published update. R 4.0 works for me.

**Comment by mkoohafkan** [comment]
@MikhailArkhipov are you referring to the VS 2019 plugin or the VS 2017 workload? I presume the VS 2017 workload will not be updated as this is no longer a Microsoft-supported product.

**Comment by MikhailArkhipov** [comment]
Yes, 2019. 2017 may be updated, but it will have to be on 2017 update schedule. I am checking how 2017 gets serviced. Stay tuned.

**Comment by mkoohafkan** [comment]
Thank you @MikhailArkhipov, it is great to see that RTVS is still being supported. Thanks also for pointing out the 2019 branch of this repo.

**Comment by MikhailArkhipov** [comment]
For 2017 I would suggest submitting an issue though VS feedback button. This way it will go to the VS issue tracking. This GH repo is not being watched by VS servicing.
