### ISSUE TITLE
??plot, run demo in console doesnt work

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#537]
previously i could:

??plot

then run the interactive density plot example and it would all work.  ie, initial bell curve graph shows up, along w the control, and the control would affect the graph.

now when you run it, the graph does /not/ show up, but the control does.   control does nothing.

if you reset the repl, the graph suddenly pops up as if it was queued.  but the control doesnt work.

also, copy pasting from the help window doesnt seem to work.  ie, 

hiliting and selecting via ctrl-C:

demo(tcltk::tkdensity)

doesnt paste into repl (ctrl-V).

**Comment by jflam** [comment]
@int19h to verify that this is actually fixed.
