### ISSUE TITLE
Exit RHost if initialization scripts aren't loaded correctly

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#622]
Also, output error to R Interactive

**Comment by MikhailArkhipov** [comment]
We probably should just log this for frown. There is nothing really that would help user...

**Comment by int19h** [comment]
We want it to be visible so that users actually report it.

**Comment by MikhailArkhipov** [comment]
Cleaning up the backlog. Is this still important?

**Comment by int19h** [comment]
It can result in hard-to-diagnose bugs if the initialization code (e.g. anything in `rtvs` package) contains errors. The old behavior was that you simply got a REPL stuck in unusable state, with no indication as to what went wrong. I'm not sure it's still true with all the changes, though. @AlexanderSher ?

**Comment by MikhailArkhipov** [comment]
currently errors in rtvs packages seen in REPL. IMO. sufficient.

**Comment by MikhailArkhipov** [comment]
Cleaning up backlog
