### ISSUE TITLE
Changing file or folder attributes is not reflected in project structure

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/RTVS#76]
1. Create new R project
2. Add file
3. Make it hidden

**Actual**: File is still in the project
**Expected**: File should disappear from the project

After project reload, file isn't in project structure

**Comment by MikhailArkhipov** [comment]
Haven't seen any complaints, probably something users never do anyway. Close?

**Comment by MikhailArkhipov** [comment]
Closing as no one complains
