### ISSUE TITLE
Provide shortcuts for <- and %>%

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#796]
R has two (and likely more) frequently used non-standard operators: the assignment arrow “<-“ and the dplyr pipe “%>%”. In RStudio there are some very handy key bindings for such strings: Alt+”-“ for the former, and Ctrl+Shirt+M for the latter. Is it possible to set this up in RTVS? Could I do this myself anywhere?

**Comment by mungojam** [comment]
While the code snippets are nice, people who use R Studio as well as RTVS or who are looking to migrate will be put off by the lack of these familiar shortcuts and no way to implement them (there doesn't seem to be a way to set up a specific keyboard shortcut for a particular snippet).

Also, the snippet is not putting in the trailing space after <- despite it being in the .snippet file.

**Comment by MikhailArkhipov** [comment]
Trailing space will be added on automatic formatting.
