### ISSUE TITLE
Intellisense doesn't show functions from code

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#843]
This is technically the same as https://rtvs.visualstudio.com/DefaultCollection/RTVS/_workitems/edit/212, but I would like to also have a GitHub issue for the ease of discussion.

Short story is that Intellisense is currently driven by 1) parsed help files for packages, and 2) live data from the session. The problem is that in scenarios where the user is editing a file with multiple functions, it doesn't work particularly well. E.g. start from a blank file:

```r
foo <- function(x) { x }
foo(
```

You'd expect to see the signature of `foo` at this point, but you won't. In fact, if you do Ctrl+Space right after typing `foo` to see the list of available completions, it's not there at all.

In this simple case, you can source the file after defining the function, so that the definition is executed and appears in globals, from whence completion will pick it up (although it still won't show the function signature currently, but that is a separate issue). The problem is it may not always be possible or convenient to do these frequent sourcings every time you add or modify a function.

This problem is more acute for authoring packages, because for package code, it may not even be possible to source individual .R files in it, because they try to call functions from other files in the same package (our own `rtvs` package is a good example).

**Comment by MikhailArkhipov** [comment]
#1094
