### ISSUE TITLE
project/REPL: setwd() short cuts needed

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#853]
the repl needs convenient setwd() short cuts of some sort.

typing setwd, quotes, paths, double backslashes, etc. gets old fast, especially when the directories you care about are right there in the Solution Explorer.   would be great to have two shortcuts:

1. an "up arrow" which like Explorer takes you up one level
2. the ability to right click on a node in a project and like "Scope to this", do a setwd(" ") to the highlighted directory.

in the pic below, a menu item to do a setwd("........\shiny-2")

![image](https://cloud.githubusercontent.com/assets/742484/12894254/8a5157cc-ce4a-11e5-9cb6-eb8098b28178.png)

**Comment by MikhailArkhipov** [comment]
see #1089
