### ISSUE TITLE
Shadowed 'ide' function breaks plot

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#885]
```
> ide <- function() { print('hello ide') }
> plot(0:10)
[1] "hello ide"
R Host process is stopped. Click Reset to start a new one.
```

Problem is that for `deviceIsInteractive` to work properly, for things such as `demo(graphics)`, the name of the graphics device must match the name of the function used to create it.  This is a name visible to the user (displayed by any of the dev.\* functions).

Example of other device names:

```
[1] "X11"       "X11cairo"  "quartz"    "windows"   "JavaGD"    "CairoWin" 
[7] "CairoX11"  "RStudioGD"
```

Additionally, this name, currently `ide` is hard-coded in R-Host as well (that's why we picked a somewhat generic name).

**Comment by MikhailArkhipov** [comment]
No complaints
