### ISSUE TITLE
Plotting errors don't produce any visual feedback in plot window

### ISSUE THREAD

**Issue by huguesv** [Microsoft/RTVS#887]
Execute these 2 statements, one at a time:

```
plot(0:10)
plot(state.name)
```

First plot is displayed in plot window.
Second plot operation causes an error, which is displayed in REPL, but plot window is unchanged (shows the first plot).

It should display a blank plot.

I have already committed changes that display a blank plot while navigating history. It's the initial plot scenario that isn't handled.

My first attempt at making this work was causing performance issues / flickering of blank plots in the normal case of plotting several plots consecutively, so I have to find a different solution.

**Comment by MikhailArkhipov** [comment]
I think error in REPL is sufficient. Nothing really is broken here.
