### ISSUE TITLE
Allow user to specify CRAN mirror via .Rprofile

### ISSUE THREAD

**Issue by MikhailArkhipov** [Microsoft/RTVS#915]
Instead of assuming RStudio mirror

**Comment by MikhailArkhipov** [comment]
![2](https://cloud.githubusercontent.com/assets/12820357/14088457/8687167a-f4e4-11e5-9fbe-c5a8f7f0ffe1.png)

**Comment by huguesv** [comment]
It must be because the new mirror.R isn't in the installer.

**Comment by MikhailArkhipov** [comment]
Ah! Lemme fix that

**Comment by MikhailArkhipov** [comment]
Yeah, I see it in the PR, let me fix the installer
