### ISSUE TITLE
help: need search field

### ISSUE THREAD

**Issue by smortaz** [Microsoft/RTVS#955]
Hey!

I miss the search box in the "R help" window. I know that I can write ? and ?? in the command window, but I often browse the help using the search box in help (when using R Studio)

(from user)

**Comment by MikhailArkhipov** [comment]
With workaround it goes to 0.4

**Comment by MikhailArkhipov** [comment]
So this is just search in functions, on on the page. I.e. mini-REPL with completion for functions in loaded packages? RS shows completion list in search but it is limited and it is unclear what exactly are items it is showing. Ex for ```pl``` it shows 'plain' but choosing it takes me to ```plotmath```. Keywords from help?

**Comment by MikhailArkhipov** [comment]
For starters I'll just show same completion list as in REPL. Seems to be close enough.

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/commit/468732e509cab0e9ff2a8d509e9afc2059d2174d
