### ISSUE TITLE
Support echo=true for Source R Script command

### ISSUE THREAD

**Issue by int19h** [Microsoft/RTVS#984]
User-reported as follows:

> I would like to be able to change the RTools.SourceRScript command (that is currently invoked by Ctrl+Shift+S) a bit. Currently it submits the following to the REPL window: `source(“/Full/Path/To/Active/Script.R”)`, whereas I would love it to run `source(“/Full/Path/To/Active/Script.R”, echo = TRUE)` instead. 

Basically, we need to add a second command that is the same, but with echo.

**Comment by huguesv** [comment]
I'm assuming we want an echo version of Source Selected File(s), which is a different command for project context menu?

**Comment by int19h** [comment]
We do. The tricky part here is what to do when debugging - we need to use `rtvs::debug_source` in that case, which doesn't support echo currently.

And adding that support is non-trivial - the reason why regular `source` can do it easily is because it evaluates the file one line at a time, but that also breaks stepping (and is why we needed `debug_source` in the first place). The only way I can think of implementing that for `debug_source` is injecting print statements into the parsed expression.

Or we could say that source w/echo simply does not support stepping, and then always use `source`. @jflam?

**Comment by huguesv** [comment]
Implemented the simple way ie. no stepping support.
